### ISSUE TITLE
[Suggestion] Allow Water Cells to be filled by machines

### ISSUE THREAD

**Issue by hron84** [turbodiesel4598/NuclearCraft#10]
If Water Cells would be a normal fluid storage, it could be filled with Fluid Transposer (TE)/Bottler (Immersive) and other machines. It'd be really good if we can automagically fill these cells with water.

**Comment by turbodiesel4598** [comment]
I thought about this some time ago - I'll come back to it after I've got the basic accelerator done.

**Comment by turbodiesel4598** [comment]
I've added a TE fluid transposer recipe allowing water and liquid helium cells to be emptied and filled with their respective fluids.
