### ISSUE TITLE
Ore dictionary error in log (1.11.2)

### ISSUE THREAD

**Issue by Endmateria** [turbodiesel4598/NuclearCraft#100]
MC 1.11.2
Forge 2296
NC 2.2b
https://gist.github.com/Endmateria/53e4673c52115f5b5dd89d228aa535df#file-new-text-document-txt

**Comment by turbodiesel4598** [comment]
Hmm - ok, should be a simple fix.

**Comment by Endmateria** [comment]
Thanks boss.  Great mod!

**Comment by turbodiesel4598** [comment]
No prob - hopefully the issue's gone in 2.2c. And thanks :)
