### ISSUE TITLE
[1.10.2-2.2c] Fusion core does not recognize fuel!

### ISSUE THREAD

**Issue by Cassiobsk8** [turbodiesel4598/NuclearCraft#101]
With version 2.2 it recognized the fuels and it maintained itself when it arrived in 8000 kK but it did not consume the fuels neither generated no energy.
In version 2.2c it does not recognize Lithium-7 nor Boron-11 and does not start at 8000 kK:

http://imgur.com/a/rWxkh

**Comment by turbodiesel4598** [comment]
The fuel levels don't seem to be updating properly on the client side - on quitting the game and rejoining, the fuels are recognised - I think this should be a simple fix.

**Comment by turbodiesel4598** [comment]
As far as I can tell, this has been fixed in 2.2d :)
