### ISSUE TITLE
(NuclearCraft-2.2d--1.10.2) Fission Reactor Port not outputting RF

### ISSUE THREAD

**Issue by ShicKla** [turbodiesel4598/NuclearCraft#102]
Just like the title says, the reactor port is not outputting RF. If you need any additional information let me know.

**Comment by turbodiesel4598** [comment]
Ah, it seems my attempt to make the searching method more efficient stopped it searching the entire structure - thanks for pointing that out. It will be fixed for the next version :)

**Comment by Aedda** [comment]
I don't know if this is related, unrelated, or a total fluke but...

I had been totally unable to withdraw RF power via EIO Conduits from the **Reactor Controller** however installing IC2 and Slugs Eu energy converters somehow enabled this to work. The Reactor Port however remained broken.

I thought it might be a fluke so I did 10 full restarts, 5 with those mods, 5 without and it checked out. IC2 by itself didn't help, and Slugs Eu energy converters crashes without IC2 being present.

**Comment by Aedda** [comment]
Update to add: I finally tracked this down to an API issue. Copying the CoFH api files from Slugs Eu energy converters into the NuclearCraft jar enabled extracting RF from the Reactor Controller via EIO Conduits without IC2 nor Slugs installed.

**Comment by turbodiesel4598** [comment]
Perhaps I just need to update the CoFH API embedded in NuclearCraft then.

**Comment by Aedda** [comment]
> Perhaps I just need to update the CoFH API embedded in NuclearCraft then.

That will work in regards to the Reactor Controller. As for the Reactor Port it of course still requires the aforementioned fix to the "searching method".

**Comment by turbodiesel4598** [comment]
The reactor port bug is fixed and the RF bug _should_ be fixed in version 2.3, coming v. soon :)
