### ISSUE TITLE
(NuclearCraft-2.2d--1.10.2) Fussion Reactor interface not working

### ISSUE THREAD

**Issue by sintaxcz** [turbodiesel4598/NuclearCraft#103]
Hello Fussion Reactor has only half of interface no imput slots nothing

**Comment by sintaxcz** [comment]
Fussion Reactor

**Comment by turbodiesel4598** [comment]
...
Again, do you mean **fission** or **fusion** - your answer of _fussion_ is a weird mix of the two, and quite interestingly, could easily be a typo or misspelling of either one.

**Comment by sintaxcz** [comment]
Sry FUSION

**Comment by turbodiesel4598** [comment]
Ok - are you trying to insert items into the reactor? If you are, then that's not how it works anymore - you need to pump fluid fuels into it. The available fuels are hydrogen, deuterium, tritium, helium-3, molten lithium-6, molten lithium-7 and molten boron-11. Simply build the electromagnet ring, pump these into the fusion core and heat the reactor up to begin nuclear fusion reactions :)

**Comment by turbodiesel4598** [comment]
I'm going to close this issue as there didn't seem to actually be an issue.
