### ISSUE TITLE
crash: too much heat?

### ISSUE THREAD

**Issue by leftyde** [turbodiesel4598/NuclearCraft#104]
I made an 3x3x3 reactor, fueld it and let it explode:

https://pastebin.com/8f1BkP8e

**Comment by turbodiesel4598** [comment]
It looks like I replace the controller block with lava _before_ the state of the controller is checked, which is causing the game to look for block properties that just aren't there - should be a simple fix :)

**Comment by turbodiesel4598** [comment]
Fixed for the upcoming version 2.3 :)
