### ISSUE TITLE
[Suggestion] Increase fission fuel consumption rate?

### ISSUE THREAD

**Issue by jmdisher** [turbodiesel4598/NuclearCraft#105]
This mod is great but the one thing I find odd about it is the very low fuel consumption (once you build a good reactor you need hardly any fuel, no matter the size).

Are there any plans to make this into something like "1 fuel rod required per fuel cell block in the fission reactor?"

As it stands, a single fuel rod is enough to fully power even the largest reactors.  I find myself wanting it to work more like IC2 where efficiency is a huge factor but larger reactors still require more fuel.

**Comment by turbodiesel4598** [comment]
It's a good suggestion... of course the issue with the 'one rod per cell block' system in this mod is that a player can change the number of cell blocks in the reactor at any point during a cycle, so I'd certainly have to take that into account.

Right now, all that happens for reactors with more cell blocks is that the fuel runs dry more quickly. So with either system, the rate of fuel consumption would be exactly the same.

Perhaps what I need to do then is just lower the base lifetimes of the fuels? If so, by how much should they be cut?

**Comment by jmdisher** [comment]
Hmm, I didn't realize that the number of cell blocks will increase the consumption rate of the one cell inside (I thought I found that didn't happen but that was in a much older version of the mod so it might have changed).  Is that linear?

The approach I am suggesting is, unfortunately, pretty complicated (since you somehow need to track/expose each fuel cell independently - works within the IC2 reactor design but this one doesn't lend itself to a similar approach).  I am not convinced that it can be done in a way which would preserve other aspects of the existing design (change reactor internals while fuelled) or make sense from a UI perspective (minimally, requires exposing partially-consumed fuel).

You might just want to make a consumption rate multiplier config file option so this can be tweaked from the outside (probably a good idea since the ore generation rates will be different when combined with different mods - since it is also up to the user/pack developer which mods generate potential fuel ores).

**Comment by turbodiesel4598** [comment]
Yes, it is linear. The fuel consumption rate is the base rate multiplied by the number of cell blocks. And there already is a fuel consumption rate multiplier - an overall one, and one for each individual fuel also :)

**Comment by jmdisher** [comment]
Those should suffice for general usage (sorry I didn't notice the cell blocks increasing the consumption rate).  I will close this since any other action on this would be pretty "pie in the sky" and might break other approaches currently in place.
