### ISSUE TITLE
Issue reprocessing fission fuels in 2.2d "1.11.2"

### ISSUE THREAD

**Issue by Dryxen** [turbodiesel4598/NuclearCraft#107]
Currently the only fuel ive been able to reprocess is LEU-233.
I've tested all of them in a creative world after i noticed my new depleted mox rods couldnt be reprocessed in survival.
if this is intended please close the issue.

**Comment by turbodiesel4598** [comment]
I am unable to recreate this - I'm able to reprocess all fuels...

**Comment by Dryxen** [comment]
sounds like a conflicting mod or forge conflict then ill do some more intinsive testing as i was able to reproduce server and client sided. thanks for the reply.

**Comment by turbodiesel4598** [comment]
Someone else has recently mentioned a possible related issue on the CurseForge page - I'll look into it.

**Comment by turbodiesel4598** [comment]
Finally tracked it down - fixed :)
