### ISSUE TITLE
2.2d--1.11.2 fission controller causes dedicated server to crash excessively

### ISSUE THREAD

**Issue by kreezxil** [turbodiesel4598/NuclearCraft#108]
server crash report
https://gist.github.com/778e93b979f9a75d837c873e4359d1c0

all of these others identical the purpose is to show you how often it crashes the server
https://gist.github.com/b1c5a3c5a126becf75d547b564ec1d2d

**Comment by turbodiesel4598** [comment]
It looks like a conflict with refined relocation - I really am not sure what I can do to fix this issue, as the fission controller certainly does have a directionality. In fact, the crash report doesn't really make much sense to me - it says it can't find the 'facing' property, but it then says that the block does indeed have that property...

**Comment by turbodiesel4598** [comment]
I'm going to close this issue as this doesn't seem to be an issue with this mod - for some reason, the tile entity tied to the position of the fission controller block is a 'fast hopper'. You may need MCEdit or remove one of the two mods to fix the issue.
