### ISSUE TITLE
Electrolyser causes MC client to crash

### ISSUE THREAD

**Issue by austragus** [turbodiesel4598/NuclearCraft#110]
Connecting the Electrolyser with either Mekanism Mekanical Pipes or EnderIO fluid conduits causes the client to crash whenever Fluid tanks fill up.

Version: NuclearCraft-2.2d--1.10.2

**Comment by turbodiesel4598** [comment]
Could be an API mismatch as I haven't updated the mod for a little while, and things are currently moving quickly - I'll look into it.

**Comment by turbodiesel4598** [comment]
This appears to be fixed now.
