### ISSUE TITLE
Console Spam due to cobble Generator

### ISSUE THREAD

**Issue by instinxx** [turbodiesel4598/NuclearCraft#111]
Using the All The Mods 1 pack using version 2.2d --1.10.2 , a player placed a cobblestone Generator over a hopper causing a ton of console spam containing the following.

 [ic2-poolthread-6/WARN] [IC2.EnergyNet]: Tile nc.tile.passive.Passives$TileCobblestoneGenerator@2dab83df (BlockPos{x=-3851, y=67, z=-6571}) removal without registration

PS since the IC2 api seems involved, I have industrialcraft-2-2.6.210 -ex110 installed also if that matters.

I tried to remove cobble using an EnderIO item conduit which also creates the spam. I am unsure how to get the cobble out without spamming console.

**Comment by instinxx** [comment]
Secondarily, can you at least make a config option that this cobble gen may require RF to operate?

**Comment by turbodiesel4598** [comment]
Hmmm... that's a strange one, but I'll see if I can find the cause. As for adding your suggestion, sure - shouldn't be a problem.

**Comment by turbodiesel4598** [comment]
How much power (RF/t) do you think the cobble gen should use if it needs it?

**Comment by turbodiesel4598** [comment]
There doesn't seem to be a way to fix this - Mekanism appears to have a similar issue. The problem is that the machine has to be removed and added back into the IC2 energy-net every time the block updates, as otherwise cables connecting to it disconnect permanently.

**Comment by turbodiesel4598** [comment]
Added the RF gen config option :)
