### ISSUE TITLE
Crash!! Client site open manufacture ( 1.10.2 )

### ISSUE THREAD

**Issue by m00nLP** [turbodiesel4598/NuclearCraft#112]
Hey guy
I have a Problem.
Your Mod run on my Server but i will open the Interface from Manufacture, Crash my client

Here the Crash report
www.m00nLP.de/download/crash-2017-06-13_15.10.46-client.txt

Plz fast Help

**Comment by m00nLP** [comment]
hello any here?

**Comment by m00nLP** [comment]
???????????????????????

**Comment by m00nLP** [comment]
amazing Support here

**Comment by m00nLP** [comment]
Ohne Blödsinn bekommt man hier auch mal ne antwort??? sowas von ein schlechter Support hier das ist das letzte mal das ich diesen Mod in einer meiner modpacks drinnen habe werde

**Comment by m00nLP** [comment]
Kannst den scheiss hier schliessen der mod fliegt raus

**Comment by turbodiesel4598** [comment]
This is a strange one. Again, like other reported issues, it might just mean I need to update some APIs, since it has been a little while since the last update.

**Comment by turbodiesel4598** [comment]
This should now be fixed in 2.3 - can you confirm this?

**Comment by frenzye** [comment]
Looks like same issue on 2.3 https://gist.github.com/frenzye/10904833f3c041d03ea6d5d0bed7a873

**Comment by turbodiesel4598** [comment]
I wasn't actually able to ever recreate this issue, as I don't even know what's causing it. However, [2.4 has just been released](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files), so if you had this issue before, could you check if you have it with the new version?

**Comment by turbodiesel4598** [comment]
Should be fixed now as discussed in the above conversation :)
