### ISSUE TITLE
Fusion Reactor Cooling System

### ISSUE THREAD

**Issue by MrGrader** [turbodiesel4598/NuclearCraft#116]
Because of constant, independent fusion reactor's heat production, it is impossible to maintain its work without turning it on and off, which is annoying and reactor does not produce energy while being turned off.

So please! Would you mind either making the reactor to produce energy while there is heat inside even if it is turned off OR adding some sort of Fusion Reactor Cooling System.

Thank you.

**Comment by QuantumTraverse** [comment]
There does exist a config option (if I remember correctly) to make the
fusion rector reach its maximum efficiency asympotically, meaning that
 constant cooling would be unnecessary.

**Comment by turbodiesel4598** [comment]
Fusion reactor cooling is being added in the next update :)
