### ISSUE TITLE
Please identify a license for this repo

### ISSUE THREAD

**Issue by wormzjl** [turbodiesel4598/NuclearCraft#117]
Thank you!

**Comment by QuantumTraverse** [comment]
There really is no license. To quote from the readme: "Feel free to go
ahead and use this mod if you wish! I love the idea of giving out the mod
in exchange for additions to it by others who want to help - at the end of
the day, if this mod is getting better, I'm happy ;) ". It seems that one
can do whatever one wants to the mod, although I would just give the
modmaker a heads up out of courtesy.

**Comment by turbodiesel4598** [comment]
Yep, as QuantumTraverse says, do what the hell you want with this mod and its code - there's nothing serious about it and it's just something for me to do in my free time :)

**Comment by wormzjl** [comment]
Ok thank you!
