### ISSUE TITLE
Voltaic Pile doesn't show RF stored

### ISSUE THREAD

**Issue by cyberdjinn** [turbodiesel4598/NuclearCraft#118]
I have a Generator operating, no power is being used elsewhere, but the generator is drained of RF ... and the Pile still says 'Storing 0/1600000RF'.
I have the Generator off, and I'm running a machine attached and it is being recharged (albeit slowly even using Glass Fibre IC2 cables) .,. and the Pile still says  'Storing 0/1600000RF'.

I know it's a work in progress, I wasn't sure if you were aware of this glitch.

**Comment by turbodiesel4598** [comment]
Fixed - the data from the tile wasn't getting to the client block. The value will now update every second :)
By the way, I think the reason that EU is being emitted slowly is because the voltaic pile is a tier 2 IC2 machine, and so only outputs at 128EU/t max.
