### ISSUE TITLE
Integration with Actually Additions' Energy Laser Relays

### ISSUE THREAD

**Issue by cyberdjinn** [turbodiesel4598/NuclearCraft#119]
The NuclearCraft machines can receive power from AA's Energy Laser Relays, however the fission reactor can't output through the network - not even with the Tier 3 Laser relays. Could this please be made possible?

**Comment by cyberdjinn** [comment]
If the Fission Port issue has been fixed, that might also solve this issue - but that needs testing.

**Comment by turbodiesel4598** [comment]
I've just downloaded Actually Additions and am gonna test this with a beta build of v2.3

**Comment by turbodiesel4598** [comment]
Seems to be working :)

**Comment by cyberdjinn** [comment]
I have tried this, and I don't seem to be drawing power from the reactor ... I had the enhanced energy laser on the fission port in the corner space of the reactor. What did I need to do to get this to work?

**Comment by cyberdjinn** [comment]
It works when the laser relay is on the fission controller, but not the fission port.
