### ISSUE TITLE
Helium collector Crash

### ISSUE THREAD

**Issue by ProxyPlayerHD** [turbodiesel4598/NuclearCraft#123]
just [this](https://pastebin.com/bQSz4Zg8)

**Comment by turbodiesel4598** [comment]
Did it just crash when you placed it? What caused the crash?

**Comment by ProxyPlayerHD** [comment]
version 2.3 it crashed in few seconds after i placed it.

**Comment by turbodiesel4598** [comment]
I've had two reports of this now - will look into it and get a fix out.

**Comment by turbodiesel4598** [comment]
[Fixed in version 2.4 :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files)

It was caused by the collector trying to push helium into machines that couldn't accept it.
