### ISSUE TITLE
Crash when mining redstone

### ISSUE THREAD

**Issue by curscascis** [turbodiesel4598/NuclearCraft#125]
It seems there is an issue in v2.3a that causes a conflict with redstone ore and ore excavation. I am referencing a previous post from the other author  #https://github.com/Funwayguy/OreExcavation/issues/57.
I did not see the issue here so I am posting it. Here is another crash log.
https://hastebin.com/xayifunini.scala

**Comment by curscascis** [comment]
After more examining it simply happens while mining redstone, with or without ore excavation present.

**Comment by CanisArtorus** [comment]
See also manual mining crash https://pastebin.com/9t0SRDgm
and RFTools Builder block w/ quarry card server crash https://pastebin.com/wzshXQ0G

Since we also don't have a single piece of Rhodochrosite on this server playthrough, that's probably the function that is NPE-ing.

**Comment by turbodiesel4598** [comment]
Been away for a few days so could not deal with this immediately as I had hoped. On top of that, I was also midway through changing the way recipes worked in the mod, but that nearly done now. As a temporary solution, I have simply removed the downloads for the version with the issue - the only constructive change made was fixing an issue with fission reactor coolers, but I will get a new version out as soon as I can :)

**Comment by curscascis** [comment]
<3 much appreciated, take your time.

**Comment by Dylanavo** [comment]
Did this end up getting a fix for 1.10.2?

**Comment by turbodiesel4598** [comment]
[Fixed in version 2.4 :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files)
