### ISSUE TITLE
Can´t launch Fusion Reactor (size 10) (1.10)

### ISSUE THREAD

**Issue by gamelnderGamler** [turbodiesel4598/NuclearCraft#126]
Iam playing the modpack "not enough mods" on 1.10 Version. 
Not really a  big deal, just want you to know:

I have a Fusion Reactor fully powered but it won´t start. The heat won´t increase anymore. I tested a smaler one in creative and it worked without problems. So i guess the intern power storage isn´t big enough to heat up a size 10 Reactor? (as you can see on the picture the heat stuck at 461663 kK)

I also have a small problem with not fully powered nuclearcraft machines. (electrolyzer and so on)
They only work if you have enough power. If you don´t have enough power, they start their process until their intern storage is used and after that they drop their progress. (machines in other mods continue their progress but slower due to the lower power). So if i power something huge it can be, that my whole automatiation stops. Wich can be crucial if they supply huge reactors.

As i said, both problems aren´t a big deal. Hope they weren´t known allready.

I really enjoy your modpack and looking forward to the return of the synchrotron :).

(sorry for my bad english) 
![fusion](https://user-images.githubusercontent.com/22398257/28878010-54bb7008-779e-11e7-832d-2dfc252c8912.PNG)

**Comment by turbodiesel4598** [comment]
I think this is an issue with later versions of Forge - I'm currently in the process of moving to the latest version, and hopefully your issue will dissappear :)

**Comment by turbodiesel4598** [comment]
I'm actually fairly confident that I somehow fixed this when implementing the new recipe system - could you [see if the new version solves the problem](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files)?

**Comment by gamelnderGamler** [comment]
Yes, it works now. 
Thank you :)

**Comment by turbodiesel4598** [comment]
Whew - awesome! Thanks, and your welcome :)
