### ISSUE TITLE
Machines not getting power

### ISSUE THREAD

**Issue by The-Doctor-cx** [turbodiesel4598/NuclearCraft#127]
I don't quite know if this is another mod or whether it is NuclearCraft that is causing this issue but it seems to have began occurring since I updated to the most up to date version of NuclearCraft for 1.10.2, the problem (For me at least) is that when I use many of the machines such as the isotope separator it gains power in its internal buffer absolutely fine when I place it but as soon as I begin placing items in any of the machines it appears to stop accepting power inputs, it shouldn't however be the method of inputting power as I have tried this by directly connecting it to an Ender IO capacitor bank, using Ender IO energy conduits and Thermal Dynamics flux ducts, all of which seem to have the same effect and to begin accepting power again I have to remove the block and place it again, this is obviously pretty tedious especially when doing something such as separating the isotopes on preparation for fission.

If this is an illegitimate issue then I would be greatly appreciated if I could be directed to the actual cause however, this does not occur with any other machines from any other mod so far leading me to believe that this may be the root of the issue.

**Comment by turbodiesel4598** [comment]
I'm coming back to modding after quite a break and I think there are many issues being caused simply by Forge having been updated - I'll see if I can get that issue fixed :)

**Comment by turbodiesel4598** [comment]
Might have fixed this [with the latest update](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files) - could you see if your issue does indeed get solved?

**Comment by JulianSchutsch** [comment]
The issue still persists with 1.10.2 with the latest forge and NuclearCraft.

I tried debugging it...i am still lost. The Logs show, that NuclearCraft accesses a different TileEnergy as the rest. So energy is "accepted", but the storage is full, but the gui shows a different storage.

This bug is new here.

**Comment by aranian** [comment]
This being limited to Fluxducts is my observation as well. Mekanism's Universal Cables work without the problem.

**Comment by LunaSquee** [comment]
Confirmed still happening on 1.12.2 with thermal dynamics ducts

**Comment by turbodiesel4598** [comment]
Ok, still looking into this, but still not entirely sure this is an NC issue - my good friend who makes the Calculator mod says that he is having the same issues that I am having with the Thermal Dynamics conduits.

**Comment by turbodiesel4598** [comment]
Thanks to a commit by Thutmose, this issue has been fixed for the next update :)
