### ISSUE TITLE
Crash on launch with 2.3 release

### ISSUE THREAD

**Issue by Weldera** [turbodiesel4598/NuclearCraft#128]
im using the latest version of nuclear craft on 1.10.2 and it hasn't errored in the crash report. not sure if it needs some sort of core or something but yeah. here is le crash report.
[crash-2017-08-13_00.06.22-client.txt](https://github.com/turbodiesel4598/NuclearCraft/files/1220133/crash-2017-08-13_00.06.22-client.txt)

**Comment by turbodiesel4598** [comment]
I'm pretty sure this is an issue caused by the mod being built on an earlier version of Forge - I'm currently in the process of moving to the latest version, and hopefully your issue will dissappear :)

**Comment by turbodiesel4598** [comment]
[Just updated the mod](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files), but could never recreate your issue - could you see if [downloading the latest version of the mod](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files) fixes the issue?

**Comment by turbodiesel4598** [comment]
Closing this as it's going nowhere and I'm not even sure that NC caused the issue.
