### ISSUE TITLE
Crash on 2.3

### ISSUE THREAD

**Issue by dobbeltmike** [turbodiesel4598/NuclearCraft#129]
Was testing some things with active coolers and the creative water source when it crashed...
[crash-2017-08-15_02.22.32-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/1223813/crash-2017-08-15_02.22.32-server.txt)

**Comment by Cntrldfusion** [comment]
Same crash on 1.11.2 using my own modpack.  Using NuclearCraft 2.3aFixaroo.  Player placed a infinite water source block between an active liquid cooler block and a supercooler block.  Right after that the server went into an infinite crash loop until I managed to destroy the water block.  Here is a couple of the reports.

[crash-2017-08-21_17.04.43-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/1240300/crash-2017-08-21_17.04.43-server.txt)
[crash-2017-08-21_17.06.42-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/1240301/crash-2017-08-21_17.06.42-server.txt)
[crash-2017-08-21_17.08.45-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/1240302/crash-2017-08-21_17.08.45-server.txt)

**Comment by turbodiesel4598** [comment]
I think I've fixed this issue for the next release :)

**Comment by turbodiesel4598** [comment]
[Pretty sure that this is fixed in version 2.4 :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files)
