### ISSUE TITLE
Crash on 2.3 [1.11.2] from fission controller

### ISSUE THREAD

**Issue by antcig** [turbodiesel4598/NuclearCraft#130]
Got a crash after fission reactor overheated.
[crash-2017-08-21_08.22.23-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/1237872/crash-2017-08-21_08.22.23-server.txt)
Using v2.3a with temp fix from #124 

Probably related to #104 ?

**Comment by turbodiesel4598** [comment]
I might have made a mistake, or, just like with many other current issues, this is related to the mod being built on an old forge version. Either way, I'm on it :)

**Comment by turbodiesel4598** [comment]
I was never actually able to recreate this, but [I did update the meltdown code for the latest release](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files), so could you see if your issue goes away?

**Comment by TvL2386** [comment]
I also managed to crash All The Mods with Nuclearcraft 2.3 several times, but not all times, by creating a small reactor in a single player game without cooling and just turn it on. It would crash the game and after returning I would see lava pouring out. The controller is always replaced by a lava source block.

**Comment by turbodiesel4598** [comment]
But has the issue disappeared in NC 2.5?

**Comment by MjrStryker** [comment]
Can confirm, it still occurs in 2.5a on my server. We're running forge 14.23.0.2517 in minecraft 1.12.2 using nuclearcraft 2.5a. 

Crash report uploaded to https://pastebin.com/QBL4nXvU but it looks like the primary issue is here:

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:flowing_lava, properties=[level]}

**Comment by turbodiesel4598** [comment]
Fixed now thanks to the recent commit by dizzyd :)
