### ISSUE TITLE
Conflict with Mekanism if NEI is present, 1.10.2

### ISSUE THREAD

**Issue by CyberCelestial** [turbodiesel4598/NuclearCraft#131]
https://pastebin.com/93tuS3yg

This log seems to cause NC to not find its own files. I've confirmed that it only occurs if Mekanism and NEI are both installed. Removing either Mekanism or NEI allows Nuclearcraft to clear.

I am using build 9.2.3.97 of Mekanism, and the Generators and Tools modules
I am using build 2.3 of Nuclearcraft
And finally, build 2.1.3.220-universal of NEI.

If there is any other useful information I can provide, please tell me and I will do so.

**Comment by turbodiesel4598** [comment]
This is very peculiar and I still don't understand the cause... I will continue to keep an eye out for any hints of a source of conflict.

**Comment by turbodiesel4598** [comment]
[The mod has been updated recently](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files) - if you are still having this issue, then perhaps the new version will work?

**Comment by turbodiesel4598** [comment]
Gonna close this as it's a very old issue and there's been no further reports of similar problems.
