### ISSUE TITLE
[1.10.2] Fission controller crashes the server when flipping the lever

### ISSUE THREAD

**Issue by polyzium** [turbodiesel4598/NuclearCraft#132]
Crash report: https://clbin.com/FiZWj

**Comment by turbodiesel4598** [comment]
[May have been fixed in 2.4](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files) as I have overheated the reactor multiple times without any crashes - could you confirm this?

**Comment by turbodiesel4598** [comment]
Fixed thanks to dizzyd's commit :)
