### ISSUE TITLE
Fusion completely broken?

### ISSUE THREAD

**Issue by chengxinlun** [turbodiesel4598/NuclearCraft#133]
Build and fully powered the smallest fusion reactor, but still get the notice of "Incomplete Ring". Also tried toroid size 4 setup. Still not working.

The worst of all, it is still taking power and heating up...

MC version: 1.10.2
NC version: 2.3
![2017-09-15_19 27 03](https://user-images.githubusercontent.com/13145137/30495521-8d22d10e-9a4c-11e7-83a2-6d0d444682fd.png)
![2017-09-15_19 27 25](https://user-images.githubusercontent.com/13145137/30495518-8d195066-9a4c-11e7-9f2c-b147d99b91f7.png)
![2017-09-15_19 27 37](https://user-images.githubusercontent.com/13145137/30495516-8d1889e2-9a4c-11e7-9137-04a772e8533e.png)
![2017-09-15_19 27 43](https://user-images.githubusercontent.com/13145137/30495517-8d18f580-9a4c-11e7-96c1-9e1b65bc95b6.png)
![2017-09-15_19 27 50](https://user-images.githubusercontent.com/13145137/30495519-8d1dd19a-9a4c-11e7-9372-cd817b0f58db.png)
![2017-09-15_19 27 55](https://user-images.githubusercontent.com/13145137/30495515-8d178d80-9a4c-11e7-8fb7-be508fb2ece3.png)

All config untouched:
![2017-09-15_19 30 22](https://user-images.githubusercontent.com/13145137/30495522-8d5035cc-9a4c-11e7-942e-d0cd2087e369.png)

**Comment by turbodiesel4598** [comment]
I am aware that there are issue with fusion, and I will have to get round to them. However, in your case, I believe that you are using the wrong type of electromagnet - you should be using the standard electromagnets, made with copper. The superconducting version will be used for particle accelerators.

**Comment by chengxinlun** [comment]
Yes, you are right. I used the wrong one. Must be playing too much gregtech... Closing now.
