### ISSUE TITLE
Fission Reactor not using oreDict Graphite Block

### ISSUE THREAD

**Issue by sandalle** [turbodiesel4598/NuclearCraft#134]
Expanding upon https://github.com/turbodiesel4598/NuclearCraft/issues/120 and https://github.com/turbodiesel4598/NuclearCraft/issues/78 , when having oreDict versions of graphite (ore, dust, ingot, and blocks) and other mods (e.g. [Extreme Reactors](https://minecraft.curseforge.com/projects/extreme-reactors)) and ore unification (e.g. [UniDict](https://minecraft.curseforge.com/projects/unidict))(may not be related and might just be from oreDict), we cannot seem to make Nuclear Craft Graphite Blocks.

I tried smelting Coal in a NuclearCraft Manufactory, but got Extreme Reactor's (first mod "grabbing" dustGraphite oreDict, is my guess) Graphite Dust. Smelting this graphite dust then makes Extreme Reactor's Graphite Bar (ingot).

Trying to make a Graphite Block from these Graphite Bars (ingot) gives an Extreme Reactor Graphite Block (again, probably first to grab blockGraphite oreDict) _unless_ I cheat in some NuclearCraft Graphite Ingots, then I can craft the NuclearCraft Graphite Block.

The Fission Reactor does not seem to recognize Extreme Reactor's Graphite Block as a valid Graphite Block for improving efficiency.

Can the Fission Reactor accept any blockGraphite? :)

> $ grep -i graphite minetweaker-oredict.log
> [SERVER_STARTED][SERVER]Ore entries for <ore:dustHOPGraphite> :
> [SERVER_STARTED][SERVER]Ore entries for <ore:ingotHOPGraphite> :
> [SERVER_STARTED][SERVER]Ore entries for <ore:blockGraphite> :
> [SERVER_STARTED][SERVER]Ore entries for <ore:ingotGraphite> :
> [SERVER_STARTED][SERVER]Ore entries for <ore:dustGraphite> 

Versions (from https://minecraft.curseforge.com/projects/nst-unofficial-exploration if you want it for testing):
Minecraft: 1.11.2
Forge Mod Loader: 1.11.2-13.20.1.2476
Extreme Reactors: 1.11.2-0.4.5.30
NuclearCraft: 2.4-1.11.2 (linked modpack still has 2.3, latest update has not been released yet)
UniDict: 1.11.2-1.1b

**Comment by turbodiesel4598** [comment]
Ah, I had not considered that. Ok, that should actually be a simple fix.

**Comment by turbodiesel4598** [comment]
Think I've fixed it - will be in 2.4a :)

**Comment by sandalle** [comment]
Hrm, I'm not sure that did what was intended. :) Now Extreme Reactor's Graphite Ingots no longer make an Extreme Reactor Graphite Block (Extreme Reactor's Graphite Block is now uncraftable) and Extreme Reactor's Graphite Bar (ingot) and Graphite Block have lost their [Project E](https://minecraft.curseforge.com/projects/projecte) EMC values they had defined.

**Comment by sandalle** [comment]
I replaced two (out of the eight total) of the NuclearCraft Graphite Blocks in my 3x3x3 Fission Reactor with Extreme Reactors Graphite Blocks and my RF/t, efficiency, and heat stay the same. Thanks@

**Comment by turbodiesel4598** [comment]
Fantastic - thanks for confirming that worked :)
Having that sort of OreDict block checking sorted out has possibly changed the mod forever, in a good way. If I recall correctly, the only reason I ever added the cooler blocks was because I didn't know of a way to do it.
