### ISSUE TITLE
Fission Reactor does not allow for a "frame"

### ISSUE THREAD

**Issue by sandalle** [turbodiesel4598/NuclearCraft#135]
When building my first NuclearCraft Fission Reactor, I gave it a frame of Reactor Casing (e.g. full square shape):
![fission reactor - frame](https://user-images.githubusercontent.com/2447608/30661193-13ec1ff2-9df8-11e7-8d7e-2be878ce0e41.png)

I was told "Casing Incomplete" when opening the Fission Controller. Based on prior videos from a while ago, I then removed the frame and got a valid 3x3x3 reactor:
![fission reactor - no frame](https://user-images.githubusercontent.com/2447608/30661194-14efafc2-9df8-11e7-8b2f-79aece3851ca.png)

**Comment by turbodiesel4598** [comment]
There's not much I have been able to do about that - you can put casing in the corners, just not on the edges, as otherwise the structure will not be read correctly. I could go through the checking code and change it, but it would be so much work that I'm not sure it would be worth the trouble.

**Comment by sandalle** [comment]
I recall it was mentioned as "future state" in one of your developer videos a while ago, so thought I'd mention it. I didn't try the corner pieces before reporting, sorry.

Would it be easier to make a multi-block system, or is that what your checking code does (a la [Big Reactors code](https://github.com/ZeroNoRyouki/BigReactors)? If that helps (I'm not a java programmer, sorry :/ ).

**Comment by turbodiesel4598** [comment]
The fission controller's checking code is different to Big Reactors', as they obviously have their differences, but I have never actually looked at the BR code. They, essentially do almost the same thing, but there are two main differences:

1. NC reactors can share reactor walls, while BR reactors can't.
2. NC reactors can't have edges, while BR reactors can.

There isn't an easy way to allow both edges and shared reactor walls.
