### ISSUE TITLE
Crash with Mekanism digital miner 1.10.2

### ISSUE THREAD

**Issue by Grypher360** [turbodiesel4598/NuclearCraft#137]
I'm getting a crash with the Mekanism digital miner with this mod installed that appears to be similar to the Redstone mining crash that was resolved previously. I have tried with and without NuclearCraft installed and the crash only appears with this mod installed.

[https://pastebin.com/Z6gPWpYR](https://pastebin.com/Z6gPWpYR)

I'm afraid I wasn't able to find out what block it was trying to mine at the time.

**Comment by turbodiesel4598** [comment]
What's happeneing is that the block drop event is looking for a player and nullPointering. I will try to create a quick test fix for this tomorrow and send it to you :)

**Comment by turbodiesel4598** [comment]
Hopefully this should work: https://www.dropbox.com/s/uo0mapck7g6g633/NuclearCraft-2.4cMekFixAttempt--1.10.2.jar?dl=0

**Comment by Grypher360** [comment]
Brilliant, thanks for doing this for me :)
I'll give it a go and let you know.

**Comment by Grypher360** [comment]
Yep, that works perfectly!

Thanks again for this.

**Comment by turbodiesel4598** [comment]
No prob :)
