### ISSUE TITLE
Config to disable auxiliary item drops from ore

### ISSUE THREAD

**Issue by jesmores** [turbodiesel4598/NuclearCraft#139]
I'm trying to use Rockhounding Mod: Chemistry as my primary source for exotic materials, but currently Nuclearcraft drops beryllium dust when mining coal ore (and I think another item from quartz ore) and I couldn't find a way to disable them from the config. Can you add one (pref. one for each item)?

Minecraft 1.11.2
NuclearCraft 2.4a
Forge 13.20.1.2476

**Comment by turbodiesel4598** [comment]
Sure thing :)

**Comment by NillerMedDild** [comment]
Is this config under Ore Configs, the one titled "ore_drops"? If yes, which ores are 0-5?
The text doesn't seem to show as intended.

**Comment by jesmores** [comment]
It should be this line: 
https://github.com/turbodiesel4598/NuclearCraft/blob/04692cd417efae7c87bfbdf379b12c368935c89b/src/main/resources/assets/nuclearcraft/lang/en_US.lang#L936

Looks like the comment was put in gui.config.other while the config value itself is referencing gui.config.ores, that's why it didn't show up.

**Comment by NillerMedDild** [comment]
Ah thank you :) Will you be submitting the fix?
