### ISSUE TITLE
[1.12.2] Creative Item Bug

### ISSUE THREAD

**Issue by EmosewaGamer** [turbodiesel4598/NuclearCraft#141]
This is a bug that many mods have had when updating to 1.12.x, however, it's the first time I've seen it in a month. Bascally your items are on every creative page, vanilla and modded:
![image](https://user-images.githubusercontent.com/25333164/31049492-98eeb9a0-a634-11e7-8b44-fd4948f767bd.png)

**Comment by turbodiesel4598** [comment]
Yeh, noticed that - found the solution, so should have a fix out tonight :)

**Comment by turbodiesel4598** [comment]
Fixed in 2.5a :)
