### ISSUE TITLE
Plasma: prevent spawning fire

### ISSUE THREAD

**Issue by OneEyeMaker** [turbodiesel4598/NuclearCraft#142]
Hello.
Fluid Plasma (while placed in world, for example, by overheated reactor) very often spawns fire blocks *in the fluid itself* and and these blocks very rapidly disappear (because fire can't stay on fluid).
Placing and breaking block (and also updating light, produced by fire) causes update for block/chunk (I hope, you knew this). This behavior of plasma causes **such huge lags** (especially on client side), so anyone can't play in descent range around this fluid.

Please, remove this behavior from fluid plasma.
If you want some cool or realistic effets - look at such fluids like Pyrotheum and Cryotheum (from Thermal Foundation) and its effects.

Thank you for your work!

/*  
    MC 1.12.2
    Forge 2491
    NuclearCraft 2.5a
*/

**Comment by turbodiesel4598** [comment]
Good point - I will instead only have fire spawn in air blocks.

**Comment by turbodiesel4598** [comment]
Will probably make plasma act a little more like steam to be a little more realistic - hopefully will be much less laggy :)
