### ISSUE TITLE
Fluids do not have an image in JEI

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#144]
MC: 1.12.2
Forge: 2494
JEI: .102
NC: 2.5a

https://ibb.co/jAdX8w

**Comment by turbodiesel4598** [comment]
Yeh, I noticed that. It's peculiar, as they show up fine in the creative tab and inventory - I'll probably have to ask mezz about it.

**Comment by EmosewaGamer** [comment]
They do in the latest JEI version.

**Comment by D3nnis3n** [comment]
Yes, i can confirm that. I'll Close this issue therefore.

**Comment by turbodiesel4598** [comment]
Awesome :)
