### ISSUE TITLE
[Suggestion] Liquid Coolers spreading Liquid or inserting without direct insertion

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#145]
I would like to have an Option that makes the Liquid Coolers spread out fluids to other Coolers.

At the moment we got 4 14x14 reactors cooled by liquid Water. To get Water to every Block om the walls we Need hundreds of Pipes. That causes Standing even near One reactor to become an fps lagfest. Despite xnet no Pipes seem to be able to not lag in this amount in one chunk. Unfortunately xnet will only be a solution until enderio is back and can provide multiple conduits per block again, then we samt to remove it again.

**Comment by turbodiesel4598** [comment]
I guess something like that would be possible (perhaps a configurable mechanic), but could I ask how exactly you are getting the water to the coolers? Are you using a whole load of buffers or just a couple? With the latest update, by default, you should only need one buffer for every ~800 active coolers.

**Comment by D3nnis3n** [comment]
Sure. I'm using 2 of them per reactor at the moment. They sit diagonally near two of the edges. With one Buffer i had another meltdown as of Running put of fuel before. As i need to fully cover all sides with cooling blocks to sustain 60000 RFt, i need to put Pipes to nearly every cooler Block.

I could think of spreading the Liquid could be a Problem when using different Liquids in different Coolers. But to be honest, i don't See how such a Build is viable, as you loose much space für the insulated pipes of the Second Fluid. Also, even you did recommend to only use Water. Maybe there also is another possibility to fix this. That was just my idea.

**Comment by turbodiesel4598** [comment]
I recommended water in that video, but that was before I changed the amount of coolant the active coolers used - using the more expensive coolers is now definitely a viable option, as the active cooler now uses coolant very slowly.

Using different coolers shouldn't be a problem, as I can just check for whether the active cooler is already filled with a different type.

**Comment by D3nnis3n** [comment]
Water seems the most viable option for us, as for reality concerns and no TE installed. It would be great if we could save on some pipes :D

**Comment by turbodiesel4598** [comment]
Yeh, I'll look into adding the 'spreading' mechanic, and I'll make it a configurable effect :)

**Comment by D3nnis3n** [comment]
Great, thank you.

I do in now way want to nag you, but as i had posted many Posts in the other issue one after the other:
Did you see my request that i can not find any disabling of Zirconium or Manganese and that oxidized manganese cannot be created out of manganese dust in the oxidizer, what causes your maganese based Things to not work when dropping of rhodo-something has been disabled (as soon as it is possible?).

**Comment by turbodiesel4598** [comment]
Yeh, I did - I just replied to that :)
Which mod is it that's adding the Manganese dust? Because if the oxidising recipe isn't working, then I don't think they've added their manganese to the ore dictionary.

**Comment by D3nnis3n** [comment]
It's the *Metals Suite again. ModernMetals to be exact. It has an OreDict entry. dustManganese.

**Comment by D3nnis3n** [comment]
Works now. I'm dumb or the last update of *Metals fixed it. Sorry. :(

**Comment by turbodiesel4598** [comment]
Don't worry - at least it works now :)

**Comment by xenoflot** [comment]
Another vote of support for this. 

IIRC in the video you mentioned that the coolers were more effective (about 250%? water bumped from 20 to 50?) but still needed to satisfy their other requirements (e.g. water against the casing). Since pipes take up block space, that means that despite the boost, you're losing space where other coolers could be. In the case of water, one active cooler at 50H/t takes the space of two passive coolers at 40H/t. The effective bonus is thus dramatically reduced.

I'd much prefer to just pipe my fluids into a reactor port and let the reactor figure out how to get them to the coolers.

**Comment by turbodiesel4598** [comment]
As of the just-released version 2.8, this is a configurable mechanic. It will also allow energy to spread through electromagnets :)
