### ISSUE TITLE
[Question] How to get Neptunium-236

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#148]
How am i supposed to get this? I got loads of 237 by recyclicing LEN Fuel, but i can't seem to find out how i get 236 which i Need to craft Neptunium fuels. Also, the only recipes i can see for getting Neptunium 236 is recyclicing LEN or HEN fuel which both Need 236 to craft in the first place oO

**Comment by D3nnis3n** [comment]
Found it. Thorium is the way to go.

**Comment by turbodiesel4598** [comment]
Yeh - Thorium and HEU-233 fuels are the best sources of Np-236. Depleted HEU-233 is particularly Np-236 rich :)
