### ISSUE TITLE
[Suggestion] Add Mekanism Ore Processing Support to your Ores

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#149]
We use the *Metals Suite to make all Ores compatible with Mekanism, unfortunatley they have not got Thorium or Boron yet (but i suggested that for later). This means, both ores can not be processed with the different Mekanism Machines from 2x to 5x. This is the case with all your ores, but as we have Tin, Copper, Magnesium, etc. spawned by BaseMetals and not by NuclearCraft those can be processed.

You might ask why you should be able to get higher yield (even that much) out of those ores? Well i think they do Need processing in real life, too and we Play with a mekanism focused pack, on which the ore spawns are so low you HAVE to use Mekanism to get enough of everything. That Forces the Player to use the electricity Systems in place, especially your mod to create big values of those.

Afaik you would only Need to add shards, clumps, dirty clumps, dusts and a dirty and normal slurry for every ore and create compatibility.

I hope you consider this, at the Moment Thorium and boron are pretty rare :D

**Comment by turbodiesel4598** [comment]
I'll put it on the to do list, but it will take some time to get round to - I've got other things to get done that are more important, and, as you say, that metals mod may have that feature at a later date.

**Comment by D3nnis3n** [comment]
ModernMetals added Thorium, Beryllium and Boron to their mods. This could be closed if you do not plan on adding it yourself, then.

**Comment by turbodiesel4598** [comment]
Ah, ok, fantastic - if they've added it then I suppose I don't need to - thanks for the info :)
