### ISSUE TITLE
[Suggestion] Allow disabling ore-doubling in your factory

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#150]
This is related to mekanism also. As we want the Players to use the Mekanism Chain of ore processing, we do not want them to use any other means, we would Need to also Balance out. We already were able to remove every other method of ore-doubling, but it seems yours can't be disabled.

**Comment by turbodiesel4598** [comment]
I highly recommend CraftTweaker (I fell like I may have recommended this on an earlier topic). Using that mod's scripts, you can edit NC's recipes in any way you like.

**Comment by D3nnis3n** [comment]
Yeah, if MalisisCore wasn't incompatible with it in the only Version it is incompatible with Sponge, i would try to do that ...

**Comment by turbodiesel4598** [comment]
Ah, well that sucks... okay, I'll add a config option - should be simple enough.

**Comment by turbodiesel4598** [comment]
Added a config option that allows you to disable the Manufactory and Melter ore processing recipes :)
