### ISSUE TITLE
Missing Recipe for Graphite Dust

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#151]
Hey, i have got no recipe for Graphite dust. How am i supposed to create it?

**Comment by turbodiesel4598** [comment]
[It's made in the Manufactory using coal or coal dust :)](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/recipe/processor/ManufactoryRecipes.java#L28-L29)

**Comment by D3nnis3n** [comment]
Okay, i can not see the Manufactory when pressing U on coal. I can also not see ANY recipes when pressing R on Graphite dust. You might want to check that.

**Comment by turbodiesel4598** [comment]
Very bizarre - what version of NC are you using? [On the latest version, I see the recipes fine.](https://prnt.sc/gw174y)

**Comment by D3nnis3n** [comment]
2.5a. Pressing R on the coal dust does open nothing. But it'S interesting. If i press R in my inventory or in the JEI Screen on the right, nothing happens. Do i press it when i created it in the machine Output Slot of the Manufactory it DOES indeed Show. lol

So:
Graphite Dust in JEI Screen or Inventory -> R does nothing
Graphite Dust in the Output Slot of Manufactory -> R works.

**Comment by turbodiesel4598** [comment]
Could just be a strange bug somewhere - if you have any core mods installed, then sometimes weird stuff like that happens - you mentioned having Sponge installed earlier which might be doing something funny.

**Comment by D3nnis3n** [comment]
Nope, Sponge is now disabled for CraftTweaker, but that doesn't Change anything. Also Sponge is not installed on the Client, usually. It's a Server mod like bukkit was some years ago. :D

**Comment by xenoflot** [comment]
@D3nnis3n Check the binding of your R key. In packs with Inventory Tweaks, R is used for sorting the inventory and overrides JEI's R (even when hovering over the JEI panel).

It may also be related to your pack. I'm running AllTheMods3 and due to minetweaker scripts, there is no recipe for NC's graphite dust. The pack authors have changed the Manufactory to produce ExtremeReactors' version of graphite dust.

**Comment by D3nnis3n** [comment]
Its my own pack and nothing interferes with the r key. R on other items
work fine.

Am 19.11.2017 03:19 schrieb "xenoflot" <notifications@github.com>:

**Comment by xenoflot** [comment]
Not sure what's happening there but it must be a conflict of some kind. I just created a clean instance with only Forge 2517, JEI, RFTools and NuclearCraft 2.5a.  Hitting R over the Graphite Dust correctly brings up the recipe for creating Graphite Dust from Coal in a Manufactory.

**Comment by turbodiesel4598** [comment]
Can I ask if this issue persists?

**Comment by turbodiesel4598** [comment]
Going to close this as I think there is ample reason to think that this is not an issue on this mod's end.
