### ISSUE TITLE
[1.12+][Bug] Fission Reactor produces wrong amount of energy

### ISSUE THREAD

**Issue by OneEyeMaker** [turbodiesel4598/NuclearCraft#152]
Hello.
The title says it all - Fission Reactor produces wrong amount of energy (and also wrong amount of heat!).
Example: HECf-251 Oxide produces amount that LECf-251 should produce.

I spend more then hour to find source of this bug. I'm still not 100% sure, but I guess it is there:

https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/recipe/generator/FissionRecipes.java#L44

There should be ```count += 4```, because you register 1st and 2nd recipes first, then 3nd and 4th and in the next loop iteration you start again from 2nd and 3rd.
Maybe, there's bugs somewhere else (I didn't check).

Also, is it intended that configuration of **fusion** reactor is in code of **fission** one?
(https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/tile/generator/TileFissionController.java#L231)

**Comment by OneEyeMaker** [comment]
@turbodiesel4598 
Any news about this?

**Comment by turbodiesel4598** [comment]
Yeh, should be a simple fix - will sort it out when I have the time :)

**Comment by repete14** [comment]
Can confirm. Plopped a LEU-235-Ox into a reactor with 600% eff and 8 cells, and somehow producing 27648RF/T (should be 8064), and also far too much heat (surprise lava pool! 😃  ). I've made no adjustments to any of the default configs.

**Comment by turbodiesel4598** [comment]
Fixed by the above pull request :)
