### ISSUE TITLE
Compatibility with galacticraft machines seem to be broken, not referring to the air-sealed areas.

### ISSUE THREAD

**Issue by Ulisse54** [turbodiesel4598/NuclearCraft#153]
By doing a bit of research I found out that users were having problems with structure detection when they were building their reactors in air-sealed areas, this is not my case. I've tried to build a fission reactor outside and it did work, it generated power and all that.
However, electricity does not seem to be transmitted or accepted by GC electronics. I've enabled the "show units in RF instead of mJ" option in the GC3 config, and I've also made sure all of the "Refuse INPUT/OUTPUT from (any mod name)" were set to false, including IC2. I'm saying this 'cos I know how this mod really bases around it for some aspects.
This said, I hope you have time to check this issue, cheers.

**Comment by turbodiesel4598** [comment]
Sorry, been away for a couple months, but am back now - could you elaborate a little on the issue related to air-sealed areas and reactors?

As for the electronics issue... I will have to do some testing and will get back to you :)

**Comment by Ulisse54** [comment]
> could you elaborate a little on the issue related to air-sealed areas and reactors?
When I mentioned the air-sealed areas in the title, I tried to specify that this github issue I opened will not be talking about how structure detection is buggy in air-sealed areas, which is not my issue. I tried to exclude a topic in the title of the issue 'cos I know how someone already complained about structure detection not working in sealed areas, which again is not my issue.
What I was complaining about is that, if you put a galacticraft wire next to a fission controller(haven't  had a chance to test it using fusion reactors, I don't really use those a lot), it simply wont flux. This problem seems to be present only in GC dimensions and since I made this post I upgraded to the most recent version of nuclearcraft for 1.11.2, but the problem didn't go away, even if it is not as frequently occurring.

**Comment by turbodiesel4598** [comment]
Just tested with the latest versions of NC (2.5a) and Galacticraft - there doesn't seem to be an issue with GC power - the generators are outputting to the GC storage blocks fine, and the storage blocks are emitting to the machines fine too. As long as there is at least one GC wire between them, it works. It seems that the conversion between GC Joules and RF/FE happens in the cables rather than the storage blocks themselves.

**Comment by Ulisse54** [comment]
Alright then, I tested it too, it seems like cables are necessary-- putting a machine directly adjacent to a power source will not work. Sorry for bothering, I'm lurking to see what's new in the next update ;)

**Comment by turbodiesel4598** [comment]
There haven't been too many changes - mainly just a lot of bug fixing!
