### ISSUE TITLE
Steam Output for the Reactors instead of electricity

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#155]
I saw NuclearCraft has this on the Roadmap, but as i didn't know when i'd like to suggest it again.
It'll be much fun to have Steam coming out, which can then be reprocessed by Mekanisms Steam Turbine into electricity. This will make cancelling the Mekanism Fusion Reactor much easier, giving an extra layer of complexity and reality.

Also, well - i do not know - but shoudln't it be pretty easy to give the Reactor a steam Output instead of electricity? You woudln't Need to add steam turbines for the meanwhile, as there are many mods out there that do and could just be a config Option if one does like steam or direct electricity for now.

**Comment by turbodiesel4598** [comment]
Steam producing, molten salt fission reactors and steam turbines are on the to-do list :)

**Comment by turbodiesel4598** [comment]
The basic process is:
1. **Molten salt fuel** in **reactor fission vessels** -> **heat** and **depleted fuel**
2. **Coolant** in **reactor heaters** -> **hot coolant**
3. **Hot coolant** + **water** in **heat exchanger** -> **coolant** + **high pressure steam**
4. **High pressure steam** in **high pressure steam turbine** -> **energy** + **exhaust steam**
5. **Hot coolant** + **exhaust steam** in **heat exchanger** -> **coolant** + **reheated steam**
6. **Reheated steam** in **low pressure steam turbine** -> **energy** + **low quality steam**
7. **Low quality steam** in **condenser** -> **water**

**Comment by turbodiesel4598** [comment]
There will be a config option to allow for the heat exchanger to produce normal steam for use in Mek and ER turbines if wanted :)

**Comment by D3nnis3n** [comment]
No, i’d definatley prefer to go the full route that seems sticking to real life as most as possible. I hope Energy Output is higher then, as of the complexity.

Gesendet von Mail für Windows 10

Von: Tom Dodd
Gesendet: Donnerstag, 10. Mai 2018 00:38
An: turbodiesel4598/NuclearCraft
Cc: D3nnis3n; Author
Betreff: Re: [turbodiesel4598/NuclearCraft] Steam Output for the Reactorsinstead of electricity (#155)

There will be a config option to allow for the heat exchanger to produce normal steam for use in Mek and ER turbines if wanted :)

**Comment by turbodiesel4598** [comment]
Oh yes, the total energy output will be worth it - it won't be a ridiculous amount better, but definitely a good option if you have a lot of resources :)

**Comment by turbodiesel4598** [comment]
Steam production has been added in v2.12 :)
