### ISSUE TITLE
Typo in lang file

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#156]
Hey! I figured it'd be easier for you to fix this yourself, than to review a pull request.

ore_drops in the Ore Configs is referencing the wrong comment, and isn't showing properly.
It should be referencing
`gui.config.other.ore_drops.comment`

**Comment by turbodiesel4598** [comment]
Yep, discovered this while trying to fix another bug - will fix :)

**Comment by turbodiesel4598** [comment]
Sorted!
