### ISSUE TITLE
[1.12.2] 2.5a Reactor doors break in single punch, and do not drop

### ISSUE THREAD

**Issue by Thutmose** [turbodiesel4598/NuclearCraft#158]
Seems the reactor doors haven't had their hardness defined.  They also don't drop when broken, either via pickaxe, or via breaking the block they are sitting on

**Comment by xenoflot** [comment]
Confirmed!

**Comment by turbodiesel4598** [comment]
Should be a simple fix :)

**Comment by turbodiesel4598** [comment]
Fixed!
