### ISSUE TITLE
1.12.2 - Crash on opening gui of newly placed machines.

### ISSUE THREAD

**Issue by Thutmose** [turbodiesel4598/NuclearCraft#160]
It seems that getDisplayName in the tiles is called before blockType is set, this results in the following crash if you try to access the gui of a very freshly placed machine:

https://gist.github.com/Thutmose/b8c38dfdeeec54088786b15788d08d85

**Comment by turbodiesel4598** [comment]
Yes, discovered this a few weeks ago - will be a simple fix :)

**Comment by turbodiesel4598** [comment]
Fixed!
