### ISSUE TITLE
1.10.2 Fusion Reactor Not Exporting Neutron Fluid

### ISSUE THREAD

**Issue by CobaltDawg** [turbodiesel4598/NuclearCraft#162]
I've got a plan to use 3 reactors to generate fuel for one another. This involves a series of reprocessing, but I"ve run into an issue.

My first reactor is powered by Tritium and Deuterium which, according to JEI, is supposed to output Helium and Neutron Fluid.

Problem is, no matter where I connect my pipes, the reactor is ONLY exporting Helium. I can hook some pipes up and lead them into fluid tanks, and all that gets pumped into them is helium, but the reactor GUI shows that both helium AND neutron fluid are being exported no matter how many pipes I connect, regardless of location.

Is this a bug? I cant seem to figure it out.

**Comment by turbodiesel4598** [comment]
Let me see if I understand you - does the GUI say that neutrons are being pulled out, yet it ends up being helium, or are the pipes never pulling the neutrons out?

**Comment by CobaltDawg** [comment]
Ok! So I took a few minutes and built another reactor just to give you a better idea of whats going on.
Before I get too far though, remember that this is NuclearCraft V2.5A running on a 1.10.2 server using the AllTheMods modpack, Ver. 3.00.0

Here is the reactor setup:
Fusion reactor
Tritium and Deuterium Fuel Input
Toroid Size 4
Two output tanks connected to EnderIO Pressurized Fluid Conduits
Both output pipes are isolated. They do not intersect anywhere. Each leads from the reactor straight into a dedicated fluid tank.
Both tanks fill with helium. Attaching a third line and tank also fills with helium.
If I break the fluid output pipe and attach a fluid tank set to Insert the fluid from the pipe, I get neutron fluid. 
Screenshots are attached.
![1](https://user-images.githubusercontent.com/33181983/32416776-ba77796e-c21c-11e7-8b5a-7947f8e71b87.PNG)
![2](https://user-images.githubusercontent.com/33181983/32416777-c7f20bd6-c21c-11e7-91e1-663116486f3d.PNG)
![3](https://user-images.githubusercontent.com/33181983/32416779-d1b56b40-c21c-11e7-95b4-e86fa9ae79b0.PNG)
![4](https://user-images.githubusercontent.com/33181983/32416786-e48701ac-c21c-11e7-8e7e-abcb3160ddb8.PNG)
![5](https://user-images.githubusercontent.com/33181983/32416788-ecef7acc-c21c-11e7-8b6c-05560d8af729.PNG)
![6](https://user-images.githubusercontent.com/33181983/32416793-f5bfbda6-c21c-11e7-96b4-74192863bd2e.PNG)
![7](https://user-images.githubusercontent.com/33181983/32416800-fd4c665a-c21c-11e7-8306-486be5b5459b.PNG)

I've scoured over your youtube videos looking to see if there is anything about this particular event, but I've not found anything. I've tried attaching the pipes to different areas of the reactor, attaching and running one output line before the other, etc. Just cant seem to figure out what the issue is.

Thanks for your time and quick response! I look forward to the results.

**Comment by turbodiesel4598** [comment]
The reason this happens is because the output buffers are emptied one by one - the way to fix this is by filtering which fluids are extracted by each of the pipelines. So when the helium is extracted, get some from the tank and whitelist the first conduit to extract helium only and blacklist helium on a second conduit. Then you will be able to pull the helium and neutrons out separately :)

**Comment by turbodiesel4598** [comment]
Closing this issue as there doesn't actually appear to be any issue.
