### ISSUE TITLE
[Question] Should reactor ports be considered casings?

### ISSUE THREAD

**Issue by xenoflot** [turbodiesel4598/NuclearCraft#164]
I've noticed that reactor ports are not considered casings for the purpose of the coolers. I was stumped for a while when a reactor that I *knew* was overcooled, suddenly was undercooled :-D

I can see reasons both for and against. If they're not casings by design, it might be worth noting that in the tooltip.

As an aside, the texture difference on the front face is awfully subtle. Might be worthwhile making it a little more obvious!

Cheers!

**Comment by turbodiesel4598** [comment]
Yeh, this is a bug - the ports should be treated as casing for the purpose of cooler-checking, but I forgot to add them to the list of blocks to look for - should be a simple fix :)

**Comment by xenoflot** [comment]
Worth checking to see if the Reactor Door is on the list, too.

**Comment by turbodiesel4598** [comment]
Should be fixed for the next version :)
