### ISSUE TITLE
About distribute this mod

### ISSUE THREAD

**Issue by sxjeru** [turbodiesel4598/NuclearCraft#166]
( Sorry, my English is poor. ) 
Hi Tom. I read the permissions you wrote. But I don't understand that. 
So I want to ask a question: "Can I distribute this mod to [mcmod.cn](http://www.mcmod.cn/) ? "
( mcmod.cn ( mc百科 ) is a Minecraft's mod wiki from China. )
I think you know, in China, Minecraft's players hard to visit the Curse. So please give me the permission.
Thx.

**Comment by turbodiesel4598** [comment]
Yeh, no problem! Go for it :)

**Comment by sxjeru** [comment]
I appreciate your support.
Thanks very much!!
