### ISSUE TITLE
Breaking a Fusion Core drops non-craftable version as well

### ISSUE THREAD

**Issue by xenoflot** [turbodiesel4598/NuclearCraft#168]
Hi,

Playing AllTheMods3 ver 4.4 and trying to put together a Fusion reactor at the moment.

I've found that if I break the 3x3 fusion core _**on either of the bottom two layers**_, I receive the craftable block with the white trim, AND one of the non-craftable blocks. If I break it on the top layer (from the top or a side face), I don't get the non-craftable block. In all cases, I get back the craftable block OK. 

To clarify, JEI shows three items called Fusion Core, two of which lack the white trim and have no recipe. /cofh hand reports [Fusion Core] for both, so I can't provide more info there, sorry.

MC 1.12.2
Forge 14.23.0.2517
NC 2.5a

**Comment by NosajDraw** [comment]
@xenoflot try "/mt hand" it should give you the full name.

**Comment by xenoflot** [comment]
/mt hand reports:
Item <nuclearcraft:fusion_dummy_side>
No OreDict Entries

**Comment by turbodiesel4598** [comment]
Wow, can't believe I never noticed this - fixed!
