### ISSUE TITLE
[Request] Clarify tooltip on Superconducting Electromagnet

### ISSUE THREAD

**Issue by xenoflot** [turbodiesel4598/NuclearCraft#170]
So... I just built a ring of 352 superconducting electromagnets but the fusion core reported the ring was incomplete. Then I just read a note in a closed issue suggesting that the superconducting magnets are for a future particle accelerator. D'oh!

The fusion core tooltip just specifies "electromagnet". Might be worth adding "Not suitable for Fusion reactors" to the tooltip for the superconducting ones!

**Comment by turbodiesel4598** [comment]
Due to the details of the tooltip code, adding an extra line of tooltip info would cause the 'hit Shift for more info' to appear, and so the player might miss the information... how about changing the name 'Electromagnet' to 'Fusion Electromagnet' and being more specific in the Fusion Core tooltip?

**Comment by trevorjd** [comment]
Sounds good to me!

**Comment by turbodiesel4598** [comment]
Done!
