### ISSUE TITLE
Add a formal license

### ISSUE THREAD

**Issue by josephcsible** [turbodiesel4598/NuclearCraft#172]
Can you add a formal license to this mod's source? If you're unfamiliar with them, here's some popular options from most permissive to most restrictive:
- MIT license (lets people do pretty much whatever they want as long as they give you credit for your work)
- GPL/LGPL (requires that forks also have their source be GPL/LGPL so that your source remains open)
- CC-BY-NC-SA (also doesn't allow making money off of it)

**Comment by NosajDraw** [comment]
The "Permissions" section is pretty vague, but if I have the spirit correct, you may also want to consider dedicating the mod to the public domain, but be mindful if you go that route, what that actually means, it means anyone can use your code in anyway they want without any reference of any type to you.

**Comment by sxjeru** [comment]
I also think this is necessary. And I also have the same problem.
#166

**Comment by turbodiesel4598** [comment]
Ok, I guess the license would vaguely be an MIT one, but a bit looser - I'll put one into the GitHub description :)

**Comment by josephcsible** [comment]
Hmm, by that amendment, it sounds like you actually want this to be public domain. You may want to consider explicitly using [CC0](https://creativecommons.org/publicdomain/zero/1.0/) or the [Unlicense](https://unlicense.org/) to do that rather than "MIT with an amendment".

**Comment by turbodiesel4598** [comment]
CC0 it is!

**Comment by josephcsible** [comment]
Awesome!

(Can you also mark this as public domain on CurseForge? It currently still says All Rights Reserved there.)

**Comment by turbodiesel4598** [comment]
Will do :)
