### ISSUE TITLE
[Suggestion] Ocean Mining

### ISSUE THREAD

**Issue by Thutmose** [turbodiesel4598/NuclearCraft#174]
Ocean water IRL is full of a random assortment of elements, many of which are currently used in this mod.  It would be interesting to have a machine that processes the sea water, and produces small amounts of the various materials, as an alternate way of getting things like calcium sulphate, lithium, flourine, uranium, etc.

It could probably be done with a machine that takes in the water, then has a chance of producing random output materials, weighted however you think best to balance the resource gain from it.

You can find the values for the real ocean here: http://oceanplasma.org/documents/chemistry.html though it also varies drastically based on salinity and proximity to volcanic vents

**Comment by turbodiesel4598** [comment]
I think that's a really cool suggestion - consider it on the to do list! I've been meaning to add a 'random' component to the recipe system, but never quite had the motivation to do it, but this is a good reason to get it sorted.

**Comment by xenon54xenon54** [comment]
This also seems like a good way of introducing new materials. Sodium and chlorine aren't in this mod, and it would be interesting to see molten sodium (or NaK) coolant and tetrachloride fuels for MSR's.

**Comment by turbodiesel4598** [comment]
Since I'm using molten FLiBe as the solvent for the molten fluoride fission fuels, molten NaK might be something I could add as a coolant base instead of just using FLiBe again... would probably have to skew the products a little bit to make potassium a bit more common, and would need to come up with other uses for the excess sodium, but otherwise, that should work nicely :)

**Comment by Thutmose** [comment]
liquid sodium as a heat exchanger for fission reactors maybe? [EBR-II](https://en.wikipedia.org/wiki/Experimental_Breeder_Reactor_II) was a rather successful liquid sodium cooled reactor.

**Comment by turbodiesel4598** [comment]
Thing is that I'm probably going to end up using NaK-based coolants (NaK mixed with the various active cooler materials) as the primary coolant - it will be heat exchanged with water to produce superheated steam which then goes through a process of high pressure turbine -> boiler -> low pressure turbine.

I guess it could be used to produce sodium hydroxide, which has a bunch of uses. There's also the chlorine to think about, but again, there are a lot of uses for that.

**Comment by Thutmose** [comment]
If you did have a pressing need to provide a use for sodium itself, you could implement some form of liquid metal coolants, ones used irl were sodium (best for life of the reactor) or lead-bismuth (self shielding for the gamma radiation), you could probably get away with just using lead instead of the lead-bismuth (which was used due to lower melting point)

The main advantage of the liquid metal ones over the salt ones is the significantly lower temperature of the coolant, which means you can use them with conventional, solid fuel reactors, infact, if you use metallic fueled fission reactors, with liquid sodium coolant, they can be configured in such a way that it is physically impossible for them to overheat, EBR-II was an example of one of these.

**Comment by xenon54xenon54** [comment]
The ocean mining process could be incredibly expensive, too. Currently there aren't any real energy sinks in this mod besides overclocking normal machines with speed upgrades, so this could be a really slow and costly process that needs the full power of a reactor. It might even become a challenge to make reactors efficient enough to run only on the nuclear material extracted from the ocean and output a bunch of raw material in the process.
So we need to figure out whether it makes sense to have the miners/filters run on water from infinite water sources, or only on water from or in the ocean, and also if they output pure/distilled water which is not useful for filtration, but useful for chemical production.

**Comment by turbodiesel4598** [comment]
I think I'll probably close this for now - although I had this on the to-do list for some time, I think the rock crusher pretty much now does the job that such a feature as this would have.
