### ISSUE TITLE
BUG : Ingot Former and Speed upgrades

### ISSUE THREAD

**Issue by NosajDraw** [turbodiesel4598/NuclearCraft#175]
It's possible to insert 40 or more speed upgrades into the Ingot Former, however doing so, prevents any ingots from being produced, as the machine starts to create a new ingot before the previous one has finished.

**Comment by xenoflot** [comment]
Is it that, or is it a power problem? When I put in "too many" speed upgrades, it seemed to me that the progress reset to zero when it ran out of power. As speed upgrades increase power geometrically, there's going to be a point where the burn rate of energy exceeds the 32K buffer so it'll get part-way through an operation, find the buffer is empty, reset to zero and start all over.

**Comment by turbodiesel4598** [comment]
Are you sure you are giving the ingot former enough power? I can install 64 speed upgrades and, with an adjacent creative energy cell, form ingots without a problem.

**Comment by turbodiesel4598** [comment]
Ok, machines have now been modified to have their energy buffers increase if a lot of speed upgrades are added - this will make sure that the buffer is always at least big enough to deal with the large power draw that very upgraded machines require :)
