### ISSUE TITLE
Suggestion : Ingot Former power usage

### ISSUE THREAD

**Issue by NosajDraw** [turbodiesel4598/NuclearCraft#176]
The Ingot Former uses huge amounts of power, which seems odd, very odd, especially when compared to other methods of creating ingots from other mods.

Whilst creating the fluid form of the metal should take good amounts of power, creating the ingots I suggest should be almost if not actually power free.

**Comment by turbodiesel4598** [comment]
You're right, it probably should be power free - I suppose, by default, I can just have it use no power. I can then add a bit of GUI code that say if a machine doesn't require power, don't show the power bar and don't connect to power cables.

**Comment by turbodiesel4598** [comment]
Fixed!
