### ISSUE TITLE
Catch-22 on initial RF generation

### ISSUE THREAD

**Issue by xenoflot** [turbodiesel4598/NuclearCraft#179]
Hi TD,

I've noticed there's a catch-22 on getting started with RF generation. Both the Basic Solar Panel and the Uranium RTG require crushed materials for crafting, however the Manufactory needed to crush them needs RF. Unless I'm missing something, it's necessary to have an RF provider from another mod in order to get started with NC.

Suggestion 1: Add a quartz glass recipe oreDict'd with AE2's quartz glass and use three pieces of that as the top layer for the solar panels, instead of crushed quartz and crushed graphite.

Suggestion 2: Let Graphite be created by smelting Coal in a regular furnace (as is done in BigReactors) and smelt the Graphite Bars into Crushed Graphite in a regular furnace.

Cheers!

**Comment by turbodiesel4598** [comment]
I see the issue - how about adding an extra inefficient recipe for the solar panel that uses quartz blocks instead of crushed quartz?

**Comment by turbodiesel4598** [comment]
I see the issue - how about an extra inefficient Uranium RTG recipe using 6 lead ingots, 2 coal blocks and a block of uranium?

**Comment by jesmores** [comment]
Make it work like a single-use battery (i.e. has a non-refillable RF buffer) and I think that would work.

What about a potato battery? :P I don't think I've seen a mod do potato batteries before, Would be funny, using potatoes to start with nuclear power.

**Comment by turbodiesel4598** [comment]
I'd rather not have to add pre-charged battery blocks or implement RF-holding items as they're both a massive pain.

**Comment by trevorjd** [comment]
> how about an extra inefficient Uranium RTG

Not a fan. The Uranium RTG already produces a mere 4RF/t.  If xenoflot's (my, logged in with wrong acct) suggestions don't grab you, perhaps you could just add a coal-burning generator?

**Comment by turbodiesel4598** [comment]
The thing is that most people play this mod in big packs which almost certainly already have other mods which add coal generators - I'd like NC's initial power gen to be a little more unique than that, or there's basically no point spending my time adding it.

An idea I had a while back was a very cheap heat converter that used the heat generated by radioactive decay in adjacent blocks to generate RF - if they generated, say, 4 RF/t per adjacent uranium/thorium block, placing a few of these down could certainly get you started.

**Comment by jesmores** [comment]
My point re. single/temporary use is to discourage people from just spamming the (what is essentially an all-day solar panel) simple RTG block for mass power gen. If you're averse to implementing some form of RF-storage, what about just making the block expire after a certain number of ticks? Kind of like a half-life I guess?

The heat converter is pretty good too, since it makes it no longer be a one-block infinite power provider. Also could make it randomly consume the heat-producing adjacent blocks to further discourage people from staying at that (earliest) tier.

**Comment by turbodiesel4598** [comment]
I guess I could have it delpete the uranium/thorium blocks after a certain amount of time...

**Comment by turbodiesel4598** [comment]
Ok, I think this is sorted - the generator uses the heat of adjacent thorium and uranium blocks to generate energy - thorium and uranium blocks generate 4 RF/t each, while the depleted thorium and uranium blocks generate 1 RF/t. After an average of ~30 mins, thorium and uranium blocks will decay and deplete.

Hopefully this works as a nice way to start generating power in NC :)

**Comment by trevorjd** [comment]
Love it! Thanks!

**Comment by turbodiesel4598** [comment]
Cheers :)

The depleted blocks have been slightly nerfed in v2.7 to produce 0.5 RF/t so that Uranium RTGs aren't made redundant.

**Comment by trevorjd** [comment]
Bah! /goes back to edit the wiki page he just wrote :D

**Comment by turbodiesel4598** [comment]
Uh.. sorry... :P
