### ISSUE TITLE
Server crash on start with 1.6d

### ISSUE THREAD

**Issue by kwpugh** [turbodiesel4598/NuclearCraft#18]
Crash report: http://pastebin.com/raw/DhNQ3XeN

**Comment by turbodiesel4598** [comment]
Did you download the mod really soon after it was initially released? If so, you may have unfortunately got a dud version - try downloading 1.6d again, and see if you get the same problem.

**Comment by kwpugh** [comment]
Re-downloaded it and it seems fine.  Thanks.

**Comment by turbodiesel4598** [comment]
Phew - glad it worked ;)
