### ISSUE TITLE
Fusion plasma persists for non-powered, cold reactors.

### ISSUE THREAD

**Issue by Thutmose** [turbodiesel4598/NuclearCraft#181]
I had a reactor which was cooled all the way down, yet the plasma persisted in it

the following should probably be changed to exclude the powered check:

https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/tile/generator/TileFusionCore.java#L307

I think the complete check might also be an issue?

**Comment by turbodiesel4598** [comment]
For some reason the line I think you were referring to has moved - are you saying that the plasma is persisting even if the reactor is allowed to cool back to below 8 MK?

**Comment by Thutmose** [comment]
Ya, the line does seem to have moved, but yes, I had a reactor that cooled all the way down, yet still had plasma in the ring.  It had an electromagnet burn out, but even when that was replaced, the plasma still persisted
https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/tile/generator/TileFusionCore.java#L300
I think it was this line that I had originally looked at?

**Comment by turbodiesel4598** [comment]
Ah, I see, so the ring was incomplete, then the core went below 8 MK, then the ring was fixed and the plasma persisted?

**Comment by Thutmose** [comment]
yep

**Comment by turbodiesel4598** [comment]
Ok, I think I have fixed the problem - now the plasma will appear when the reactor starts processing, and will be removed either when the fuel runs out or the reactor is too cool and the ring is complete, whether or not it was previously broken.

**Comment by Thutmose** [comment]
Thanks, it was a bit strange that the plasma persisted even when it was repaird, cool and out of fuel :D

The original reason why the electromagnet burned out was that the fuel ran out for the reactor, which made the power for the electromagnets run out, and then the plasma burned one of them.

**Comment by turbodiesel4598** [comment]
I think the only reason I never noticed the issue is because I've never actually let a reactor sit and cool down before :P

And yes, usually my reactors get damaged by the same thing... the penalty for this has changed a bit now, as the previous plasma mechanics were insanely laggy. The unpowered electromagnets will now have a small chance of exploding every tick if in contact with the plasma, and the plasma will no longer place fire inside itself - this was what was causing the lag as the fire and plasma were rapidly replacing each other all over the place.

**Comment by Thutmose** [comment]
ya, we noticed the reactor had run out of fuel from the sudden lag spike on the server :D

**Comment by turbodiesel4598** [comment]
I guess you'll now have to start listening out for explosions instead...

**Comment by Thutmose** [comment]
ahh, those I already have to listen for.  The boomrocks<sub>(Gravelers)</sub>, boomseeds<sub>(Pinecos)</sub> and boombags<sub>(Weezing)</sub> tend to make rather large ones at inconvienent times and places.

**Comment by turbodiesel4598** [comment]
At least there are no Voltorbs or Electrodes...

**Comment by Thutmose** [comment]
ahh, there are those as well, but they only spawn currently if you place too many vanilla "Tech" blocks (furnaces, hoppers, droppers, dispensers, etc) around.

I really need to start adding default compat configs for modded blocks for that.

**Comment by turbodiesel4598** [comment]
That sounds dangerous!
