### ISSUE TITLE
[1.12.2] No CraftTweaker integration

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#183]
Hey!

When I try to make CraftTweaker scripts for NuclearCraft machines, I get the error message "nuclearcraft is not a module" - Is it not yet implemented in this version? I used the syntax from the CraftTweaker doc in the root of this git.

Minecraft 1.12.2
Forge 1.12.2 - 14.23.1.2556
NuclearCraft-2.5a--1.12.2

**Comment by turbodiesel4598** [comment]
Turns out that there was some extra code necessary to register the recipe addition and removal methods which I was not aware of - this has been fixed by TheGuyRunningSouth in a pull request :)

**Comment by NillerMedDild** [comment]
Cool, thanks the both of you :D
