### ISSUE TITLE
Cannot add capabilities to dummy tiles.

### ISSUE THREAD

**Issue by Thutmose** [turbodiesel4598/NuclearCraft#184]
The forge capability system allows adding capabilities to other mods' TEs via an event.  This cannot be done for the TileDummy classes, as they return "null" when getCapability is called for anything other than the hardcoded capabilities.

https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/tile/dummy/TileDummy.java#L455

This null should be replaced with super.getCapability.

**Comment by Thutmose** [comment]
If the fix for #182 also fixed this one, it should probably be closed

**Comment by turbodiesel4598** [comment]
I think this will now be fixed by the changes made in response to #182 , so sure, I'll close it.
