### ISSUE TITLE
Machines stop updating in 1.12

### ISSUE THREAD

**Issue by ZeekDaGeek** [turbodiesel4598/NuclearCraft#187]
NuclearCraft-2.5a--1.12.2.jar
Mincraft 1.12.2
Forge 14.23.1.2556

NuclearCraft in 1.12 is very very broken, any time a tile entity, excluding reactors, goes idle it will not start up again unless updated by redstone being placed next to the machine. This makes the mod very unplayable or ridiculous to keep running.

Here is my solution to the problem at the moment which is silly:
![Stupid machine.](http://zeekdageek.tv/ss/oGZw8.png)
_Mechanical user placing redstone on top of a machine. Block breaker breaking it and cycling it back into the mechanical user._

**Comment by 28Smiles** [comment]
In 1.12 Nuclearcraft has Problems with RF, for now use Immersive Engineering cables.

**Comment by ZeekDaGeek** [comment]
Well that doesn't really solve the problems because it also happens with items and liquids as well. All of the inputs and outputs become inaccessible, not just power.

![Dead tile entity](http://zeekdageek.tv/ss/X1Rgk.png)
_Water will not be pumped in and gases cannot be pumped out using Thermal Expansion pipes._

**Comment by 28Smiles** [comment]
I play with this mod in 1.12 and i also automated the electrolyser.
For the Fluids use also Immersive Engineering pipes (simply put one at the end of your TE Liquid pipe).
For export I use Fluid Import Bus but mekanism pipes or immersive engineering again, also work.
Nuclear Craft doesn't work with Thermal Expansion in 1.12.

**Comment by 28Smiles** [comment]
For Items use Hoppers for export (I did not test import).
And Applied Energistics export or interfaces for import into the machine.

**Comment by turbodiesel4598** [comment]
Would just like some clarification - is the issue that NC machines aren't updating correctly in general, or that they aren't playing nice with TD ducts?

**Comment by 28Smiles** [comment]
In my opinion it's just a problem with TD Item, Fluid and Flux Ducts.
But till now I could not isolate the Problem. You may should look into the TD Code and compare it with what others do.

**Comment by Thutmose** [comment]
I have had issues with NC machines not taking power properly from Immersive Engineering connectors, they just stall at some point.  I found a solution of placing an uranium RTG touching the machine seems to fix it.

Could it be something to do with the way the NC machines pull power?

**Comment by turbodiesel4598** [comment]
The way RF and Forge Energy used to work (it may not now) was that energy sources _pushed_ energy and energy sinks _accepted_ energy. The sources could no be pulled from and the sinks did no pulling.

**Comment by Thutmose** [comment]
The bug also affected Integrated tunnels energy tunnels, here is what I ended up having to do:
Electrolysers:
![image](https://user-images.githubusercontent.com/2363472/33739925-d9150102-db6c-11e7-9894-52636fb4d119.png)
supercoolers:
![image](https://user-images.githubusercontent.com/2363472/33739969-fb91bfb8-db6c-11e7-8a70-d7c3ba410e1b.png)

Could it be an error in the code NC uses for saying how much power it requires? when sources push energy, they often do a check to see how much power is needed, all of the machines I had that were affected had speed upgrades in them, infact, I didn't notice the bug at all until I added speed upgrades

**Comment by Thutmose** [comment]
This one never stalled for example:
![image](https://user-images.githubusercontent.com/2363472/33740050-464d990a-db6d-11e7-9639-3ecccf17c3b6.png)

The hoppers are for avoiding that crash from when it checks blocktype for opening gui :D

**Comment by turbodiesel4598** [comment]
Turns out this is also a 1.10/11.2 bug - again, it's only certain conduit types such as thermal dynamics that don't work. Will do some searching!

**Comment by turbodiesel4598** [comment]
Ok, after a lot of testing, for now, I am forced to conclude that this isn't an NC bug, or at least is not solely an issue with NC - I just tried setting up a simple furnace automated using ducts and the item movement was totally broken.

The only solution for now is to not have the block texture change when it starts/stops running, so for now, that will have to be disabled until I find a better solution.

**Comment by turbodiesel4598** [comment]
I already tried this after a conversation on the Forge forums to no avail. The issue seems to be rooted in the fact that NC machines are comprised of two individual block types - one for each texture (idle and active). When the block type changes, some pipes such as TD's or Integrated Tunnels' forget that the machine is there.

For whatever reason some pipes/wires such as EnderIO's or Galacticraft's have been made to cope with something like that happening.

**Comment by Thutmose** [comment]
Ahh, then you should probably swap to using a different blockstate instead of the seperate block entirely, here is an example of one of my tiles that is rotatable and has a boolean based block state if it will help:

https://github.com/Thutmose/Pokecube/blob/1.10/Pokecube%20Core/src/main/java/pokecube/core/blocks/tradingTable/BlockTradingTable.java

Not sure what the scope of the changes for that would encompass though...

Do the Integrated Tunnels/TDs work with vanilla furnaces? those work like yours currently do...

**Comment by turbodiesel4598** [comment]
Exactly - I think it would be a reasonably simple change code-wise, but it would probably be a major game-breaker, so I will have to make sure it is very clear that updating to a new version where that change had been made would potentially break a lot of machines, especially if active.

Thermal Dynamics ducts don't play nicely with the vanilla furnace at all, no.

**Comment by Thutmose** [comment]
If you push the current changes you have to github, I can see about looking at it on my end, if you have a simple way to replicate the issue in development environment, I can at least look into the rotation issue.

**Comment by turbodiesel4598** [comment]
Sure thing - I'm about to release 2.6, and I will then update the repo :)

**Comment by Thutmose** [comment]
Ok, once that is updated I will look into the rotation issue, that at least is something on NC's side, if the ducts don't like vanilla furnaces either, I will assume that is their problem instead, and wait for that to be fixed before looking into any fixes for NC.

**Comment by EmosewaGamer** [comment]
Well technically it's NC's fault because its machines act like Furnaves, which we already established don't work well with most mods' piping.

**Comment by Thutmose** [comment]
That is the fault of most mod's piping.  Mods should always work with vanilla blocks.
