### ISSUE TITLE
Rotating machines loses items in 1.12.

### ISSUE THREAD

**Issue by ZeekDaGeek** [turbodiesel4598/NuclearCraft#188]
NuclearCraft-2.5a--1.12.2.jar
Mincraft 1.12.2
Forge 14.23.1.2556

Rotating any machine will lose all of the contents of the machine in 1.12. Apparently this is because Forge causes all tile entities to be rotatable by default and if you don't support it properly it will cause issues.

**Comment by turbodiesel4598** [comment]
Yep, noticed this myself - will sort it out.

**Comment by turbodiesel4598** [comment]
Ok, I will have to work out how rotation of tile entities work, but for now, I have just diasbled rotation so that nobody accidentally loses their stuff.
