### ISSUE TITLE
[Suggestion] Blocks for Pu, Am, Cm...

### ISSUE THREAD

**Issue by xenon54xenon54** [turbodiesel4598/NuclearCraft#190]
When I am refining a ton of uranium and thorium, I build a huge wall of depleted uranium and thorium. It would be really amazing to make a wall out of Plutonium or Neptunium too, even if it's just a simple recolor of other blocks.

**Comment by turbodiesel4598** [comment]
It would be easy but would take a while - there are quite a lot of isotopes that would have to be given blocks!

**Comment by xenon54xenon54** [comment]
Yeah, seems like another thing to put on the long term to-do list then.

**Comment by ASDFGHT0** [comment]
One thing to keep in mind with this is that it would not be physically realistic to have blocks of some of those isotopes. In particular, a block made from any of the fissile isotopes would be well above that isotope's critical mass, and some of the shorter-lived isotopes such as Pu-238 would generate excessive amounts of heat. This leaves us with the possibility of having blocks of Np-237 (dangerous, as it is fissile to fast neutrons, but not thermal neutrons), Pu-242, possibly Am-243, Li-6, Li-7, B-10, and B-11. Th-232 would also work, but the 3x3 recipe to make a block is also used to make TBU fuel (at least in the 1.7.10 version.)

**Comment by xenon54xenon54** [comment]
If we’re talking about realism and half lives, then all the Cf isotopes would be putting off so much energy that they would glow at least orange hot in bulk form, and that’s hoping that a chain reaction doesn’t start from a stray neutron, say, from a nearby nuclear reactor? But if the heat from these radioactive isotopes is taken into account, then realistically, all the Cf and some Am and Cm would make economical RTG’s. Also, critical masses taken into account, a stack (items) of any radioactive isotope you listed minus Th-232 and Pu-242 would be more than enough to fizzle, depending on how volume works in inventories (another story). Critical masses would also be awesome to implement, but probably a lot harder, and not for this thread.

**Comment by turbodiesel4598** [comment]
Added in version 2.8 :)
