### ISSUE TITLE
[Suggestion] Configs to disable the ore blocks themselves

### ISSUE THREAD

**Issue by Vyraal1** [turbodiesel4598/NuclearCraft#192]
Hi, 

This is kind of a nitpicky request, but would it be possible to change the configs for ores so instead of disabling the ore generation, it just disables the ore blocks themselves from being registered? This just saves some pack makers the time from having to also hide the ore itself from JEI and/or removing it from ore dictionary if they wanted to keep their ores to only one texture/chosen block after disabling it.

Thanks!

**Comment by turbodiesel4598** [comment]
It's a little dangerous for configs to determine whether or not blocks are registered - if two people have different config options for some reason it would lead to crashes.

How about an ore config that determines whether the ores get removed from the ore dictionary and removed from JEI?

**Comment by turbodiesel4598** [comment]
Seems to work nicely - if this config is enabled, then you basically won't be able to notice that the disabled NC ores or their products even exist :)
