### ISSUE TITLE
[1.12.2] 4 Ores missing in JEI 

### ISSUE THREAD

**Issue by danikk14g** [turbodiesel4598/NuclearCraft#193]
Hello,
i tried today the current version of NuclearCraft for 1.12.2, last time i played it was in 1.7.10, but i noticed 6 ores are missing in the JEI, but they are showing in the creative tag of NuclearCraft Base Blocks.
Ores not appearing in JEI are Uranium, Copper, Tin and Lead.

I didn't change the default config, which is enabling all the ores and

-#Remove disabled ores from the Ore Dictionary and JEI?
    B:hide_disabled_ores=false

Also i dont see anymore Silver and Plutonium ores from 1.7.10, is this intended or there is any plan to add them again in future versions?

Thanks.

**Comment by turbodiesel4598** [comment]
Hmm, that's very bizarre - I have a fresh 1.12.2 profile with NC installed, and none of them are missing. I don't see any reason why those particular ores would be missing, either. Can you even see those ores in recipes, such as the recipe for copper dust in the manufactory as it cycles through all of the ore dict entries for copper ore?

And no, silver and plutonium ores are no longer in the mod.

**Comment by danikk14g** [comment]
Sorry for taking so long to answer, i was busy with Uni this week, 
I tried removing some mods and as you say, i can see again the ore and all its uses in JEI

The mod causing this is UniDict-1.12.2-1.7, it was my fault not to notice this mod unifies several ores into one, thats why i couldn't see any uses for the Uranium Ore either.

Sorry for taking ur time for nothing and thanks for the mod

**Comment by turbodiesel4598** [comment]
No worries - have a good chrimbo :)
