### ISSUE TITLE
[1.7.10] Electrolyser simply doesn't work.

### ISSUE THREAD

**Issue by recolic** [turbodiesel4598/NuclearCraft#199]
Game version := 1.7.10-Forge10.13.4.1614
Mod version := NuclareCraft 1.9f
Environment := Single player + Multi player

I put empty fluid cell in, and gave enough RF, as what recipe(provided by NEI) says. However, nothing happened.
I tried to add Energy Update and Speed Update, but it doesn't help.

Is it caused by an outdated recipe? Screenshots attached below.

![my recipt](https://recolic.net/tmp/snap-1225-131213.png)
![NEI guide](https://recolic.net/tmp/snap-1225-131232.png)

**Comment by turbodiesel4598** [comment]
As of version 1.8 or so, the Electrolyser requires water to be pumped into it as well as power - that little bar beside the input slot is the internal water tank.
