### ISSUE TITLE
[Suggestion] Change the key 'U' into 'R' to display recipe info for Water Cells

### ISSUE THREAD

**Issue by GWYOG** [turbodiesel4598/NuclearCraft#2]
In 0.0.1.6, the recipe info for water cells will be displayed after pressing 'U' with NEI. Will it be better to change this key to 'R' which means Recipe rather than Usage? =D

**Comment by turbodiesel4598** [comment]
Yeh, it would be, although right now I have not yet added a 'recipe' version of that feature - there is only a 'use'. This will be added at some point though, as it could prove to be useful ;)

**Comment by GWYOG** [comment]
Got it. :D

**Comment by turbodiesel4598** [comment]
Just been added - will be updated soon ;)

**Comment by GWYOG** [comment]
Glad to see it added in 1.6a :)  but it seems that you forgot to update the zh_CN.lang :(
Anyway, it's time to close this issue XD
