### ISSUE TITLE
[Compatibility Issue]Metal Furnace and Basic Machine Casing

### ISSUE THREAD

**Issue by ImperaServ** [turbodiesel4598/NuclearCraft#20]
The iron plating and the iron plate from IndustrialCraft² share the same entry in the OreDictionary, and so the two recipe of the Metal Furnace and the Basic Machine Casing overlaps. The Metal Furnace blocks the recipe for the Basic Machine Casing...

**Comment by turbodiesel4598** [comment]
Ooh, didn't think of that... an easy fix, however ;)
