### ISSUE TITLE
[Suggestion] I would love to see a way to visualize a reactor being built in-world

### ISSUE THREAD

**Issue by levicc00123** [turbodiesel4598/NuclearCraft#204]
For ideas, check out Advanced Rocketry's Holo Projector, and the Lexica botania.

**Comment by turbodiesel4598** [comment]
Ok, I've taken a look - I'm just wondering how this would work for this mod. Just like Big/Extreme Reactors, the multiblocks' sizes and internal structure can vary, and so an in-built hologram would not be much use. Part of the challenge of the mod is learning how to design the reactors. Again, just like Big/Extreme Reactors, I do think that they're simple enough not to need assistance from a holographic projection - they are basically just a hollow cuboid of blocks.

**Comment by InterPlay02** [comment]
Yeah... If the reactor has a unique and, unchangeable shape, then this would be uesful.

**Comment by turbodiesel4598** [comment]
Maybe if I add something that requires a specific structure at some point in the future then I will add this, but for now, I don't think this is a necessary feature, so I'll close this issue.
