### ISSUE TITLE
Fusion reactor temperature resetting after a few seconds

### ISSUE THREAD

**Issue by kungfunick123** [turbodiesel4598/NuclearCraft#207]
Im on version 2.7a of Nuclearcraft on All the Mods 3 and I put down a fusion reactor and started it up once, let it go for a minute and then shut it off because I had to leave and wasnt sure I could keep it cool enough to not melt since I was using active liquid coolers with water and the efficiency in the reactor still said 0. Fast forward 3 days, I go to turn the reactor on since I can spend time seeing what I did wrong and now the thing wont start. I put down any number of power cells or even fluxducts/universal cables connected to powercells and no matter what, the temperature starts going up but after a few seconds it resets and starts from 0, but it doesnt reset my battery's charge, it keeps drawing power but keeps resetting back to 0 temp.
Also as a side note, in WALIA, its saying that 2 of the output tanks have a bucket each of deuterium and tritium (my fuels of choice) and I cant seem to get them out even by breaking the reactor block

**Comment by turbodiesel4598** [comment]
Can you show me some pictures of this or something? I'm unable to recreate this, so would like to see what is happening.

**Comment by kungfunick123** [comment]
https://gyazo.com/de036f1fd85b8983359cf7f29adc00d1  Gyazo didnt last long enough for it to reset twice but it doesn't always reset at the same temperature, it seems to be a fairly short time that varies by about a second or 2. This is an outside picture of how I have it set up: https://gyazo.com/fc19be7ea1b8da86ca79827d32dc4b97 I have 2 export busses from AE2 exporting the deuterium and tritium into the reactor. And to power it up, I placed a powercell from Thermal Dynamics on top of it. The blue blocks are infinite water sources from PressurePipes, they put out something like 60mb/t of water into the coolers

**Comment by turbodiesel4598** [comment]
I think you might be over-cooling the reactor - in version 2.7a and below, the active cooling happens in chunks every 4 seconds or so, hence why the heat shoots down to 0 kK every so often. If you were to remove the coolers then I think (hopefully) the heat would stop plummeting.

As of version 2.8a, the heat is removed continuously and the fusion core GUI will show you how much cooling is taking place.

**Comment by kungfunick123** [comment]
Ahhhh yes that was it. I took some out and its working now. Also, little did I know they consume so little lol. Will be doing some downsizing :p. Tyvm. Can't wait for 2.8a to come over to ATM3, will make things a little easier.

**Comment by turbodiesel4598** [comment]
Great! Yeh, they consume so little as if you were to use the more expensive coolants you wouldn't want the coolers to just burn right through it all. I feel that 10 mB/s is reasonable - one redstone dust every ten second if using destabilised redstone for example. Most of the time water is defo the best, especially for small fusion reactors, but nowadays in modded MC you can eventually have so many resources that it's not a problem to continuously use up materials. Happy fusing!
