### ISSUE TITLE
[1.12.2] Fusion reactor core won't render correctly

### ISSUE THREAD

**Issue by kwpugh** [turbodiesel4598/NuclearCraft#209]
After placing a fusion reactor core, it does not render completely.  It shifts and distorts as your view of block shifts.

Forge: 2284
Mod: NuclearCraft-2.8b--1.12.2.jar

https://imgur.com/a/2X3Sx

**Comment by turbodiesel4598** [comment]
Wow, not seen this before... not even sure where to start. Umm, have you tried playing to mod standalone? Have you got Java 8?

**Comment by kwpugh** [comment]
Crazy huh?

I'm running this as part of my own modpack: https://minecraft.curseforge.com/projects/pughland-plethora.   The mods in the modpack are listed on the page.

This situation occurs on the dedicated server.   Both client and server are Java 8 151.

Anything else you need?

**Comment by kwpugh** [comment]
I tried it with and without Optifine, no difference.

**Comment by kwpugh** [comment]
Oddly, it seems to work fine in single player.   Double checked to ensure that client and server are running the same version of Nuclearcraft.

**Comment by turbodiesel4598** [comment]
I'll take a closer look tomorrow - getting a tad late here. It's possible that something changed with a later version of Forge than I'm building with, but yeh, guessing for now :P

**Comment by kwpugh** [comment]
I built a small working fusion reactor setup on single player and everything seems fine.  Just no joy on the server.

**Comment by turbodiesel4598** [comment]
Still unable to recreate this - have you trie playing with only NC installed, or with a different pack?

**Comment by kwpugh** [comment]
In single player with my pack it is fine.

On a server with just NC, it is fine.

**Comment by turbodiesel4598** [comment]
Right, but have you tried playing with only NC installed on a server? If it is fine there, then we have an incompatibility of some sort.

**Comment by kwpugh** [comment]
Yes.   Setup a server with just NC installed and it worked fine.

**Comment by turbodiesel4598** [comment]
Ok, so it is an incompatability. I tried downloading your pack but was getting an error for some reason, hence why I couldn't replicate the issue. The only suggestion I have is to remove mods, particularly rendering-altering mods, until the issue goes away. I'll do the opposite in the meantime - add mods until the issue appears.

**Comment by kwpugh** [comment]
So you added no additional mods to server only?   Just what was in the modpack?

I will make the same test on my side.

Btw: what are your thoughts about using the particle accelerator to collide gold ions, resulting in Quark gluon Plasma, harnessing the heat in a hyper thermal conductive material for RF?

**Comment by turbodiesel4598** [comment]
I downloaded the pack, set up a new server with the version of Forge your pack uses and copied all mods and configs into the server. I logged in, placed a fusion core and did not see the graphical bug.

Quark-gluon plasma will definitely feature, although it will pronbably be lead ions that are used like in the ALICE experiment at CERN. It will not be used to generate RF as there is no point - at least as much energy would be put into the acceleration of the ions as would would be gained from the subsequent collision.

**Comment by kwpugh** [comment]
Ok, I’m going to test by removing the server only mods I have and see if the glitch is still there.

On the QGP, I was stretching beyond the known particle physics by suggesting a made-up hyper thermal conductive material that could absorb the ~4 trillion Celsius temp and produce billions of RF in moments.   The high cost to get there would be payed off by limitless RF.   Not realistic but possible fun.

**Comment by kwpugh** [comment]
Btw: I’m really enjoying this mod.   I built a 27x27x27 fission Reactor.   It’s like a big puzzle to figure out the best setup inside.

**Comment by kwpugh** [comment]
Ok.  I tried the server with a fresh world/ folder and no glitch.   Same setup, but existing world/, get the glitch.  How is it possible that something IN an existing world could cause the glitch?   Same mods before and after.

**Comment by kwpugh** [comment]
Another weird one, if I go to location 0,0 it works without any glitches with the existing world folder.   The farther away I got from 0,0 the worse the glitch gets.

In the current world, my home is at 500,000 by 500,000.

I tried the same thing on a fresh world/ folder and traveled to 500,000 by 500,000 and placed the fusion core.  It glitches as well.

Can you try on your copy of my server at a distance location to see if you have the issue?

**Comment by kwpugh** [comment]
I tried the same test with a server with just Nuclearcraft in it.   One with a fresh world folder and one with an existing world folder.  On both servers, I placed a fusion core near 0,0 and near 500000,500000.  No glitch near 0,0 but glitchy near 500000,500000 on both servers.

No other mods present other than NC.

**Comment by turbodiesel4598** [comment]
Ah, so you have found a legitimate bug! Very peculiar behaviour... I'll see if I can sort it out.

**Comment by kwpugh** [comment]
I'm determined.  I want to build my Fusion Reactor.   Good luck and thank you.

**Comment by kwpugh** [comment]
I have 2.3 million and 800,000 lithium 7 and 6 stored up just waiting to build a fusion reactor.  ;)

**Comment by turbodiesel4598** [comment]
Hopefully you will be able to build it soon - I'm having to go back to the old model rendering methods from 1.7.10, which would be quick, if it wasn't for Techne, the modelling program, not opening... I'm having to write the model classes by hand :P

**Comment by turbodiesel4598** [comment]
Okay! I think it's sorted for v2.8d :)

**Comment by kwpugh** [comment]
awesome.  I'll test it out.

**Comment by kwpugh** [comment]
No glitch now.   Looks Good!   Thank you for your patience and effort in fixing the situation.

Keep up the great work.

**Comment by kwpugh** [comment]
Is it wrong to make a max size fission reactor with a door and use it for a house?

**Comment by turbodiesel4598** [comment]
That sounds like a wonderful idea. erhaps until I add radiation at some point in the far future ;)

**Comment by kwpugh** [comment]
;(


but seriously, I'm having fun with the interior puzzle of the fission reactor.   Really good work.

**Comment by turbodiesel4598** [comment]
Cheers - you can thank IC2 for the inspiration! Always wondered what those reactor puzzles would be like in 3D. There are still two or three small things that I really don't like about the mechanics, but I'm afraid that making any changes at this point could have disastrous consequences for some people's already-built reactors. I guess I'll wait until 1.13...

Your suggestion also led me to making adding new models far easier in the future - I might even be able to do it without any sort of exterior program from now on, as long as my spatial awareness doesn't fail me :P
