### ISSUE TITLE
Major Bug: Losing items from Heavy Duty Workspace 1.6d/1.6e

### ISSUE THREAD

**Issue by b0bst3r** [turbodiesel4598/NuclearCraft#21]
Replication Instructions:

Place down a HDW bench, 
Put in a recipe (for example the reactor casing one)
Then come off the table without making it and leaving the items in the table
From the 12 plates and 4 ingots used to make the recipe it only drops 4 plates and 2 ingots on the ground

Place those 4 plates and 2 ingots in the HDW and come off the table and you get back just 1 of each.
Place those 1 plate and 1 ingot in the table, come off the table gui and you get nothing back

Edit: It seems to give you only 9 items back if you fill the entire grid, so maybe that's related to normal crafting table?

**Comment by turbodiesel4598** [comment]
Aha! You were right about it being related to the vanilla crafting table - it was only dropping the first 9 items from the grid on closing the GUI - fixed now ;)

**Comment by b0bst3r** [comment]
Hi turbo, do you have a jenkins I can pull a dev build from?

**Comment by turbodiesel4598** [comment]
I don't, unfortunately - I can just give you this, though...
https://www.dropbox.com/s/ful13aqvpl8aphz/NuclearCraft-1.7dev--1.7.10.jar?dl=0

**Comment by b0bst3r** [comment]
Thanks
