### ISSUE TITLE
[1.10.2] 2.7a Not enough Energy Output

### ISSUE THREAD

**Issue by darkman1984** [turbodiesel4598/NuclearCraft#210]
Seems that there's a problem with the max output of the fission controller.
Tested with: Draconic Basic I/O Crytsal, Ender I/O Conduits and infinite Flux Ducts from Thermal Expansion.
Output of Fission Controller should be 196K RF/t. Output still 120K Rf/t. Rest of it lands in the internal storage of the controller.

**Comment by turbodiesel4598** [comment]
Found the mistake - will get it fixed shortly... it's quite late here so it will probs be tomorrow :)

**Comment by turbodiesel4598** [comment]
Ok, should be [fixed in 2.8c](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2517776) :)
