### ISSUE TITLE
Can't remove bronze alloy recipe from alloy furnace using Crafttweaker

### ISSUE THREAD

**Issue by Intipablo** [turbodiesel4598/NuclearCraft#211]
I've been using Crafttweaker in my pack to tweak some recipes in Nuclearcraft, every recipe has worked up until now. I'm trying to remove the bronze alloy recipe from the Alloy Furnace.

_mods.nuclearcraft.alloy_furnace.removeRecipe(<nuclearcraft:alloy:0>);_

Removing other recipes from the furnace seems to work, although this one doesn't. Writing /ct syntax in-game prints no errors. However, upon joining the game a message pops up saying:

_ERROR: alloy_furnace: Removing Recipe - Couldn't find matching recipe [1xitem.alloy@0]_

**Comment by turbodiesel4598** [comment]
Ah, yes, that would be it - glad you got that sorted :)
