### ISSUE TITLE
[1.12.2] Cascading World Generation

### ISSUE THREAD

**Issue by JonasCiss** [turbodiesel4598/NuclearCraft#213]
I traveled back from the Nether and got the following in the console:

02:22:50] [Server thread/WARN] [FML]: NuclearCraft loaded a new chunk (18, -28  Dimension: -1) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by turbodiesel4598** [comment]
The world gen for glowing mushrooms was a little lazy - I think I have it fixed in the next release :)
