### ISSUE TITLE
[1.12.2] NuclearCraft 2.8c - Active Coolers only work with Water

### ISSUE THREAD

**Issue by LokeYourLord** [turbodiesel4598/NuclearCraft#214]
I am facing an issue when trying to cool my large ass Fusion Reactor with anything that isn't water, this even includes Liquid Helium from NuclearCraft itself. Basically, I have the Active Coolers placed just as they are meant to be placed, and when I pump water into them, the interface shows "Active Cooling Rate: xxxxK/t", but when I use ANYTHING else, be it Gelid Cryotheum or even NuclearCraft it's own Liquid Helium, the interface never shows anything about Active Cooling being, well, active. So I am wondering about what this can be or what can cause this.

Here is a picture of the mods folder for my server:
![mods](https://user-images.githubusercontent.com/5807595/34800203-188a80c6-f663-11e7-9b7e-fc52ac6143d7.PNG)

I hope that we can find a solution for this soon :)

**Comment by turbodiesel4598** [comment]
Seems I made a mistake when declaring which fluids are available for the active coolar- now fixed for v2.8d :)
