### ISSUE TITLE
Random crash on opening the nuclear furnace [Multiplayer]

### ISSUE THREAD

**Issue by Janrupf** [turbodiesel4598/NuclearCraft#215]
Hi,
my friend is randomly crashing when opening the nuclear furnace. It doesn't matter if something is in.
The crash report:
https://pastebin.com/J0TrdXUZ

I think this should already be fixed, but this still happends on the latest version.

Minecraft version: 1.11.2

**Comment by turbodiesel4598** [comment]
Yep, that's a known bug - I will try to get round to fixing it as soon as I can - it is a little tricky right now as I am not at home, but when I get back in a couple or weeks or so I'll try to get a fix out.

**Comment by turbodiesel4598** [comment]
Finally fixed for versions 1.10.2 and 1.11.2 - https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2527447
