### ISSUE TITLE
NuclearCraft Steam incompatible with ThermalFoundation Steam

### ISSUE THREAD

**Issue by kythorn** [turbodiesel4598/NuclearCraft#216]
With NuclearCraft 2.8d installed, steam produced from a Thermal Expansion dynamo cannot be consumed by another Thermal Expansion Dynamo. Downgrading to 2.7a (the version in FTB Revelation) seems to resolve the issue. 

Tested against TE 5.3.10.14 and TF 2.3.10.6.

I don't know if it's relevant, but after removing NuclearCraft completely, I needed to purge the default fluid list from level.dat to get Thermal Expansion working properly again.

Also opened https://github.com/CoFH/Feedback/issues/847

**Comment by turbodiesel4598** [comment]
Well, I have changed absolutely nothing about the steam fluid for a long time now, certainly not between those two versions, so I'm not sure what's going on. I don't quite understand what you mean by steam being produced in one dynamo not being consumed in the other, though.

**Comment by kythorn** [comment]
Sorry, that's something specific to Thermal Expansion. A machine with a boiler augment makes steam, and one with a turbine augment consumes it. 

With that version of NuclearCraft installed, the TE boiler makes a steam that the TE turbine can't consume. I can upload a twitch profile export with just sufficient mods to illustrate the problem if it would help.

**Comment by turbodiesel4598** [comment]
Ah, I did not realise you could do that now - pretty cool. My instinctive guess is that the boiler is generating the first instance of steam it can find in the fluid dictionary (that being the NC entry), while the turbine dynamo is accepting only the TF steam, but I could be wrong - I guess we'll wait on Lemming or whoever else's answer.

**Comment by kythorn** [comment]
I just went to recreate my test case to package it up for you, and I was unable to reproduce it a second. I thought I was losing my mind, so I went to my other test case and I can still reproduce it there.

I apologize for opening up a misinformed case - what I now suspect is actually happening is the following:

1) Start a new world with Thermal Expansion + Thermal Foundation installed
2) Add NuclearCraft
3) Start the game up again

The NuclearCraft steam wins (gets registered first), but some other part of the game (perhaps the fluid registry / default list in the save) is still clinging onto the Thermal Steam instead and this is the actual root of the problem.

The thing I I cannot explain is why downgrading the mod changed anything, perhaps it simple shook things up enough it forced a re-evaluation of which steam in the cache was valid.

**Comment by turbodiesel4598** [comment]
Hmm, yeh, it very well could just be, as you say, an artefact of adding a new type of steam that gets registered earlier than the original. The fact that downgrading changed anything is a bit bizarre too. Does the issue persist after breaking and replacing the dynamo(s)?

**Comment by kythorn** [comment]
Yeah, I broke and replaced all of the dynamos, pipes, etc. I think once you get in that state it just stays broken. Machine A produces steam 1 but Machine B expects steam 2.

**Comment by turbodiesel4598** [comment]
Well, I'm not sure what I can do to fix this then. I will close this issue as I'm pretty confident at this point that it is not an NC issue, but it's perhaps something that Forge should look at.
