### ISSUE TITLE
[Suggestion] More Melter compatability

### ISSUE THREAD

**Issue by Lukas45** [turbodiesel4598/NuclearCraft#218]
The Melter is awesome when automating a Tinkers smeltery, but it is missing a few pieces.

- Mekanism:
  - Refined Obsidian
  - Glowstone Ingot

- Tinkers:
  -  Sand/Glass -> Liquid Glass
  -  Clay

- PlusTIC:
  -  Botania:
       -   Elementium
  -  PSI:
      -   Psimetal

- JAOPCA/PlusTIC:
  -  Astral Sorcery:
      -   Starmetal
  -  Mystical Agriculture/Agraditions:
      -   Soulium
      -   Base Essence
      -   Prudentium
      -   Intermedium
      -   Superium
      -   Supremium

Probably more, but that's the ones I could find in our modpack

**Comment by turbodiesel4598** [comment]
Ok, I've added all the recipes you've listed here, plus a few others that I found along the way. I have to say that I'm surprised that the seared glass recipe didn't work, though, as I added that a while back.

**Comment by Lukas45** [comment]
Maybe the issue is that you tried to make Seared Glass, which is a block? It is called Liquid Glass.
Also, Seared Stone is missing, although debatable if it should be meltable?

**Comment by turbodiesel4598** [comment]
I looked at the Tinkers source code and the fluid is just called ‘glass’, which is what I’ve specified in the recipe...

**Comment by Lukas45** [comment]
hm, maybe because we default to Forestry glass?
Which is forestry:fluid.glass - which I think is the same anyways?

**Comment by turbodiesel4598** [comment]
Well, whatever the case, it's not working in the upcoming v2.9 :)

**Comment by Lukas45** [comment]
Oh well ¯\_(ツ)_/¯
Still, the rest are really nice to have - just gotta find a workaround to make Mirion without waiting for glass to smelt somehow :P

**Comment by turbodiesel4598** [comment]
[Version 2.9 is out now with all the new recipes :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2522022)
