### ISSUE TITLE
Dedicated Server Crash During Init Using latest version 2.9 on 1.12.2

### ISSUE THREAD

**Issue by karbonkitt** [turbodiesel4598/NuclearCraft#219]
Looks like the changes to how you register fluids are causing a crash on dedicated servers, calling client only code in common proxy during preInit.

Full crash report here
http://termbin.com/gaie

**Comment by turbodiesel4598** [comment]
Yep, noticed that just after I uploaded the file - [new one is out now :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2522022)
