### ISSUE TITLE
A ghast blew our server up 

### ISSUE THREAD

**Issue by b0bst3r** [turbodiesel4598/NuclearCraft#22]
Just kidding, a ghast fireball hit one of the plutonium ores and took the server down.

http://pastebin.ubuntu.com/15531208/

At least that's what we think happened.

**Comment by b0bst3r** [comment]
Another pastebin for you maybe better detail, this time a nitro creeper in the nether blowing up, same issue I believe.

http://pastebin.ubuntu.com/15538226/

**Comment by turbodiesel4598** [comment]
Fixed! Plutonium, Quartz and Lapis were given extra drops, and I forgot to check that a player was breaking the block.
