### ISSUE TITLE
[1.12.2] Fission Reactor Ports doesn't work correct

### ISSUE THREAD

**Issue by darkman1984** [turbodiesel4598/NuclearCraft#221]
Hi again ;)

Version: NuclearCraft 2.9

Fission Reactor Size: 2x2x3
Pic: https://imgur.com/a/JfGvi

Second Layer: Backside in the middle of the three reactor casings is the Fission Port.
Exported from Applied Energistics LEU-235 the Fission Controller get no Fuel Rods.
Fission Port one up on the third Layer the Controller get the Fuel Rods but don't recognize that there are Fuel Cells and response with: No Fuel.
Pic: https://imgur.com/a/yEbXi

Greetings
DaRkMaN

**Comment by turbodiesel4598** [comment]
Did this work in previous version if the mod or has it been broken in the past?

**Comment by darkman1984** [comment]
That if i could answer. The Fission Port of the other two reactors did on Version 2.7 sometimes the same problem. Reactor complete build up and nothing would be imported. After switching the sides of the import and export it worked. Best example: the second small reactor on the first picture (same build as the first small) don't accept fuel rods too.

For Explanation and clarity:

2 small reactors. Same build. 2x2x3
Fission Port layer 2 don't work. Doesn't matter on which side i place an export bus.

First reactor: Moved the fission port one layer up. backside of the port don't accept fuel rods. The top of it accept it and the controller doesn't recognize the rods.

Second reactor: Second Layer: Don't accept Fuel Rods. Third layer - surprise surprise - don't accept fuel rods. 

Now i'm confused right now cause this are the same builds.

Well i build the same reactor in a few minutes and i think i have the solution and where it depends on ;) 
Maybe Chunks. My first 2 reactors are in nearly with the interior in one chunk. The small ones aren't. The chunk border is exactly behind the controller.

**Comment by turbodiesel4598** [comment]
That might be the issue then, as I can't recreate this with hoppers, AE2 or thermal dynamics. Does it work for you if you just stand next to the reactor while it's being refueled?

**Comment by darkman1984** [comment]
I moved one small whole reactor inside of a chunk. After than it worked correctly. So it seems that there is a problem with the chunk borders if the multiblock overlaps in a new chunk.

Answer for your question:
I stand the whole time next to the reactor 'cause i tried to configure the export bus correctly. 
That don't depend on unloaded chunks.

**Comment by turbodiesel4598** [comment]
I'm still a little confused... so, even though all chunks are loaded around where the reactor is, the ports don't work if they are in different chunks to the controller?

**Comment by darkman1984** [comment]
Yep... i think so

**Comment by turbodiesel4598** [comment]
Aha! Think I found the problem - will get it fixed for the next version :)

**Comment by turbodiesel4598** [comment]
Sorted (I'm pretty sure).
