### ISSUE TITLE
[Question] 357 Block ID's as of the latest version according to Caliper mod

### ISSUE THREAD

**Issue by Vyraal1** [turbodiesel4598/NuclearCraft#223]
As a preface, I've heard of Not Enough ID's mod, but I was told by other mod devs to use it with caution or to avoid it entirely as it can compromise a pack. Anyways, I just updated your mod to the latest version and ended getting several crashes upon start with my modpack and saw that the mod was now using a whopping 357 block ID's via Caliper.

Was this in early preparation for the eventual switch to 1.13? I'm developing a [fairly large pack](https://minecraft.curseforge.com/projects/interaction) for 1.12.2 and as a result I'm pushing fairly close to the Block ID limit. Would you possibly consider using meta for some of the blocks again to help compact usage of the Block ID's?

If you don't want to undo your work, that's understandable, I can find workarounds, but figured I'd ask first. 

On a separate note, this update kinda caught me off guard and scrambled a testing world and a server world after hitting the Block ID limit, and having to delete/remove/shuffle mods around trying to figure out what happened, causing Block ID's shuffles as well, normally a buffer of 160 ID's is more than enough.

**Comment by turbodiesel4598** [comment]
...Ah, I completely forgot about the block ID limit. The reason that there are suddenly so many blocks is because of all of the new fission fluids that have been added to the game, and each one has to take up a whole block ID. I will get a new version out as soon as I can that gets rid of the blocks - I should be able to just keep the fluids.

**Comment by Vyraal1** [comment]
I'm always for properly documented and flexible configs. Can never say no to that. 

I went through most of the fluids and had a couple of question:
**Helium/Deuterium/etc.** 
Are Helium and Liquid Helium both recognized as a fluid by forge? Or is one registered as a gas and the other is a fluid? Mostly asking for CraftTweaker reasons for processing blocks like the SuperCooler.  Would I need to use Mekanism gas tubes/gas tanks to store Helium, and then use Thermal Dynamics fluiducts to extract the output? Same with Deuterium and any other 'gasses' that have a fluid counterpart?

Do the fluids have any functional in-world use? If I use the configs to disable the registered fluids, will the player be missing out on any gameplay that you have in the mod? (aside from burning themselves in molten plasma). I'm open to in-world mechanics (eg how Big Reactors uses fluids to cool its own reactors), but I just wanted to weigh off opportunity costs with the Block ID's (eg. the ID's used up by fluids could be used for adding PnematicCraft instead).

**Comment by turbodiesel4598** [comment]
> Are Helium and Liquid Helium both recognized as a fluid by forge? Or is one registered as a gas and the other is a fluid?

All fluids in the mod are standard Forge fluids - I don't, and probably won't, use the Mek gas system - the API is pretty broken so I don't have much of a choice in that anyway.
> Do the fluids have any functional in-world use? If I use the configs to disable the registered fluids, will the player be missing out on any gameplay that you have in the mod?

No, aside from trivial things, they won't miss much. The only fluid that technically _must_ be in the game as a block is the fusion plasma that fills the ring.
> Is NC steam oredict'd to steam?

For the moment, yes it is. However, chances are that it will not be anymore once I start actually adding the molten salt reactors, steam turbines etc, as I want the reactors to produce super-heated steam from distilled water, which turns into regular steam after passing through a high-pressure turbine, which can then either be dumped or reheated into 'reheated steam' to finally be passed through a low-pressure turbine to produce water.

**Comment by Vyraal1** [comment]
So just saw your latest update, looks mostly good regarding this issue but: you mentioned earlier that plasma is the only fluid that will have an ingame use, since it will form as fluid blocks within the fusion coil ring, however it seems to have been collateral damage as it also got disabled as shown below: 
![image](https://user-images.githubusercontent.com/26587049/35422529-2d7e43ea-0217-11e8-8b9b-e19d4f134aad.png)

**Comment by turbodiesel4598** [comment]
Ugh.. I made a silly mistake - will get a fix out shortly!

**Comment by turbodiesel4598** [comment]
Ok, how about this - since the fission fluids aren't currently being used, perhaps the config option should be changed so that all of only the fission fluids are disabled, block and all?

**Comment by Vyraal1** [comment]
`I've asked on the forge forums if there is a way to register the fluids properly without their blocks - hopefully I get a 'yes'.`

There should be if I recall correctly, Mekanism has liquids that weren't placable in world, and asking asking briefly in the Modded Minecraft discord, one of the Mekanism devs said it's definitely possible.

Since the fission fluids aren't being used, that's also fine, but figured it might be a problem for your later down the line when you eventually implement more fission mechanics/salt reactors (would the fluid blocks then be 100% necessary then?)

**Comment by turbodiesel4598** [comment]
Aha, found my mistake - it was a sneaky one. Ok, I'll put out a hotfix for 2.9b, where that config option now specifically allows for the disabling of the registering of all the new fission fluid blocks without removing the fluids themselves :)

**Comment by Vyraal1** [comment]
Everything seems to work fine, I can still access the fluids and put them in buckets, and the Block ID count is lower. Thanks for your help on this!

**Comment by turbodiesel4598** [comment]
Great!
