### ISSUE TITLE
Configs for Fission Side Length Not Working

### ISSUE THREAD

**Issue by Vyraal1** [turbodiesel4598/NuclearCraft#225]
```
    # Minimum side length of fission structures.
    I:fission_min_size=1

    # Maximum side length of fission structures.
    I:fission_max_size=24

```
![image](https://user-images.githubusercontent.com/26587049/35283923-7845dc22-0027-11e8-800a-d6ca0a9bf88d.png)

I left it at the default configs of 24.

**Comment by turbodiesel4598** [comment]
Will look into it - I suspect that the issue is just that it is checking one or two blocks too far rather than there being no size limit at all.

**Comment by turbodiesel4598** [comment]
Sorted - was just checking one block too far :)
