### ISSUE TITLE
[1.12.2] Machine energy input rate fails to keep up with upgrades

### ISSUE THREAD

**Issue by Vyraal1** [turbodiesel4598/NuclearCraft#226]
Bit of a corner case here, but machines energy input rate does not scale along with the amount of speed upgrades. As a resullt, a stack of 48 upgrades in a Pressurizer causes it to constantly reset (which is great mechanic btw, I think more RF based machines should do this) even though it has a creative energy source attached to it because input rate from one side isn't enough. 

I figured this might be unintentional because the machine energy buffer scales with the energy upgrades, so it seemed thematically inconsistent.

**Comment by turbodiesel4598** [comment]
Yep, you're right - the capacity was being changed, but the max input rate wasn't. All fixed now!
