### ISSUE TITLE
[1.12.2][2.9b] Log Spamming: Found Active Cooler

### ISSUE THREAD

**Issue by darkman1984** [turbodiesel4598/NuclearCraft#229]
Hey there.
Can you please stop the logspamming in the next version?
Get five times in a row the message:

[21:12:48] [Server thread/INFO] [nuclearcraft]: Found Active Cooler

and that nearly every second.

**Comment by turbodiesel4598** [comment]
Sorry, must have missed getting rid of some of the logging I was using while testing for why the active coolers weren't working :P

**Comment by darkman1984** [comment]
I have an idea :) Why you don't implement an debug config value (function with return the boolean -> true / false) to activate the log and then everything you need to know you'll use the function? :) :P :D

**Comment by turbodiesel4598** [comment]
Guess I could do that, although I've now just removed all of the messaging :P
Thing is that I barely use logging to debug stuff as it's usually a last resort option.

**Comment by turbodiesel4598** [comment]
Anyways, all sorted in 2.9c :)
