### ISSUE TITLE
[Suggestion] Config option for Glowing Mushroom spread

### ISSUE THREAD

**Issue by SSyl** [turbodiesel4598/NuclearCraft#231]
Would it be possible for you to add an option in the config to change how fast/slow Glowing Mushrooms spread? I love using them, but it gets a bit tedious having to cull them fairly often because they spread so fast.

**Comment by turbodiesel4598** [comment]
Sure thing :)

**Comment by turbodiesel4598** [comment]
Added in 2.9c :)
