### ISSUE TITLE
[1.12.2] [2.9b] Graphite dust missing recipe

### ISSUE THREAD

**Issue by NutBurger** [turbodiesel4598/NuclearCraft#232]
Forge1.12.2-14.23.1.2603

In a custom mod pack i went to make some graphite dust using the manufactory, but the input side of the machine would not accept any coal, so i checked with jei (r key) and no recipe was shown at all. Graphite blocks and ingot recipes show up though.

I then created a new forge 1.12.2 profile with just nuclearcraft-2.9b to rule out any other mods messing with the recipe but the recipe still seems to be missing.

**Comment by turbodiesel4598** [comment]
Yep, my mistake - currently the recipe is coal dust -> graphite dust, which doesn't work if you don't have a mod that adds coal dust. Will get it fixed :)

**Comment by turbodiesel4598** [comment]
Fixed in 2.9c :)
