### ISSUE TITLE
[Suggestion] Add configureable I/O to all machines

### ISSUE THREAD

**Issue by derdotte** [turbodiesel4598/NuclearCraft#234]
Well, how can you sum it up better than just simply, i would like to be able to configure all sides of all machines.
i have been playing lots of modern skyblock 2 and automation can be quite a pain to setup without configuration.

**Comment by turbodiesel4598** [comment]
Probably a good idea - will get on it when I have some time :)

**Comment by turbodiesel4598** [comment]
After thinking about this for some time, I've ultimately decided not to add this for now - maybe I will in the future, but there is just too much on the to-do list for an overhaul like this. I think there are more than enough ways to automate the machines using pipes, conduits, etc. that pull from them.
