### ISSUE TITLE
Molten fusion fuels missing for 2.9c

### ISSUE THREAD

**Issue by Beyliff** [turbodiesel4598/NuclearCraft#236]
Using 2.9c on FTB Revelation 1.4. Updated manually from 2.9 and still cannot see any Lithium or Boron variants in the Melter. Was this feature added? How is one supposed to make the molten fuels for the Fusion reactor.

Thanks in advance. Love the mod....

**Comment by turbodiesel4598** [comment]
Hi there - to get the molten lithium and boron you need to melt the individual isotopes, which you get from processing lithium/boron in the isotope separator.

**Comment by Beyliff** [comment]
Understood but they won't go into the melter either. There doesn't appear to be a pattern for it. I can get the isotopes from the seperator but no luck with those on the melter.

**Comment by turbodiesel4598** [comment]
Ah, my mistake - somehow I managed to break the lithium and boron melting recipes - will get a fix out shortly!

**Comment by turbodiesel4598** [comment]
Fixed in version 2.9d - https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2526922
