### ISSUE TITLE
Adding NC ores to ET void ore miners

### ISSUE THREAD

**Issue by Beyliff** [turbodiesel4598/NuclearCraft#237]
I cannot seem to get NC ores from the ET void ore miners. Was this intended and/or is there an easy fix for a non-programmer? 

Thank you

**Comment by turbodiesel4598** [comment]
Hmmm, sounds like an issue on ET's side - NC ores are no different to anybody else's. ET isn't open source so I can't look at their code - I recommend heading to [their issue tracker](https://github.com/ValkyrieofNight/EnvironmentalTech/issues) and giving whatever details they might want :)

**Comment by sharkbite3105** [comment]
If this is a bug, how is it that our server owner added the ores to the void ore miner's list? I would think that there should be a config file that could be updated for the ET mod.

**Comment by turbodiesel4598** [comment]
Is this still an issue?

**Comment by scotty9090** [comment]
Latest versions of ET have NC ores included.  When they were initially included, spelling mistakes in the ET .json files kept them from actually getting generated, but this is fixed now.  

The only thing you will not get from the Void Miners are the secondary drops (flourite, beryillium, and roda-something or other ... not sure I spelled any of these correctly) that you get when mining other types of ore (e.g. Redstone.)

**Comment by turbodiesel4598** [comment]
Ok, great :)
