### ISSUE TITLE
Nuclearcraft 2.9d Basic Voltaic Pile erroneous charge reporting

### ISSUE THREAD

**Issue by Fatmice** [turbodiesel4598/NuclearCraft#238]
Basic Voltaic Pile not reporting right amount of power then right click with hand.  The printed value seems to be frozen, whereas value reported on the upper left was increasing.
![2018-02-02_04 45 30](https://user-images.githubusercontent.com/8956281/35729353-f8b01716-07d3-11e8-89bd-d6444f40f7af.png)

**Comment by turbodiesel4598** [comment]
Fixed!
