### ISSUE TITLE
Fission reactor using fuel after being turned off.

### ISSUE THREAD

**Issue by crawln45** [turbodiesel4598/NuclearCraft#24]
I noticed in your spotlight that when  you turned off the fission reactor. Fuel consumption stopped. Currently playing BTP Reborn using 1.6E and noticed that when I turn the fission reactor off. Fuel consumption continues. Seeing as I've searched around and found no answer to this. I'd ask if that was intended or not. I would assume not since it allows you to do nothing to get depleted cells.

Edit: using 1.7dev from #23

**Comment by turbodiesel4598** [comment]
Ah, I was told about this in the Minecraft Forum thread - fixed now ;)
