### ISSUE TITLE
[Suggestion] OpenComputers support

### ISSUE THREAD

**Issue by BrisingrAerowing** [turbodiesel4598/NuclearCraft#240]
Being able to write programs for controlling reactors would be quite useful. A program could monitor the energy usage of what the reactor is powering and scale production, and could shut down a reactor that was overheating (and possibly set off alarms). I usually use OC for automation of many machines, allowing for fine-grained control of what is being made.

**Comment by turbodiesel4598** [comment]
Definitely something I wanted to get done earlier, but I had a bit of trouble actually implementing the integration. Once I get the steam turbines and new reactors sorted I will come back to OC support and see if I can get it sorted.

**Comment by turbodiesel4598** [comment]
Added in [version 2.11a](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2604610) :)
