### ISSUE TITLE
2.9d: Electrolyzer not working if directly connected to Fission Reactor using IC2 cable

### ISSUE THREAD

**Issue by Fatmice** [turbodiesel4598/NuclearCraft#241]
Top most setup does not run.

The other two variants work fine.

All electrolyzers have energy.

![2018-02-04_04 26 02](https://user-images.githubusercontent.com/8956281/35776529-eb3777aa-0963-11e8-8adc-e04a07c00f5d.png)

**Comment by turbodiesel4598** [comment]
> All electrolyzers have energy.
Including the top one? So although it has energy, is doesn't run? If so, the issue is with the Electrolyser, not the Fission Controller, and given that the others are running fine, that would be very puzzling...

**Comment by Fatmice** [comment]
I've only checked IC2 cables.  Problem only shows up when cabling directly to the fission controller.

**Comment by turbodiesel4598** [comment]
Could I have a screenshot of the GUI of the broken Electrolyser?

**Comment by Fatmice** [comment]
![2018-02-04_19 34 34](https://user-images.githubusercontent.com/8956281/35784985-7fc91fa8-09e2-11e8-856d-1cb099c0fdbc.png)

Here is a MultiMC instance of the setup.  I also found another bug.  If inf water source block touches a reactor port, it will drain the reactor of RF.
[Nuclearcraft-Test.zip](https://github.com/turbodiesel4598/NuclearCraft/files/1693562/Nuclearcraft-Test.zip)

**Comment by Fatmice** [comment]
Melter seems similarly afflicted if connected to reactor through IC2 cable.  

There seems to be a solution, which may also point you to the problem.  If I drop a stack of speed upgrade into the entity to quickly deplete the energy reserve, then often I can jump start it.  It will then continues to work as long as the speed upgrade(s) did not increase consumption in RF/t beyond the  equivalent EU/t input, which depends on the setup.

A) For reactor -> Ic2 cable -> Electrolyzer/Melter => consumption must not exceed (reactor-output/4) RF/t, e.g. reactor output 1600 RF/t, then speed upgrade must not increase RF/t beyond 400 RF/t.

B) For reactor -> Ic2 cable -> Ic2 Battery -> Ic2 cable -> Electrolyzer/Melter => consumption must not exceed the (Ic2 battery rated output)*4 RF/t <= This setup is "working" as a user would have expected.

C) The RTG->IC2 cable->Electrolyzer/Melter => same as A

From observation though, this is not just a mere graphical glitch but something deeper within the mod's interface with other mods' energy cables.  Since your mod does not provide a conversion block, I will take note of the current behavior and work around the issue.  It's a bug in my opinion, but not really a serious one.
![2018-02-05_14 13 27](https://user-images.githubusercontent.com/8956281/35826793-62b3f148-0a7f-11e8-8862-c61e9180271d.png)
Also what goes into the empty slot next to the slot for the speed upgrades ?

**Comment by turbodiesel4598** [comment]
Well, whether it was me updating forge or IC2, I can not recreate this bug - [here is a pic of the two electrolysers running](https://prnt.sc/is453a). When I release the update, hopefully the issue will disappear for you as well.

As for the additional slot: at some point I am gonna add more 'specific' upgrades like Thermal Expansion's augments. I was gonna do it a while back, hence why the slot has always been there, but never got round to it.

**Comment by Fatmice** [comment]
Sure, I'll look at the issue again when you push a release

**Comment by turbodiesel4598** [comment]
[2.9e released](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2541792) :)

**Comment by Fatmice** [comment]
Problem still there.  I used the same test world that I provided you.  Broke and replace the Electrolyzer.  It does not work until I force deplete its internal energy reserves with a stack of speed upgrade...

Is there anything that I am missing here?

**Comment by turbodiesel4598** [comment]
Aha! I have the reason... that was quite tricky to spot, and I'll have to fix it.
Basically, there is a simple logic to when the machines actually run (provided they have a valid recipe, of course). If the total energy of the operation is lower than the buffer of the machine, then it will run when there is at least enough energy for the operation. Otherwise, the machine will run when the buffer is full. Because of some dodgy rounding when converting between RF and EU, not at all helped by the fact IC2 uses doubles rather than integers, the energy level of the Electrolyser that was not running was stuck at _just_ under the buffer max.

[Here is a hotfix that seemed to work for me](https://www.dropbox.com/s/u1y6abdvs2bvc2i/NuclearCraft-2.9f--1.12.2.jar?dl=0) - if this works for you, then I'll include the fix in the next update.

**Comment by Fatmice** [comment]
Works for me.
