### ISSUE TITLE
Melting boron and lithium isotopes

### ISSUE THREAD

**Issue by Basso2** [turbodiesel4598/NuclearCraft#244]
Patched the FTB to 1.4.0 and I cannot melt boron or lithium isotopes anymore?
Didnt find anything in changelogs, is it supposedly removed?

**Comment by Piegonmc** [comment]
Ive just done the same thing, updated server to FTB Revelations 1.4.0, and Melter just won't except Boron or Lithium

**Comment by turbodiesel4598** [comment]
It was fixed in the latest update, 2.9d, so you just need to update the mod to fix the issue. Hopefully FTB do that soon.
