### ISSUE TITLE
Controller Turning on it's own after game restart

### ISSUE THREAD

**Issue by DenTommes** [turbodiesel4598/NuclearCraft#246]
After my latest restart i noticed, that my fission reactor wouldn't turn on any more. after i tore down everything except the controller I noticed, that the controller actually turned around by 180 degrees. at first, the front side was facing north, now it was facing south.

i tried to reproduce the issue, but to no avail so far.

version of nuclear craft used: 2.9
other mods: many,  I played with the FTB revelations modpack on 1.4.0

**Comment by turbodiesel4598** [comment]
I think you got an uncommon occasional glitch that happens sometimes with Minecraft when NBT data can be incorrectly written to the world save. The code that determines the way that the controller (and all machines for that matter) is facing is exactly the same as that for a vanilla furnace, so if it's not reproducible, I don't think it's an actual NC-specific bug.
