### ISSUE TITLE
Question: Where rf/heat and reactor (cooling) components setup can be found in code.

### ISSUE THREAD

**Issue by Kite1024** [turbodiesel4598/NuclearCraft#247]
Hey, I'm trying to find the location where the base rf/heat p.t. for the fuels is stored, as well as the setup requirements and heat dissipation for the different cooling blocks. As I could not find them in the code, I'd thought I'd ask here :)

**Comment by Kite1024** [comment]
As a clarification, I'm looking for the _code_ where these restraints are set. I'm already aware of the many great locations (wiki's e.a.) where we can get the numbers.

**Comment by Fatmice** [comment]
Many numbers are in the config.

**Comment by turbodiesel4598** [comment]
As Fatmice says, every fission fuel stat [is set in the configs](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/config/NCConfig.java#L272-L333). They are then used in the [fission recipes](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/recipe/generator/FissionRecipes.java).

The energy/heat calculation is done in the [fission controller tile entity class](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/tile/generator/TileFissionController.java#L793-L905).
