### ISSUE TITLE
No Recipe for Some Melter Items

### ISSUE THREAD

**Issue by RezaSmith** [turbodiesel4598/NuclearCraft#249]
hello so im playing modpack FTB Revelation in a server (v1.4) and i wanted to make some tritium today and i noticed some of the melter recipes are missing . like :
Molten Boron
Molten Lithium

hope you take a look , thanks.

**Comment by turbodiesel4598** [comment]
Hey there - this was fixed in [v2.9d](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2526922) and version 1.5 of the pack has the update :)
