### ISSUE TITLE
Enhancement: Make compatible with rftools 

### ISSUE THREAD

**Issue by crawln45** [turbodiesel4598/NuclearCraft#25]
Noticed today rftools energy module can't read rf being produced by the fission reactor. But it can read rf being drained from the internal battery. Just thought I'd see if that could be added. Not sure about fusion yet.

Rftools Screen /w Energy module's: http://storage4.static.itmages.com/i/16/0405/h_1459822625_2957250_c604dfcf34.png
Fission reactor: 
http://storage8.static.itmages.com/i/16/0405/h_1459822770_1267536_f4c51e0413.png

**Comment by turbodiesel4598** [comment]
I can't figure out where the issue lies - it may have been fixed by accident in recent versions, but I have the Fission Controller produce energy in the same way as any other generator.

**Comment by turbodiesel4598** [comment]
I made some slight changes to the way the generators output RF - I have a slight hunch this may fix the issue.
