### ISSUE TITLE
Heath bar

### ISSUE THREAD

**Issue by RenanVieira88** [turbodiesel4598/NuclearCraft#256]
Good afternoon, I have a serious problem here, I put the version "rads" 1.7.10, what happens now is that when placing any item (like canisters of Tinkers) or armor that increases the number of hearts, I have an animation of hurt (blinking and shaking the screen), when I remove the NuclearCraft that stops, but never again does the health pass from normal hearts.
I'm afraid of not being able to solve this, I'm having server problems with this, and resetting the world is not a valid option, I really appreciate the attention

**Comment by turbodiesel4598** [comment]
The 'rads' version was a very unstable build which I made to test out the idea of modifying the health of the player... as you have discovered, this didn't really work very well.

I highly recommend scrapping the rads version and just use a stable build such as 1.9f instead.

**Comment by RenanVieira88** [comment]
I've resolve the issue puting the "normal" version, tnks
