### ISSUE TITLE
[NuclearCraft-2.9d--1.12.2] Multiple missing textures

### ISSUE THREAD

**Issue by wBakunis** [turbodiesel4598/NuclearCraft#258]
Currently using NuclearCraft-2.9d--1.12.2 in FTB Revelations. Multiple textures are missing. These errors are found on the game output window.

> nuclearcraft:textures/items/depleted_fuel_thorium_tbu.png, java.io.FileNotFoundException
...
nuclearcraft:textures/items/depleted_fuel_californium_lec_249.png, java.io.FileNotFoundException

**Comment by turbodiesel4598** [comment]
I'm gonna make fuel rods obsolete and am half-way through adding the depleted fuel pellets - will be sorted soonish :)
