### ISSUE TITLE
Suggestion !

### ISSUE THREAD

**Issue by 47delasPECII** [turbodiesel4598/NuclearCraft#259]
Can u make the fusion reactor accept fuel from mekanism like in the version from minecraft 1.7.10 / 1.10.2?
Plus can u make so the machines that produce more then 1 liquid the extra liquid to be deleted? (like if i only want oxygen from the electrolyzer the hydrogen and deuteriu to be deleted, same for the chemical reactor etc)

**Comment by turbodiesel4598** [comment]
Unfortunately I can't, because the Mekanism API is in a totally unusable state :(
If it gets fixed, I'll be sure to add that functionality back in!
