### ISSUE TITLE
Drop handler not checking for silk touch correctly

### ISSUE THREAD

**Issue by thiakil** [turbodiesel4598/NuclearCraft#261]
https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/handler/DropHandler.java#L51

Don't do that.

Use `HarvestDropsEvent#isSilkTouching()`, as machines that silk mine do not have tools.

Also the held item will never be null.

**Comment by turbodiesel4598** [comment]
Cheers - did not know about that. Fixed now!
