### ISSUE TITLE
Using the Fluid Infuser to create Immersive Engineering Treated Planks causes texture error

### ISSUE THREAD

**Issue by JimmyAllnighter** [turbodiesel4598/NuclearCraft#262]
Combining Creosote Oil from Immersive Engineering on wooden planks in the Fluid Infuser to create Treated Wood Planks causes these weird pink squares. They're functional as in I can place them in the world and they will be the proper Infused Wood (and upon breaking too). 
![2018-03-10_17 40 29](https://user-images.githubusercontent.com/36003168/37239586-34d0ee78-248a-11e8-9545-e1a1a570e7df.png)

According to the tooltip, it appears to be a problem with the item ID? Note the #7519/0 (normal Treated Planks) vs #7519/32767 for the Fluid Infuser output.

Hopefully this is just a simple fix adjusting the output of the Fluid Infuser. Thanks!

**Comment by turbodiesel4598** [comment]
Fixed!
