### ISSUE TITLE
Fusion reactor clears inventory when unchunkloaded.

### ISSUE THREAD

**Issue by mthp1999** [turbodiesel4598/NuclearCraft#263]
When on a server and then chunks become unloading, i.e. leaving the server for a little bit, the internal tanks will be empty when I log back in, meaning the reactor will have to reheat up, for long heat up times like a Dt-Dt fusion this is very inconvenient.

**Comment by turbodiesel4598** [comment]
I can't recreate this - the contents of the tanks are saved just like any other fluid handling machine. What version of NC are you using, and are you sure that there can't be any other reason that the fusion reactor runs out of fuel?

**Comment by mthp1999** [comment]
Yeah, sorry I think I figured it out. I believe it was a bug with how ae2stuff and ae handles channeling (I was using fluid storage buses and fluid export buses) where they were not connected causing the reactor to run through it reserves and ae not supplying anything to it. Sorry to bother you ;(, great work on the mod!

**Comment by turbodiesel4598** [comment]
No worries, and thanks very much :)
