### ISSUE TITLE
Calcium Sulfate

### ISSUE THREAD

**Issue by Archdiocese** [turbodiesel4598/NuclearCraft#264]
I have no way or idea how to create calcium sulfate or calcium sulfate solutions. Nothing online even mentions it and all post on it says its fixed but what is the recipe?

**Comment by turbodiesel4598** [comment]
You should be able to follow the chain of recipes through JEI, no?

In addition, [I've updated the wiki pages on it](https://ftb.gamepedia.com/Calcium_Sulfate) and so now it should be possible to work out how to make it through that :)

The recipe chain is:

Fluorite -> Manufactory => Crushed Fluorite -> Fluid Enricher => Fluorite Water

Sulfur -> Melter => Molten Sulfur -> Chemical Reactor w/ Oxygen => Sulfur Dioxide  -> Chemical Reactor w/ Oxygen => Sulfur Trioxide  -> Chemical Reactor w/ Water => Sulfuric Acid

Fluorite Water + Sulfuric Acid -> Chemical Reactor => Hydrofluoric Acid + Calcium Sulfate Solution
Calcium Sulfate Solution -> Crystallizer => Calcium Sulfate
