### ISSUE TITLE
Chemical Reactor doesn't accept molten Boron

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#265]
Hey!

As the title says, the Chemical Reactor does not accept molten Boron. It does accept both Boron-10 and Boron-11.
JEI says Molten Boron + Hydrogen = Diborane, so it should be able to, afaik.

Minecraft 1.12.2
NuclearCraft-2.9e--1.12.2

**Comment by turbodiesel4598** [comment]
Ah, you must have another mod that adds molten boron - should be an easy fix :)

**Comment by turbodiesel4598** [comment]
Hmmm, that is bizarre. Which mod is adding the molten boron?

**Comment by NillerMedDild** [comment]
D'oh, I didn't notice it wasn't from NuclearCraft, my bad! It's from JAOPCA.

**Comment by turbodiesel4598** [comment]
It still should have worked though. I've just spent all day tring to fix this, but ultimately I think it's JAOPCA doing something weird. Recipes involving fluids added by other mods works absolutely fine, but those from JAOPCA just don't.
