### ISSUE TITLE
Reactor from tutorial overheats!

### ISSUE THREAD

**Issue by davidsielert** [turbodiesel4598/NuclearCraft#266]
I build the 2x2x3 Fission reactor per the tutorial,  Using current version of FTB revelation.  I do not get the negative heat modifier as shown in the wiki (-12H/T) and instead heat keeps steadily rising and rising..

Screens... 

![2018-03-24_02 05 10](https://user-images.githubusercontent.com/456592/37862381-10e378c6-2f09-11e8-9732-4d34c157e23f.png)
![2018-03-24_02 06 00](https://user-images.githubusercontent.com/456592/37862382-10f8e2a6-2f09-11e8-8987-eb3887983518.png)
![2018-03-24_02 05 31](https://user-images.githubusercontent.com/456592/37862383-110d9692-2f09-11e8-8b94-5da11aab31d9.png)

Using just the regular TBU Fuel cells as listed...

**Comment by turbodiesel4598** [comment]
As hinted to at the top of that tutorial, the instructions are a little out of date as the reactor rules have changed - I will get them fixed up today if I can :)
