### ISSUE TITLE
Chemical Reactor not accepting molten boron

### ISSUE THREAD

**Issue by Landstryder** [turbodiesel4598/NuclearCraft#267]
Can't get the chemical reactor to accept molten boron in any manner.. via bucket, placing machines next to each other, piping it through mekanisim pipes. Is there some other thing you need to do... tried all three version of it as well... Boron, Boron-10 and Boron-11

Forge 14.23.2.2629

NC-2.9e

Modpack - Atom Smasher

**Comment by turbodiesel4598** [comment]
[As discussed briefly here](https://github.com/turbodiesel4598/NuclearCraft/issues/265#issuecomment-375822826), there does not appear to be anything I can do on my side to fix the bug that molten boron from JAOPCA is not accepted by the chemical reactor - I think it has something to do with the way it adds new fluids to the game, as recipes using fluids from other mods work perfectly fine, such as those from Thermal Foundation.

However, molten boron-10 and boron-11 are added by NC and should _definitely_ be accepted. Are you sure no recipes have been altered in the pack?

**Comment by Landstryder** [comment]
OK yea boron-10 and 11 work, I was just trying only with a bucket, pipes put the boron-10 in just fine

**Comment by turbodiesel4598** [comment]
Great - so yeh, not sure about the boron thing, but it's been added directly to NC now, so it should accept it in later versions :)
