### ISSUE TITLE
[Crash] Clash of dimensions after upgrade (Nuclearcraft 2.10 <-> AE2) [1.12.2]

### ISSUE THREAD

**Issue by JulianSchutsch** [turbodiesel4598/NuclearCraft#271]
Environment: Minecraft 1.12, Linux Ubuntu 17.10, Forge 14.23.2.2629. Several other mods.

Was a new dimension introduced in Nuclearcraft 2.10? Upgrading Nuclearcraft 2.9e to 2.10 makes AE2 crash an exception regarding dimension id=2.

I was able to get around that by simply deleting the AE2 config here. The dimension was then id=3.

Not sure about the side effects of renumbering dimensions like that.

**Comment by turbodiesel4598** [comment]
This was fixed in [v2.10a](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2546611) :)
