### ISSUE TITLE
CraftTweaker integration

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#272]
Hey! It looks like the recent changes to your CraftTweaker compatibility messed something up, I'm getting this error from my script:
![billede](https://user-images.githubusercontent.com/21295394/38145512-fb0eab24-3449-11e8-8e7c-513b32616f8f.png)

[Script](https://gist.github.com/NillerMedDild/ee3918b693165d30ab9e152c9608977f)
My script worked fine in 2.9e, although the `removeRecipeWithOutput` were all `removeRecipe`.

Minecraft 1.12.2
NuclearCraft-2.10a--1.12.2

**Comment by turbodiesel4598** [comment]
Does the CraftTweaker log tell you which line errored?

**Comment by NillerMedDild** [comment]
It appears to be line 17, as everything before that works correctly.

**Comment by turbodiesel4598** [comment]
Thanks - was a simple fix. [New version should be available on CurseForge shortly :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2546704)

**Comment by NillerMedDild** [comment]
Thanks once again :D

**Comment by turbodiesel4598** [comment]
No prob!

**Comment by NillerMedDild** [comment]
Err.. It's throwing the same error.

**Comment by turbodiesel4598** [comment]
Wow, I missed something really obvious - it's those errors which are sometimes the most difficult - [does this version work?](https://www.dropbox.com/s/a863s1xpu9huh2v/NuclearCraft-2.10b--1.12.2.jar?dl=0)

**Comment by turbodiesel4598** [comment]
Seems like a slightly bigger issue than I first thought, but will hopefully have a fix sometime tomorrow - will use your script as a test :)

**Comment by turbodiesel4598** [comment]
Ok, from quite a bit of testing, [I think I've fixed all of the errors you were having](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2547236) and have also fixed the ore dictionary support :)

**Comment by NillerMedDild** [comment]
It works! Good job :D

**Comment by turbodiesel4598** [comment]
Awesome - sorry about the fail first time round, but the end result was worth it!

**Comment by NillerMedDild** [comment]
No worries at all!
