### ISSUE TITLE
Double-Click Returns Processing Fuel Then Crash

### ISSUE THREAD

**Issue by Gitsum-Taran** [turbodiesel4598/NuclearCraft#273]
Had a TBU fuel rod lined up for my reactor and wanted to take it out, using double click I picked up the one in the reactor inventory (queued), the one sitting in my inventory, and the one inside the reactors 'hidden' inventory (fuel rod currently being processed as fissile fuel inside the reactor).

TLDR: Double click on a already present fuel rod while an identical one is already being used in the reactor gets pulled out and causes the crash.

Crashlog:
https://pastebin.com/46Br7Ss4

Versions: 
Minecraft 1.12.2
Forge 14.23.2.26.27
FTB Revelation: 1.6.76
NuclearCraft-2.9e--1.12.2

**Comment by turbodiesel4598** [comment]
Ah, I see what you mean. Will get working on a fix tomorrow morning :)

**Comment by turbodiesel4598** [comment]
Scratch that - [here's a build that contains the fix](https://www.dropbox.com/s/6xf4bcklejpyfk5/NuclearCraft-2.10c--1.12.2.jar?dl=0), will get a new version out on CurseForge tomorrow after getting a couple other things done :)

**Comment by Gitsum-Taran** [comment]
Talk about hotfix! Thank you for the brisk bug-stomps and I wish you good luck with the rest!

**Comment by turbodiesel4598** [comment]
No prob, and thanks a bundle :)

**Comment by turbodiesel4598** [comment]
[Fixed in version 2.10c :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2548564)
