### ISSUE TITLE
Nuclear Fission Reactor Causing Client Crash

### ISSUE THREAD

**Issue by TraversTT** [turbodiesel4598/NuclearCraft#274]
[crashlog](https://pastebin.com/xmzQ4v2y)
I have been crashing (client not server) whenever I get near the nuclear fission reactor, this can be fixed by restoring to a point prior to running it.  I can add fuel and turn it on, it works fin for a while (variable time) then starts crashing my game till I restore, this even happens after it is out of fuel provided I have not toggled it off.

**Comment by turbodiesel4598** [comment]
Seems to be related to the Compact Machines mod in some way -I'm not very fimiliar with it, so could you give me some more details about your setup?

**Comment by TraversTT** [comment]
Yeah, so the compact mod makes small (what seems to be perm chunck loaded) dimentions in order to store machines, my reactor is housed in one of these dims and interacts with a redstone signal that comes from the wall of this dim that can be switched on/off outside the dim. Also in this dim a setup for processing my ore and drops exists which feeds a seires of nuclearcraft machines uranium that is directly pumped into the reactor. The reactor causes no server side crashes while running and cont to pump out power but upon entering the dim the crash occurs.

**Comment by turbodiesel4598** [comment]
Could you run the reactor without the redstone signal? There is definitely something nasty going on with it...

**Comment by turbodiesel4598** [comment]
Given that there's been no similar reports in eight months, I think I'll close this issue.
