### ISSUE TITLE
Request: Investigate EnderIO 1.12 compatibility

### ISSUE THREAD

**Issue by scotty9090** [turbodiesel4598/NuclearCraft#275]
I'm not sure if I should be opening this issue or not, but on the EnderIO page it states the following:

_The following mods are known to crash or cause malfunctions when Ender IO is installed. This is not Ender IO's fault._
---snip---
_NuclearCraft_
---snip---_

I asked about this on Reddit and it sounds like it has to do with some IDs they changed.  I would love to have EIO available again in 1.12, but not sure I want to do it at the expense of NC.  

I suspect you are probably aware of this already but didn't see it on the tracker so hopefully it's okay to add it.

**Comment by turbodiesel4598** [comment]
Apparently it was a bug related to the EIO tank searching through the fluid registry and NC fluids not being registered correctly - [should be fixed as of 2.10c :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2548550)

**Comment by scotty9090** [comment]
You are awesome - thank you!
