### ISSUE TITLE
NuclearCraft and enderio 1.12.2

### ISSUE THREAD

**Issue by IchigoGames** [turbodiesel4598/NuclearCraft#276]
this is more of a question but are you working on fixing any mod compatibility issues between this mod and enderio 

The following mods are known to crash or cause malfunctions when Ender IO is installed. This is not Ender IO's fault.

NuclearCraft

not the only mod on the list i just removed the others to make this short.

**Comment by turbodiesel4598** [comment]
I've just fixed it - was only a small issue with the EIO tank, [but it should now be sorted in the latest version](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2548581), which is still being reviewed at the time of writing but should be available pretty soon :)
