### ISSUE TITLE
Californium RTG - Inconsistent Behavior

### ISSUE THREAD

**Issue by scotty9090** [turbodiesel4598/NuclearCraft#279]
v 2.10d

I'm getting very odd behavior with the Calif RTGs, particularly when I place two of them touching.  I've spent the last hour or so experimenting and trying to isolate some type of pattern here but other than figuring out that putting two or more of them directly adjacent makes them freak out (sorry - best description I can come up with), I'm having difficulty pinning things down.  Here are some of the things I've observed (TE Resonant ducts / RFTools Advanced Powercells / TE Multimeter used for tests):

* Power seems to conduct between the RTGs in some cases but not others.  E.g. I can place down three in a row with only the center one connected to a conduit and I get 1200 rf/t - even though one is connected. If I add a few more though (top or back) there's no increase though.  This behavior happens sometimes, but not always.  On one occasion when testing with the RFT Powercell, power simply stopped being transmitted at all.

* Placing them adjacent, again sometimes, makes them appear to stop outputting power.  So I have RTG-Empty-RTG and am getting 800 rf/t.  If I fill that empty space with another RTG (all connected via flux ducts) I actually get a power decrease (which is not a round number) in some cases, and in other case I simply get no change at all.

* The TE multi-meter reads 800 rft/t for a single RTG - which should be 400 according to the tooltip.  Maybe this is a problem with the multi-meter though since the RFT Powercell tells me 400.

There were other weird things too, but having them touching each other seems to be the main trigger.  Is this supported, or are there some limitations on setup I'm missing?  The behavior I expected here is that I get 400 x n rf/t where n is the number of cells and assuming they all have to be wired.  I'd appreciate it if you could have a look to see if you can reproduce.

**Comment by scotty9090** [comment]
UPDATE:  I did some more testing with EIO power conduits which offer the ability to set to Extract only mode and this definitely seems to help things.  As long as: a) no RTGs are touching one another and,
b) all conduit connections are set to extract only, everything seems to behave.

So my best guess here is that the RTGs are somehow **accepting** power and possibly cannibalizing one another.

**Comment by turbodiesel4598** [comment]
Thanks very much for the very thorough info! I managed to track down the issue - as you predicted, power was sloshing back and forth between the RTGs. That will no linger happen in future versions :)
