### ISSUE TITLE
Fusion reactor needs too much energy to start

### ISSUE THREAD

**Issue by 456Xander** [turbodiesel4598/NuclearCraft#28]
On the wiki it says, that a fusion reactor would use 40,000,000 RF to get started. But when I testet the Fusion Reactor in my world, it used many billions of RF to get started. Also the Reactor drops below 7MK, although in the wiki and in all the videos I watched it didnt get colder at 7MK.

**Comment by Dazzik316** [comment]
I've noticed the same thing, stacking 5 or 6 creative energy cells around it finally gets it going but in my survival world I have everything built but no practical means to generate enough to turn it on.

**Comment by Dazzik316** [comment]
I've just discovered a config option in FusionConfig.cfg that seems to fix the issue.

 #  [range: 10 ~ 1000, default: 100]
    I:"Fusion Reactor Heat Production Multiplier"=100

setting this to a higher number allows the reactor to warm up at a faster pace, at 1000 I was able to get it started with several Resonant Energy Cells.  It also speeds up the ramp up time once the reactor is self sufficient.

**Comment by turbodiesel4598** [comment]
The amount of power required is certainly too high - this is an easy fix for the next version - for now, as Dazzik316 says, you can turn the heat production multiplier up to speed up the heating rate of the reactor.

**Comment by turbodiesel4598** [comment]
Fixed as of version 1.7 :)
