### ISSUE TITLE
[Request] Config to turn off the Wasteland Dimension

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#280]
Hey hey!

I'd like a config to turn off the Wasteland Dimension, as it's adding a little bit of lag to my server. It's always loaded, and cannot be unloaded for some reason.

I'm a bit curious, what is the purpose of the dimension, and is there a way to get there?

Minecraft 1.12.2
NuclearCraft-2.10c--1.12.2

**Comment by turbodiesel4598** [comment]
Yes, that should be simple - will get that sorted for the next version.

It doesn't have a massive purpose right now, but will be used in the future for... various things ;)

**Comment by NillerMedDild** [comment]
Thanks!

Looking forward to the future plans for the place :D
