### ISSUE TITLE
Wasteland Biome disable?

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#281]
More of a question before upgrading - can the biome be disabled? I ask because sometimes mod biomes do mess with the generator of minecraft, so that the generation of a seed does no longer give the output that was expected, maybe this is not the case with your biome, but if it is, i need to disable it, or the world will look pretty ugly.

**Comment by turbodiesel4598** [comment]
Yes, the biome can be disabledin the configs, in the 'Other' section.
