### ISSUE TITLE
Wasteland Dimension generates regardless of config

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#282]
Heya!

It seems that the Wasteland Dimension generates whether the config is true or false.
Steps to reproduce: Change the `wasteland_dimension_gen` config to `false`. Make a new world, use the command `/forge tps` after a few seconds, and see the Wasteland in the list.

Minecraft 1.12.2
NuclearCraft-2.10f--1.12.2

**Comment by turbodiesel4598** [comment]
I wonder, [does this work?](https://www.dropbox.com/s/y7u2tek4z9nu94a/NuclearCraft-2.10f--1.12.2.jar?dl=0)

**Comment by NillerMedDild** [comment]
Yeah that woks, thanks!
