### ISSUE TITLE
Cooling Bug or Hard Limit on cooling?

### ISSUE THREAD

**Issue by RobertBouillon** [turbodiesel4598/NuclearCraft#283]
I built an 11x9x11 reactor, and when I went to improve the cooling by switching my passive helium coolers to active coolers, I noticed that it didn't change the cooling AT ALL.

I thought it might be a bug with active cooling, but when I replaced the passive helium cooler, I noticed even the passive cooler had no effect. I checked to ensure it was next to an active redstone cooler, and it was.

I'm using 2.9e on 1.12.2 (FTB Revelation Pack v1.8).

https://imgur.com/a/emfJT

I can zip my world if you need it.

**Comment by turbodiesel4598** [comment]
Yo - the reason the liquid helium cooler is doing nothing there is because it must touch **_exactly_** one redstone cooler - it looks like it's touching two in the picture ;)

**Comment by RobertBouillon** [comment]
Ahhhhh good to know. Thanks!
