### ISSUE TITLE
Allow for heat sinks with new types of placement rules

### ISSUE THREAD

**Issue by RobertBouillon** [turbodiesel4598/NuclearCraft#285]
Wanna see a wider variety of designs? :)

Examples: 
Bronze Cooler - 20 H/t for every active adjacent cooler. Must touch reactor casing. (Filler, makes routing pipes for active cooling harder).
Aluminum Brass Cooler - 40 H/t for every adjacent moderator block
Cryotheum Cooler - 200 H/t. Touches 2 active Reactor Cells. Cooling reduced by 50% for every adjacent moderator block. (Mitigates the reactor cell / moderator XO design)
Enderium Cooler - 20 H/t for every active moderator it touches. Cooling doubles for every casing it touches.
Aluminum Cooler - Acts as an internal "reactor casing" which can activate other blocks that must touch the reactor casing to be active (essentially extends the reactor casing internally). Must touch a reactor casing (or active aluminum cooler) to be active (i.e. chaining is supported). Reduces efficiency of adjacent cells, moderators, and coolers by 50%.
Water Cooler - Must touch 1 moderator block or cell (same as current). 20 H/t for every reactor casing it touches.

**Comment by turbodiesel4598** [comment]
I will leave this here as some of those are really nice ideas. Unfortunately, due to the way the fission reactor is set up, I've hit the max number of coolers possible (ran out of metadata), but in 1.13 we will be free of those shackles and I will add a bunch more coolers with new rules such as the ones above :)

**Comment by ToMe25** [comment]
@turbodiesel4598 couldn't you relatively easy split the coolers into "nuclearcraft:cooler_solid" and "nuclearcraft:cooler_liquid" or into "nuclearcraft:cooler" and "nuclearcraft:cooler2" even with only one class and if you need to move some old coolers to a new id just use DataFixers or a check in the TileEntity update?
Or does that cause any problems so you don't want something like that?
If you want me to i think i could implement that(the cooler splitting) if there isn't any Part i don't know about yet.

**Comment by turbodiesel4598** [comment]
@ToMe25 I certainly could, and did consider doing that, but since there are now basically [complete plans in place](https://www.youtube.com/watch?v=GDm0JxynPR0) to overhaul the fission system and allow for custom heat sinks and molten salt coolants via configs and addons :)

**Comment by ToMe25** [comment]
OK Thank you for the Reply i didn't knew the overhaul was even close to fully planned or even being implemented :)

**Comment by turbodiesel4598** [comment]
Will hopefully be released in a couple of months, once I'm back from uni :)

**Comment by turbodiesel4598** [comment]
Although custom heat sinks have been possible for a while via addons, there is now a system in place for addons to introduce parsers of strings and tooltip generators for rules of arbitrary complexity. By default, NC has the capability to deal with 'adjacency-type' recipes, i.e. `Must be adjacent to x, y, and/or z`, including axial and vertex sub-rules :)
