### ISSUE TITLE
[Suggestion] Active Coolant recycling

### ISSUE THREAD

**Issue by RobertBouillon** [turbodiesel4598/NuclearCraft#286]
I really like the idea of active cooling, but find it wholly unreasonable in survival. Water doesn't provide enough of a benefit, and everything else is just far too expensive. 

What if you made it a little more realistic, where the active cooling block modifies the coolant?

For example, liquid helium returns to helium. It gets pumped out and needs to hit a supercooler (or 30) to be condensed again. (Supercoolers are punishingly expensive RF-wise. Can this be revised? Maybe feed in liquid nitrogen for an efficiency boost or something? Or an efficiency upgrade that reduces RF scaling? Maybe add a super-duper cooler? XD)

Water turns to steam (See #155). This is easy enough to vent or used for something else. It COULD be recycled with a condenser, and this may be an option early-game where infinite water machines are not yet available (or disabled by modpack designers). A coolant vent block that attaches to a buffer or pipe could be really cool.

This also gives a real benefit to late-game multi-channel fluid pipes. Early game, each active cooler would need one-in and one-out. mid-game, multi-channel pipes would make for better designs.

**Comment by turbodiesel4598** [comment]
Similarly to the reason I gave on the other active cooler issue, this is ultimately a 'balance' thing - active coolers are meant to be super expensive to run.

Again though, the new molten salt coolers will be recyclable :)

As for the supercooler issue, the best solution is just... build more supercoolers ;)

**Comment by RobertBouillon** [comment]
Looking forward to the new molten salt coolers! :)
