### ISSUE TITLE
[Suggestion] Fission Reactor Analyzer Goggles

### ISSUE THREAD

**Issue by RobertBouillon** [turbodiesel4598/NuclearCraft#288]
A craftable helmet that shows a UI when worn that:

1. Displays A 2D UI with the total cooling of the multiblock structure you're looking at, efficiency and heat ratios.
2. Shows an overlay for coolant blocks that are not currently active. (Changes the texture to make them darker, or shows a red outline similar to XNET. Should be visible THROUGH other blocks). Helps to guarantee that all your cooling blocks are actually working.
3. Optional overlays, similar to bullet 2, which highlights blocks that are creating heat or RF, with some visual indicator of range (higher efficiency is brighter?)

"Cool" in current version. "Valuable" with #285

**Comment by turbodiesel4598** [comment]
Well, it's a nice idea, but it will take a while to implement something like this - will put it on the long-term to-do list :)

**Comment by ben-mkiv** [comment]
haven't looked at the new OC integration yet, but how about a method that returns the current Reactor Layout?

If you have the Layout the HUD could be done with OpenComputers + OpenGlasses

**Comment by turbodiesel4598** [comment]
The addition of a reactor layout reader was added a few versions back, so I think this can now be achieved through OpenGlasses :)
