### ISSUE TITLE
[MMD] Missing depleted fuel textures

### ISSUE THREAD

**Issue by samip5** [turbodiesel4598/NuclearCraft#289]
Logs and required information can be found on the other issue.

Related: MinecraftModDevelopment/New-MMD-Public-Pack#54

**Comment by turbodiesel4598** [comment]
Yep, I know ;)

The textures are missing because I haven't fully phased those items in yet - when I do, I'll get the textures sorted for them. You won't see them in the game, so it shouldn't be a problem :)

**Comment by turbodiesel4598** [comment]
Alrighty!
