### ISSUE TITLE
Fusion Blacklist\Whitelist and less than a bucket left

### ISSUE THREAD

**Issue by Zunth5** [turbodiesel4598/NuclearCraft#292]
I was curious if there is a way to blacklist/whitelist fluid fuels in the fusion reactor gui to a specific fuel type(s) to specific input tanks, so that if one fuel runs out, the other wont fill an empty slot.

I need to check this one when I get home (I could be wrong on how this behaves):
If there is less than a bucket of fuel left (say Hydrogen) Im pretty sure you cannot load another fuel because there is not enough fuel complete a cycle and empty the tank. I propose a button on the gui that toggles the ability for the fusion reactor to be able to either void partial buckets of fuel at the end of a reaction, or the ability to process partial buckets for a percentage of process time based on how much fluid is left.

Just starting out I found these two reactions produced Hydrogen and Helium3 inversely, so I was able to sustain temperatures (and over time increase efficiency) by swapping the products out and using the Neutron fluid to produce great amounts of Tritium. This is not net gain; Hydrogen, Lithium and/or Boron would need to be created/processed. The idea is that you would only need a single reactor to alternate between T-H and T-He3 combos if set up correctly and it would take considerably less reserve fuels get a reactor to desired efficiency.

This could also help when using a less costly fuel to "pre-heat" a reactor and automatically swap over to another fluid after these fuels run out.

These things cannot currently be done because fuels in the tanks cannot be controlled/separated automatically.

**Comment by Zunth5** [comment]
Confirmed that leaving less than a bucket in the tank of any liquid stops alternative fuels from being loaded.

**Comment by turbodiesel4598** [comment]
When I originally read this, I didn't imagine it would be possible wihtout some trouble, but I think I have managed to implement it in a reasonably intuitive way, pretty much as you described above. Every time a process gets completed, if this voiding option is on, then if it is not possible to initiate a new process, the input fluids will be voided - this will be available in the next release, which should be tonight :)

**Comment by Zunth5** [comment]
Epic, I cant wait to see this tank clearing in action. I am curious if tank white-listing has also been added to manage fuel control more effectively as well. I also quite enjoyed the fission video that covered everything in one go. Keep up the awesome

**Comment by turbodiesel4598** [comment]
Fluid whitelisting is quite tricky do do on the machine's side of things - could you not set up some redstone-controlled filtered input pipes?

**Comment by Zunth5** [comment]
Not really because the internal tanks don't care if you have multiple fuels. If your trying to load T-He3 (after completing T-H for example), It will input Tritium into the second tank causing a T-T reaction. This would not be an issue if there were dedicated input ports for each internal tank on the 3x3x3 or some method of white-list per tank.

**Comment by turbodiesel4598** [comment]
Have you tried using the ‘Prevent Input Overflow’ mode? This will prevent one fuel type filling both input tanks.

**Comment by Zunth5** [comment]
Is this the function of the button on the upper right corner of the interface without text label? I must have missed the info on that in an update and was actually wondering what the mode change did.

My apologies; I have not tried this. If this functions as described it should work fine for alternating between T-H and T-He3 combos. The tank will empty with the help of the new (less than a bucket cleanup) toggle button, and then the alternate fuel can load while Tritium remains in the first tank and will not load to the second.

The only thing I can think of being an issue is when trying to intentionally load the same fuel (possibly for pre-heat) and then wanting to swap to primary fuels, but you can use Li7-B11 for this as an alternate method than Li7-Li7 or B11-B11 which all have similar higher Heat Variables. 

I appreciate the help and wanted to state again how epic this mod is, and like your vision for its progress and functionality. Please keep up the good work. My hope is that this remains a power generation option in the popular FTB packs.
