### ISSUE TITLE
Infinite water source produces water very slowly

### ISSUE THREAD

**Issue by nullifiedcat** [turbodiesel4598/NuclearCraft#296]
Instead of producing 640 mb/t, it produces 640 mb every few seconds.

**Comment by turbodiesel4598** [comment]
I'm guessing this is the dense water source... there was a similar issue before with the cobble generators, but it seemed to be a one-world issue. If you place it down in another new world, does it still generate water slowly?

And do keep in mind that the water/helium/cobble/nitrogen sources don't update every tick - they will only actually produce stuff every four seconds or so, but it should be the right amount per tick on average.

**Comment by nullifiedcat** [comment]
>If you place it down in another new world, does it still generate water slowly?

Yes

>And do keep in mind that the water/helium/cobble/nitrogen sources don't update every tick

I think it's better to change tooltip from mb/t to mb/s then

**Comment by turbodiesel4598** [comment]
Ok, good to know - still need to figure out why this issue happens at all. It's very bizarre.
