### ISSUE TITLE
Buffers for items

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#298]
I thought i can use Buffers to input Nuclear Fuel and output the depleted fuel - but this does not work. Is it supposed to work?

**Comment by turbodiesel4598** [comment]
You need to use _fission ports_ to access the controller. Buffers are for getting fluids to active coolers ;)

**Comment by D3nnis3n** [comment]
Okay, i now tried the same with Fission Ports - i was able to remove the depleted cells, but i'm not able to put in new, fresh cells. What might be the reason for that?

**Comment by D3nnis3n** [comment]
See the following screenshots with the guis being from the left cable to the right (so first left chest, fission port, right chest).

<img width="432" alt="aa" src="https://user-images.githubusercontent.com/25908592/39205940-5d106f72-47fc-11e8-9ee8-53ec10b4a466.png">
<img width="429" alt="bb" src="https://user-images.githubusercontent.com/25908592/39205942-5d2b2254-47fc-11e8-84fe-4cb0236d48ab.png">
<img width="428" alt="dd" src="https://user-images.githubusercontent.com/25908592/39205943-5d44f4e0-47fc-11e8-8a7a-1fdb840f10f7.png">
<img width="430" alt="ee" src="https://user-images.githubusercontent.com/25908592/39205945-5d5e2898-47fc-11e8-8cc6-cf47a3637f25.png">

**Comment by D3nnis3n** [comment]
@turbodiesel4598 
Tried around with Mekanism Pipes - same result. Inputting does not work. Do i need to input them from a special side (front instead of downside)?
