### ISSUE TITLE
[Question] Alternate Fluids?

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#299]
What does this:
    # Register alternative redstone, glowstone, cryotheum and ender fluids? It is recommended that this is set to true if no CoFH mods are installed.
    B:register_cofh_fluids=true
exactly do?

I set it to true, as i no longer have anything from CoFH - but e.g. enderium is still unavailable?

**Comment by turbodiesel4598** [comment]
Perhpas look up '_molten ender_' instead?

**Comment by D3nnis3n** [comment]
Well i can't craft the enderium cooler, while i can with the crytoheum for example - it's made out of tin, it seems.

**Comment by turbodiesel4598** [comment]
You can craft the cryotheum coolers?

**Comment by D3nnis3n** [comment]
Yes. They're made with molten crythoeum which can be made out of tin and beewax in forestry.
Molten Ender is there but has no recipes. The enderium cooler also has no recipe.

**Comment by D3nnis3n** [comment]
Your molten redstone and glowstone also have no recipe - but i can use the one from enderio and Tic.

**Comment by turbodiesel4598** [comment]
Yeh, the reason you can't make enderium coolers is because they require enderium, not just ender pearls or molten ender.

Can you not produce NC's molten redstone, glowstone and ender in the Melter?

**Comment by D3nnis3n** [comment]
No.
Glowstone = Glowstone Gas (Ender IO)
Redstone = Molten Redstone (Ender IO)
Ender Pearls = Molten Ender Pearls (Ender IO)

Evil Ender IO.

**Comment by turbodiesel4598** [comment]
But that's fine - those fluids will still be valid active coolants.
