### ISSUE TITLE
[Suggestion] Add support MineTweaker/ModTweaker

### ISSUE THREAD

**Issue by Tsyklop** [turbodiesel4598/NuclearCraft#3]
Please. add support MineTweaker/ModTweaker for machines in your mod

**Comment by turbodiesel4598** [comment]
I will do this at some point, although it is not a huge priority right now - I have been talking about adding the particle accelerator for some time now, and that's at the top of the to-do list.

**Comment by Tsyklop** [comment]
Okay. thanks.

**Comment by turbodiesel4598** [comment]
I've updated the mod so that there is a new config file that disables the workspace and enables vanilla crafting recipes - these recipes can then be edited with MineTweaker.

**Comment by Tsyklop** [comment]
@turbodiesel4598 I can change the recipes in the machine? if disable this option

**Comment by turbodiesel4598** [comment]
Not the machines - I don't really have the time to do an addon for those, but somebody else might.

**Comment by Robijnvogel** [comment]
In that case I have to disable the crafting of most Nuclearcraft processing machines in my modpack, I guess. :/

**Comment by indoorsNB** [comment]
same problem
