### ISSUE TITLE
Fusion reactor placement bugs with Galacticraft Sealed rooms and various light generating blocks.

### ISSUE THREAD

**Issue by kurtu5** [turbodiesel4598/NuclearCraft#30]
I am playing Galactic Science 1.5.9 and it uses NuclearCraft-1.6c--1.7.10.jar.  I stumbled across a few bugs with preventing reactor placement.

1.  You can't place a reactor in a room sealed by the Galacticraft Oxygen Sealer.  If you expose the room to vacuum, you can place the reactor.

2.  Various blocks that change light levels prevent placement.  Removing these blocks allows placement.
   a) Galacticraft Core Arc Lamp.   This lamp is very bright and illuminates a very large fan shaped area.   
   b) Router Reborn Flood Light.  This block makes the first non-transparent block directly beneath it act as if there is a torch on it.   If this block intersects the 3x3 reactor footprint, you can't place it.   
   c) Greg's Lighting Floodlight.   This lamp is also bright and illuminates a long rectangle shaped area.
   d) I guess other light changing blocks as well prevent placement...

I can replace the light sources and reseal the room after placement and the reactor seems to start working fine(its warming up).

**Comment by turbodiesel4598** [comment]
This is all to do with the fact the the reactor is only placeable when the volume in which it will sit is all air blocks - these mods are adding their own 'air' blocks with the effects you have described - I have noticed this before, and I can't really see how I can get around this problem for now :/

**Comment by kurtu5** [comment]
Well at least there is a work around by temporarily changing the environment.  By the by, is the wiki still correct that it takes 3/4 of a full vibrant capacitor to get to 8MK?  I can't seem to get to 6Mk with 5 full capacitors before running out of juice and the reactor stops heating and starting to cool.  Still I am having fun breeding MOX into HEP 241.

I will probably make a wilki edit to note the 'bug' and perhaps add some fuel research tables, so knowing the current reactor requirements has me curious.

**Comment by turbodiesel4598** [comment]
Yeh, I made it far too difficult to heat up the fusion reactor - there is a config option which increases the heat production as a temporary get-around, but this problem will be fixed next version.

**Comment by kurtu5** [comment]
Cool. Thanks for the update.  I know you are working on different types of new fusion reactors; stellerators/tokmats/pinch devices... so I am looking forward to those new updates.
