### ISSUE TITLE
Lag through NuclearCraft Active Coolers

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#301]
Hey,
you said you optimized that a bit - i don't know if it got much better, but after we had started to get massive lag spikes, i asked over at enderio if they could help and sent them reports from sampler.

That's a screen from the results - the coolers take 10% of the complete tickrate and seem to be at least also causing these spikes:

![unknown](https://user-images.githubusercontent.com/25908592/39376875-7abe4c8e-4a53-11e8-81c3-f4a991bfa8d8.png)

Any way to optimize them further? For a big reactor loads of coolers, at least when used water is needed.

**Comment by turbodiesel4598** [comment]
I've made them update more slowly now so hopefully that should help. I'll get the new version out soon so you can see whether there's a meaningful difference :)

**Comment by D3nnis3n** [comment]
That did not help for that lag - and it made the reactor unusable, as it is too slow. Now i need to put an enderio cable to every cooler again - which lags the server even more :(

**Comment by D3nnis3n** [comment]
Maybe i should just configure the non-active watercoolers to give the same effect and restrict those for normal players. I don't know.

**Comment by D3nnis3n** [comment]
Here is a sampler file - i do not know how to open them, unfortunatley. 

[sampler-snapshot_1.zip](https://github.com/turbodiesel4598/NuclearCraft/files/1957493/sampler-snapshot_1.zip)

**Comment by D3nnis3n** [comment]
Btw: I got a 14x14x14 reactor.

**Comment by turbodiesel4598** [comment]
Ok, I've given them a bigger buffer and slightly increased their update rate again. Whatever the case, I can't ever get the spread rate to be infinitely smooth, because it is limited by both the buffer size of each cooler and also the rate of the spreading.

[Here is the new version.](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2556403)

Could I see a picture of your setup to see if it can be optimised in some way? And how many active coolers are you using?

**Comment by D3nnis3n** [comment]
I'm sure it definatley can be optimized, but it was the most asthetic try with high output we made.
We use a lot of them, the complete cube edges and corners are full of them. Here you got a screenshot.

Well, i know to get it completley smooth it would need to be a complete other mod (e.g. the reactor itself takes the water in it and the amount of coolers only define how fast it drains and how good it cools, but that wouldn't work with multiple coolers placed like the mod is thought to be.)

Here is a screenie from the inside. It's pretty basic. Aim is primarily aesthetic, secondarily easy and third enough energy. It must be walkable.

I'll test the new version later on.

<img width="429" alt="reactor" src="https://user-images.githubusercontent.com/25908592/39399272-3778e43e-4b1b-11e8-939e-da5ac99dcb10.png">

**Comment by D3nnis3n** [comment]
That's the one main reactor for steady power supply for the complete city, it needs to be easy.
There are three other blocks that will be filled with more complicated designs for other fuels. (If lag is fine ...)

<img width="432" alt="calvert" src="https://user-images.githubusercontent.com/25908592/39399306-d47c5b94-4b1b-11e8-8453-fe20e101ca19.png">

**Comment by turbodiesel4598** [comment]
So you have about 1000 active water coolers?

**Comment by D3nnis3n** [comment]
Yes. How big are your reactors?
See: A 5x5 Reactor in that big reactor containments would look ... well.
Also, that reactor does meet the needs of around 40 players.

**Comment by turbodiesel4598** [comment]
Well, I usually never use that many active coolers - I usually look for the most efficient passive design, then sometimes introduce active cooling where I can if I have the resources. The active cooling is bound to introduce at least some lag, as the reactor has to deal with the fluid, while the passive coolers just sit there, and 1000 of any machine is gonna hit your tps. Have you tried using infinite water sources instead of conduits?

**Comment by D3nnis3n** [comment]
What do you mean with that? I need the conduits to spread the water in from a big tank we have. If i use lesser conduits the autospread is too slow. (I did not test the new version yet, the one before did not work anymore).

We got no infinite water sources on the server - it's a reallife themed server. Therefore in this nuclear power plant only water is allowed for active cooling *g*

**Comment by D3nnis3n** [comment]
I also understand lagging while the reactor is running (which is at max 30 minutes a day) - but it keeps doing that while it's not active, btw.

**Comment by turbodiesel4598** [comment]
What I mean is to not use conduits at all, but instead use NC's infinite water sources connected directly to buffers.

I really do think the lag you're getting is _completely_ due to the number of active coolers you have. They were never meant to be used in the way you're using them, i.e. in huge quantities. Why don't you use a different design with more passive cooling? It looks like most of your reactor is empty.

**Comment by D3nnis3n** [comment]
NC has infinite water sources? Hope noone used them to glitch out our finite water sources. I'll see if that helps. (But would have something of cheating.)

Well, i tried around a lot, but a main goal is to have a design that somehow can be considered "real life" and that would only be the case with water coolers.

**Comment by D3nnis3n** [comment]
Edited previous post as it was misunderstandable.

**Comment by turbodiesel4598** [comment]
Hmm, if you built the other three reactors and used _much_ less active cooling, you'd probably produce enough power and have far less lag.

**Comment by D3nnis3n** [comment]
Well, the other three were planned to be used for other materials - which we not got in that amount as we got uranium. I'll see if i can find an near efficent design with passive water cooling instead of active cooling.

**Comment by turbodiesel4598** [comment]
Aren't you using passive redstone coolers already in your design?

**Comment by D3nnis3n** [comment]
Yes, but their cooling is not really needed, it was more of a security net when sometimes some coolers do not get water fast enough and is rarely needed. I justified it with a hull around the cells *g*

**Comment by D3nnis3n** [comment]
Haha, i can drive the same setup when filling the reactor with water coolers (not active) completley BUT still have 2060 heat. DAMN.

**Comment by D3nnis3n** [comment]
So, i'll get those through active coolers and therefore justify the "filling" of the water coolers. That should be fine. And six or so coolers should not be too much.

**Comment by turbodiesel4598** [comment]
Aaah... I think I know why there was more lag in the later versions I sent out - I've fixed it now. Will get that new version out soon.

**Comment by D3nnis3n** [comment]
Yeh, it's still massiveley lagging. :D
I also got a new problem with heat calculation
https://github.com/turbodiesel4598/NuclearCraft/issues/302

Sorry for the many questions :(

**Comment by D3nnis3n** [comment]
Would you mind sharing the jar, as CurseForge seems slow again? Since the update TPS is down to 8 despite only 12 active coolers being left. :O

**Comment by turbodiesel4598** [comment]
Yep, uploading now :)

**Comment by turbodiesel4598** [comment]
https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2556542

**Comment by D3nnis3n** [comment]
I just wanted to tell you (after i found out how to snapshot and read them myself) that your spread mechanism is not that laggy. By reducing from around 900 active coolers to 12 the usage only dropped from 9 to 6%.

EnderIO, though, is taking 60%.

**Comment by turbodiesel4598** [comment]
Ah, well that's good to know. In that case, I think the massive lag you got when you updated to 2.10l was caused by the controller, as it was updating every tick, while in 2.10m that's been fixed and it now updates every 80 ticks.

**Comment by turbodiesel4598** [comment]
So in that case, could this issue be closed?

**Comment by D3nnis3n** [comment]
Well, i somehow think that your code adaptions to active coolers were not worth it (not working active cooler system vs 3% less usage), but despite that: Yes!

Your spreading did make the situation better, as less enderio conduits were needed. So most probably we now would have more usage with the old reactor.

**Comment by turbodiesel4598** [comment]
Ok - well, good luck with your reactor(s)!
