### ISSUE TITLE
Active Coolers Config does not correctly apply?

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#302]
Am i getting something wrong?
For my new reactor i got 2060 H/t too much heat.
So i replaced 12 passive water coolers through active water coolers.

The config says:
Water Passive: 60
Water Active: 300

So i assumed i would have the following heat afterwards:
2060-(12x300)+(12x60) = -820 H/t
De facto i got: 980 H/t

Misunderstanding? Did something wrong? Bug?

**Comment by turbodiesel4598** [comment]
It's because the config specifies the cooling effectiveness in H/mB, and by default, the active cooler uses up 0.5 mB/t, so if the active water rate is 300 H/mB, then the cooling rate of an active water cooler is 300 x 0.5 = 150 H/t.

**Comment by D3nnis3n** [comment]
"by default"?

Does this mean there is an option - i can't find one.

**Comment by turbodiesel4598** [comment]
Yep - 'active cooler max rate' I think, in the Fission section.
