### ISSUE TITLE
Disable registration of machines

### ISSUE THREAD

**Issue by PandaBoy444** [turbodiesel4598/NuclearCraft#304]
That would help me a lot, right now what I would need to do is remove the machine and then go through all the recipes and remove them one by one. A crafttweaker removeAll() function to each machine would work well too.

**Comment by turbodiesel4598** [comment]
You mean not registering them to the game at all, or just removing their recipes?

**Comment by PandaBoy444** [comment]
Either works

**Comment by PandaBoy444** [comment]
I just don't want to see the item and recipes in jei

**Comment by turbodiesel4598** [comment]
Sorted!

**Comment by PandaBoy444** [comment]
When will it be implemented?

**Comment by turbodiesel4598** [comment]
Hopefully tonight :)
