### ISSUE TITLE
Disable registration of tools and armour

### ISSUE THREAD

**Issue by OneEyeMaker** [turbodiesel4598/NuclearCraft#306]
Hello.
I've simple suggestion - add config options to disable armor and tools (separately).
It would be very useful for modpacks with specific tools/armor progression.

And great thanks for your work!

**Comment by OneEyeMaker** [comment]
I'm speaking not only about disabling recipes This task can be done with CraftTweaker.
I'm speaking about completely disabling of registration of tools and armor. (CraftTweaker scripts has tangible impact on memory usage in large packs; and also to write 50 lines of script just to disable *one feature* is a bit tedious).

**Comment by turbodiesel4598** [comment]
Ok, that should be no problem :)

**Comment by turbodiesel4598** [comment]
Sorted!
