### ISSUE TITLE
[Question] Is the Nuclear Monster in 2.x?

### ISSUE THREAD

**Issue by hammurabi1337** [turbodiesel4598/NuclearCraft#309]
Coming back to Minecraft after a long break and glad to see this is still in development!

I was wondering if the Nuclear Monster is in these new 1.12 versions and if not, when it will be implemented?

Thanks for all that you do :)

**Comment by turbodiesel4598** [comment]
Yup - we're still chugging along!

The monster is not in yet... and may not be, at least in the form it originally was. When radiation is added to the game, I want to add some more Fallout-style mobs which should be more interesting than just a tall, fast enderman :)

**Comment by hammurabi1337** [comment]
Sounds good, excited to see how it ends up fleshing out.

I do have a bit of nostalgia for the old one though. I had a grinder of them going in my old 1.7 base. Organic, free range, renewable reactor fuel 👍

**Comment by turbodiesel4598** [comment]
I'm sure that there will be an opportunity for similar setups in the future ;)

**Comment by turbodiesel4598** [comment]
Been a while since this issue was posted, but at some point in the future (could be a while) the nuclear wasteland biome will get a bunch of 'irradiated' mobs. It probably will not be the nuclear monster specifically, but we'll see what emerges.
