### ISSUE TITLE
Suggestion:  GUI shows how bad the heat will be, more than just a number. 

### ISSUE THREAD

**Issue by delet3r** [turbodiesel4598/NuclearCraft#31]
I put plutonium into my reactor for the first time, with the lever Off to be safe... and it says 1240 h/t.  None of the uranium cells generated any heat at all.  

Its great that I can see this before I turn it on, but my issue is that I have no idea how much heat per tick the reactor will absorb.  Is 1240 h/t bad?  If this is explained somewhere and I missed it, my apologies, but the Wiki is fairly sparse on information.  I watched a video of the latest features and it was stated that a big youtube video explaining everything in detail, like a video wiki, would come out, but i dont see it.  (I realize mod devs have jobs, etc.  No worries, just explaining that I have no options that I know of, to figure this out)

**Comment by turbodiesel4598** [comment]
The H/t shown in the GUI is the heat gained by the reactor each tick. 1240 H/t isn't good - your reactor would overheat in 40 seconds if you turned it on. The reason your Plutonium fuel generates heat but the Uranium doesn't is because your reactor's design is able to overcome the heat generated by the Uranium, but it is not able to cope with the Plutonium.

I was hoping that I could get that video done a month or so ago, but unfortunately the work I need to do has cranked up dramatically, since I'm right in the middle of my A-level exams.

**Comment by delet3r** [comment]
So is it safe to say that reactors can handle 1 million heat before exploding?  1240/t *20 *40?  

I wasnt sure if the idea was to just eliminate all heat, or to get the heat managed to where it would start heating up, but not overheat before the cell ran out.  If they dont work that way, a fun mechanic would be if the reactors put out more power as they heated up.  So if someone runs at 0 h/t, its totally safe, but you get say, 1000 rf/t.  Increasing graphite increases that number, and beyond that if you went with a reactor that generated 100 h/t, as it heated up, it would generate more and more power per tick.  Then people could try to run the reactor hot but not overheat before the cell ran out, then have a timer not put another cell in before it overheated.  

Or is the idea to just set up the reactor to run at zero heat?  If so ill add cooling blocks to be able to run plutonium.  

Also no worries on the vidoe, its a free mod, its a great mod!   So no complaints here, was just trying to get information to enjoy the mod more.  :)  Good luck with exams.

**Comment by turbodiesel4598** [comment]
Yes, right now, the reactors can have up to 1 million heat before they give in.

Right now, the idea is to simply eliminate all heat, yes, but you've hit the nail on the head with your suggestion - having the power output vary with temperature is a planned feature - fission in general will become quite different. It will be more advanced, involved, and hopefully more fun and will open up more variation.

Thanks ;)

**Comment by delet3r** [comment]
Look forward to those things, thanks for replying. :)

**Comment by turbodiesel4598** [comment]
Higher heat levels increase the efficiency of fuels now, and fission as a whole has changes quite a bit :)
