### ISSUE TITLE
[Request] Unification Configs

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#310]
Hey!

As far as I understand, some outputs like Ingots and Dusts have their modid/type determined by which ever modid/type is the first entry in the appropriate oredict -

If that is the case, I'd like to request a config option for picking which mod in the oredict NuclearCraft should prioritize, very much like what UniDict does to other mods. This would make the unification of dusts and Ingots a lot easier for me, so I'd really appreciate it.

In UniDict, the config looks like this, for inspiration (if you decide to do it)
https://gist.github.com/NillerMedDild/af99b2e48a87845658a55c91dda27803

**Comment by turbodiesel4598** [comment]
Sorted!

**Comment by NillerMedDild** [comment]
Thank you very much!
