### ISSUE TITLE
Brian and Paul

### ISSUE THREAD

**Issue by MCManiac52** [turbodiesel4598/NuclearCraft#311]
So I have NuclearCraft on a server I'm running and playing on and the Paul/Brians are fine, other than the annoying sounds they make. I've disabled them both in the config and restarted the server yet they still appear. I even tried disabling all mobs from the mod and they still spawn. Is this a glitch or are they just impossible to get rid of? I'm running 1.7.10 with mod version 1.9f

**Comment by turbodiesel4598** [comment]
Hey there - the disabling of their spawning should work fine, but it will not remove any of them which have already spawned. You should be able to kill all types of a given entity using [the kill command](https://minecraft.gamepedia.com/Commands/kill).

**Comment by turbodiesel4598** [comment]
Just put out [a new 1.7.10 build](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2568943) which will kill any Brian and Pauls in the world if they are disabled :)

**Comment by Sumis34** [comment]
How can I remove Paul and Brian?

**Comment by turbodiesel4598** [comment]
@Sumis34 There is a config to delete them in the last 1.7.10 build.
