### ISSUE TITLE
[BUG] "Virtual Liquid" in NuclearCraft

### ISSUE THREAD

**Issue by xsun2001** [turbodiesel4598/NuclearCraft#312]
#Recently I am playing a modpack with about 80 mods including NuclearCraft. But I noticed there is a lot of strange liquid that says it belongs to NuclearCraft. When I get it from the jei, it gave me a `forge:bucketfilled` item with 2 nbt tags. I right clicked to pour the liquid, a purple-black liquid appeared. At first, I think it just missed its texture. But when I exited and reentered the world, the liquid all disappeared! And if pour the liquid in a server with modpack's mods, it crashed with a tons of NullPointerException.
I think there is something wrong with the integration with NC and other mods such as TConstruct. NC seems to generate a lot of "virtual liquid" as the result of molten other mod's metal. And those liquid are not properly registered.
Sorry for my poor English.

Some example of NC's strange liquid:
![2018-05-15_23 42 57](https://user-images.githubusercontent.com/14010993/40067985-16ca6be0-589a-11e8-9ae2-7ad293489e3e.png)
![2018-05-15_23 43 02](https://user-images.githubusercontent.com/14010993/40067987-175caf0a-589a-11e8-8f94-ae68267597e9.png)

When liquid is poured...
![2018-05-15_23 43 11](https://user-images.githubusercontent.com/14010993/40067989-17c48292-589a-11e8-9bc3-0917c7cb8b3c.png)

But it disappeared after reentering
![2018-05-15_23 43 39](https://user-images.githubusercontent.com/14010993/40067992-1834ae5a-589a-11e8-9336-d7bc3bbf8f0f.png)

TConstruct's molten metal works well, and they won't disappeared...
![2018-05-15_23 45 10](https://user-images.githubusercontent.com/14010993/40067996-199534d6-589a-11e8-8694-fb57447725ca.png)

The crash report of the unfortunate server. And the mods list also printed in this report.
https://paste.ubuntu.com/p/HhGSfTq5zf/

**Comment by turbodiesel4598** [comment]
Hey there! The issue is that you do not have the fluid block registration enabled in the NC config - it is disabled by default as they can take up a large amount of block IDs. If you want the fluids in-world, then you just have to enable this option :)
