### ISSUE TITLE
Crashing after placing any machine 1.10.2

### ISSUE THREAD

**Issue by OUYEAAAAA** [turbodiesel4598/NuclearCraft#315]
I can't place machines or the game ista crashes . Tried few of them but not all ,  always crash.

[crash-2018-05-25_18.45.09-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/2040240/crash-2018-05-25_18.45.09-server.txt)

**Comment by turbodiesel4598** [comment]
Looks like I just need to update the IC2 API I was using - unfortunately, I am away from home and can't fix this for a few weeks, so I'm sorry to say that you won't be able to use any of the machines until then :(

**Comment by OUYEAAAAA** [comment]
Okay , thanks for the fast response anyway . :(

**Comment by turbodiesel4598** [comment]
Ok, managed to get Teamviewer set up to try to fix this - does [this build](https://www.dropbox.com/s/6ajll7c6ecbekd8/NuclearCraft-2.7c--1.10.2.jar?dl=0) crash or is the issue fixed?

**Comment by OUYEAAAAA** [comment]
Nope , doesn't work , still crash.

[crash-2018-06-03_10.27.45-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/2065784/crash-2018-06-03_10.27.45-server.txt)

**Comment by turbodiesel4598** [comment]
Worked it out with the help of lebanni - was a conflict in IC2 APIs with Mekanism. [This version should work](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2569108) :)
