### ISSUE TITLE
Question: Is radiation in yet?

### ISSUE THREAD

**Issue by DonMegel** [turbodiesel4598/NuclearCraft#316]
I know, stupid question, but is radiation, and its negative effects, in the game yet? The wiki says it is not but I think it may be out of date.

**Comment by turbodiesel4598** [comment]
No, it is not - chances are it won't be until 1.13, as there's quite a lot on the to-do list :)

**Comment by DonMegel** [comment]
Aww, I am really looking for a mod with radiation. Will you be back porting to 1.12?

**Comment by turbodiesel4598** [comment]
Probably not, no - I don't really have the time to build for two versions simultaneously :(

**Comment by turbodiesel4598** [comment]
@DonMegel [Radiation was added in v2.11b](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files) :)
