### ISSUE TITLE
Connection Error with the newest version of forge

### ISSUE THREAD

**Issue by pdglobal** [turbodiesel4598/NuclearCraft#317]
https://gist.github.com/pdglobal/0fad5772ea19d550dadc0a1f7d81a64e

I get this error only when nuclearcraft is installed when attempting to connect to my server using the latest release version of forge.

**Comment by turbodiesel4598** [comment]
Are you sure this is a NuclearCraft issue? I don't see any references to NuclearCraft methods.

**Comment by pdglobal** [comment]
Sorry go ahead and close this, it was a configuration error which was actually being caused by a sponge plugin in the mods folder client-side, everything works now, looking forward to diving into this mod soon!

**Comment by turbodiesel4598** [comment]
No worries - have fun!
