### ISSUE TITLE
[Request] Comparator support for Voltaic Piles/Lithium Ion Batteries

### ISSUE THREAD

**Issue by accessdenied0** [turbodiesel4598/NuclearCraft#318]
Hey @turbodiesel4598 ,

I further thank you for the great work you put in your mod. I just wanted to put this suggestion/request for Comparator support to read out the fill-status of Energy-storage. 

It has no hurry, its just a suggestion.

**Comment by turbodiesel4598** [comment]
Your welcome!

Comparator battery-reading is in :)
