### ISSUE TITLE
1.10.2 client crash

### ISSUE THREAD

**Issue by lebanni** [turbodiesel4598/NuclearCraft#319]
It only crashes on client startup, not server side.

[crash-2018-06-02_17.44.15-client.txt](https://github.com/turbodiesel4598/NuclearCraft/files/2065126/crash-2018-06-02_17.44.15-client.txt)

**Comment by turbodiesel4598** [comment]
Any luck with [this build](https://www.dropbox.com/s/6ajll7c6ecbekd8/NuclearCraft-2.7c--1.10.2.jar?dl=0)?

**Comment by lebanni** [comment]
Still crashing.
[crash-2018-06-02_22.17.09-client.txt](https://github.com/turbodiesel4598/NuclearCraft/files/2065333/crash-2018-06-02_22.17.09-client.txt)

**Comment by turbodiesel4598** [comment]
Weird... I can't recreate this error, neither client nor server. Which version of Forge are you using?

**Comment by lebanni** [comment]
Forge 12.18.3.2511. It's all in the details, in the crash log.

**Comment by turbodiesel4598** [comment]
Don't worry, I was using that version too.

Does the mod run fine on its own? Just wondering if there's a particular nasty mod-mod interaction happening.

**Comment by lebanni** [comment]
I think I identified Not Enough Items as the faulty mod, but another mod must be in conflict, as when I run NuclearCraft alone with NEI and it's dependencies (JEI, CodeChicken Core and codeChicken Lib), it doesn't crash.

**Comment by lebanni** [comment]
You're welcome :)

**Comment by turbodiesel4598** [comment]
Here we are - [on CurseForge now](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2569108) :)
