### ISSUE TITLE
Quarry How to

### ISSUE THREAD

**Issue by shivachirr** [turbodiesel4598/NuclearCraft#32]
so i running the bevo mod pack and saw that nuclearcraft had a quarry that did not require super expensive things tho i dont see how to use it after i made it. and looking all over there is not even a hint to it so any chance you can tell me how to use it. ill keep looking for info but doubt ill find any

**Comment by turbodiesel4598** [comment]
I have also seen others use that pack, and for some reason I can't understand at all, that block is being called the quarry, when it should be called a 'machine block'. It's not actually a quarry - it's just a base block used to make some machines. In the language files, the block is definitely named 'machine block' - in every other pack I've played, it works normally, but for some reason, in that pack there's a strange incompatibility somewhere playing silly tricks :P 
Sorry for the confusion!

**Comment by b0bst3r** [comment]
Ahh that's my fault because people were looking for the Buildcraft quarry and that was in the pack as machine block lol so I renamed it :D
