### ISSUE TITLE
[1.12.2] Opening Crystallizer Crashing Due To Invalid @NonNull Annotation

### ISSUE THREAD

**Issue by SonarSonic** [turbodiesel4598/NuclearCraft#322]
To recreate: Place Crystallizer and right click it.
You may not see this error on older versions of Java.

Report: [crash-2018-06-04_12.07.20-client.txt](https://github.com/turbodiesel4598/NuclearCraft/files/2067976/crash-2018-06-04_12.07.20-client.txt)

**Comment by turbodiesel4598** [comment]
Fixed!
