### ISSUE TITLE
Quartz Active Cooling

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#324]
Hey! It looks like Active Cooling of the Fission Reactor with Quartz has one more zero than it should - It cools for 80000.0 heat/t, in comparison Gold cools for 16000.0 heat/t.

Minecraft 1.12.2
NuclearCraft-2.10o--1.12.2

**Comment by turbodiesel4598** [comment]
I think this may have been fixed at some point in the past - if you reset that config it should be set to the correct rate. I would be wary, though - there are probably some designs people have build that rely on that high cooling rate to be stable.

**Comment by NillerMedDild** [comment]
Ah alright, thanks.
