### ISSUE TITLE
Depleted Thorium?

### ISSUE THREAD

**Issue by 0something0** [turbodiesel4598/NuclearCraft#325]
From what I gather, this mod is supposed to be on the realistic side of things. 

Depleted Thorium is not a thing in real life (but the documentation on it seems to be nonexistant and I'm too lazy to boot up Minecraft).

**Comment by turbodiesel4598** [comment]
No, technically depleted Thorium is not really a realistic name, but is just called that to be in line with the other 'depleted' isotope blocks. I suppose I could just call them blocks of thorium-230.
