### ISSUE TITLE
[Suggestion] Config option to disable recipe registration for specific machines

### ISSUE THREAD

**Issue by wormzjl** [turbodiesel4598/NuclearCraft#326]
The newly added register_processor option is really cool. However, even the machines are not registered, their recipes can still be shown in JEI. Which could be a bit confusing for players.
Could you add a separate config option for recipe registration of each machine, or make them depend on the availability of corresponding machines?
Thank you!

**Comment by turbodiesel4598** [comment]
Ah yes, good point - I suppose it would best make sense to hide the recipes of the corresponding disabled machine :)

**Comment by turbodiesel4598** [comment]
Sorted for next version!
