### ISSUE TITLE
Recipe removal with crafttweaker not working?

### ISSUE THREAD

**Issue by wormzjl** [turbodiesel4598/NuclearCraft#327]
I was trying to use the follow script to tweak the recipe a bit
`
mods.nuclearcraft.chemical_reactor.removeRecipeWithOutput(<liquid:ammonia>, <liquid:ammonia>);
mods.nuclearcraft.chemical_reactor.removeRecipeWithOutput(<liquid:sulfuric_acid>, <liquid:sulfuric_acid>);
mods.nuclearcraft.chemical_reactor.removeRecipeWithOutput(<liquid:oxygen_difluoride>, <liquid:oxygen_difluoride>);
mods.nuclearcraft.chemical_reactor.removeRecipeWithOutput(<liquid:sulfur_trioxide>, <liquid:fluorine>);
mods.nuclearcraft.chemical_reactor.removeRecipeWithOutput(<liquid:hydrofluoric_acid>, <liquid:fluorine>);
mods.nuclearcraft.chemical_reactor.removeRecipeWithOutput(<liquid:oxygen>, <liquid:hydrofluoric_acid>);
mods.nuclearcraft.chemical_reactor.removeRecipeWithOutput(<liquid:potassium_hydroxide_solution>, <liquid:hydrofluoric_acid>);
mods.nuclearcraft.chemical_reactor.removeRecipeWithOutput(<liquid:sodium_hydroxide_solution>, <liquid:hydrofluoric_acid>);
mods.nuclearcraft.chemical_reactor.removeRecipeWithOutput(<liquid:hydrofluoric_acid>, <liquid:calcium_sulfate_solution>);
`

However in ct log it shows that it has errored

`
[INITIALIZATION][CLIENT][INFO] Error: Failed to remove nuclearcraft_chemical_reactor recipe with [1 x fluid:ammonia, 1 x fluid:ammonia] as the output
[INITIALIZATION][CLIENT][ERROR] Some NuclearCraft CraftTweaker recipe removal methods have errored - check the CraftTweaker log for more details
[INITIALIZATION][CLIENT][INFO] Error: Failed to remove nuclearcraft_chemical_reactor recipe with [1 x fluid:sulfuric_acid, 1 x fluid:sulfuric_acid] as the output
[INITIALIZATION][CLIENT][INFO] Error: Failed to remove nuclearcraft_chemical_reactor recipe with [1 x fluid:oxygen_difluoride, 1 x fluid:oxygen_difluoride] as the output
[INITIALIZATION][CLIENT][INFO] Error: Failed to remove nuclearcraft_chemical_reactor recipe with [1 x fluid:sulfur_trioxide, 1 x fluid:fluorine] as the output
[INITIALIZATION][CLIENT][INFO] Error: Failed to remove nuclearcraft_chemical_reactor recipe with [1 x fluid:hydrofluoric_acid, 1 x fluid:fluorine] as the output
[INITIALIZATION][CLIENT][INFO] Error: Failed to remove nuclearcraft_chemical_reactor recipe with [1 x fluid:oxygen, 1 x fluid:hydrofluoric_acid] as the output
[INITIALIZATION][CLIENT][INFO] Error: Failed to remove nuclearcraft_chemical_reactor recipe with [1 x fluid:potassium_hydroxide_solution, 1 x fluid:hydrofluoric_acid] as the output
[INITIALIZATION][CLIENT][INFO] Error: Failed to remove nuclearcraft_chemical_reactor recipe with [1 x fluid:sodium_hydroxide_solution, 1 x fluid:hydrofluoric_acid] as the output
[INITIALIZATION][CLIENT][INFO] Error: Failed to remove nuclearcraft_chemical_reactor recipe with [1 x fluid:hydrofluoric_acid, 1 x fluid:calcium_sulfate_solution] as the output
[INITIALIZATION][CLIENT][INFO] Error: Failed to remove nuclearcraft_electrolyser recipe with [1 x fluid:koh] as the input
[INITIALIZATION][CLIENT][INFO] Error: Failed to remove nuclearcraft_dissolver recipe with [1 x fluid:fluorite_water] as the output
`

**Comment by wormzjl** [comment]
Ok seems that I need to add the amount of fluid then, this can be a bit confusing...

**Comment by turbodiesel4598** [comment]
Looks like I need to fix the logging, but yeh, fluid stacks are like item stacks and need the size of the stack also... perhaps I could add a boolean to not check stack sizes.
