### ISSUE TITLE
Nitrogen Collectors

### ISSUE THREAD

**Issue by Malch07** [turbodiesel4598/NuclearCraft#328]
Sorry, I found this mistake:
Nitrogen Collector produce 50mB/t, but Compact Nitrogen Collector only 20mB/t. 

Thank you.

**Comment by turbodiesel4598** [comment]
Are you sure? The basic Nitrogen Collector should produce 50 mB per _**second**_.

**Comment by Malch07** [comment]
Yes, you are right. My mistake, sorry.

**Comment by turbodiesel4598** [comment]
No prob!
