### ISSUE TITLE
Bug Exceeds max stack side

### ISSUE THREAD

**Issue by tyler489** [turbodiesel4598/NuclearCraft#332]
Tinkers construct exposes the internal slots of the cobblegen even with 
https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/container/SlotInaccessible.java 

Allowing for things like this https://gyazo.com/13dff994370e6d91a6ebf9cebf2456ba

EDIT:Seems like Cobblestone Generator does not call Slot Inaccessable?

**Comment by turbodiesel4598** [comment]
Hmm... I can't do anything with container slots as, well, the cobble gen doesn't have one (it doesn't have a GUI). I don't think there's too much I can do about this without adding extra slots, but that would needlessly increase the tick time eaten up by the machine (having to put items into multiple slots and then distribute the cobble from those slots to adjacent inventories).
