### ISSUE TITLE
NC make NEI slow

### ISSUE THREAD

**Issue by AustenHong** [turbodiesel4598/NuclearCraft#334]
When I was install this mod, if I'm searching how to make an item, NEI was too slow.
If I'm uninstalling this mod, the NEI speed will go back.

**Comment by turbodiesel4598** [comment]
Hmmm... I'm not sure I can do anything about that really. Which version of the mod is this?

**Comment by HydrogenC** [comment]
I think it's because this mod addes too many recipes.

**Comment by turbodiesel4598** [comment]
There are many mods which add far more recipes so I don’t think it’ll be that.

**Comment by AustenHong** [comment]
That I'm trying all version of NC, but the problem never gone.
I don't think the reason of why NC make NEI slow is because It add too many recipes, the GregTech is also in my pack, but GT never make my NEI slow.

**Comment by AustenHong** [comment]
I was create a new folder that the NC is the only mod in that pack(except NEI), and the NEI "speed" is same as that huge modpack, I don't think the reason of NEI become slow is NC conflict with other mods (or other problems)

**Comment by turbodiesel4598** [comment]
Which version of Minecraft is this? 1.7.10?

**Comment by AustenHong** [comment]
Yes, the version is 1.9g of 1.7.10

**Comment by turbodiesel4598** [comment]
Hmmm... I'm really not sure. Unfortunately I don't support 1.7.10 anymore as I don't have the time to work on it :(

**Comment by AustenHong** [comment]
That was ok, I just want people feel better when they are playing this pack, but this is not a very serious problem(It won't cause my game crash).QAQ
