### ISSUE TITLE
Missing Recipes / Compatibility Issue ?

### ISSUE THREAD

**Issue by 6rKbS6grBM7Q** [turbodiesel4598/NuclearCraft#337]
I have setup a new minecraft server/client running FTB Revelation 2.2 and manually added NuclearCraft 2.10p to it (by dropping the jar file in the mods folder, both on the server and the client).

I just found that while the three plating (basic, advanced, elite) show up in JEI, the only way to get the basic is through dungeon chests.  The other two have no ways to get. 

I also tried adding 2 graphite dust and 2 lead ingots in a crafting grid and it did not recognize the pattern.

Is there a way to troubleshoot these missing recipes?

- Dyweni

**Comment by 6rKbS6grBM7Q** [comment]
Minecraft version:  1.12.2
Forge version:  14.23.4.2729
FTB Revelation version: 2.2.0
NuclearCraft version: 2.10p

**Comment by 6rKbS6grBM7Q** [comment]
Server Java version: 1.8.0_172
Client Java version: 1.8.0_171

**Comment by 6rKbS6grBM7Q** [comment]
Just tested Vanilla Minecraft 1.12.2 + Forge 14.23.4.2730 + NuclearCraft 2.10p... it works.  Must be something with the FTB Revelation 2.2 modpack.

**Comment by 6rKbS6grBM7Q** [comment]
Figured it out.  Not an issue with NuclearCraft.

FTB Revelation 2.x modpacks have a line ('mods.unidict.removalByKind.get("Crafting").remove("plate");') which removes all plate recipes during startup, including NuclearCraft plate recipes.

If you comment out that line in the file 'scripts/01_unification.zs' in their modpack, the NuclearCraft plate recipes come back.

**Comment by Jonnoiscooler** [comment]
I have also encountered this issue, and I am aware it has been closed at this time of writing. Just wanted to add my own fix. I have found that commenting out the line in 'scripts/01_unifcation.zs' will also return other unwanted plate recipes and undo some of the unification work for combining all plate recipes from other mods. 

I have attached my own version of the '01_unification.zs' file that can be used to maintain proper recipe unification and re-enable the nuclearcraft plate recipes. Just replace the old file with this one and it should work. The file to replace is in the instance of the version of FTB folder you are playing on, in the scripts folder:
<instance name>/scripts/01_unification.zs

**NOTE: github wont accept .zs files, so just change the file type from .txt to .zs after you've downloaded it.**

[01_unification.txt](https://github.com/turbodiesel4598/NuclearCraft/files/3006009/01_unification.txt)

For anyone curious, all I have added is these lines: 
```
	//fix nuclearcraft plate recipes
recipes.addShapedMirrored(<nuclearcraft:part:0>,
[
[<ore:dustGraphite>, <ore:ingotLead>,],
[<ore:ingotLead>, <ore:dustGraphite>]
]
);
recipes.addShaped("Advanced Plate", <nuclearcraft:part:1>,
[
[<ore:dustRedstone>, <ore:ingotTough>, <ore:dustRedstone>],
[<ore:ingotTough>, <nuclearcraft:part:0>,  <ore:ingotTough>],
[<ore:dustRedstone>,  <ore:ingotTough>, <ore:dustRedstone>]
]
);
recipes.addShaped("Du Plate", <nuclearcraft:part:2>,
[
[<ore:dustSulfur>, <nuclearcraft:uranium:8>, <ore:dustSulfur>],
[<nuclearcraft:uranium:8>, <nuclearcraft:part:1>, <nuclearcraft:uranium:8>],
[<ore:dustSulfur>,  <nuclearcraft:uranium:8>, <ore:dustSulfur>]
]
);
recipes.addShaped("Elite Plate", <nuclearcraft:part:3>,
[
[<ore:dustRhodocrosite>, <ore:ingotBoron>, <ore:dustRhodocrosite>],
[<ore:ingotBoron>, <nuclearcraft:part:2>, <ore:ingotBoron>,],
[<ore:dustRhodocrosite>, <ore:ingotBoron>, <ore:dustRhodocrosite>]
]
);


```
