### ISSUE TITLE
[1.12.2] Mod ore dictionary entries

### ISSUE THREAD

**Issue by TheSnowyChickens** [turbodiesel4598/NuclearCraft#338]
Hello,
I wonder about the ore dict. entries, because I get some Uranium dust in the pulverizer from NuclearCraft, but my config say that is should be some Uranium from Immersive.

Did I make a mistake?

Determines the priority of each mod's ore dictionary entries - earlier mods' IDs in this list have a higher priority. This is used to determine which mod's corresponding item is produced in machine recipes. If no matching mod is found, the default entry is used.
    S:ore_dict_priority <
        minecraft
        thermalfoundation
        immersiveengineering <----
        techreborn
        mekanism
        nuclearcraft
        appliedenergistics2
        actuallyadditions
        thaumcraft
        biomesoplenty
     >

1.12.2
Forge 2739
NuclearCraft-2.10p--1.12.2
ThermalExpansion-1.12.2-5.5.0.29-universal
ImmersiveEngineering-0.12-84

**Comment by turbodiesel4598** [comment]
Hey there - have you enabled the ore dict mod priority? It is another config option that tells the mod whether to care about that list.

**Comment by TheSnowyChickens** [comment]
I have:

    # Will Ore Dictionary outputs be prioritised according to the mod list below? If false, the default Ore Dict entry will be used when deciding machine outputs.
    B:ore_dict_priority_bool=true
and
    # Remove disabled ores from the Ore Dictionary and JEI?
    B:hide_disabled_ores=false

**Comment by turbodiesel4598** [comment]
Oh, hang on - which machine are you using? The manufactory from NC or the pulveriser from TE?

**Comment by TheSnowyChickens** [comment]
pulveriser from TE

**Comment by turbodiesel4598** [comment]
Ah, ok. Unfortunately that config option only affects the machines from NC - there may be a similar config option for TE, but if not, you may have to do something like removing the NC uranium dust from the ore dictionary via CraftTweaker.

**Comment by TheSnowyChickens** [comment]
Ah okay.
I will look into the TE config and/or disable it with crafttweaker.

Thx for the help. :)

**Comment by turbodiesel4598** [comment]
No prob!
