### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by HydrogenC** [turbodiesel4598/NuclearCraft#339]
Hi, the crash happens when I check usages of Redstone Block in JEI. 
(Only checking Redstone Block will cause this, others won't)

Crash related mods: 
NuclearCraft
EnderIO? 
JEI
IC2

Crash Report: [Pastebin](https://pastebin.com/CDryhk07)

**Comment by DeadSix27** [comment]
Same issue, but different fluid: https://pastebin.com/JgQgP4V8

**Comment by turbodiesel4598** [comment]
Yep, this is a known bug and will be fixed in the next release, which has been taking a while but will arrive shortly :)

**Comment by turbodiesel4598** [comment]
Fixed in v2.11 :)
