### ISSUE TITLE
Fission controller + lever

### ISSUE THREAD

**Issue by nightshard** [turbodiesel4598/NuclearCraft#340]
Noticed this on the latest version (used in atm3) and on previous versions.

When a lever is placed on top of a fission controller and is switched on, the controller physically turns around, it's front becomes it's back.
Sometimes it doesn't happen right away but does when you log off and on, then the structure is shown as broken and doesn't work until you break and replace the controller.

All of this doesn't happen if you place a lever next to the controller, only when placed connected to a face of the controller (not entirely sure if any face or just the top).

**Comment by turbodiesel4598** [comment]
I've been unable to recreate this in my test instances, so I'll have to download ATM3 and see if I can get it to happen there. If so, then I don't think there's anything I can do about it on my side, as there is no part of the block code that even hints that that should happen - it may well be another mod that is doing it.

**Comment by turbodiesel4598** [comment]
Still not able to recreate this on ATM3 - which blocks are adjacent or near the controller?

**Comment by nightshard** [comment]
Got an ae2 export bus at the front, import bus at the side and a mekanism ultimate universal cable at the bottom.
The controller is placed at the bottom right corner of the structure.

Would a video showing it happen help?

**Comment by turbodiesel4598** [comment]
[So like this then?](https://imgur.com/a/59MDtdh) Weird... in that case it may have just been a couple of nasty loading imperfections - it's certainly not an area I know a lot about but I suppose it's possible when there's a lot of stuff going on.

**Comment by turbodiesel4598** [comment]
Fixed in 2.11b as far as I can tell :)
