### ISSUE TITLE
Hard Crash interaction with ExCompressum

### ISSUE THREAD

**Issue by remclave** [turbodiesel4598/NuclearCraft#342]
https://pastebin.com/S7Zw2ckB

**Comment by remclave** [comment]
Added: Repeatable. Place NuclearCraft Infinite water source. Placed one Oak Crucible from ExCompressum on one side then placed another on the opposite side. When placing the second crucible is when the game crashes. The game cannot be restarted from the launch menu. Instead the game needs to be restarted from the launch icon.

**Comment by turbodiesel4598** [comment]
Hmmm... not exactly sure why this happened, but I've added an additional safety feature to try to prevent it for the next version - if it continues happening, you may want to the devs of ExCompressum if they can do anything on their side.

**Comment by turbodiesel4598** [comment]
Was this fixed on ExCompressum's side or is the bug still present?

**Comment by remclave** [comment]
I honestly have no clue. The particular version of the pack that this was part of has been discontinued by the pack dev. However, thank you for your reply and query. (I'm not a young person and keep forgetting to follow up on queries, so very much thank you for patience in receiving this reply.)

**Comment by turbodiesel4598** [comment]
No worries! I'll just assume it was - it's the easy option :P
