### ISSUE TITLE
[Question] ComputerCraft integration?

### ISSUE THREAD

**Issue by dmarcuse** [turbodiesel4598/NuclearCraft#344]
In the source code, I see commented out partial integration for ComputerCraft and OpenComputers. Is this still a WIP, or something that was disabled? It would be really convenient to be able to access reactor stats and respond accordingly.

**Comment by turbodiesel4598** [comment]
It's been commented out as it didn't work :P

I certainly will attempt OC support again though :)

**Comment by apemanzilla** [comment]
Why not CC support as well?

**Comment by turbodiesel4598** [comment]
I may do that too, but OC is the priority as it is a little more popular - CC hasn't been updated in nearly a year and is still in Alpha, too

**Comment by apemanzilla** [comment]
There's a few different forks of CC which are being actively maintained and are compatible with the same API - notably ([CC: Tweaked](https://github.com/SquidDev-CC/CC-Tweaked)). I'd also be happy to give it a shot myself and PR it if you prefer.

**Comment by turbodiesel4598** [comment]
The OC integration will defo be able to read those sorts of stats - really that's all it needs to do other than be able to turn off the reactor and things like that. I do think I now understand how the API works, so hopefully I can begin making progress with this :)

**Comment by turbodiesel4598** [comment]
Turns out the OC API is awesome and it’s quite easy to add computer functions for a machine - expect to see OC support for the Fission and Fusion Reactors in the next update ;)

**Comment by apemanzilla** [comment]
What about CC support? I'd be happy to implement it in a PR if you'd like.

**Comment by darkman1984** [comment]
Nice one :) Can you integrate the method to get a response which fuel is inside ? Would be great :)

**Comment by turbodiesel4598** [comment]
Oh yeh, that's a good one - sure :)

**Comment by darkman1984** [comment]
oh and a table which fuel is allowed :) sorry but my ideas are exploding :D

**Comment by turbodiesel4598** [comment]
Can you not just do something like that with the name of the fuel, i.e. read the fuel name and wait for there to be `No Fuel`?

**Comment by darkman1984** [comment]
Well it's possible to read out an inventory (like a chest) with the fuel and sort it out but i stuck currently on the point if more than one slot contain the same fuel. i should think about it again.

**Comment by darkman1984** [comment]
After checking all of the methods from the fission controller i suggest something:

activate & deactivate should response with a boolean (true or false) if the reactor is running while a redstone signal is on the controller. Or better would be a method called "isRunning" that response with: true or false

getReactorProcessPower response with what? Normally if i understand it correctly it should output how much RF/t the reactor produce.

getReactorProcessTime() don't change the time while running (or i missunderstood the method)

Then there are methods called getEnergyStored() & getMaxEnergyStored(). While getMaxEnergyStored() seems to be working, getEnergyStored() won't work and response with 0.0. 

These methods are for fission reactors and not tested with fusion reactors.

**Comment by turbodiesel4598** [comment]
> Or better would be a method called "isRunning" that response with: true or false

Done!
> Then getReactorProcessTime should response with the time which being used currently

Added a method called 'getCurrentProcessTime'.
> If no Fuel is present then it response with 0.125? Shouldn't it be 0?

Fixed!
> getProblem response everytime with "Casing Incomplete". Don't understand the sense behind this method

Fixed!
> getMaxHeat would be very nice to get the maximum heat capacity of the reactor.

Added!
> Added a method called 'getEnergyChange' :)

**Comment by darkman1984** [comment]
WOW :) Then i'll wait for the next release :)

**Comment by turbodiesel4598** [comment]
I think it is rather unlikely at this point that NC will get CC support. OC is the way to go!
