### ISSUE TITLE
1.12.2 [2.11A] Fission Controller Fuel loss Processtime

### ISSUE THREAD

**Issue by darkman1984** [turbodiesel4598/NuclearCraft#346]
Found another bug. If for example LEU-235 is processing and the fuelslot is empty (so the last of the stack is currently processing) and you fill the slot with an other fuel (f.e. LEU-233) and the process of the LEU-235 ends, it switches to the next fuel (LEU-233) but the arrow shows a quarter green. Don't know if the process time jumps to the same state or if it's only a displaybug. 

Hope you understand what i mean ;)

**Comment by turbodiesel4598** [comment]
I _think_ I've fixed this but I will do a bit more testing to be sure :)

**Comment by turbodiesel4598** [comment]
Yep, defo sorted!
