### ISSUE TITLE
Fission reactor destroys contents with redstone current change

### ISSUE THREAD

**Issue by Delscid** [turbodiesel4598/NuclearCraft#349]
Minecraft Version: 1.12.2
NuclearCraft Version: 2.11a--1.12.2
Modpack used is ATM3

Fission reactors destroy any contained fuel and power when redstone current is changed if there is a reactor door next to the controller. This seems to only occur when redstone current is changed (in this case, a lever), this occurs whether or not the reactor is being turned off or on. This doesn't occur on a reactor with the same configuration, but with the door spaced one block away from the controller. 

The specific reactor configuration tested has a lever on a casing block next to the controller, it still happens when the lever is directly on the controller but only when turning the reactor off.

**Comment by turbodiesel4598** [comment]
I'm not able to recreate this exactly, but I instead did get a crash - this is because I wasn't accessing the block type of the controller correctly, which caused the door to crash when updating. I think this should now be fixed then, but I will leave this open until I get a new build out :)

**Comment by turbodiesel4598** [comment]
Fixed in 2.11b as far as I can tell :)
