### ISSUE TITLE
Fusion reactor stops producing 

### ISSUE THREAD

**Issue by sonvar** [turbodiesel4598/NuclearCraft#350]
On single player, it seems when I log off the server and then return, the fusion reactor just stops producing power. It will have a full supply, empty products, full power and temp in the >1500 MK. The RF/t is initially saved upon log on, but will quickly drop to zero with no explanation on why. If gone unnoticed it will then wipe out my power storage. The only way I found to fix it is to break the reactor and replace it.
Nuclearcraft version 2.10p 1.12.2 on modpack ATM3.

**Comment by turbodiesel4598** [comment]
Which fuels are you using?

**Comment by sonvar** [comment]
Deuterium and tritium

**Comment by turbodiesel4598** [comment]
Yeh, thought so - what's happening is that you're overshooting [the efficiency curve](https://www.wolframalpha.com/input/?i=y+%3D+741.5*(e%5E(-h%2F670)%2Btanh(h%2F670)-1),+h+from+0+to+4000). The optimal temperature for D-T is ~816.5 MK, so once your reactor continues to heat up past that point, the efficiency goes down and down. You want to use a comparator or active cooling to keep your reactor at near-max efficiency.

**Comment by sonvar** [comment]
I am using a comparator. What I've found, if I follow your suggestions and use the max 15 redstone the reactor explodes, so I am using 13 redstone line hoping to keep temperature down. It doesn't explode now but it does this now.

**Comment by turbodiesel4598** [comment]
It still should not explode with a full signal - is the comparator reading efficiency or heat?

**Comment by turbodiesel4598** [comment]
In the reactor GUI, there is a button laballed efficiency/heat comparator - the blue colour represents efficiency and the other is heat. If you want to use the comparator to keep the reactor at a decent efficiency, you want the former setting.

Could I perhaos get a picture of your core comparator setup?

**Comment by turbodiesel4598** [comment]
Ah, ok - the problem is that the comparator must be at the **base** of the core, i.e. on the bottom level.

**Comment by sonvar** [comment]
Is that why? Guess I need to reroute everything then

**Comment by sonvar** [comment]
Ok, that was the issue. thank you. I guess the tutorial you made on this did not explain this or how important inputs/output locations are. Did not think it was important, as long as it was set up

**Comment by turbodiesel4598** [comment]
Yeh, the tutorial is a little outdated now - need to update it!
