### ISSUE TITLE
Incompatability With The Latest GTCE Builds

### ISSUE THREAD

**Issue by EmosewaPixel** [turbodiesel4598/NuclearCraft#351]
Recently, the e-net system in GTCE was changed and so now the Fission Reactor has broken TOP tooltips
![image](https://user-images.githubusercontent.com/25333164/44874357-39892e00-ac9b-11e8-9999-6c3a7402efb0.png)
And the following crash occurs when a cable is connected to it.
https://pastebin.com/N8pqRv1z

**Comment by turbodiesel4598** [comment]
Oh dear... well, I'll get that updated I guess!

**Comment by turbodiesel4598** [comment]
Fixed!
