### ISSUE TITLE
Fusion Reactor loses input fluids and stops working

### ISSUE THREAD

**Issue by Nicdel87** [turbodiesel4598/NuclearCraft#352]
Version 2.11a
See video: https://puu.sh/Bn1ps/a0e6d74fc7.mp4
Setup:
![ss 2018-08-30 at 09 54 12](https://user-images.githubusercontent.com/21983173/44875900-c209cd80-ac9f-11e8-8b81-a4e49aa6a74e.jpg)

**Comment by turbodiesel4598** [comment]
Ah, found my mistake - fixed!
