### ISSUE TITLE
[2.11b -- 1.12.2] Crash with mcjty mods

### ISSUE THREAD

**Issue by antcig** [turbodiesel4598/NuclearCraft#354]
[Crashlog](https://pastebin.com/zRdLKYK9)

**Comment by antcig** [comment]
Startup was ok. Crashed on loading the world, about a 1 sec after.

**Comment by turbodiesel4598** [comment]
Ok, I'll see if I can talk to McJty. The crashlog is a little puzzling to me and it could easily be an issue on McJtyLib's side.

**Comment by turbodiesel4598** [comment]
Ok, I've quickly had a chat and he says that you should [head to the McJtyLib repo](https://github.com/McJtyMods/McJtyLib/issues) with your crash report :)

**Comment by turbodiesel4598** [comment]
Ok, I was actually unable to recreate this, so could you install [this version](https://www.dropbox.com/s/b1bi9hvnbg3i52t/NuclearCraft-2.11c--1.12.2.jar?dl=0) of the mod and send your whole log, `logs\latest.log`?

**Comment by antcig** [comment]
Tested this version - no crash on world load, still crashed after successful load a bit later when I opened inventory and point to depleted TBU fuel and pressed shift. Still could be something to do with rftools builder running as quarry in another dimension.
https://pastebin.com/xiTyts5g

**Comment by antcig** [comment]
[21:49:08] [main/INFO] [nuclearcraft]: 1xitem.charged_porter@0
probably what you looking for?

**Comment by antcig** [comment]
Tested again - definitely crashed on opening inventory and just pointing to rftools porter.

**Comment by turbodiesel4598** [comment]
Thanks very much, and thanks for posting on the other issue. Definitely a weird one though - I am still unable to induce this crash. I'll try downloading some of the other mods you have.

**Comment by turbodiesel4598** [comment]
Ah, I have a suggestion - perhaps try Forge 2758 or earlier?

**Comment by turbodiesel4598** [comment]
Alright, the search continues!

**Comment by antcig** [comment]
Addition: dimlets and parts from rftools not crashing - show tooltip ok.
Also disabled:
TOP
grappling hook
MAGE

Same.

**Comment by turbodiesel4598** [comment]
Well, I installed every single mod that you had and I didn't get a crash - what if you install nothing but nucleacraft?

**Comment by turbodiesel4598** [comment]
Ok, so I found out what's going on - this was not a McJtyLib issue, but just a mistake I made in registering tooltips. [This build](https://www.dropbox.com/s/qn6pvzqvw7rf4xh/NuclearCraft-2.11c--1.12.2.jar?dl=0) should work now :)

**Comment by antcig** [comment]
Tested - crash is gone )
Gonna try new things.
Good work, thanks.

**Comment by turbodiesel4598** [comment]
Awesome! Thanks for helping out :)
