### ISSUE TITLE
Broken Mekanism tooltips and crash

### ISSUE THREAD

**Issue by CvoidWyvern** [turbodiesel4598/NuclearCraft#356]
Mekanism 9.4.13.349
Nuclearcraft 2.11b

When Nuclearcraft is installed, Mekanism machines lack proper tooltips, and crash when hovering over them in inventories (no crash in jei or in world with walia).  These items instead say to check the logs, which look like this when hovering over items:
https://hastebin.com/uhaboyivok.rb

Here's the crashlog it gives when hovering over an item:
https://paste.dimdev.org/ohugaqerej.mccrash

And here's the full log if needed:
https://goo.gl/WZbK4B

**Comment by turbodiesel4598** [comment]
Already fixed for the next version :)

**Comment by turbodiesel4598** [comment]
[Fixed in version 2.11c](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2613688) - at least, I think so :)
