### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by 1skandar** [turbodiesel4598/NuclearCraft#357]
Version 2.11b--1.12.2 From the Modular Mayhem modpack.  Alloy Furnace duplicates itself on place.

From here: https://www.youtube.com/watch?v=5NiNqWH7lWQ

At time 8:30

**Comment by 1skandar** [comment]
Never mind. On closer inspection, I think he simply made another somewhere along the way. Trying to verify, I'll getre-open if I can get verification

**Comment by turbodiesel4598** [comment]
Yeh, he just had another one in his inventory and inventory tweaks moved it to his hot bar after placing the first one ;)
