### ISSUE TITLE
Config to disable recipes for upgrade armor with shielding

### ISSUE THREAD

**Issue by Bulldog83** [turbodiesel4598/NuclearCraft#359]
Can you make this option in config file? Not all recipes works correctly. For example, recipes for jetpacks from Simply Jetpaks create creative versions of jetpack and flux pack. And I want to make my own recipes for shielding upgrade, but it's very difficult to removing all of your recipes with CraftTweaker.

**Comment by Bulldog83** [comment]
By the way, how about add config for items with default radiation protection?

**Comment by turbodiesel4598** [comment]
Ok, part 1 is done - I've added a blacklist and whitelist to remove and add shielding recipes, and I've fixed the Simply Jetpacks bug. Unfortunately JEI still shows the wrong recipe, but there's not much I can do about that.

Part 2 (default shielding) may be a bit trickier, but I think I know how it could be done :)

**Comment by turbodiesel4598** [comment]
The recipe metadata bug has been fixed and a config option for default resistance has been added :)

**Comment by Bulldog83** [comment]
Great, thanks! :)

**Comment by turbodiesel4598** [comment]
No prob! I'll still look into fixing that JEI issue, but for now at least the recipes work :)
