### ISSUE TITLE
EnderIO Capacitor Banks can't recive RF directly from Reactor.

### ISSUE THREAD

**Issue by EriBloo** [turbodiesel4598/NuclearCraft#36]
Placing any EnderIO Bank next to Reactor Controller doesn't charge it. It works perfectly with mods conduits, but they are capped at 20k RF/t max which is a lot less than most of Reactors. Cells from Thermal Expansion charge fine by direct contact.

**Comment by EriBloo** [comment]
BTW EnderIO Banks are one of the best ways to store high RF/t input, would be nice if it worked ;)

**Comment by turbodiesel4598** [comment]
I think I've accidentally fixed it :)
