### ISSUE TITLE
Issue when using Nuclearcraft and Tinkers Construct

### ISSUE THREAD

**Issue by DefenderofTheTimelines** [turbodiesel4598/NuclearCraft#360]
I have only Tinkers Construct, Mantle, and NuclearCraft in the mods folder among others, but if either Tinkers(and Mantle) or NuclearCraft are removed, the game loads perfectly fine. With both mods in folder game crashes almost immediaetely, and never makes it to the main menu screen.

Crash report:
https://gist.github.com/DefenderofTheTimelines/36cd1e8c36867b67aadada930f40a321 using NC 2.11c
https://gist.github.com/DefenderofTheTimelines/31056159148011222405eef05493a6c4 using NC 2.11f and other mods.

Mod List to create issue:
Mantle
Tinkers Construct
NuclearCraft

Versions:
Minecraft: 1.12.2
Forge: 14.23.4.2759
Mantle: 1.3.2.24
Tinkers Construct: 2.10.1.87
NuclearCraft: 2.11f & c

Error:
java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo

**Comment by DefenderofTheTimelines** [comment]
Let the Tinkers authors know as well, here is that issue.

https://github.com/SlimeKnights/TinkersConstruct/issues/3641

**Comment by turbodiesel4598** [comment]
Fixed!
