### ISSUE TITLE
fission reactor fuel consumption

### ISSUE THREAD

**Issue by RaveMaker** [turbodiesel4598/NuclearCraft#361]
Hello.
When i input fuel into any fission reactor for the first time it will consume the fuel without giving a depleted fuel or power output, also if i insert a full stack it will be completely consumed in a sec and there will be no power/depleted fuel output.
redstone signal doesnt affect it, will happen when reactor is on or off.
this really makes automation difficult since i cant change the type of fuel that goes into the fission reactor unless i do it manually, if i just pipe a new type of fuel into a reactor it will just be consumed without any output until i place one manually and reactor updates.
ended up making a different reactor for each fuel type.
thx :)

**Comment by turbodiesel4598** [comment]
I'm either unable to recreate this or I have misunderstood you - could you perhaps send some pictures or a video? Which version of the mod are you using? When you insert fuel for the first time, does the name of the fuel appear in the GUI?

**Comment by RaveMaker** [comment]
i used 8 tbu fuel to show this bug.
i split them, first 4 i put inside just vanish, no depleted fuel and no energy, then i used the other 4 and they process just fine.
now i can pipe tbu into the reactor but if i try a different kind of fuel it will disappear unless i put one manually and let it disappear before piping in the rest.
best way to describe it is that the first fuel i put into the reactor sets the type and then i can pipe that type into the reactor.
![1](https://user-images.githubusercontent.com/3329748/45632911-281b9080-baa7-11e8-978d-00478461798d.PNG)
![2](https://user-images.githubusercontent.com/3329748/45632912-28b42700-baa7-11e8-90a6-365de472bfbd.PNG)
![3](https://user-images.githubusercontent.com/3329748/45632913-28b42700-baa7-11e8-9c82-db30d8028764.PNG)

**Comment by turbodiesel4598** [comment]
Ok, I **may** have tracked this down. Does this onlt happen after a reload? In other words, if you break and replace the controller, then put fuel in, it is still buggy, or does it work as expected?

**Comment by RaveMaker** [comment]
the bug is gone now so i think the issue came from the pack and not from the mod itself.
the change i did was removing the stages script from the pack because of another issue i had with it, we were at the end anyway so all stages were supposed to be unlocked but for some reason we had many bugs with staged items, and in a test world everything worked fine so we figured the bug was with our world only.
i was past the nuclearcraft stage so i didn't know it fixed it until u replied and i checked.
thanx for your help
