### ISSUE TITLE
[Conflict]AE2 nether quartz dust disappears

### ISSUE THREAD

**Issue by LucunJi** [turbodiesel4598/NuclearCraft#362]
I run AE-rv5-stable11 and NC-2.11 only under mc 1.12.2. AE2 nether quartz dust disppears.
Crushed quartz dust added by NC can neither be made in IC2 macerator, nor be smelt into AE silicon. Since  nether quartz is more abundant than certus quartz, this conflict affects a lot.

**Comment by turbodiesel4598** [comment]
I believe this is an AE2 feature - if other mods add silicon/quartz/quartz dust, then AE2 will hide theirs and/ore disable the recipes for them. The lack of particular recipes such as the IC2 macerator one is just a side-effect of this (both nether quartz dust and silicon can be made in the NC manufactory).

If you head into config\AppliedEnergistics2\AppliedEnergistics2.cfg and search for 'orecamouflage', you will find a list of config options where you can disable the automated integration for a bunch of material types :)
