### ISSUE TITLE
Cannot see crafting recipe for any plating except basic plating

### ISSUE THREAD

**Issue by bisousbisous** [turbodiesel4598/NuclearCraft#364]
Using 2.11c, and JEI doesn't show any crafting recipe for anything besides the basic plating. Unknown if a bug or if I have to somehow unlock the recipes. Should mention I'm using Nuclearcraft in FTB Revelations as a replacement for extreme reactors

EDIT: Scratch that, I can't see the basic plating recipe either, just that it can show up in dungeon chests.

**Comment by turbodiesel4598** [comment]
Hey there! Unfortunately this is just a problem with part of one of the CraftTweaker scripts used by the pack. Head into the script file '01_unification.zs', remove the line `mods.unidict.removalByKind.get("Crafting").remove("plate");`, and the recipes should be visible :)
