### ISSUE TITLE
[suggestion] Fluid rate controller with μB precision

### ISSUE THREAD

**Issue by LucunJi** [turbodiesel4598/NuclearCraft#369]
When I try to fix a fusion reactor's efficiency to 100, I need exact -5000K/t to cancel the tempChange. However, liquid helium is cooling at 52800 mB/t and the flow rate should be 0.09469697mB/t. The gate in DE or controller in IC2 fails with such a number(1.89394mB/s, but IC2's controller can only do 2 or 1 mB/s). So there should be some way to deal with such a precision.

**Comment by turbodiesel4598** [comment]
Hey there - unfortunately I'm not sure that sort of thing is possible. If the cooling rate is too high, all I can recommend is to use different, less powerful coolers - most of the time you won't need much more than water.

The active cooling as it is now is not super well designed, and will defo change in the future.
