### ISSUE TITLE
The OverPower of Sword/tools

### ISSUE THREAD

**Issue by TataTawa** [turbodiesel4598/NuclearCraft#37]
I love the mod， it's great .but i'm making a mod pack , your mod's tool is overpowered. for example 24 attack DU sword. It will be imbalance in a modpack. WOULD you please turn the ATK down by half?

**Comment by turbodiesel4598** [comment]
Would config options for the power, durability, mining levels etc. of the mod's tools do the trick?

**Comment by TataTawa** [comment]
yes， a config option for ATK, duraility, mining speed of the DU tools will be perfect. but i haven't found config option about that, will it be possible in next version of NC?

**Comment by turbodiesel4598** [comment]
Yes, very possible. It should be simple :)

**Comment by TataTawa** [comment]
wow, cool! Is the next version coming in this weekend?＞▽＜

**Comment by turbodiesel4598** [comment]
A new version just went out, but I'll get another one out tonight or tomorrow with the tool configs in it :)

**Comment by turbodiesel4598** [comment]
Version 1.7h, with tool configs, as well as other things, is out now :)
