### ISSUE TITLE
[Bug] CraftTweaker not apply

### ISSUE THREAD

**Issue by andrelec1** [turbodiesel4598/NuclearCraft#370]
In my mod pack i have : 

CraftTweaker2-1.12-4.1.9
NuclearCraft-2.11g--1.12.2
externaltweaker-1.12-0.3
 
and other mods ...

nuclear craft is listed on /ct mods
but i can't see nuclearcraft in recipe type of extTweaker ...

I try to make custom recipe by hand... but i can't see ingame ( after relunch my game )

my script : 

```
mods.nuclearcraft.rock_crusher.removeAllRecipes();
mods.nuclearcraft.rock_crusher.addRecipe([<minecraft:quartz_ore>, <minecraft:quartz>*2, null, null, {1, 1, 0}]);
mods.nuclearcraft.rock_crusher.addRecipe([<gregtech.ore_lapis_0>, <minecraft:dye:4>*12, null, null, {1, 1, 0}]);
mods.nuclearcraft.rock_crusher.addRecipe([<thermalfoundation:ore:4>, <thermalfoundation:material:68>*2, null, null, {1, 1, 0}]);
```

**Comment by turbodiesel4598** [comment]
Hey there! A couple things:
First, those numbers need to be doubles (decimal numbers), so make sure they're '1.0' and '0.0' instead of just '0' and '1'.
Second, you need to remove the curly brackets.

So instead of `{1, 1, 0}`, you need `1.0, 1.0, 0.0` ;)

**Comment by andrelec1** [comment]
Well seem to work now ;)

I think you need to provide more exemple in the file, like a real working exemple ...
I didn't understand yet how to add random output ( need to make somme try ),

Another issue is the mod isn't list in extTweaker. But i can't determine if your mod or the extTweaker is the guilty party.

**Comment by andrelec1** [comment]
I speak with the ExternalTweaker modder's, he answer me : 
![image](https://user-images.githubusercontent.com/3273204/46548331-128fce80-c8cf-11e8-815a-cb35aaa676cc.png)
