### ISSUE TITLE
[Bug] D-D fusion only producing H3 and running out of fuel

### ISSUE THREAD

**Issue by Water-Cat1** [turbodiesel4598/NuclearCraft#372]
Since Nuclearcraft-2.12c--1.12.2 the Deuterium-Deuterium fusion reaction has been giving only helium-3 as an output. A system that was working before the update with electrolyzers and H-H fusion to supply the required Deuterium now runs out of Deuterium, and the Helium-3 output is moved to an input and blocks the system.
I have some config values changed for these processes to make it more reasonable to run, but these were done before the update and haven't been reset from the update.

**Comment by CrazedPhysicist** [comment]
I ran intop the same problem yesterday using Nuclearcraft 2.12d--1.12.2. The D-D reaction seemed to require too much fuel, ran too cool for the displayed efficiency and produced too little power.
From my testing using H-H, D-D, T-T and B-B reactions it seems like the reactor displays the correct fuels in the input tanks but follows wrong recipes in the last three cases. The fuel intake, efficiency curve and power output matched almost exactly what I would expect from the first fuel being replaced by Hydrogen, meaning the reactor performed like H-H, H-D, H-T and H-B respectively. Hopefully that Observation helps to narrow it down a little. It at the least explains why your H-H reactor has no problems.

**Comment by Water-Cat1** [comment]
Previous version was NuclearCraft-2.11g--1.12.2, where the setup was working fine (did the update 3 days ago).
When I updated there was also a change from forge-14.23.4.2756 to forge-14.23.4.2765

Thanks for those observations CrazedPhysicist. Yes, the H-H fusion and electrolysers are working fine and I am not running out of Hydrogen.

**Comment by turbodiesel4598** [comment]
Cheers - ok, will be a bit tricky go get a fix out fast as I'm now at uni, but will try find the problem :P

**Comment by turbodiesel4598** [comment]
Found the problem! Will try get the new build out tonight if I can get TeamViewer working ;)

**Comment by turbodiesel4598** [comment]
Here's [version 2.12e](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2627055) :)
