### ISSUE TITLE
[suggestion] Device with EU Tier 4 output

### ISSUE THREAD

**Issue by LucunJi** [turbodiesel4598/NuclearCraft#373]
In order to get tier 4 EU output, the only way is directly using fusion reactor output or combine 4 Lithium Batteries together. However, when powering the fusion magnets, a large power is needed. It will be great to have some blocks which directly output Tier 4 power.

**Comment by turbodiesel4598** [comment]
Next version or so I'll try getting the higher-tier voltaic pile and lithium ion batteries in, with higher output tiers :)

**Comment by LucunJi** [comment]
That's great. Since glass fiber cable is much cheaper than the Cryo-Stabilized Fluxduct, what's in need is only a higher tier output.

**Comment by LucunJi** [comment]
By the way, what's new in 2.12d version? I did not see it in changelog

**Comment by turbodiesel4598** [comment]
Oh, not much - some mods were crashing with NC installed because I wasn't doing some error catching properly :)

**Comment by turbodiesel4598** [comment]
Higher tier storage blocks added for the next version :)
