### ISSUE TITLE
Fusion Reactor Doesn't Remove Used Coolant

### ISSUE THREAD

**Issue by LucunJi** [turbodiesel4598/NuclearCraft#374]
MC Version:1.12.2
MOD Version: NuclearCraft-2.12d--1.12.2

It should be -5280K/t when Liquid Helium is pumped into the active cooler at a rate of 2mB/s.
Because 52800K/20t*2mB=5280K/t
However: the cooling rate keeps increasing and finally stops at the maximum possible cooling rate of a single active cooler with liquid helium.

After some tests, it's clear that the fusion structure dose not remove the used coolant in active cooler.

![avatar](http://i68.tinypic.com/2itsd2q.png)
![avatar](http://i63.tinypic.com/20jhjq0.png)

**Comment by LucunJi** [comment]
Also, when I changed version back into 2.11g, the magnets does not work properly, and the reactor will finally explode.

**Comment by turbodiesel4598** [comment]
The switching-back caused an issue because the way NBT data was saved and loaded changed between 2.11 and 2.12. It was forwards-compatible but I didn't think to make it backwards-compatible.

I will look for the cause of the cooling error, though!

**Comment by turbodiesel4598** [comment]
Found the problem - bit of a sneaky one. Will try to get a fix out for this and the fusion issue tonight if I can get TeamViewer working ;)

**Comment by turbodiesel4598** [comment]
Here's [version 2.12e](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2627055) :)

**Comment by LucunJi** [comment]
Another thing, I noticed the NC Youtube channel, and the videos are quite good for beginners. However, players here in China can not see it for the GFW, so I'd like to repost your videos in another website.
Can I reproduce the videos on a Chinese video site [Bilibili](https://www.bilibili.com/)? I will mark the source for each video I reproduce.
