### ISSUE TITLE
Thorium, uranium, lithium not spawning

### ISSUE THREAD

**Issue by Ewallee** [turbodiesel4598/NuclearCraft#375]
Forge 2770
Minecraft 1.12.2
Sponge spongeforge-1.12.2-2705-7.1.0-BETA-3446.jar

Here is the config:
https://pastebin.com/HsdaxVhX
The other ores spawn as they should.

**Comment by turbodiesel4598** [comment]
Are you sure that there is none spawning? Have you used a tool like MCEdit to try find some in the world?

**Comment by Ewallee** [comment]
It works with the default generated config file. It doesn't work with the config a showed previously.

**Comment by turbodiesel4598** [comment]
Hmm, so, looks like number of ores spawning per ore chunk is two less than expected, so a config option of two or less will generate none at all. Also looks like the magnesium, at four, is spawning in groups of two at max, and the others are only spawning in groups of one, so it does seems this is what's happening- an easy fix will be to just bump this number by two in the spawning code :)
