### ISSUE TITLE
More of a question than issue

### ISSUE THREAD

**Issue by Tuvermage** [turbodiesel4598/NuclearCraft#377]
Many of the machines have multiple output slots. While I know many different ways to selective remove what I want. I was wondering what the intended method was. I want to write up a tutorial for my community to use, but I want to state the intended method of selective removing the stuff instead of tying it to the mods i just happen to use.

**Comment by turbodiesel4598** [comment]
Heyo! There isn't really a special 'intended' method as such. All sides are available to extract from, so you can use whichever sides you want. If you don't have enough sides to work with, then connecting a 'machine interface' is an option, giving more sides to work with :)
