### ISSUE TITLE
Fission Reactor Controller Energy Buffer and Redstone Integration

### ISSUE THREAD

**Issue by Vyraal1** [turbodiesel4598/NuclearCraft#379]
Given a completely safe/passively cooled design (which is the majority of fission reactors I think) makes the reactor redstone comparator functionality completely redundant. Would it be better to re-implement it so that it gives a redstone output level depending on the energy buffer? That way when the fission reactor is full and a proper redstone gate is set, the reactor shuts off at full buffer.

This would be mechanically different from the fusion reactor (but then again the fusion reactor was meant to run 100% all the time, even voiding excess energy), so I think it's still a reasonable deviation from previous mechanics. Worst comes to worst, you can add a toggle in the GUI of the fission reactor controller, telling it whether to output redstone levels depending on heat levels or on energy buffer levels.

edit: So I guess there was a native battery in NuclearCraft that had the redstone functionality, but I don't think that works with EU (for full context, I'm playing GregBlock and I'm trying to find a way to toggle fuel in the fission reactor without just manually turning it on and off).

**Comment by turbodiesel4598** [comment]
That should defo be possible :)
However, the battery comparator should work with EU - all of the EU gets converted to FE when added.
