### ISSUE TITLE
Game Crashes when placing Integrated Dynamics Cables next to machines

### ISSUE THREAD

**Issue by tommyTT** [turbodiesel4598/NuclearCraft#380]
When I place a cable from Integrated Dynamics next to a Chemical Reactor from NuclearCraft, the entire game crashes and the world can no longer be opened. This only happens when Mekanism is installed as well.

I looked into the code and found the crash occurs [here](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/util/GasHelper.java#L45) because asking a capability for their default instance may throw a InstantiationException or a IllegalAccessException (see the capability factory in the CapabilityManager class) that isn't caught.  The capability that is queried is [ICable](https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.12/src/main/java/org/cyclops/integrateddynamics/api/block/cable/ICable.java) from Integrated Dynamics which has an abstract default implementation and therefore can't be instantiated. This of course is a mistake in itself, but NuclearCraft should guard against those Exceptions anyways.

**Information**
Minecraft: 1.12.2
Forge: 14.23.4.2705
NuclearCraft: 2.12e
Other Mods:
Mekanism 1.12.2-9.4.13.349
Integrated Dynamics  0.11.17
Cyclops Core 0.11.10  
Common Capabilities 1.4.0
JEI 4.13.1.220

Crash Report [here](https://gist.github.com/tommyTT/f7763ef1acb0b519df705b277d745de5)

**Comment by turbodiesel4598** [comment]
Ah, thanks very much for pointing that out - will get that sorted!

**Comment by turbodiesel4598** [comment]
Fixed for next build :)
