### ISSUE TITLE
radiation crashing

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [turbodiesel4598/NuclearCraft#382]
this one happened when i fell from space (galacticraft mod) right when i hit the ground, i had radiation shielded armor on if that matters 
https://pastebin.com/5nNL7Brp

and this one happened when i destroyed a radiation scrubber in creative, i had a lot of them in the chunk and a custom config value D:radiation_scrubber_rate=0.75
https://pastebin.com/bfHXUMta

**Comment by turbodiesel4598** [comment]
Pretty sure I've fixed the first issue, and kind of sure I've fixed the second. I'll close this for now, but let me know if the changes I made for the next version don't fix it :)
