### ISSUE TITLE
Geiger counter gui render issue

### ISSUE THREAD

**Issue by BlayzerQ** [turbodiesel4598/NuclearCraft#383]
If use Geiger counter, on screen will white cube instead of a cross
http://dl4.joxi.net/drive/2018/10/22/0029/0646/1909382/82/204a918d96.png

**Comment by C4PTRAMPAGE** [comment]
it also breaks the rendering for the immersive engineering mining drill hud.

**Comment by BlayzerQ** [comment]
Removing GlStateManager.pushAttrib() and GlStateManager.popAttrib() fix this for hud render class.

**Comment by BlayzerQ** [comment]
> it also breaks the rendering for the immersive engineering mining drill hud.

Also breaks F3 menu (black background) if installed only Nuclear Craft.

**Comment by turbodiesel4598** [comment]
I was not able to recreate the crosshair issue, but removing the pushAttrib and popAttrib lines did fix the F3 menu, so thanks for the help :)
