### ISSUE TITLE
Extra EU Generated from Fission Reactor

### ISSUE THREAD

**Issue by Crindigo** [turbodiesel4598/NuclearCraft#388]
Copied from: https://github.com/NillerMedDild/Enigmatica2ExpertSkyblock/issues/216

Version 2.12e

Issue Description

A reactor with multiple Fission Reactor Ports outputting EU will not divide the power properly.

In my case, I have a reactor generating 10,080 RF/t, which normally would output 630 EU/t as it divides by 16. If I only use one port, it correctly outputs 630 EU/t at voltage 4. If I use 4 ports, it outputs 512 EU/t @ voltage 3 from each, giving me a total of 2,048 EU/t as measured by an EU reader.

If I have 5 ports, each would output 128 EU/t @ voltage 2. I believe this is because the original 630 is divided by 5, giving 126 which fits under 128. With 4 ports it's ~157 so it rounds to the next tier at 512.

https://imgur.com/a/Qg37ePK

**Comment by turbodiesel4598** [comment]
Ah, found the problem - fixed for the next build!
