### ISSUE TITLE
[Bug]Power output/input from certain NC blocks fluctuates wildly

### ISSUE THREAD

**Issue by Rosethorns** [turbodiesel4598/NuclearCraft#392]
For power output I have only noticed this with the fusion reactor. However the Fusion reactor does not appear to output power per tick as the readout suggests. causing external power readouts to fluctuate wildly and averages to be off.

This test was done with a EIO stellar conduit, and a Flux mod Flux Plug separately. Both mods provide a per tick readout and a average readout.

These tests are not shown in the attached video nor are the fluctuating power retrieval of many (all?) of the NC processing machines.
However an example of the fluctuating input and output is shown in the fusion reactor.
Fusion Reactor for output
Magnets for Input.

![](https://cdn.discordapp.com/attachments/425461908716519425/507679544547999749/unknown.png)

![](https://cdn.discordapp.com/attachments/425461908716519425/507679626944839680/unknown.png)

[]https://www.youtube.com/watch?v=VfOGXfrw8ps

**Comment by turbodiesel4598** [comment]
As discussed in the Discord chat, we think this was due to the e-magnets absodrbing some of the energy every few seconds :)
