### ISSUE TITLE
Able to craft Tough Alloy with 2 x Ferroboron

### ISSUE THREAD

**Issue by xenoflot** [turbodiesel4598/NuclearCraft#394]
Playing Enigmatica 2, v1.49 JEI only shows the regular recipe (Ferroboron + Lithium) but I've found that if you put Ferroboron in both inputs of the alloy furnace, you get Tough Alloy. Considering how rare Lithium is in this pack, I'm going to milk that for all it's worth :P

MC 1.12.2
Forge 14.23.4.2751
NC 2.12d-1.12.2

**Comment by turbodiesel4598** [comment]
Was fixed in 2.12f ;)
