### ISSUE TITLE
NullPointerException extracting Mekanism gas

### ISSUE THREAD

**Issue by FrKevin** [turbodiesel4598/NuclearCraft#395]
https://pastebin.com/GneGJfLN

**Comment by turbodiesel4598** [comment]
Try updating to the latest version of the mod - I think I fixed it in that release.

**Comment by zaekeon** [comment]
Is this the same issue where trying to hook extra cells gas export bus or me capability adapter onto the fusion controller causes a crash?

**Comment by turbodiesel4598** [comment]
Possibly? I'm not sure. Either way, the original issue was fixed.
