### ISSUE TITLE
Nuclearcraft Cooling Overflow

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#397]
Hey! This issue was reported on my tracker: https://github.com/NillerMedDild/Enigmatica2ExpertSkyblock/issues/221
I'll copy paste it here, I hope you don't mind.

**Issue Description**
Large Nuclearcraft fission reactors, with active cooling, can overflow the cooling rate value, as it can go over 65535, and NC doesn't handle that. Apparently default NC config cooling values were "recently" updated, but not sure when, so the config may need a regen. Or if the heat values were intentionally boosted, they may need to just be set to normal. If the coolers are set to half efficiency that could maintain the 'difficulty' if that was the case

Just an example:
Nearly overflowing:
![2018-11-10_18 29 13](https://user-images.githubusercontent.com/2611674/48308998-1399d700-e5c4-11e8-908b-1884fdc5e1d5.png)
Then with one more cooler:
![2018-11-10_18 28 55](https://user-images.githubusercontent.com/2611674/48308997-13014080-e5c4-11e8-8a61-fac4f8d61d2b.png)

## Version
1.12.2-2.12f

**Comment by NillerMedDild** [comment]
Ah alright, thanks!

**Comment by turbodiesel4598** [comment]
Finally fixed for the next version :)

**Comment by NillerMedDild** [comment]
\o/ thanks!
