### ISSUE TITLE
Transparent Heat Exchanger Shells generating as ores?

### ISSUE THREAD

**Issue by kerts93** [turbodiesel4598/NuclearCraft#398]
Any idea what may cause this?
https://minecraft.curseforge.com/projects/the-society-transportcraft/issues/22

Modpack: https://minecraft.curseforge.com/projects/the-society-transportcraft
Forge version: 14.23.5.2772
NuclearCraft version 2.12f-1.12.2
Server latest log: [latest.log](https://pastebin.com/vTBBbPrp)

**Comment by Beannsss** [comment]
Did anyone use MCedit on the server recently? Cause I know it runs into problems saving modded worlds and things like this can happen.

**Comment by kerts93** [comment]
No, server world hasn't been touched since launch with anything external.

**Comment by turbodiesel4598** [comment]
Given the randomness of this, I can only suspect there was some ID mismatching of some sort. I can't think how this would have anything to do with NC directly...
I may be wrong, but it seems the most likely explanation.
