### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by Keridos** [turbodiesel4598/NuclearCraft#4]
If wanted I could help out with setting up the github wiki with information on how to do things in this mod once I get to know it a bit better.

**Comment by turbodiesel4598** [comment]
That would be great if you want to! I would certainly help along the way - is it worth doing though, considering the current wiki still needs work?

On another note, I will be uploading a mod spotlight explaining everything in the mod so far, and then I will make a very long wiki-vid, explaining everything with the maximum detail - this will help hugely developing the wiki.

**Comment by Keridos** [comment]
I personally dislike videos as instructive content, since wikis are far more easier to navigate if you want to just see some specific information, e.g. how a specific block acts in a nuclear reactor. When you upload the video I will start pulling out info into the wiki. I will probably soon start peeking into the source of the mod as well and be putting up a few more issues regarding features/changes.

**Comment by turbodiesel4598** [comment]
Same with me - it's just much, MUCH quicker to do the video, as it will be a few hours rather than potentially weeks, and from there, making the wiki is much easier too, as there's info to work with. I will have video times of certain topics in the description of that video, too, so you will be able to find specific info in the video.

The link to the wiki is fixed on the CurseForge page is now fixed, too.

**Comment by spannerman79** [comment]
I know this is 23 days old but which direction do you wish to take?

The "current" wiki is plasted with that many ads its not funny (Switch off your adblock and you'll see).  Where now that you have your repo here @turbodiesel4598 using the wiki here is *very* easy.  Just need to allow users to add/create.

**Comment by turbodiesel4598** [comment]
I have decided to do the video within the next week, as I now have some free time to play with. I have seen how wikis work on GitHub, and am very tempted to move towards having one. One thing is that I'm not really sure how it works, but you mention that it's easy which is nice to hear - I have a friend who's done one in the past so I'll see if I can get some help from him.

**Comment by turbodiesel4598** [comment]
I am hoping to record the video tomorrow, and then I will begin setting up a wiki here.
