### ISSUE TITLE
Energy & Speed Upgrades' Recipe in NEI using Induction Smelter Does Not Work

### ISSUE THREAD

**Issue by QuantumTraverse** [turbodiesel4598/NuclearCraft#40]
NEI says 1 iron plate and 4 universal reactant in the induction smelter will yield 1 Energy Upgrade, but that doesn't work, neither does the recipe of 1 iron plate and 4 crushed lapis yielding a speed upgrade

**Comment by turbodiesel4598** [comment]
Strange - it's working for me. Which slots are you putting the plates/dust into? The plate needs to go on the right.

**Comment by QuantumTraverse** [comment]
nevermind, I restarted my game and it all works now
