### ISSUE TITLE
Spaxelhoes don't count as anything but a pick.

### ISSUE THREAD

**Issue by ErdrickXLII** [turbodiesel4598/NuclearCraft#400]
Because the spaxelhoe only inherits from the NCPickaxe class, which extends the vanilla pickaxe class, and nothing else, it can't harvest snowballs, till dirt, or break Random Things' Nature Core as it specifically requires an axe with a minimum harvest level of "obsidian" (as The One Probe puts it).

**Comment by turbodiesel4598** [comment]
Quite the oversight - fixed!
