### ISSUE TITLE
[Bug] Fission Reactor magnet power not spreading power to adjacent blocks

### ISSUE THREAD

**Issue by PABessero** [turbodiesel4598/NuclearCraft#410]
The title basically describes it, unless i missed something (im pretty new with the mod and learned how it worked through your videos) the magnets need a cable for each one to be powered instead of one source powering all the adjacent ones

**Comment by turbodiesel4598** [comment]
There is a config option called 'passive permeation' that needs to be enabled for power to spread between the e-magnets ;)
