### ISSUE TITLE
[Question] Quick question about your code

### ISSUE THREAD

**Issue by PABessero** [turbodiesel4598/NuclearCraft#411]
Here's the question / suggestion:
Why arent the lang files organized in a resource bundle? it would be pretty much the same when you work on the actual mode, but for translation it would make the process faster, especially when doing it from scratch

**Comment by turbodiesel4598** [comment]
A resource bundle? Could you explain in a little more detail? I don't write the translations, but separate lang files is how MC deals with different languages.

**Comment by PABessero** [comment]
Sure, resource bundles are basically property files that will sync attributes between different langs and locals, thats how Java usually handles it. (https://gyazo.com/11e03a6c99f10da1ab4e7c5564d09c23)

**Comment by PABessero** [comment]
it is still made in multiple files, but those files are linked with each other

**Comment by turbodiesel4598** [comment]
So how would this actually work in practice? I don't actually write the translations so would this help?

**Comment by PABessero** [comment]
from what i know, it wouldnt change anything for you,  wouldnt make it easier nor harder, its for the ones making the translation that it would change something

**Comment by turbodiesel4598** [comment]
So what about making the translations would be easier? This is a very new thing to me and I'm not at all sure how this would actually be implemented, particulalry in this context.

**Comment by turbodiesel4598** [comment]
I don't think this is something supported by Minecraft/Forge, so unfortunately I don't think I can use this.
