### ISSUE TITLE
Incorrect value for advanced voltaic pile

### ISSUE THREAD

**Issue by Gimpler** [turbodiesel4598/NuclearCraft#412]
The value for the advanced voltaic pile should be 6400k, not 64000k which is making it better than the elite which sits at 25600k.

https://cdn.discordapp.com/attachments/425461908716519425/525841960548696099/2018-12-21_20-08-41.gif

Minecraft: 1.12.2

Forge: 2796

Nuclearcraft: 1.12h

**Comment by turbodiesel4598** [comment]
This is fixed by resetting the battery configs - I recommended this in the changelog, but I often forget that you don't see it when updating through the launcher :P

**Comment by Gimpler** [comment]
Oops, I didn't realize a mod update wouldn't change configs.

**Comment by turbodiesel4598** [comment]
Yeh, maybe I should have just made a new config and removed the old one... oh well :)
