### ISSUE TITLE
item not registered dust 

### ISSUE THREAD

**Issue by kain184** [turbodiesel4598/NuclearCraft#416]
Please use a paste tool such as Pastebin (https://pastebin.com) for crash logs!
![image](https://user-images.githubusercontent.com/1027230/50382316-c0528400-0659-11e9-9e18-d8ba4c3943b4.png)
i keep getting this issue when trying to run your mod where it says the dust item is not registered.

**Comment by kain184** [comment]
[latest1.log](https://github.com/turbodiesel4598/NuclearCraft/files/2705872/latest1.log)

**Comment by kain184** [comment]
at least as far as i can see.

**Comment by turbodiesel4598** [comment]
This might be some Sponge-related thing as I have both of these mods installed and don't have this issue. Are there any mods that might be tweaking recipes? When does this error occur?

**Comment by kain184** [comment]
This error occurs on the client to server connection. When the client tries
to connect it throws this error out shown in the picture. I have not added
any mods that change recipies. I was planning to at a later date. I am
thinking though after going through the log. It does show project e
adjusting some of its values based on creating emc value amd keeps
referencing item.dust for a few it had to adjust values for. Could be an
interaction between thermal project e and nuclear. But i cant find a
definitive error to atribute it to.

**Comment by kain184** [comment]
The only plugins loaded for sponge are for multi world and world edit. And
i doubt those are the issue. But i will do some testing.

**Comment by turbodiesel4598** [comment]
Hmm... so what happens if you remove Thermal, ProjectE or NC? Does the issue disappear?

**Comment by turbodiesel4598** [comment]
@kain184 Are you still getting this issue?

**Comment by turbodiesel4598** [comment]
Have you talked to KingLemming about this issue? It might be a simple fix on either of our sides.

**Comment by kain184** [comment]
Sorry has been a while since i looked into the issue at all. I will run
some tests as soon as i can.

**Comment by turbodiesel4598** [comment]
Any luck?
