### ISSUE TITLE
Capability lag in recipes

### ISSUE THREAD

**Issue by LemADEC** [turbodiesel4598/NuclearCraft#417]
As of 2.12h-1.12.2, lag is observed in capability handling during crafting:
![image](https://user-images.githubusercontent.com/4776032/50388241-86908480-0710-11e9-8014-b0383c70251f.png)

net.minecraftforge.oredict.OreDictionary.getOreIDs() is known to be very slow and cause memory allocations. Consider using a cache or fast filter before using that method.

**Comment by turbodiesel4598** [comment]
Ok, using a cache now - hopefully will speed this up :)
