### ISSUE TITLE
[Suggestion] Config option to make structure chunks radioactive

### ISSUE THREAD

**Issue by Turrari** [turbodiesel4598/NuclearCraft#419]
Awesome mod.  It fits in very well with a mod pack I am trying to put together.  Would it be possible to make chunks radioactive based on whether the chunk contains a structure?  I see that InControl can do this for mob spawns so I was hoping that it would be possible to get the tag somehow for the chunk and use it for radiation.  Specifically, it would be nice to be able to set radiation for The Lost Cities, buildings, streets, cities and/or spheres.  It might also be nice to be able to do it for vanilla structures like strongholds, fortresses, villages, etc.  Also adding in a random chance for them to be radioactive or by how much might be a cool idea too rather then globally setting it.

Thanks

**Comment by turbodiesel4598** [comment]
If InControl can do it I'm sure NC could too, but this sort of thing is a little beyond me for now - I'll leave it up in case a PR pops up or the to-do list thins out a bit.

**Comment by turbodiesel4598** [comment]
I was recently pointed to a really nice solution to this - I'll get it sorted when I'm back from uni :)

**Comment by turbodiesel4598** [comment]
Added for the next release :)
