### ISSUE TITLE
Is there a way to change Recipe Order for Radiation Shielding for Armors?

### ISSUE THREAD

**Issue by KaneHart** [turbodiesel4598/NuclearCraft#421]
I either want to disable them all but still allow them to be crafted (so hide it) or a way to order it better so they show up behind the armor recipes.

Thanks :)

**Comment by turbodiesel4598** [comment]
The shielding recipes have been pushed back to post-initialistation and so should be registered after all other recipes for the armour and appear at the back of the JEI recipe list :)

**Comment by KaneHart** [comment]
Thanks mate you been awesome!
