### ISSUE TITLE
Fission Reactor Buffer Not Emptying

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#422]
Hey o/

It seems like the Fission Reactor is no longer able to transfer energy fast enough to clear it's buffer. I believe the maximum energy outputted needs to be increased, as the update rate is fairly low.

Original issue: https://github.com/NillerMedDild/Enigmatica2Expert/issues/532

## Version
- NuclearCraft-2.12k--1.12.2

**Comment by turbodiesel4598** [comment]
I think I have this fixed for next version :)
