### ISSUE TITLE
Electrolysers causing TPS lag on server

### ISSUE THREAD

**Issue by GameBurrow** [turbodiesel4598/NuclearCraft#425]
Several Electrolysers were causing TPS drop of 10 on our server, even when unpowered.

**Forge version** 14.23.5.2796
**Nuclearcraft version** 2.12k
Used modpack (v5.0.10.0): https://minecraft.curseforge.com/projects/the-society-transportcraft/files

Here is our tickprofiler result:
![Server profiler result](https://i.imgur.com/uaNJJQz.png)

Here is the setup in question:
![](https://media.discordapp.net/attachments/474224915437060116/531748541199155210/unknown.png)

Full chat log with the players who built the setup
> [Server] Is anybody using Electrolyser
[Lilu_Paine] no
[Piston_man20] we have them but not on
[Piston_man20] no power
GameBurrowToday at 10:09
Remove them.
TheSocietyBOTToday at 10:09
[Piston_man20] what's up?w
GameBurrowToday at 10:09
They are causing huge lags.
TheSocietyBOTToday at 10:14
[Piston_man20] thats odd considerint that they arent even powered
TheSocietyBOTToday at 10:15
[dominator2486] they are unpowered
[Lilu_Paine] maybe someone else has them and they arent online
[Lilu_Paine] ?
[dominator2486] might be on to something in science
GameBurrowToday at 10:16
Look at the coordinates, they match the base location. They may be unpowered but they are lagging, can you guys send me screenshots of the setup.
TheSocietyBOTToday at 10:16
[Piston_man20] try now, i cleared thier water tanks
[dominator2486] they are giving particles when there is water, even if there is no power
GameBurrowToday at 10:17
Running profiler.
TheSocietyBOTToday at 10:17
[dominator2486] josh draining them now
[Piston_man20] done
[dominator2486] your profiler is wrong
[dominator2486] not showing all the electro
GameBurrowToday at 10:18
Now it's okay, did 3 tests in a row.
It showed the top 5 users.
JoshGToday at 10:18
gotcha
GameBurrowToday at 10:19
I'll make a bug report on their github because it almost crashed the server.

**Comment by turbodiesel4598** [comment]
Hmm... I'm really not able to recreate this - I've set up [50 inactive electrolysers in my test world](https://imgur.com/oJS14lJ) and they are taking [a total of 1 microsecond](https://imgur.com/oJS14lJ) to tick. What are the units of tick time used by that profiler?

**Comment by kerts93** [comment]
Good question, this is the mod I used for profiling as I didn't have access to client at the time.
https://minecraft.curseforge.com/projects/tickprofiler

What I do know is that server TPS was around 7 before draining the Electrolysers and after that it was around 16.

**Comment by kerts93** [comment]
Comparing values with LagGoggles, it looks like it uses same units:
μs/t

**Comment by turbodiesel4598** [comment]
Are you able to recreate this in another world, client or server?

**Comment by turbodiesel4598** [comment]
@kerts93 Still having trouble recreating this with various combinations of mods. I've updated the mod recently (2.13d is now the latest) with a bunch of bug fixes and a few performance improvements here and there - maybe give that a try?

**Comment by kerts93** [comment]
Sorry for not replying, haven't had a chance to try outside of our world or server, but the issue is still there:
![](https://cdn.discordapp.com/attachments/159559598657765376/537182462141530122/unknown.png)

I will try your update soon to see if that fixes/improves things and will let you know.

**Comment by kerts93** [comment]
After the last update it's the same:
![image](https://user-images.githubusercontent.com/4341091/51543426-32d79f00-1e66-11e9-92c5-3d7eda9cc86f.png)

But I think I fiqured something out thanks to JEI, their states flicker from active to idle and this is something we have seen that can cause tps lag from other mods also. See gif below:

![image](https://user-images.githubusercontent.com/4341091/51543477-4edb4080-1e66-11e9-866d-b795bd8ed884.png)

**Comment by turbodiesel4598** [comment]
I don't see a gif, but if the block is flickering, then yes, that will probably be the cause - are they being supplied enough power? Are they processing the water very quickly?

**Comment by kerts93** [comment]
No power yes, I leave a not to them but is there a way to check this on the mod side, for example some kind of minimum amount it needs to have before it turns on or something like that?

**Comment by turbodiesel4598** [comment]
So they're not being supplied power _at all_? If so, they shouldn't turn on in the first place.

**Comment by kerts93** [comment]
I turned them all off and I noticed no power coming into them at all (all stayed at 0RF)

**Comment by turbodiesel4598** [comment]
And they were still flickering?

**Comment by kerts93** [comment]
They were flickering yes until I turned them manually off with redstone.

**Comment by turbodiesel4598** [comment]
Ohhhh... I may have found the cause. Let me put together a quick build, and I'll post it here shortly :)

**Comment by turbodiesel4598** [comment]
[Give this a go](https://www.dropbox.com/s/w3ltzdep6919cyn/NuclearCraft-2.13eSupaSecretBuild--1.12.2.jar?dl=0) - it may fix the problem...

**Comment by turbodiesel4598** [comment]
@kerts93 [Give this a go](https://www.dropbox.com/s/w3ltzdep6919cyn/NuclearCraft-2.13eSupaSecretBuild--1.12.2.jar?dl=0) - it may fix the problem...
