### ISSUE TITLE
Spaxelhoes don't accept sword enchantments

### ISSUE THREAD

**Issue by Gimpler** [turbodiesel4598/NuclearCraft#429]
Spaxelhoes currently do not accept looting, sharpness, smite, etc as valid enchants despite being part sword.

![2019-01-11_13 03 52](https://user-images.githubusercontent.com/44327798/51051441-c45f2b00-15a1-11e9-88a1-4f24e207c4ee.png)

**Comment by turbodiesel4598** [comment]
Unfortunately it seems this is impossible as whether an enchantment is valid or not is dependent on the class of the item being enchanted - as the spaxelhoe can't extend two classes, I can't allow for both tool and sword enchantments to be applicable :(
