### ISSUE TITLE
missing textures (1.7.10-1.8)

### ISSUE THREAD

**Issue by Cronosus** [turbodiesel4598/NuclearCraft#43]
theres missed some textures:
-Pistol
-Energy Upgrade
-Speed Upgrade
-Nuclear Grenade
![2016-07-06_18 17 07](https://cloud.githubusercontent.com/assets/5349950/16625735/3a2632f0-43a6-11e6-80cb-a6bacb927772.png)

**Comment by turbodiesel4598** [comment]
Yep, I've already noticed this, as it's already fixed for the next update :)
