### ISSUE TITLE
isArmor performance issue

### ISSUE THREAD

**Issue by Sir-Will** [turbodiesel4598/NuclearCraft#430]
NuclearCraft-2.12k--1.12.2

![](https://i.imgur.com/J0rsLzO.jpg)

**Comment by turbodiesel4598** [comment]
Horse armour rad shielding will be removed next version. It was a hacky addition across the board :P

**Comment by turbodiesel4598** [comment]
Fixed! Have not removed horse armour shielding but it is now a config option, and even when enabled it should be much, much less laggy :)
