### ISSUE TITLE
Gregtech + NuclearCraft = Crash

### ISSUE THREAD

**Issue by realmbmc** [turbodiesel4598/NuclearCraft#431]
Crash on server startup when using mods together.
Everything is totally fine when I delete NuclearCraft.
[Debugging Log](https://pastebin.com/aQUCsmNr)
[Crash Report](https://pastebin.com/4hUWVNTq)

**Comment by turbodiesel4598** [comment]
I have notified the GTCE devs - hopefully they find an easy fix on either their side or mine :)

**Comment by realmbmc** [comment]
Sorry for long time not answering. Sure, I will ;) Thanks!

**Comment by turbodiesel4598** [comment]
@realmbmc 2.13e just went out, a few more bug fixes in case 2.13d didn't do the trick.

**Comment by turbodiesel4598** [comment]
Going to assume this was fixed - if not, feel free to open up another issue!
