### ISSUE TITLE
Load time very slow with NC installed (some packs)

### ISSUE THREAD

**Issue by TimGoll** [turbodiesel4598/NuclearCraft#432]
Might be connected or the same as issue #430 

It worked fine until my most recent update (from 2.12f to version 2.13). Eversince the update the JEI phase of the gamestartup takes ages. [[Image of said load stage]](https://imgur.com/a/SeW45zp)

Additionally the loading of maps is really slow. Like really slow. 

And there are some heavy lag spikes in game every now and then. But I'm not 100% if they are connected with this issue.

Minecraft: 1.12.2
Forge: *.68
NC: 2.13

**Comment by TimGoll** [comment]
Update: Can confirm it is 100% tied to Nuclearcraft. I've updated all 230 mods and it works perfect when I use the older NC version

**Comment by asomedude9897** [comment]
k so heres the rub
it may just be radiation

**Comment by turbodiesel4598** [comment]
@TimGoll When you say "it works perfect when I use the older NC version", are you referring to the JEI slowdown, the map load time, the lag spikes or a combination of them?

**Comment by turbodiesel4598** [comment]
I've had reports of JEI slowdown and lag when using 2.13, from some people, and others have said it's fine. I think it's a mod interaction which is doing something nasty, but I'm still not sure which actually update introduced the issue. Could you try using version 2.12k and see if you have the same problems?

**Comment by TimGoll** [comment]
I will test it

**Comment by turbodiesel4598** [comment]
@TimGoll I think I may have solved the issue - [here's a test build](https://cdn.discordapp.com/attachments/528692982757588992/536516209164943360/NuclearCraft-2.13a--1.12.2.jar) if you'd like to see if the problem has gone away.

**Comment by TimGoll** [comment]
Nice! Sorry for not answering sooner. I'm not at home right now. But I'm back later today.

**Comment by turbodiesel4598** [comment]
Great :)

**Comment by turbodiesel4598** [comment]
Are loading times significantly slower with NC uninstalled?

**Comment by DeadSix27** [comment]
> Are loading times significantly slower with NC installed?

It never finishes loading and just hangs for me with it Installed (the newest version).

With the older ones it works fine and I see no notable difference.

I am in the progress of testing with older JEI versions and latest NC version.

**Comment by turbodiesel4598** [comment]
Could I see the game log for this hanging? I can't think why that would happen.

**Comment by DeadSix27** [comment]
@turbodiesel4598 Here's log of when it hangs up: <https://gist.github.com/DeadSix27/65619b8d616611573a65e2a5290e170a> (I saw nothing interesting in the last lines though, whichever mod does something there probably doesn't log it?)

I also tested with the suggested JEI version `1.12.2-4.14.0.231` and it finishes loading but its quite a lot slower than on older NC versions still. (about 3minutes vs. around 1 minute with older NC) heres a log with that version:
<https://gist.github.com/DeadSix27/74ab575b267698ded8fdc1f5ed01ede4>

**Comment by turbodiesel4598** [comment]
Are you using a particular pack or able to export a profile of it? I can play around with it then... it's a tricky one because I can't think of anything that changed recently that would cause this...

**Comment by DeadSix27** [comment]
Here's an export of the profile, needs around 8-9GB of RAM:
https://share.toji.site/mc1.12.2-1.0.zip

**Comment by turbodiesel4598** [comment]
Okay, so someone found out that the problem occurs when MistyWorlds is installed alongside NC. I should be able to get this fixed on my side - I'll let you know when I have ;)

**Comment by DeadSix27** [comment]
@turbodiesel4598 awesome :) I'll test when I find the time to. Is that an issue on mistyworld's side? Do We/I need to report it to him/her?

**Comment by turbodiesel4598** [comment]
Probably not - it's really an issue with NC's way of caching that I wasn't expecting. In general it would be a good improvement to make in fixing crashes such as this :)

**Comment by turbodiesel4598** [comment]
Fixed for the next version; the cache should be more efficient in genral now too - thanks!
