### ISSUE TITLE
Feature Request: Allow Full NBT Access When Clicking on Any Fusion Core Side

### ISSUE THREAD

**Issue by Darkosto** [turbodiesel4598/NuclearCraft#434]
Hello!

I have a bit of strange request:

I'm using advancements to detect how much RF is generated with the Fusion Reactor. The only way to detect this information is by opening the GUI of the Fusion Core Block in the center block on the bottom. This is the only location I can open the GUI to get the RF nbt data. All the other sides of the multiblock do not give it. I noticed this coincides with the bounding box when pointing at individual blocks in the structure. The only one to show the full bounding box is the bottom, center block.

Is it possible to allow any of the sides to give this information when clicked on? It would make my life so much simpler.

Thank you!!
Darkosto

**Comment by turbodiesel4598** [comment]
Hey there darkosto!

I think I just had a viewer of yours ask a similar question - right now, yes, the dummies just point to the core, and so it is not really possible to get to the info through jsons and nbt. I can save some core data to the dummies, though, and I'll happily do that if you let me know what you need :)

Tom

**Comment by Darkosto** [comment]
No worries on the time frame! I can make a workaround and just let players know where to click in the meantime. The info I would need to track via advancements would be the following:

{size:24}

{processPower:3333333.0}

Both the size and power production.

Thanks for checking this out :)

**Comment by turbodiesel4598** [comment]
Sure thing, and no prob - I'll let you know when it's in!

**Comment by Darkosto** [comment]
Thank you!!

**Comment by turbodiesel4598** [comment]
Managed to get a bit of time to do some work - should be added now, will release at some point today :)
