### ISSUE TITLE
[Enigmatica 2] Reactor is set up properly, but power and efficiency are at 0

### ISSUE THREAD

**Issue by Ryliia** [turbodiesel4598/NuclearCraft#435]
I made the same reactor in single player and it worked perfectly. Toroid 4 reactor, pumping in Deuterium and Tritium. Powered the reactor on and only the heat is going up. Power and efficiency are still at 0. Any ideas why?

**Comment by turbodiesel4598** [comment]
Hey there - which version of NC are you using?

**Comment by Ryliia** [comment]
Looks like 2.12 according to my server files
