### ISSUE TITLE
Primitive mobs Grove Sprites interacting weirdly with radiation.

### ISSUE THREAD

**Issue by Darkere** [turbodiesel4598/NuclearCraft#436]
> Grove Sprites seem to conflict with Nuclearcraft Radiation when they are trying to place saplings. Not sure what's causing it.
> 
> ![image](https://user-images.githubusercontent.com/4283717/51275992-bfe8a700-19d3-11e9-896e-21066aad8eb5.png)
> https://sparkprofiler.github.io/?mCIYeTQaBR
> 
> Pack: ATM3 - Remix
> Forge: 2769
> Primitive Mobs: 1.2.2.
> Nuclearcraft:2.12k

https://github.com/Daveyx0/PrimitiveMobs/issues/204#issue-399978390 Report on Primitive Mobs Git

**Comment by turbodiesel4598** [comment]
Is this crashing the game, or is this just a comment on the slow method? If it's the latter, yep, the horse armour rad shielding is causing problems in a few places and will have to be removed in the next version.

**Comment by Darkere** [comment]
Not Crashing or anything similar just a thing that was noticed while hunting down lag sources.

**Comment by turbodiesel4598** [comment]
Fixed in dev, will release the build soon. Thanks for spotting this!
