### ISSUE TITLE
In-mod method of item/fluid/energy transport

### ISSUE THREAD

**Issue by bigyihsuan** [turbodiesel4598/NuclearCraft#438]
As of the turbine release, there is no way for Nuclearcraft itself to transport items, fluids, and energy without resorting to an outside mod providing one.

You could "transport" energy via chaining together many voltaic piles together, but that is very expensive and impractical.

Transporting items are provided with vanilla mechanics (hoppers, droppers, water streams, minecarts, etc.), however highly radioactive fuels could easily irradiate the landscape if they are transported via water streams. Hopper chains or dropper/dispenser chains are possible, but inefficient on the scale Nuclearcraft is on.

Fluid transport is simply not possible.

Possible solutions to this transport problem:

* Have a way to configure machine sides like the molten salt reactor coolant blocks to push or pull items/fluids.
* Implement a Nuclearcraft piping and cabling system somehow.

**Comment by ab9rf** [comment]
I'd rather Tom spend his time adding unique content to NuclearCraft than on reinventing the wheel. There are many fine mods that add transport mechanisms. Pick one (or more) and use it.

**Comment by turbodiesel4598** [comment]
Yeh, I'm really not focusing on pipes/conduits as many other mods already add them. If you want some sort of 'new' piping system to use, perhaps try out [Pressure Pipes](https://minecraft.curseforge.com/projects/pressure-pipes) which can easily deal with the large amounts of fluid NC produces and needs distributing :)
