### ISSUE TITLE
Ticking entity ( NuclearCraft-1.8)

### ISSUE THREAD

**Issue by 9000bowser** [turbodiesel4598/NuclearCraft#44]
Domino create a ticking entity
http://pastebin.com/Q40MkL8w

and mechanical pipe of mekanism ticked with connected to the steam decompressor
http://pastebin.com/Scv25gWv

**Comment by turbodiesel4598** [comment]
First of all, the domino's issue is fixed.

As for the Mek crash, it seems you're using an old version of Mekanism. I don't get this crash with the latest version, so could you check if the problem is fixed when you update?

**Comment by 9000bowser** [comment]
Mechanical pipe is not fixed with mekanism update
Mod Version :
MekanismTools-1.7.10-9.0.3.278
Mekanism-1.7.10-9.0.3.278
MekanismGenerators-1.7.10-9.0.3.278
MDK-1.7.10-9.0.3.278
NuclearCraft-14.8a
http://pastebin.com/JdKVhBeE

**Comment by turbodiesel4598** [comment]
Well, in that case, I'll update my version. I only updated it the other day, but perhaps the dev kit is a little more tetchy that hoped.

**Comment by turbodiesel4598** [comment]
Could you see if this version gets rid of the issue?
https://www.dropbox.com/s/i69sq95rmcnbg04/NuclearCraft-1.8b-Test--1.7.10.jar?dl=0

**Comment by 9000bowser** [comment]
Sorry, NuclearCraft-1.8b-Test don't fix the mechanical pipe issue
http://pastebin.com/h4dTpuPz

**Comment by turbodiesel4598** [comment]
Hmm, this is very strange, as it's working fine for me (1.8 and 1.8a did). I'll look into it more I guess.

**Comment by AnIncognitoOtter** [comment]
Just want to say that I also get this same issue and crash report, it isn't Mekanism related as it also happens when placing the steam decompressor adjacent to a big reactors turbine input port. Might also be related, but the decompressor also won't output to thermal dynamics pipes for more than a split second.

**Comment by turbodiesel4598** [comment]
Right, so I'm guessing this is an issue with the decompressor **outputting** steam. That will make things easier to track down. As for inputting dense steam, do things generally behave?

**Comment by AnIncognitoOtter** [comment]
Just tested using the mechanical pipes to insert dense steam to the decompressors, that works fine.

**Comment by turbodiesel4598** [comment]
Ok, thanks, I'll get another test build to you soon :)

**Comment by turbodiesel4598** [comment]
Ok, hopefully this will work. Now dense steam decompressors will automatically push dense steam into steam decompressors, and steam decompressors will only push steam into steam generators: https://www.dropbox.com/s/yg9cr1xzoqhcx34/NuclearCraft-1.8b-Test--1.7.10.jar?dl=0

**Comment by AnIncognitoOtter** [comment]
Just tested that version, and yeah it appears to work fine now, no crashing. Mechanical pipes and fluiducts work as expected.

**Comment by turbodiesel4598** [comment]
Nice - thanks! Ok, a few little tweaks in other places and 1.8b will be ready :)
