### ISSUE TITLE
Radiation crash tabbing in/out of full screen game

### ISSUE THREAD

**Issue by funfight22** [turbodiesel4598/NuclearCraft#440]
https://pastebin.com/Z8scbMhh

Playing on a server if that helps.  Can't tell if it is crashing when I tab out or when I am tabbing back in.

**Comment by turbodiesel4598** [comment]
One of those things that shouldn't really happen but snuck through - I'll add some extra code to protect against a crash happening :)

**Comment by turbodiesel4598** [comment]
Just updated the mod - could you see if you can recreate the issue with the latest version?
