### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#441]
Heya!

NuclearCraft currently crashes on startup in Enigmatica 2: Expert.
Here's the crash-report: https://gist.github.com/NillerMedDild/d92e9fc3b2d133d246ffa065a158984b

### Versions
- Forge 1.12.2-14.23.5.2781
- NuclearCraft-2.13b--1.12.2

**Comment by turbodiesel4598** [comment]
Fixed in [2.13c](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2663001) :)
