### ISSUE TITLE
Generate valid machine input lists on game load rather than on tile instantiation

### ISSUE THREAD

**Issue by Sir-Will** [turbodiesel4598/NuclearCraft#442]
NuclearCraft-2.13--1.12.2

![](https://i.imgur.com/4LRKGFJ.jpg)

**Comment by turbodiesel4598** [comment]
`RecipeHelper.validFluids` is a slow method but is only called when the tile entity is first created and never again - are you sure this is actually causing a performance hit?

**Comment by Sir-Will** [comment]
Well it's 3% more the most tile ents and this seems a lot for one method.

**Comment by turbodiesel4598** [comment]
Is 3% really a lot though? It's a big method because it has to set up the filters on the machine's tanks by going through all the recipes. It's only ran a single time though, so I can't see how that would cause any performance hits other than on world load. I guess a I could set up a set of static filters to speed it up a little more.

**Comment by Sir-Will** [comment]
Does it run it every time a new one is placed or every time it gets loaded?

**Comment by turbodiesel4598** [comment]
Either on placement or on world load, yeh.

**Comment by Sir-Will** [comment]
I guess it's fine then.

**Comment by turbodiesel4598** [comment]
I think so, but since you did bring it up, I think I could improve the performance a bit by doing one big set of recipe checks on game load instead of when each of the TEs load :)

**Comment by Sir-Will** [comment]
If it's all the same that would be great, I thought it would be different depending on the settings of the tile.

**Comment by turbodiesel4598** [comment]
Each machine of the same type will share the same list of valid fluids, so once the list is generated for each machine type on load no more would have to be generated.

**Comment by turbodiesel4598** [comment]
Sorted for the next version :)
