### ISSUE TITLE
[Question] Can't get Fission reactor produce RF

### ISSUE THREAD

**Issue by audaciousSalix** [turbodiesel4598/NuclearCraft#443]
Hi so, I'm completely new to this mod and for context am playing it through the Enigmatica 2 Expert pack and I just built my first reactor, using the tutorial build from the wiki page. I have casings on all faces but not edges, and the controller recognises the structure and shows me data. But when I put fuel in (LEU-235), it consumes the fuel but no RF is outputted. Not to the internal buffer, and not to external batteries through mekanism universal cables or through thermal expansion cables (the two I use). I feel like it's more likely to be something I'm missing than a bug, but I am very confused lol

**Comment by turbodiesel4598** [comment]
Try a redstone signal to the controller;)

**Comment by turbodiesel4598** [comment]
No prob!
