### ISSUE TITLE
Radiation information request and suggestions.

### ISSUE THREAD

**Issue by EasterncheesE** [turbodiesel4598/NuclearCraft#444]
Hello there.
Sorry to bother you, but i try to get the idea of Radiation system and some things look to complicated for me to understand.

1) Radiation scrubbers. For now (i powered them with IC2 power), i don't see them anyhow reduce radiation in chunk. I put 1-25 scrubbers into chunk with many RTG working and radiation level increase rate doesn't change with them powered/unpowered.

2) Can you please explain the radiation numbers? Scrubber show 0.1, Rad-x show 25 protection. Is this some % or like -25 rad/t? 
a.   S:radiation_blocks < minecraft:sandstone_0.25 - please tell what is 0.25 - 0,25 rad/t?
b. D:radiation_spread_rate=0.01 - is it 0.01 rad/t?
c. D:radiation_decay_rate=0.01 - same question
d.  The rate at which rads is removed when using RadAway in Rads/t D:radiation_radaway_rate=7.5. How does this work? Is it possible to switch RadAway into some continous mode? Like instead of -300 rad, get -10 rad/t?
e.    The time taken for one dose of Rad-X to wear off in ticks. D:radiation_rad_x_lifetime=12000.0. Is there some potion effect or other effect that can be added to food or something else to help make some noob anti-rad measures?

3)    If enabled, the radioactive stacks in a player's inventory irradiate the chunk the player is in as well as the player directly.
    B:radiation_hardcore_stacks=false
Is there way to turn off chunk radiation for items on the ground for certain world? Let me expain the usage context: I make server where PVP and griefing is not welcomed. For now, someone can drop a stack of californium near some noob base and render it completely impossible to live.

4) Is it possible to make a cap for maximum radiation per chunk per biome? What i mean is to make cap of 1 rad/t to be max and no matter how many sources of radiation are here, it will not increase further? This will greately help to control the radiation for some specific areas.

**Comment by EasterncheesE** [comment]
Any update? As for suggetions, they are suggetions, so we wait when you have time for them.
Could you please share radiation information for us to analize and use at first place? For now, it's pretty hard to understand the way it works :(

**Comment by turbodiesel4598** [comment]
Sorry I've taken so long to reply! Recently back from uni and wanted to get on a roll of doing bug fixes.

1) Scrubbers are a bit broken at the moment, though this will be fixed for the next build :)

2) All radiation resistances are dimensionless, while all radiation levels have units of `Rads` or `Rads/t` depending on the context.
a) That would be 0.25 Rads/t for each piece of sandstone.
b/c) That's also Rads/t, yes.
d) There are two separate configs - one is the overall rad removal, while the other is the rate. If you wanted it to remove radiation at 10 Rads/t, then just set the rate to 10.
e) Unfortunately it's not a potion effect - it's just an effect specific to Rad-X which taps into the player's radiation data.

3) Yes, I can do that :)

4) Added per-biome and per-dimension limit configs, as well as an overall chunk radiation limit :)

Hopefully that answers your questions and fulfills your needs!

**Comment by EasterncheesE** [comment]
Thanks a lot for full and understandable explanation!
