### ISSUE TITLE
Fusion cooling not working properly

### ISSUE THREAD

**Issue by Basedgod199** [turbodiesel4598/NuclearCraft#446]
I have a size 5 fusion reactor and each fluid cooler, when provided with water gives 20 active cooling, so with each pair gives 160 cooling (or at least this is what i have figured out thus far, i'm not 100% on the numbers and how it all works.) this is true up until a certain point, typically around 3-4k, at which point a pair gives 159. Now i'm not sure if this is intended, but i thought it is guaranteed 160 with each pair, at least for this size reactor.

**Comment by turbodiesel4598** [comment]
Probably just a simple rounding error - should be a simple fix :)

**Comment by turbodiesel4598** [comment]
Fixed!
