### ISSUE TITLE
Option for player rad level to decrease over time

### ISSUE THREAD

**Issue by chez4** [turbodiesel4598/NuclearCraft#448]
I recently noticed that radiation levels do not decrease over time, at all. I have tried using an older version of the mod (2.13 instead of 2.13e), but the same thing happens. I have not altered any config settings aside from the "turn on radiation" setting, which I set to true.

As you can see, radiation levels increase fine here: (this is from a distant wasteland)
![2019-02-03-193836_591x413_scrot](https://user-images.githubusercontent.com/16373900/52181585-577b3180-27eb-11e9-9e67-57d4f12f0d95.png)

However, there is no background radiation, despite it being on in the config. Also to note, if I stand in an area with 0 radiation, my rad level does not change at all.
![2019-02-03-194723_532x380_scrot](https://user-images.githubusercontent.com/16373900/52181678-8b0a8b80-27ec-11e9-93f8-1208d2697656.png)

In one of the mod spotlights I could see that it decreased on it's own, so I'm guessing this is a bug or it's just not been implemented.

**Comment by turbodiesel4598** [comment]
That is your _player_ radiation count - that will not decrease with time. Only the local radiation level of the chunk slowly decreases.

**Comment by MX-wb** [comment]
I see. I spawned right next to a nuclear wasteland, so i got irradiated pretty early on.
Well I suppose this is just a suggestion then. Sorry I didn't realise that this was supposed to happen. So all I can suggest is for player irradiation to gradually decrease, because that makes sense to me.

**Comment by turbodiesel4598** [comment]
It could certainly be added as a config option if you'd like :)

**Comment by MX-wb** [comment]
That would be great! Thanks :)

**Comment by ab9rf** [comment]
If you want to get really clever (and vaguely realistic) you should have 90% of it decay over time, but the other 10% remain permanently, as a reflection of the reality of radiation sickness, which has both acute and chronic components.

Feel free to tweak the 90/10 relationship (or, if you feel especially silly, make it configurable).

**Comment by turbodiesel4598** [comment]
Ok, config added - I've made the rate configurable, but always proportional to the radiation level, so a classic exponential decay ;)
