### ISSUE TITLE
Unable to toggle power drain

### ISSUE THREAD

**Issue by syndran** [turbodiesel4598/NuclearCraft#453]
Currently running All the Mods 3 (ATM3) v5.11.2.  Fusion  core currently operates normally, however does not respond to redstone signals correctly. Have tried - Lever, opencomputer Reactor.deactivate(), EnderIo conduit with lever,  RFTools Redstone Transmitter/Receiver. 

No matter which option i try, the Core continues to draw power and attempts to maintain ignition temperatures.  (can suck 500 billion RF pretty quick at @250krf/t

**Comment by turbodiesel4598** [comment]
Hey there - the core doesn't respond to redstone like that. As long as the temperature is below 8000 kK, it will draw any power sent to it. The thing to do is to just not send power to it while you don't want to try to start it up ;)

**Comment by syndran** [comment]
Aye is what i ended up doing, have redstone controlled power to the core
and coils that shuts down in sequence after reactor deactivate.
Cheers

**Comment by turbodiesel4598** [comment]
No prob!
