### ISSUE TITLE
Request to let CraftTweaker recipes come first on load order if possible.

### ISSUE THREAD

**Issue by KaneHart** [turbodiesel4598/NuclearCraft#454]
Not sure if this can be done but I been changing a lot of recipes. Especially ones like armor slots and sadly all the plates are going back in front when I CraftTweaker the recipes on a lot of armors.

If possible anyways :)

Thanks ;)

**Comment by turbodiesel4598** [comment]
Not sure this is possible, unfortunately :(
All of the recipes get registered via an event that fires at the end of pre-initialisation, and if I do it any later, then _those_ recipes wouldn't be modifiable :P
