### ISSUE TITLE
Thorium ingots not stacking in output slot of furnace from FastFurnace mod.

### ISSUE THREAD

**Issue by JayRS152** [turbodiesel4598/NuclearCraft#455]
I'm using Enigmatica 2 Expert. When I put thorium dust into the furnace it cooks one item then gets stuck. They stack everywhere else. This doesn't happen with any other ingots from NuclearCraft.

**Comment by turbodiesel4598** [comment]
As far as I can tell, all other furnaces I have tested seem to work fine. It's probably got something to do with the way FastFurnace is caching recipes, though I may be wrong. I'd say let the devs know of this, as NC isn't doing anything that's causing other furnaces to fail. Hopefully a simple change that will fix this problem :)
