### ISSUE TITLE
[Suggestion] Vacuum system and linear particle accelerator

### ISSUE THREAD

**Issue by Neuromantix** [turbodiesel4598/NuclearCraft#456]
Suggestion:
1. Vacuum system for accelerators. In-game vacuum can be like liquid. For accelerators need 2 kind of vacuum pump - forvacuum pump for low vacuum and oil/Hg diffusion pump (low tier) or turbomolecular/cryogenic pump (high tier) for high vacuum.
2. Linear accelerator/heavy ion source.
Parts: vacuum system, injector, target system, accelerator tube (longer tube - higher output beam energy), power supply system. Power supply can be high voltage (on in-game RF energy) or high frequency (in real - on magnetron and wave-guide). Injector can produced electrons (if empty) or heavy metal ion (if use metal dusts/nuggets/ingots). Target system use metal blocks for metal transmutation or rare isotope sintezis. Also it can use for electron beam furnance for super-clear or hard-molten metals.
(Sorry for mistakes)

**Comment by turbodiesel4598** [comment]
A lot of this stuff will probs make it into the mod, albeit in some cases in a slightly simplified, 'NuclearCraft-y' way ;)

**Comment by turbodiesel4598** [comment]
@Neuromantix Check out [QMD](https://www.curseforge.com/minecraft/mc-mods/qmd), an addon for the new overhaul versions of NuclearCraft if you're still interested!
