### ISSUE TITLE
Game crashes when destroying multiblock controller

### ISSUE THREAD

**Issue by LubieKakao1212** [turbodiesel4598/NuclearCraft#458]
The game crashes when i destroy multiblock controller. Crashes only with Molten Salt Reactor, Heat Exchanger and Turbine.
Crashlog: https://pastebin.com/FZ1UffWi
nuclearcraft version: 2.13e

**Comment by turbodiesel4598** [comment]
Ok, I couldn't actually recreate this, but I've put an extra safety check in to try to protect against this for the next build. If it still happens after the update, let me know!
