### ISSUE TITLE
Fission Controller not updating redstone comparator correctly (through block)

### ISSUE THREAD

**Issue by mFIND** [turbodiesel4598/NuclearCraft#460]
Redstone comparator not updating correctly, state change in controller should 'carry' through block. (You can see that mechanics if you put vanilla chest on the one side of a block and comparator on the other, as seen in second screenshot)

![2019-02-24_19 15 22](https://user-images.githubusercontent.com/6615448/53303301-0948d380-3869-11e9-982f-37cbd3355303.png)
![2019-02-24_19 22 33](https://user-images.githubusercontent.com/6615448/53303345-8f651a00-3869-11e9-8faa-b1cfd5551d0c.png)

**Comment by turbodiesel4598** [comment]
Looks like this is working fine: the comparator is [reading through the block correctly](https://i.ibb.co/tz3XN6v/2019-03-19-10-41-13.png). The comparator reads the heat level of an unstable build or the energy storage of a stable one ;)
