### ISSUE TITLE
Capability lag in ItemStack.copy()

### ISSUE THREAD

**Issue by LemADEC** [turbodiesel4598/NuclearCraft#461]
As of ProjectOzone3 3.0.38 / NuclearCraft 2.13e-1.12.2, lag is observed in 
RadiationCapabilityHandler_attachStackRadiationCapability
RadiationCapabilityHandler_attachArmorDefaultRadiationResistanceCapability

As seen on 5 mn profiling with a single player using 2 hoppers to transfer cobblestone:
![image](https://user-images.githubusercontent.com/4776032/53670527-4fdc6a80-3c7b-11e9-8c7d-fb0e3e6a2d0d.png)

It appears an hashmap is used on objects with no defined hash() method, defaulting to the slow default one.

Full profiler report is https://sparkprofiler.github.io/#cc4afQiY0S .

**Comment by turbodiesel4598** [comment]
Have improved stack capability attachment to query these stats only when asked for :)
