### ISSUE TITLE
Radiation chunk update crash

### ISSUE THREAD

**Issue by MacWhinny** [turbodiesel4598/NuclearCraft#462]
Hi, i'm having issues with the radiations update on a ATM3 Remix 1.1.0 server running forge-1.12.2-14.23.5.2814-

Here is the crash report
https://pastebin.com/Y2G6T0Eh

**Comment by turbodiesel4598** [comment]
Probably a similar proble to the one here: https://github.com/PaperMC/Paper/issues/313
Will try to sort it out!

**Comment by turbodiesel4598** [comment]
Ok, think I've fixed it for the next release :)
