### ISSUE TITLE
Fusion Reactor Won't Produce Power

### ISSUE THREAD

**Issue by AzzBlock** [turbodiesel4598/NuclearCraft#463]
I am new to this mod and have been following the mod author's handy Youtube tutorials and built my own fusion reactor in a Modern Skyblock 3 Departed world.

However I cannot get the reactor to produce any power. I have pumped hydrogen into both of the tanks of the reactor and the magnets are powered and I have powered the reactor itself. But despite this all that happens is the temperature rises to about 8000kK and then hovers around that point raising only slightly but no power is produced. It does consume power and I do have 1.5 billion RF stored and available so it doesn't run out.

In his video when the reactor reaches 8kK it turns on but mine does not.

Not sure what I am doing wrong but would appreciate any help.

**Comment by turbodiesel4598** [comment]
Hey there! Would you happen to be applying a redstone signal near the base of the core? That will deactivate the reactor if so.

**Comment by AzzBlock** [comment]
Hi. No I'm not. The temperature goes slightly over 8000kK then it stops drawing power and throttles back below that temperature then goes back up again and repeats. I've tried using Ender I/O to power it and flux points but that hasn't made a difference. It seems to receive power fine but just won't produce it.

**Comment by AzzBlock** [comment]
Just looked at the GUI and it says energy and power are both zero. On your video the energy went up when you added the power cell but mine does not. However adding power definitely makes a difference to how fast it heats up.

**Comment by turbodiesel4598** [comment]
Could you send some screenshots of the GUI and setup? From the info you've given it sounds like it should have started up.

**Comment by AzzBlock** [comment]
This image shows my setup:
![2019-03-07_15 42 21](https://user-images.githubusercontent.com/42791537/53969054-0020f780-40f0-11e9-91bd-532e0606462f.png)

This image shows the gui shortly after adding  power to the base of the reactor:
![2019-03-07_15 43 07](https://user-images.githubusercontent.com/42791537/53969055-0020f780-40f0-11e9-909d-b5f42c87ac95.png)

This images shows the state it gets to but won't heat anymore or produce any power:
![2019-03-07_15 43 48](https://user-images.githubusercontent.com/42791537/53969056-0020f780-40f0-11e9-89e9-8beab0c2e4e5.png)

**Comment by AzzBlock** [comment]
It stays above 8000kK for probably about a tick yes. However I have also tried the reactor with no cooling at all and the only difference it makes is it dramatically increases the time it takes to cycle from above 8000kK to below.

**Comment by turbodiesel4598** [comment]
Ok, so that's not it. The only two things I can think of then unless this is a bug is some rogue redstone signal, which you say there isn't, or that you're potentially using an older version of the mod?

**Comment by AzzBlock** [comment]
Fixed it! So I thought about what you said about "rogue redstone signals" and remembered that I had accidentally broken the reactor when I had a lever turned on at the base and I had noticed that when I replaced the reactor certain things did not update such as the ender I/O power cable which I had to break and replace to get it to connect again. 

So I thought maybe if I break the blocks next to the base of the reactor it could cause an update if it thinks it is still being powered by redstone and as soon as I did it started working! There was definitely no redstone there or a lever so it's the only explanation I have.

Thanks for your help and for an in-depth and interesting mod.

**Comment by Aranak** [comment]
my reactor had blow up and i have the same issue as you i have replace every single block and its stuck at 8000kk and i have break the block next to the base. I could have break the reactor while its was redstone signal.
![reactor bug](https://user-images.githubusercontent.com/44117604/54576531-f42a1500-49ce-11e9-86c4-2ceca4785725.png)

**Comment by turbodiesel4598** [comment]
@Aranak So is the temperature flickering or stuck at 7999 kK?

**Comment by Aranak** [comment]
It's flicker 7999-8010ish

**Comment by turbodiesel4598** [comment]
And there's nothing clogging up the output slots (can't be sure from the picture) or any 'ghost redstone' like in the situation above that could be keeping it off?

**Comment by Aranak** [comment]
after 2 server reset its decided to work again took at less a couple hours of down time for it to fix. Im 100% sur its not a output issue the output is empty. so could be a redstone uodate but even in destroying 3 layer of the whole chunk its was not working.

**Comment by turbodiesel4598** [comment]
I can't think of any reason it would happen other than because there is some other mod causing problems with keeping ghost redstone signals active - there's nothing else actually in the code to turn it off :P
Anyway, at least the problem went away :)
