### ISSUE TITLE
Feature Request: Nuclear Weather (like Fallout 4)

### ISSUE THREAD

**Issue by LokeYourLord** [turbodiesel4598/NuclearCraft#464]
Hey man, has been a while. Anyways, I would like to ask you if you could add a feature like the "True Storms" mod for Fallout 4, with the Radioactive Fog and that kind of Radioactive Thunder (with the halling/echo effect in the background, really really cool) to a chunk that is heavily irradiated and full of biohazards. If you need an example, it can be seen (or better yet heard) in this video from 0:32 to 0:36. Video: https://youtu.be/hvi244wzH3E?t=32

Oh and of course the yellow sky/clouds with the fog and lightnings inside the clouds would be mega cool! Of course, all of this only works if the Radiation Module is enabled (which it is on my Hardcore server & modpack :P )

Thanks for checking it out :D

**Comment by turbodiesel4598** [comment]
Hola! As much as I agree this would be awesome to have, I am really out of my depth as a mod dev with features such as this. I'll keep this up here in case I learn how to do it or someone decides to help out though :)

**Comment by LokeYourLord** [comment]
@turbodiesel4598 You could ask the Tornado mod maker to help you, he should be really good with this (not sure of his name, maybe AtomicStryker?). Anyways yeah, the idea is super cool and I am sure you could pull this off, your mod is so awesome and well made I am sure you could do this!

**Comment by utoxin** [comment]
I'm actually considering toying with doing this as part of an add-on mod, once the API is ready to go.

**Comment by LokeYourLord** [comment]
> 
> 
> I'm actually considering toying with doing this as part of an add-on mod, once the API is ready to go.

That would be cool if you get there, please let me know if you need testers, I don't mind ruining my worlds for the sake of debugging :D

**Comment by AquaticFish** [comment]
Wowzies, I would really love to see this, Minecraft and mods need more immersion, nuclearcraft's radiation affecting the landscape like trees, grass, crops, water, and weather + feel of the area would be damn amazing.

**Comment by tekker2234** [comment]
you could also ~~steal~~ get inpiration from the code used by the mod [pollution of the realms](https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms) (or just add compatability) dunno how hard that would be though.

**Comment by turbodiesel4598** [comment]
It's very unlikely that I will ever have the time to add anything like this. NuclearCraft addons have begun to emerge and perhaps someone can come along to do something fancy like this.
