### ISSUE TITLE
Allow NC mod jars to be accessible via the CurseForge maven.

### ISSUE THREAD

**Issue by Phylogeny** [turbodiesel4598/NuclearCraft#466]
Apparently, adding `--` in a jar's filename on CurseForge screws things up, and even Maven Helper utilities (like those by Wyn-Price and Darkhax) can't figure out the CurseForge maven URL for such files. No one I asked at Forge knew what the URL is for such files either.

The simple fix is to just refrain from using `--` in the filenames of future releases.

**Comment by turbodiesel4598** [comment]
Will be fixed with the next version :)
