### ISSUE TITLE
Liquid Helium Cooler Recipe Eating Tanks

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#467]
### Version
NuclearCraft-2.13e--1.12.2

### Can it be reproduced?
Yes

### Issue
Crafting a Liquid Helium Cooler using a Portable Fluid Tank and a Cooler Frame consumes the tank and all of the fluid in it. When crafting the Cooler with a Bucket you get an empty Bucket back, which is the normal behaviour, but when crafting with tanks they are destroyed.

**Comment by turbodiesel4598** [comment]
Fixed!
