### ISSUE TITLE
CCL rendering error

### ISSUE THREAD

**Issue by Cronosus** [turbodiesel4598/NuclearCraft#469]
Hello
i have this error spammed in console (i can disable it, but its still error)
https://pastebin.com/kX3GxgDy

codechickenlib + nuclearcraft

**Comment by turbodiesel4598** [comment]
Have referred this issue to the CCL devs - hopefully will be simple to prevent :)

**Comment by turbodiesel4598** [comment]
Well, unfortunately I didn't learn why the error was being thrown - the best thing to do would just be to disable it :)
