### ISSUE TITLE
hazmat suits and radiation

### ISSUE THREAD

**Issue by Cronosus** [turbodiesel4598/NuclearCraft#47]
what about radiation and hazmat suits? :)
I miss it here, so many dangerous materials and no radiation..

anyvay, nice mod, i like it :)

**Comment by turbodiesel4598** [comment]
After I've finished porting to 1.10, I hope to implement a radiation system similar to that of Fallout 4, so I guess you can look forward to that :)

**Comment by RealKC** [comment]
Expanding on HazMat suits:
1. They should also work as HazMat suits for IC2 radioactive materials.
2. They should work as the HazMat suit thingamajig from Deep Resonance.
3. If EnderIO is added, maybe have a HazMat suit upgrade for the Dark Armor?

**Comment by turbodiesel4598** [comment]
I'll see if I can do some sort of cross-compatability, but I have not worked out how to do that so far.

There have been some issues with the health-based radiation system, as it messes with other mods which alter health, so although the radiation system will stay as planned, instead of affecting health, the player will just get plagued by worse and worse status effects until they do something about it.

**Comment by xenon54xenon54** [comment]
Don't forget about radiation detection. It's probably a good idea to have a way of measuring radioactivity other than how green you're getting.
(pause for ideological rambling)
For early game radiation detection, cheap film dosimeters might lose durability with radiation exposure, and later in the game, the player can upgrade to reusable geiger counters that run on RF. Static detectors that occupy a small blockspace (like torches) can monitor the ambient radioactivity of a certain area.

**Comment by sharkbite3105** [comment]
a suggestion along with this, since this mod has craftable armor, in particular the armor made with boron, you could include some sort of radiation protection included. (Boron being a very good at absorbing neutrons IRL)

**Comment by xenon54xenon54** [comment]
Or cadmium, which is a waaay better neutron poison than boron irl, but that would need implementation. Maybe some composite armor that contains a neutron poison and lead? Graded z shielding?

**Comment by turbodiesel4598** [comment]
Radiation system added in 2.11b :)
