### ISSUE TITLE
Items fail to stack due to differing radiation levels

### ISSUE THREAD

**Issue by quaixor** [turbodiesel4598/NuclearCraft#471]
I'm playing with radiation turned off. On very rare occasions I see items that have radiation values different from the radiation values they are supposed to have. This clogs up my machines as such items don't stack with other other items of the same type. I've had this happen three times in a few weeks of play.

Just now it happened with a nugget of Neptunium 237 Oxide that clogged up my factorizer. To investigate further I put a "good" nugget and a "bad" nugget into a thermal expansion strongbox, picked it up, and examined its NBT tags using NBT Tooltip mod:

Good nugget: https://i.imgur.com/8O6qZWP.png
Bad nugget: https://i.imgur.com/kMJ539t.png

The bad nugget has a radiation level much higher than the normal nugget.
If I enable radiation (client-side only), the NuclearCraft tooltip shows 52 nRads/t for both the good nugget and the bad nugget. Seems like the tooltip is displaying the radiation value the item is supposed to have, not its actual value.

My setup looks something like this: 
Nuclear reactor -> Strongbox -> Fuel Reprocessor -> Strongbox -> Factorizer
The Factorizer got clogged up by the "bad" Neptunium-237 Oxide nugget.

I tried processing one of each depleted fuels that produce Neptinium 237 Oxide nuggets, thinking that perhaps some fuels produce nuggets with bad radiation values, but that turned out to not be the case. They all stacked.

Since this issue happens so rarely I have not been able to repro it. I suspect it might be caused by Thermal Expansion pipes but have not been able to confirm.

I don't know how the radiation value is stored (it's not an NBT tag?) so I don't know what could be going wrong. Let me know if you think this is the wrong place for the bug and I'll open it elsewhere. 

Forge 2768
NuclearCraft 2.13e
Latest Thermal Expansion, Dynamics, etc, and about 40 other mods.

**Comment by turbodiesel4598** [comment]
Thanks for the bug report - bit of a sneaky one! I've downloaded that NBT Tooltip mod, but I'm noty able to see the information you are. Perhaps there's another tooltip mod you have installed that's giving you the capability info?

**Comment by quaixor** [comment]
The NBT tooltip mod doesn't display the radiation levels of the nuggets directly. I assume this data is stored in some other way or is hidden. To see it as NBT you need to place the nugget into a container that saves its contents as NBT, and then view the NBT.

**Comment by turbodiesel4598** [comment]
For some reason I'm not able to see this capability NBT after placing the items in a strongbox and reloading, even with radiation enabled. From the pics you've sent, it looks like somehow the bad nugget NBT obtained the radiation level of a piece of Np-236, which is the same item but of metadata 0. The tooltip gets the radiation info directly from the stack capability, which is what's used to determine how much radiation is added to the world, so somehow the NBT is being saved in your case, and being saved incorrectly. As you say, recreating your setup hasn't allowed me to recreate the issue... certainly a strange one.

**Comment by turbodiesel4598** [comment]
I'm changing the way stack radiation is handled slightly for the new version which may fix this bug if it is NBT-related. Can only hope! If you'd like you can test out the new build now by [getting it here.](https://www.dropbox.com/s/aqz99zshvdabxs3/NuclearCraft-2.14c-1.12.2.jar?dl=0)

**Comment by turbodiesel4598** [comment]
@quaixor Think this actually should have been fixed by the recent changes to radiation on item stacks - it's no longer saved to NBT, so the stacking issue shouldn't be there anymore, but feel free to let me know if the problem continues and I'll reopen the issue ;)

**Comment by quaixor** [comment]
Cool! I'll let you know if it happens again.
