### ISSUE TITLE
Fusion core caused extensive server lag while player loaded the chunk

### ISSUE THREAD

**Issue by mingl0280** [turbodiesel4598/NuclearCraft#472]
- This is not a crash.
- Based on the result of LagGoggles
Result:
https://i.imgur.com/98H5vAE.png

If the player is not in the chunk and the fusion core is running, this does not happen (highly likely only less than 50μs on the core). However, if the player loaded the chunk, this will increase to approximately on one of the fusion cores, and reaches approximately 400μs.

**Comment by turbodiesel4598** [comment]
Unfortunately this is not an easy issue to fix - this will definitely be sorted in the future when the fusion reactor undergoes its overhaul, but for now unfortunately there's nothing I can do without breaking worlds :(
