### ISSUE TITLE
[Request] A way to purge/remove fluids from reactor/heat exchanger

### ISSUE THREAD

**Issue by Aridean** [turbodiesel4598/NuclearCraft#473]
Can't find any mention of this, and I very well may just be overlooking something.

My request is to (if there isn't already some way that I've overlooked) add a method to extract or flush molten salt / coolant from Molten Salt Fission Reactors, and Heat Exchangers.

Any time I try to change the type of fluids in the machines, I have to fully disassemble and rebuild the internals of the reactor and exchanger.  This is extremely time consuming and tedious.

Like I said there may be a way to do this that I have overlooked.  If that's the case then my apologies.  But if not, I feel like it would be a great addition.

**Comment by turbodiesel4598** [comment]
Would this need to be something that was automatable? If so, that might be a bit tricky. Otherwise I can add a method of removing all fluids in the components manually.

**Comment by Aridean** [comment]
No, I don't think it would need to be automatable.  Even something like a gui button to clear all fluids, or a way to pump the fluids out in reverse from how you pump them in. Unless you have another idea for a way to do this. 
Not entirely sure how tricky either of those options would be.  but obviously the least tricky to implement would be best for you XD

**Comment by turbodiesel4598** [comment]
Okay, added a small button to the GUIs of the MSR, Heat Exchanger and Turbine to clear out all fluids ;)
