### ISSUE TITLE
Melter does not accept ore dictionary for silver.

### ISSUE THREAD

**Issue by Renari** [turbodiesel4598/NuclearCraft#474]
Silver blocks from Ice & Fire mod are not accepted in the NuclearCraft Melter. Both items are registered as `<ore:blockSilver>`.

**Comment by turbodiesel4598** [comment]
This looks to be because Ice & Fire are registering items to the ore dictionary too late - they should be doing it in preInit while they seem to be doing it during init, which occurs after recipes are registered.
