### ISSUE TITLE
Active coolers use fluid when fission reactor is disabled.

### ISSUE THREAD

**Issue by RobertBouillon** [turbodiesel4598/NuclearCraft#475]
When my reactor is disabled, it still consumes liquid redstone via the active coolers.

I have a super-simple reactor with a 7x7 block of cells surrounded by a few active coolers filled with liquid redstone. I have a simple OpenComputers program that toggles the reactor based on the heat, power, and fuel.

I ran out of fuel overnight and noticed the reactor still drained my supply of redstone, even though it wasn't running. I broke the controller and replaced it (and left it disabled), came back a few hours later and it was still drinking all the redstone that was being pumped into it.

I'm not sure if this is intended behavior because I've left it disabled before and it stopped consuming coolant.

**Comment by turbodiesel4598** [comment]
Think I've fixed this :)
