### ISSUE TITLE
Some kind of radiation render error

### ISSUE THREAD

**Issue by LatentDesire** [turbodiesel4598/NuclearCraft#476]
Opened went to go look around a bit to see if I can run into any of the mod's ores. Crashed. Crashes again if I try to load world.

Here is the crash log. https://pastebin.com/1zruSsmq

**Comment by DeadSix27** [comment]
Also happens when joining a different dimension: https://gist.github.com/DeadSix27/415b146c476ef2f8dc5c9278840b6378

**Comment by turbodiesel4598** [comment]
Fixed - will get a new build out now!
