### ISSUE TITLE
1.8b Steam Fission Controller cannot have non-fluid pipes connected

### ISSUE THREAD

**Issue by dshadowwolf** [turbodiesel4598/NuclearCraft#48]
In trying the "Steam Fission Controller" I have found that, unlike the standard Fission Controller, you cannot hook up pipes to automatically place new fuel cells or remove the used ones. The only pipes that the Steam Fission Controller can be connected to are liquid ones. This makes the Steam Fission Controller basically useless, as it stops the reactor the second a single used fuel cell hits the output slot.

**Comment by turbodiesel4598** [comment]
Can't recreate this - in 1.9, at least, item, fluid and power cables hook up to it fine, and nothing changed between 1.8b and 1.9 for the steam fission controller: 
http://prnt.sc/bz2hjv

**Comment by dshadowwolf** [comment]
Captured the build of a small reactor and the pipes for a demo.  The quality is horrid and limited thanks to not wanting to spend huge amounts on software I'll only use a few times.

Anyway... I can get that same result with a standard Fission controller. It is when I attempt it with a Fission Steam controller that things do not function - things like the Fluiducts will connect to it, but no Itemduct or EnderIO Item Conduit will. (Though I have yet to try connecting something like an AE2 import or export bus to one)

Updated the mod to the just released 1.9 and this issue is gone. I do not understand this - I actually checked the code and didn't see what the issue would be before reporting this bug, but did note that there were quite a few files in the merge for 1.9 - if nothing else, perhaps there was an update to the API jar's that solved this issue ?

**Comment by dshadowwolf** [comment]
Did find something - it appears that you fixed a rather glaring issue in TileSteamProducer.java in the 1.8b -> 1.9 update window - prior to 1.9 "getAccessibleSlotsFromSide" always returned "null".

**Comment by turbodiesel4598** [comment]
Well, I stand corrected then - consider that another fix!

**Comment by dshadowwolf** [comment]
I do consider it a fix - and a good one. I'm updating to using 1.9 for that reason :) Thanks for the work - this mod is better than the alternatives.

**Comment by turbodiesel4598** [comment]
No problem! Have fun with the logistics of the new fission fuel mechanics - even I haven't quite worked out the best way to do it yet :P
