### ISSUE TITLE
2.14a, Crash upon loading world

### ISSUE THREAD

**Issue by RikkoFrikko** [turbodiesel4598/NuclearCraft#482]
I updated from 2.13e to 2.14a, I had the same crash with the 2.14 version but didn't report because I saw someone else post a similar crash. I assumed it was the same thing, apparently not. Whenever I try to load up my existing world or even create a new world, it crashes. Crash log below:

https://pastebin.com/CJPUgUUE

I see something about an IC2 reactor but I don't have IC2 installed and I've never had it installed.

**Comment by turbodiesel4598** [comment]
Yes, this is just a mistake I made in not checking to see if IC2 is installed before running a particular segment of code - will get a new build out shortly :)

**Comment by turbodiesel4598** [comment]
Fixed for the next build which will go live shortly :)

**Comment by RikkoFrikko** [comment]
Nice!!! Looking forward to it, I really like your radiation feature and when I saw you turned the Geiger counter into a baubles item I was ecstatic, can't wait to try it out!
