### ISSUE TITLE
[Crash] 2.14a compatibility issue with Prefab

### ISSUE THREAD

**Issue by mr-poyo** [turbodiesel4598/NuclearCraft#483]
Hello,

I am receiving the following crash when loading 2.14a with the Prefab mod in my pack (https://pastebin.com/tgjM8j3B). I've tested a new project to ensure that it isn't any other mods:

![image](https://user-images.githubusercontent.com/11811815/54862661-34550480-4cfb-11e9-8620-dbe9c00be65e.png)

The previous version 2.13e does not crash with Prefab. Hope this helps and thank you!!

**Comment by turbodiesel4598** [comment]
Bit of a sneaky one - fixed for the next build :)
