### ISSUE TITLE
[1.12.2] Heat Exchanger isn't working

### ISSUE THREAD

**Issue by ToMe25** [turbodiesel4598/NuclearCraft#485]
I have build a Molten Salt Fission Reactor with a Heat Exchanger and a Turbine, but as the Heat Exchanger wasn't working i have tested some more things with them.

Than i have build a Heat Exchanger like the one from the NuclearCraft Spotlight - Heat Exchanger [1.12.2].

Nuclear Craft Version:2.14a

Other Mods used:
Code Chicken Lib 3.2.2.353,
CoFHCore 4.6.2.25,
CoFHWorld 1.3.0.6,
Just Enough Items 4.15.0.268,
Redstone Flux 2.1.0.6,
Thermal Dynamics 2.5.4.18,
Thermal Expansion 5.5.3.41,
Thermal Foundation 2.6.2.26

**Comment by ToMe25** [comment]
It was not working means it was not putting the Fluids in the Heat Exchanger Tubes.

**Comment by turbodiesel4598** [comment]
Fixed for the next version :)
