### ISSUE TITLE
Electromagnets not powering

### ISSUE THREAD

**Issue by DaStormDragon** [turbodiesel4598/NuclearCraft#486]
I'm setting up a fusion reactor, but when I hook up power to the electromagnets they only occasionally power for a few seconds, and the power doesn't spread to others (I have the config option on)

**Comment by turbodiesel4598** [comment]
Which version of  the mod are you playing with? How much power are you feeding them?

**Comment by DaStormDragon** [comment]
2.14b, and I'm using a vibrant capacitor bank with however much output 98 blocks give, though I've tried different power sources

**Comment by turbodiesel4598** [comment]
Did you build the actual toroid ring a while back, or only just now? Have you got any screenshots of the setup?

**Comment by DaStormDragon** [comment]
Only just now. Size four toroid, transparent on top and bottom. I'll get a screenshot in the morning.

**Comment by turbodiesel4598** [comment]
Any luck?

**Comment by DaStormDragon** [comment]
Got distracted making a cheese mining operation and a gourmet venison burger factory. Will check in a mo.

**Comment by turbodiesel4598** [comment]
No no please, cheese-mine away. You have the priorities in check.

**Comment by DaStormDragon** [comment]
![image](https://user-images.githubusercontent.com/40438827/55097216-552ea880-50b3-11e9-90a1-9926aca0a485.png)

Tried other power conduits, no luck

**Comment by turbodiesel4598** [comment]
Could you try breaking and replacing them?

**Comment by DaStormDragon** [comment]
Tried a few times - no luck

**Comment by turbodiesel4598** [comment]
Do you have WAILA or TheOneProbe installed? If so, looking at the e-magnets should tell you how much power they have.

**Comment by DaStormDragon** [comment]
They seem to be getting trickles of power, but whenever they turn on they lose a bunch and turn off. Any idea why the cryo-stabilised fluxducts aren't transferring enough power?

**Comment by DaStormDragon** [comment]
Update: more often when I add a loop touching all of a row - the electromagnets seem to have a limitation on the power they'll accept from a conduit

**Comment by turbodiesel4598** [comment]
Yeh, that's what I suspected - the reason I was asking about breaking and replacing is because that was a bug a while back. I can't recreate the problem though. Have any other configs been changed from their defaults?

**Comment by DaStormDragon** [comment]
Regenerated the config file - no luck. Electromags get up to around 16k rf, power up for a moment, then go back to 0 rf and shut down.

**Comment by DaStormDragon** [comment]
Oops - breaking and replacing the electromags seems to work, thought you meant the power conduits *facepalm*

**Comment by turbodiesel4598** [comment]
Sorry, I should have been clearer. Well, for some reason you encountered an old bug, but I'm really not sure how :P
Is it sorted then? I guess this issue can be re-opened if you run into it again.

**Comment by DaStormDragon** [comment]
Yeah - sorted
