### ISSUE TITLE
Radiation Scrubber not working

### ISSUE THREAD

**Issue by LokeYourLord** [turbodiesel4598/NuclearCraft#487]
So I have an issue with the Radiation Scrubber. I watched the video tutorial on how to use it, however it has no effect on the polluted chunk at all, even when placed far up and apart from things and powered, the Radiation Removal Rate = 0 at any given time. Screenshot: 
![2019-03-23_17 47 17](https://user-images.githubusercontent.com/5807595/54869068-e4764c00-4d93-11e9-9178-5717ef6ebd6b.png)

Please advise for further steps to fix this. Thanks.

**Comment by turbodiesel4598** [comment]
Which version of the mod are you playing with? Is that 61 nRads/t of radiation latent chunk radiation or coming from your inventory?

**Comment by LokeYourLord** [comment]
> 
> 
> Which version of the mod are you playing with? Is that 61 nRads/t of radiation latent chunk radiation or coming from your inventory?

I am playing with 2.13e on 1.12.2 and yes, that is from the chunk, not inventory.

**Comment by turbodiesel4598** [comment]
Ah - if you update tho the latest versions of the mod, the scrubbers will work properly, although as you may see others have pointed out issues with these versions, which I'm trying to get to now ;)

**Comment by LokeYourLord** [comment]
The issue still persists, please reopen. I updated to the latest version both server and client side, still removes 0 rads per tick even though I purposely heavily irradiated the chunk the scrubber is placed in.

**Comment by turbodiesel4598** [comment]
So the tooltip still states that it's removing 0 Rads/t at an efficiency of 97%?

**Comment by LokeYourLord** [comment]
> 
> 
> So the tooltip still states that it's removing 0 Rads/t at an efficiency of 97%?

That is correct, even with 1mRads/t in the chunk it is in.

**Comment by turbodiesel4598** [comment]
Have you tried breaking and replacing or waiting for the scrubber to update?

**Comment by LokeYourLord** [comment]
> 
> 
> Have you tried breaking and replacing or waiting for the scrubber to update?

Yeah tried all of that, I have replaced it many times and waited multiple hours sometimes for it to update, does nothing still.

**Comment by LokeYourLord** [comment]
I can do any debugging necessary, tell me what and I do it, if you have a debugging/verbose enabled version of the mod, or if there is a config toggle, then tell me and I do what is needed :D

**Comment by turbodiesel4598** [comment]
Are you playing a pack on the Twitch launcher or through MultiMC that you could send to me? I don't really know what more I can ask for given that I can't recreate the problem.

**Comment by LokeYourLord** [comment]
> 
> 
> Are you playing a pack on the Twitch launcher or through MultiMC that you could send to me? I don't really know what more I can ask for given that I can't recreate the problem.

Yeah I am playing my own modpack as a matter of fact on the Technic Launcher, look for "Stargate Galaxy", that should do it :D

**Comment by turbodiesel4598** [comment]
I've downloaded your pack, created a new world and placed a scrubber down - [it seems to be working fine for me](https://i.ibb.co/r0gqq2T/2019-03-24-15-41-02.png). Are there any actual radiation sources in the chunk? The scrubber will lower the radiation level by quelling the radiation produced by sources. If there are no sources, the scrubber will show 0 Rads/t, but the radiation level should drop. I'll add extra scrubbing from the current radiation level - that should sort the confusion :)

**Comment by LokeYourLord** [comment]
Oh I see, so if there are no active sources, then it will show 0? Alright, yeah that is why I always think it does nothing XD

**Comment by turbodiesel4598** [comment]
Issue resolved perhaps, but in the future it'll be much more obvious that something's happening. Thanks for the heads up!
