### ISSUE TITLE
Forestry farm broke due to radiation NBT

### ISSUE THREAD

**Issue by SSKirillSS** [turbodiesel4598/NuclearCraft#489]
After upgrading to the latest version of NuclearCraft, stopped correctly working farms from forestry. Mineral fertilizer is simply not put in the right slot. Quite a strange mistake, I do not even know what to write.

After removing NuclearCraft farm again worked normal.

NuclearCraft-2.14b-1.12.2
forestry_1.12.2-5.8.2.387
binnie-mods-1.12.2-2.5.1.188
spongeforge-1.12.2-2768-7.1.6-RC3616

![image](https://user-images.githubusercontent.com/38190325/54872931-3099ae80-4ddd-11e9-80d8-b7318a2caab6.png)

**Comment by turbodiesel4598** [comment]
This is an issue related to the saving of radiation-related NBT data on items. Looking for a solution now ;)

**Comment by turbodiesel4598** [comment]
@SSKirillSS [Could you see if using this build fixes the problem?](https://www.dropbox.com/s/aqz99zshvdabxs3/NuclearCraft-2.14c-1.12.2.jar?dl=0)

**Comment by SSKirillSS** [comment]
Yeah, fixes.

**Comment by turbodiesel4598** [comment]
Awesome :)
