### ISSUE TITLE
Update 1.9 Wiped Machines' Inventories

### ISSUE THREAD

**Issue by QuantumTraverse** [turbodiesel4598/NuclearCraft#49]
In my world, after updating to 1.9, all the fuel cells, neutron capsules, various upgrades, etc. inside of any machine from helium collectors to electrolysers disappeared upon loading the world. Nothing difficult for me to hack back in, but an odd bug.

**Comment by turbodiesel4598** [comment]
Well, I didn't think about that as much as I should. I renamed some of the tile entities to try to deal with some conflicts, and in the process the tile entities were clearly reset. I apologise for the inconvenience!
