### ISSUE TITLE
Radiation NBT TiC Issue

### ISSUE THREAD

**Issue by mr-poyo** [turbodiesel4598/NuclearCraft#491]
**Update:** My apologies, it looks like this is a duplicate post #488 

Hello,

I am experiencing a Tinkers construct Stencil Table bug with the latest Nuclearcraft

![image](https://user-images.githubusercontent.com/11811815/54878820-18756e00-4e75-11e9-959c-ecc52fb14bb8.png)

When loading 2.14b with tinkers, I am unable to create patterns with the stencil table as seen below:
![image](https://user-images.githubusercontent.com/11811815/54878772-92592780-4e74-11e9-85df-829c11b31f84.png)

However, if I switch to the old build, 2.13e as seen below, it works:
![image](https://user-images.githubusercontent.com/11811815/54878807-dba97700-4e74-11e9-958d-92b89adf6791.png)
![image](https://user-images.githubusercontent.com/11811815/54878812-fd0a6300-4e74-11e9-99ef-0dfd47fdf8fc.png)

Hope this helps with the development / bug fixes! Thank you as always!

**Comment by turbodiesel4598** [comment]
This has already been reported and in fact this is a much broader issue - I'm looking into a solution now :)

**Comment by turbodiesel4598** [comment]
@mr-poyo [Could you see if using this build fixes the problem?](https://www.dropbox.com/s/aqz99zshvdabxs3/NuclearCraft-2.14c-1.12.2.jar?dl=0)

**Comment by turbodiesel4598** [comment]
Should be fixed in the latest build :)
