### ISSUE TITLE
Crash when radiation is enabled. IC2 Reactor 

### ISSUE THREAD

**Issue by trygve55** [turbodiesel4598/NuclearCraft#493]
After I updated to 2.14a I enabled radiation in the config. With this the game crashed when loading a world. It seems like Nuclearcraft is trying to interface with IC2 without it being present. I found a possible similar issue from OpenComputers linked below. I will try to isolate which other mod is causing the issue tomorrow.

Crash log:
https://pastebin.com/hSb0S9Jx

Possible related issue:
https://github.com/MightyPirates/OpenComputers/issues/567

**Comment by turbodiesel4598** [comment]
This should be fixed in version 2.14c :)

**Comment by trygve55** [comment]
Thanks, I love this mod and the radiation system makes it so much more immersive. :)

**Comment by turbodiesel4598** [comment]
Thanks very much!
