### ISSUE TITLE
[Suggestion] Config entry to adjust Manufactory planks / sticks output

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [turbodiesel4598/NuclearCraft#494]
I don't know whether this is too niche of a suggestion, but I personally think it'd be a good idea if I was able to set the amount of planks or sticks given by the Manufactory when grinding down wood  via an option in the NC config file.

This could make adjusting something as little as wood outputs to a pack's progression a lot easier to packmakers, as they would then be able to specify how much stuff a player is able to get from a certain resource at what part in the pack. ^^

**Comment by turbodiesel4598** [comment]
Added!
