### ISSUE TITLE
Server Crash on 2.14c 

### ISSUE THREAD

**Issue by RobertBouillon** [turbodiesel4598/NuclearCraft#495]
Crash log attached - https://pastebin.com/nxzuXr0w

**Comment by RobertBouillon** [comment]
Upgraded server from 2.13e. Also failed with the original 2.14.

This was added manually to the FTB Rev 2 pack 2.7.0. No other custom mods.

**Comment by turbodiesel4598** [comment]
I could not recreate this - I dowloaded FTB Rev, unlocked the profile, added v2.14c and the game loaded fine, as expected really. The server also loaded correctly and I was able to connect. That looks like a very bizarre crash that really shouldn't happen, so something funny's happened somewhere that is beyond my control. Unfortunately I really don't know what would have caused this :\
