### ISSUE TITLE
[Suggestion] OR-ing IIngredients in CrT support

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [turbodiesel4598/NuclearCraft#497]
Very, very minor thing, but I recently noticed that I can't make recipes look as neat and tidy as the internal ones you've got without manually adding one recipe for each possible input type (e.g. with stainless steel, it'd be either a steel ingot + a custom dust i made or steel blend + a custom dust i made)

Again, very very minor, but still would be nice to have ^^

**Comment by turbodiesel4598** [comment]
Hey there! I've asked the CT devs about the possibility of this - I'll let you know if it's possible, and if so, I'll get it added :)

**Comment by MaxNeedsSnacks** [comment]
Woot! Thanks a ton, hope you'll be able to figure something out ^^

**Comment by turbodiesel4598** [comment]
And luckily CT have native support for such recipes! Added for the next build which should arrive very shortly :)
