### ISSUE TITLE
Fission reactor changing fuels does not start new fuel until open the GUI

### ISSUE THREAD

**Issue by Rue82** [turbodiesel4598/NuclearCraft#498]
I am trying to automate my fission reactor to allow it to burn server fuels that i have reprocessed to try and be efficient with my resources.  When on fuel burns up and I try and pump in the next one the reactor will not start back up until i look in the GUI which kind of defeats the purpose of automation.  Please let me know if this is enough information.  I am Playing the Enigmatica 2 Expert Skyblock

**Comment by turbodiesel4598** [comment]
Hey there - which version of NuclearCraft is this?

**Comment by Rue82** [comment]
2.13e it is what the pack is currently running. sorry forgot to put that in the post

**Comment by turbodiesel4598** [comment]
Could you try NC 2.14c (the latest build)? I don't seem to be able to recreate this issue.
