### ISSUE TITLE
Steam Fusion Reactor

### ISSUE THREAD

**Issue by 6210classick** [turbodiesel4598/NuclearCraft#50]
hello, i found what might be a big issue in v1.9.

when the steam fusion reactor runs out of fuel or the conduit/pipe/tank ..etc is removed or the fluid storage is filled up it will start voiding steam and will not store it in the Reactor whenever it reaches 400,000mn until the the conduit/pipe/tank ..etc is connected back again or the fluid storage is emptied.

so in short the reactor will not store steam inside it and will instead void it whenever it reaches 400k mb unless the steam is being stored/ or used externally

PS : i don't know if this is intended but the reactor will only output 200mb of dense steam when the internal storage reaches 400,000mb of steam

**Comment by turbodiesel4598** [comment]
This is now fixed as of 1.9b :)
