### ISSUE TITLE
More GregTech integration

### ISSUE THREAD

**Issue by Firew0lf** [turbodiesel4598/NuclearCraft#500]
I've started tweaking every NuclearCraft recipe to use GTCE's machines instead of NC's (because I like integration), but there are way too many...

Would it be possible to add an option to disable all NC machines and add the recipes to GregTech instead ? It is already in the dependencies, and adding recipes is pretty easy (GregicAdditions has some examples for this). Only the recipes involving NC stuff tho, as most other things are already integrated (ingot to molten metal and such).

**Comment by turbodiesel4598** [comment]
I don't think I'll do this unless written as a PR, because although the recipe API may be good (I haven't used it before), it would probably still take a little while to implement, and I'm a bit short on time right now which I need to dedicate to more fundamental mechanics of the mod. So yes, I'll leave this here, but I don't know when I'll get to it!

**Comment by Firew0lf** [comment]
I'll give it a try.

![a try](https://uc17813c591aa92fc97da304da99.previews.dropboxusercontent.com/p/thumb/AAYx3Fr68fzi-CyU3dGBmDZNZokjFTm2aly8O3dv3ZdNGdCjm9AnK4uQuXSYRyzK0BqgjGjft-K8euBd8hp9WNqtidDduSqRIdEW-6uQ_uyxwtEVn-5XXjeLGxvoW3e4xT17Yngc6MUFZDsbWVpl7515CjZIgLU6GycPLFtlKFIRE_3t_IquXHnscTh5m638g3cDCZdVwR61UIpQeIF1ju4xDw5KPbsAdzVdrzHCZEUuLy32lpPenYwcwMct6hVTrSieIE1qjeuQk--xM50qQgVq-kwCvBQS6z0UnZyRP5gW9rPMOs6-mHRG_R5Izvu4alW3cXiCFWM9tPMpJrbrFmoMH7kQDzLYrRlys0Pu8eYSLMEBFM4MfiIBC1c0s-TvZFI/p.png?size_mode=5)

Btw, what scale are you using for `time` and `power` ?

**Comment by turbodiesel4598** [comment]
That would be awesome! The time and power variables are multipliers of the base processing time/power of the machine, which can be found in the configs :)

**Comment by Firew0lf** [comment]
I pushed some code for recipe integration on my fork, never done anything like this so I'd like to know if it works on your side... Also I'm gonna need your help for reading the config class, there are *way* too many fields x) .

**Comment by turbodiesel4598** [comment]
Wow, you've done a fantastic job! There are gonna be a lot of happy GTCE players if your work goes to plan.

I'll move over your addition to the active code, and of course credit you on release :)

I'll play around with it a bit - see if there are any duplicates, etc., then get a release sorted.

**Comment by Firew0lf** [comment]
Thanks ! I just optimized the code a bit (didn't find any machine/recipe without exactly 2 extras).

**Comment by turbodiesel4598** [comment]
Also added some code to check through all potential ingredient clashes to prioritise GTCE recipes :)
