### ISSUE TITLE
CraftTweaker integration fails to remove by output when using ore dictionary

### ISSUE THREAD

**Issue by CerulanLumina** [turbodiesel4598/NuclearCraft#501]
When using removeRecipeWithOutput with an ore dictionary tag, an error is returned to CT.
This occurs only in 2.15, rolling back to 2.14c fixes the issue.

This seems to only occur when there are multiple entries for a given oredict key.

CraftTweaker script: https://hastebin.cerulan.net/bugosiqavu.css
crafttweaker.log: https://hastebin.cerulan.net/jesufejixi.md

**Comment by turbodiesel4598** [comment]
Fixed for the next release :)
