### ISSUE TITLE
Same fluid in both input slots of a machine

### ISSUE THREAD

**Issue by PatchyKnowly** [turbodiesel4598/NuclearCraft#502]
If the first slot of a chemical reactor is empty, and the second slot has fluid A in, attempting to insert fluid A with a bucket (or jerrycan) will put fluid A into the first slot, instead of stacking with the fluid already in the second slot. Haven't tested with pipes. Also applies to the salt mixer and presumably any two-liquid-input machines. 

Tested with the chemical reactor using fluorine and water, and the salt mixer using boron-11

Steps to reproduce:
1. Obtain two buckets of water and one bucket of nitrogen
2. Add the nitrogen bucket to an empty chemical reactor
3. Add a water bucket
4. Clear the slot with the nitrogen
5. Add the second water bucket
6. If done correctly, there should now be 1000 mB of water in both slots

Tested on 2.14c, but it wasn't mentioned in the changelog for 2.15.

![190414-01 23 02](https://user-images.githubusercontent.com/8378762/56086729-f3ad5e80-5e54-11e9-95a9-f117814db1ab.png)
![190414-01 23 17](https://user-images.githubusercontent.com/8378762/56086731-f4de8b80-5e54-11e9-873f-6333f500beca.png)
![190414-01 43 45](https://user-images.githubusercontent.com/8378762/56086833-c3ff5600-5e56-11e9-93fc-e39f95cc9f91.png)

**Comment by turbodiesel4598** [comment]
Think this is fixed for the next release ;)
