### ISSUE TITLE
Alloy furnace ejects ingredients on SpongeForge

### ISSUE THREAD

**Issue by bluelightning32** [turbodiesel4598/NuclearCraft#504]
Version info:
* Modpack: DD&SS version 4.10a
* NuclearCraft-2.15-1.12.2.jar
* forge-1.12.2-14.23.5.2822-universal.jar
* spongeforge-1.12.2-2768-7.1.6-RC3629.jar

The alloy furnace accepts the first ingredient. When the second ingredient is placed in the alloy furnace, 9 out of 10 times it just ejects both of them without alloying them. If I repeatedly pick up the ejected items and shift click them back into the alloy furnace, it eventually accepts them.

The bug does not reproduce in single player, and the bug does not reproduce when I remove sponge.

The below image shows the ejected tin and copper.
![image](https://user-images.githubusercontent.com/21202621/56559768-5e4a5280-6557-11e9-8fdd-99e1a374dd9d.png)

**Comment by turbodiesel4598** [comment]
Looking at [this issue](https://github.com/SpongePowered/SpongeForge/issues/2644) posted in the SpongeForge repo a month or so ago, it looks like this was a small issue on SF's side. Either it is fixed in later versions or you'll need to downgrade if the problem still persists.

**Comment by bluelightning32** [comment]
Oh thanks. Sorry I didn't search there first.

**Comment by turbodiesel4598** [comment]
No worries!
