### ISSUE TITLE
Update to new versions?

### ISSUE THREAD

**Issue by BlueCreeper160** [turbodiesel4598/NuclearCraft#508]
Forge 1.13 is available, soon will be available forge 1.14, Why there isn't updates to these versions?

**Comment by turbodiesel4598** [comment]
The simple reason is because 1.13 will almost certainly be skipped by modders, and Forge for 1.14 is still in the alpha stages. It will be a little while before I start making the move!

**Comment by miiichael** [comment]
What's the likelihood of a 1.15 version? :sweat_smile:

**Comment by turbodiesel4598** [comment]
Still a while until one yet as the overhaul for 1.12.2 is still in development :)

**Comment by Colonizor48** [comment]
Bump because 1.17.1 is 100% stable at this point.

**Comment by ab9rf** [comment]
> Bump because 1.17.1 is 100% stable at this point.

That's a ludicrous statement. There isn't a stable release of Forge for 1.17.1 yet, and the most recent unstable release has six open acknowledged issues on Forge's github.

**Comment by Colonizor48** [comment]
Then atleast 1.16.5. But ive seen perfeclty working 1.17.1 modpacks with forge so.
