### ISSUE TITLE
Californium RTG issue

### ISSUE THREAD

**Issue by spannerman79** [turbodiesel4598/NuclearCraft#51]
Forge 1614
NuclearCraft-1.9a--1.7.10
Java 8 u102
MultiMC Log https://gist.github.com/spannerman79/181580556dbc93d3ac0f5eb68afab2d1
Standard generated configs (created new instance within MultiMC - no other mods or tweaks added)

When breaking the Californium RTG with either a diamond pickaxe or even a NC paxel the block dropped is a Plutonium RTG

Is this intended behavior?

**Comment by turbodiesel4598** [comment]
This is now fixed as of 1.9b :)
