### ISSUE TITLE
Client crashes on adding Manufactory log recipes

### ISSUE THREAD

**Issue by thehypertext** [turbodiesel4598/NuclearCraft#510]
When I start my client, it simply just crashes with this log:

https://pastebin.com/raw/5MUUhj9b

**Comment by turbodiesel4598** [comment]
I don't seem to be able to recreate this - are you able to recreate it using a client profile without so many other mods?

**Comment by thehypertext** [comment]
The problems seems to be related to a Flan's Mod Content Packs, which is making trouble with NuclearCraft.
