### ISSUE TITLE
Enhancement Request: Config option to disable Fission Reactor comparator signal for stable builds

### ISSUE THREAD

**Issue by scotty9090** [turbodiesel4598/NuclearCraft#511]
Based on #379 it looks like a Fission Controller now outputs a signal related to the energy in the buffer, rather than the heat level, for a stable build.  I'm trying to run a breeder setup specifically for the purpose of creating RTGs that runs a variety of fuels - so sometimes the reactor is stable, other times it isn't.  I'd prefer to be able to keep the reactor going even if it would be voiding energy but with the current behavior I can't see a way to do this and still preserve the ability to shutdown the reactor to throttle heat.

Would it be possible to add a config option to revert the comparator behavior to the way it used to work and only detect heat level?

**Comment by turbodiesel4598** [comment]
Certainly can :)

**Comment by scotty9090** [comment]
You're the best!

**Comment by turbodiesel4598** [comment]
Added for the next build ;)
