### ISSUE TITLE
NC machines sporadically not behaving well with Ender IO conduits on a server

### ISSUE THREAD

**Issue by AwesomeLikeThis** [turbodiesel4598/NuclearCraft#512]
I have a 100% Active Cooling Rate [5000 K/t] Fusion reactor with a toroid size of 6. I'm using Deuterium and Tritium, and they can keep up with the fuel demand (I never run out of fuel). I am also cooling it with 14 active coolers (lol), 12 of them water, and 8 of those are in opposite corners. The other two are liquid helium coolers. All in all, it sums to 100% active cooling rate.

But the issue is that when my reactor runs for a long time, it still overheats. I managed to watch this happen as the temperature change started to INCREASE when I'm cooling, which should never happen past 100% efficiency. Even still, I let it run for a couple more hours and when I came back, the efficiency was 67% and temperature change was rising. 

Now I don't know if I don't understand how cooling works fully, but from what I could gather, the cooling rate % signifies how efficient your reactor is going to be in the long run, with cooling deviating from 100% hurting efficiency. 

This is occurring on the 1.6.2 version of Enigmatica 2 Expert series, which is running NuclearCraft-2.15-1.12.2.jar (I don't actually know which one is the version number). 

I also browsed through and could not find anyone with the same issue as me, which is why I think I may be missing something.
Any help would be greatly appreciated! Just say if you need pictures, videos, etc.

On a side note, my ender fluid conduits don't seem to be extracting fluids after a long time of continuously transferring fluids, but that's for a different thread.

**Comment by turbodiesel4598** [comment]
Sounds like your setup should work. When you say "past 100% efficiency", you didn't only start active cooling once it was at this stage, did you? Also you mention you think there may be a problem with your fluid conduits - is it possible that for some period of time the active coolers weren't receiving any fluid, causing the heat to rise over the 100% efficiency point?

**Comment by Fred-104** [comment]
I'd like to contribute to this as I'm experiencing a similar issue. I'm using the Skyfactory4 4.0.5 on a private server. Ever since updating to 4.0.5, my fusion reactor has begun exploding on login. Reactor is size 3, running on hydrogen-hydrogen. Fuel supply isn't an issue; cooling is water-based, using nuclearcraft dense water sources connected to active coolers directly (one source per cooler). Output liquids go to a mekanism tank but are also set to void if necessary. When I login the temp is down to zero efficiency (what you get at the start of the reaction) and flickers as the reactor explodes in fire.

**Comment by turbodiesel4598** [comment]
@Fred-104 Sounds like something different there - your e-magnets aren't getting enough power.

**Comment by Fred-104** [comment]
Really? I thought they were (my battery has billions stored and millions transfer rate) but I'll have to look into it more closely. Is there some kind of documentation website that I can look at for this kind of info? (I'd love to see fuel stats and equations for fission/fusion reactors too.)

**Comment by turbodiesel4598** [comment]
@AwesomeLikeThis So the issue is just that, for some reason, the fluid was not getting to the coolers. Do you know whether the issue is at the coolers' end (i.e. not accepting the fluid) or the machines' end (i.e. not pulling out the water/liquid helium)?

**Comment by turbodiesel4598** [comment]
@Fred-104 Pretty much all the info you _need_ is on the tooltips of the relevant items/blocks - that foes for the fission fuels and reactor components too. As long as the e-magnets get the power they require, they'll stay active and won't fail when the plasma comes into contact with them. For fusion, there are other equations to do with the efficiency and so forth that the player doesn't see, but it's not that interesting.

**Comment by Fred-104** [comment]
I’m mainly interested in knowing how Fast reactors burn fuel. JEI gives a number but doesn’t say how the fusion reactor size affects it, and timing is difficult because my game (and the server) don’t run at consistent speeds. Is it as simple as (default time) x 1/(toroid size)?

**Comment by AwesomeLikeThis** [comment]
Yeah, the issue is that at some point, the fluid doesn't reach the cooler and the temp goes past the 100% efficiency mark. Before I go on though, once my reactor was too hot and it was losing efficiency, it was still gaining heat when it was 100% cooled. Is this intended?


But the actual problem, I believe, is inserting into the active cooler AND extracting from the super cooler (which means no cooling so an overheat), and I think all nuclearcraft machines that take fluids (using ender fluid conduits).

 I popped into a creative world, and set up a bunch of electrolyzers to run forever and after a few hours they were all stopped even though they were feeding straight into liquid trash cans using those ender fluid conduits. I did the same with supercoolers and liquid helium and once again, the fluid stopped extracting eventually. You can of course test this for yourself, just simply:

1.
Set up an electrolyzer (or a lot depending on how long you wanna wait)
2.
Pump fluids in and out with ender fluid conduits, (from a creative tank into the electrolyzer to a liquid trash can as an example)
3.
Give it a couple hours. 

Realizing now you probably don't have this sort of time and I can't exactly record for 3 hours, I'll record a short clip the next time things get clogged demonstrating that liquid should be extracting/inserting when it's not. I'll post a link to the YouTube video once I catch it doing it.

Also, I do not know if it's ender io's fault with some weird interacting with nuclearcraft, or if it's nuclearcraft having issues with ender io.

It may be worth noting that ender fluid conduits don't have an internal capacity of fluid and may be the cause of some weirdness.

Also thanks for trying to help, lots of mod devs that don't care/too lazy i.e, "use a different conduit" or something

**Comment by turbodiesel4598** [comment]
@Fred-104 Yep, that's exactly it - base time divided by toroid size ;)

@AwesomeLikeThis Yeh, that's intended - just how fusion works at the moment, but in the near future the whole system's being stripped up and totally revamped :)

I've got some maths to do for the next few hours, so I'll leave the game running in the background to see if anything breaks - a pretty annoying issue if it does indeed happen, so best to sort it!

**Comment by turbodiesel4598** [comment]
@AwesomeLikeThis By the way, what exactly do you mean by 'clogged'? Do you mean the output fluid (such as the liquid helium) just sits in the supercooler?

**Comment by AwesomeLikeThis** [comment]
yes, its just chills in there (ha) even though the active cooler or something is empty.

Also, i've been using integrated dynamics to try and keep the reactor from overheating without the big giant redstone comparator setup and just read the heat directly, but I don't think theres a heat nbt tag for it, is there? I may just be blind lol.

**Comment by turbodiesel4598** [comment]
Ok  - well, so far I've been running ten upgraded electrolysers and supercoolers and they haven't stopped running yet. I don't really know why they would anyway tbh.

And if you want to use ID to read the core, you probs need to read the bottom-centre block, as the rest are just dummies ;)

**Comment by AwesomeLikeThis** [comment]
Thanks, bottom block it is. Also you are using the ender fluid conduits right? I also did mention I'm running this on a server right?
BTW, I chunkloaded my setup and i went exploring for a bit when I was in creative because I was a little bored, maybe the chunkloading may have something to do with it?

**Comment by turbodiesel4598** [comment]
Yep, ender fluid conduits. Whether it's running on a dedicated server or not shouldn't matter, and I don't see why chunkloading would be the issue, especially if it was chunkloaded anyway.

**Comment by AwesomeLikeThis** [comment]
I'm sure that the coolers were completely empty, and the problem would be fixed if you turned off extract and turned it back on. It happened again, but I will definitely record a small clip to show. It's what I should've done from the start.

I also have another theory for the cooling.. maybe the active cooling isnt actually 100% and is off by some small fraction but rounds when displayed and over time the temperature goes past 100%

**Comment by AwesomeLikeThis** [comment]
I finally got a clip of the conduits not working right. Happened just now as I went to check on the reactor. Hadn't touched it at all since yesterday and everything was working fine until now.

Heres the link:
https://youtu.be/CYLxZLDSg4Y

(note: its not finished uploading when I posted this link and/or it may have crappy quality but give it some time)

**Comment by turbodiesel4598** [comment]
That defo is strange, but I have a feeling it may have something to do with the conduits in some subtle way. I noticed that the electrolyser updated or turned on again when you entered the fluid filtering GUIs, which leads me to suspect that something about your setup is causing the conduits to try to push/pull the wrong fluids to/from the electrolyser. This will require a proper debugging in-dev, because unfortunately I don't know enough about how EIO conduits work internally to figure out what's going wrong.

**Comment by AwesomeLikeThis** [comment]
this has happened without any filters in the way before, i will try to catch this and post a video also. It's literally just 2 conduits. I also dont think that its the conduit because when the fluid wasnt extracting nothing was going into the electrolyzer either. Both input and output was broken.

**Comment by turbodiesel4598** [comment]
Cheers - an isolated example may be more useful, as I'm still unable to reproduce it :P

**Comment by AwesomeLikeThis** [comment]
just logged in to see my fusion reactor off, my base out of juice, but the fusion reactor still has fuel

**Comment by AwesomeLikeThis** [comment]
which makes no sense. If it overheated (which it wont because of my integrated dynamics system)
it would eat all the fuel and then die.
which means the only explanation is that the fuel was put in after my base already died, which means that deuterium somehow wasnt making it in until the reactor went below the 800MK threshold

**Comment by turbodiesel4598** [comment]
Could you perhaps try updating to the latest build, v2.16f? Maybe these issues were occurring in older versions and no-one told me about them...

**Comment by AwesomeLikeThis** [comment]
I'll update and put this on a single player and duplicate the setup, but I can't change the version of the server as I don't own it. It may take a while so I'll get back to you as soon as I have something. 

It's annoying because it seems to happen at completely random intervals.

**Comment by turbodiesel4598** [comment]
@AwesomeLikeThis would you happen to know if there's a bad tps rate on the server? `/cofh tps` should be able to tell you if there is.

**Comment by AwesomeLikeThis** [comment]
Ah yes. Overall it's good 20 tps but there are spikes sometimes which maybe could cause problems.
I also did not ever get an issue with the single player version (I left it running for HOURS) so maybe it is only on servers.

**Comment by turbodiesel4598** [comment]
Possibly, but all of the machine updating runs 'server-side' anyway. Given that you seem to be able to recreate the issue, could you try leaving a similar setup running but using something like TD ducts instead of EIO conduits?

**Comment by AwesomeLikeThis** [comment]
Yes, once I get back home I will replace the conduits with fluiducts and I'll leave it running over the weekend.
we will see If the problem persists

**Comment by AwesomeLikeThis** [comment]
Well after replacing the conduits with fluiducts and leaving it for a couple days, nothing went wrong. Then I decided to switch back to ender io conduits and everything has been fine for a couple days now. Not a single hitch. I'm tempted to say it that somehow its fixed now. I'll give it a couple more days and if nothing goes wrong I'll  update once more.

**Comment by turbodiesel4598** [comment]
Good to hear - weird that it's suddenly stopped, but I'll take it :P

Any more problems in the last few days?

**Comment by AwesomeLikeThis** [comment]
No more issues, and I don't even have a theory for why it didn't work in the first place. Maybe there was a conflict with a different mod (possible considering there's about 250 in this pack) and that mod got updated.

Anyway thanks for all the time you spent on this and sorry for all the time you spent on this xD.

**Comment by turbodiesel4598** [comment]
Woop woop! No worries - at least the issue seems to have disappeared. If it returns, let me know ;)
