### ISSUE TITLE
Fusion reactor output capping (3.8Mrf)

### ISSUE THREAD

**Issue by Aang23** [turbodiesel4598/NuclearCraft#513]
So, this issue is somewhat similar to https://github.com/turbodiesel4598/NuclearCraft/issues/161
When you change the output multiplier of the fusion reactor, you can easily get output of way more than 3.8Mrf, but since the buffer is only of that size, any "surplus" energy is lost...
Could you make the buffer configurable ? Or fix this issue in some way ?
![Screenshot from 2019-05-09 10-30-07](https://user-images.githubusercontent.com/23421917/57439034-6daee880-7245-11e9-8129-d2533b5912d4.png)
![Screenshot from 2019-05-09 10-30-34](https://user-images.githubusercontent.com/23421917/57439057-7ef7f500-7245-11e9-9797-555a130e5e18.png)

**Comment by turbodiesel4598** [comment]
Did you change the config option after you'd already placed the core?

**Comment by Aang23** [comment]
I broke / replaced the core after changing the config.

**Comment by turbodiesel4598** [comment]
Did you change the configs from the cfg file or the in-game mod options? If the former, you need to restart the game for Forge to reload them, them breaking and replacing should work. If the latter, that should have worked - which version of the mod are you using?

**Comment by Aang23** [comment]
I'm using v2.16f. I changed the config through the .cfg on the client & server. I restarted both the client & server (twice), and also broke / replaced the fusion core.

**Comment by Aang23** [comment]
Well, I restarted everything again and it's now working... Thanks for your help !

**Comment by turbodiesel4598** [comment]
No prob!
