### ISSUE TITLE
Geiger counter HUD does not work in multiplayer

### ISSUE THREAD

**Issue by AquaticFish** [turbodiesel4598/NuclearCraft#514]
Hey, playing in a server I'm hosting with a couple of friends, made my geiger counter and noticed that it doesn't have the HUD on the bottom left corner, this glitch only occurs in multiplayer, in singleplayer, even with the same mods, the issue does not persist.

**Comment by turbodiesel4598** [comment]
I can't seem to recreate this. Are you using the latest version of the mod? Is radiation enabled on the server?

**Comment by AquaticFish** [comment]
Nevermind, sorry turbo, I had a stroke and forgot to enable nuclear radiation in the config. Why is it disabled by default though?

**Comment by turbodiesel4598** [comment]
No worries! It's disabled by default simply because it was a late addition to the mod, so having it on by default would have suddenly started killing players without them knowing what was going on.
