### ISSUE TITLE
Name of Alloy/Ingot in Recipe

### ISSUE THREAD

**Issue by ForceofWill42** [turbodiesel4598/NuclearCraft#515]
When i was programing my AE2 computer in SF4 to make the alloys, i noticed that the recipe for Lithium Mangnase Dioxide Alloy has instead of Manganese Dioxide Alloy(MDA) but ingot. It appears to be two different entries in JEI, but there is no way to produce the ingot (unless i am missing something). Please help...

**Comment by turbodiesel4598** [comment]
In NC, manganese dioxide is obtained from oxidising manganese oxide, which in turn is obtained from smelting rhodochrosite dust ;)

**Comment by ForceofWill42** [comment]
OK, my bad i was looking at the wrong thing. I was looking at Diboride not Dioxide.

**Comment by turbodiesel4598** [comment]
No worries!
