### ISSUE TITLE
Server crashed when using alloy furnace

### ISSUE THREAD

**Issue by Quarris** [turbodiesel4598/NuclearCraft#516]
Modpack: Sky Factory iiii
Mod Version: NuclearCraft-2.16f-1.12.2
Forge Version: forge-14.23.5.2831
Crashlog: https://pastebin.com/6dUPumtz

Unknown reason as it happened on a server and I don't know who did it or how. Let me know if you need more details and I'll try to find it.

**Comment by turbodiesel4598** [comment]
Looks like you're using 2.16e - update to 2.16f and that'll fix it ;)

**Comment by Quarris** [comment]
you know what... you're right. I looked at the wrong name. My bad
