### ISSUE TITLE
[Suggestion] 1.12.2 - New food and outfit

### ISSUE THREAD

**Issue by DWX12** [turbodiesel4598/NuclearCraft#519]
On a whim and for the sake a of a joke (and because it's what I'm having for dinner tonight);

Fission Chips - Basically raw fish and potatoes cooked using radiation of some sort. Would give high food and saturation levels, but at the cost of radiation poisoning. Would use semi-late game items or mechanics to justify the high levels on the food.

Then there's the matter of the outfit that could be added - A Hawaiian shirt and surfer shorts similar to what Duke Nukem wears in the Captain Planet cartoon:
https://vignette.wikia.nocookie.net/captainplanetandtheplaneteers/images/5/5b/Nukem.gif/revision/latest?cb=20110324041005

Maybe the outfit could provide slight radiation resistance or absorption or just be a cool easter egg to throw in. Maybe some sunglasses to compliment the outfit.

Neat mod. Thank you for all the hard work and time spent making this and hope to see further progress on it.

**Comment by turbodiesel4598** [comment]
Both things are certainly doable, though the former will first require the implementation of radioactive food in general ;)

**Comment by DWX12** [comment]
Feel like some Simpsons references should be added at some point.

**Comment by turbodiesel4598** [comment]
I'm unlikely to get round to adding this myself... things are only getting busier and busier for me unfortunately! It would definitely be possible to make an addon for NC doing this though - in the future I plan to record some tutorials about how to do that.
