### ISSUE TITLE
Off-hand item prevents Voltaic Pile configuration.

### ISSUE THREAD

**Issue by JHawkley** [turbodiesel4598/NuclearCraft#521]
For about two hours, I was trying to draw power out of a Voltaic Pile block.  My main-hand was empty, but nothing would happen when I shift right-clicked; a normal right-click reported the energy, like the tool-tip says, but I could never get it to configure the output.

Turns out, the Tinkers Construct arrows I was holding in my off-hand were preventing its configuration.  This should probably be fixed to prevent someone else from banging their head on the wall for so long.  😝

**Comment by turbodiesel4598** [comment]
Unfortunately not I'm afraid, as far as I know. If there is an object in the off-hand and not in the main hand, then MC will attempt to use whatever is in the off-hand, and sneak-clicking on a block prioritises the use of the item over the clicking on the block :\
