### ISSUE TITLE
hazmat suit config options

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [turbodiesel4598/NuclearCraft#522]
please add a config settings for hazmat suit armor amounts like there is for other armors.

**Comment by AquaticFish** [comment]
Hey, there's already a setting for that.
"# List of armor item stacks and their default radiation shielding levels. Format: 'modid:armorName:meta_resistance'. Note: this is not the only way to add these values if you have CraftTweaker installed. Radiation resistance can also be given to armor by changing their recipe such that an NBT tag called "ncRadiationResistance" with the double value equal to the resistance level is attached to it."
For me, it's in line 1301 in the config

**Comment by C4PTRAMPAGE** [comment]
i see you didn't even read my comment before replying, i said want a config option to set the >>>ARMOR<<< for hazmat suits.

**Comment by turbodiesel4598** [comment]
Added for the next version ;)
