### ISSUE TITLE
CraftTweaker support for 1.7.10

### ISSUE THREAD

**Issue by CamperPro** [turbodiesel4598/NuclearCraft#523]
PLEASE,PLEASE,PLEASE , add CraftTweaker support for Nuclearcraft 1.7.10,  it is very important.  
At least copy from 1.12.2

**Comment by turbodiesel4598** [comment]
I'm sorry, 1.7.10 isn't supported anymore - the recipe system used in 1.7.10 is completely different to the one in 1.12.2.
