### ISSUE TITLE
Crash with IC2

### ISSUE THREAD

**Issue by Barchtic** [turbodiesel4598/NuclearCraft#524]
https://pastebin.com/7KaKUp3R
Issue when starting up game with latest version of IC2 experimental installed. Seems to involve hazmat suits. Found that it is a problem with version 2.17 and 2.17a.

**Comment by turbodiesel4598** [comment]
Unfortunately more recent versions of IC2 have been labelled as beta on CF, for reasons that I don't really know - the latest version is actually 2.8.157, so the last 'stable' release is actually nearly 40 versions behind :P
