### ISSUE TITLE
1.7.10 Workspace for NC

### ISSUE THREAD

**Issue by CamperPro** [turbodiesel4598/NuclearCraft#527]
Hello,its me again, if you can't do minetweaker support,then can you give me gradlew libraries as in the screenshot only for 1.7.10? I can't do anything without these files
![tGWofVVMY9U](https://user-images.githubusercontent.com/51127535/58550024-8c394b80-8215-11e9-9d7b-bcf406a2c0b7.jpg)

**Comment by turbodiesel4598** [comment]
I don't quite understand the question - you should be able to just install the [Forge MDK for 1.7.10](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html) and use ForgeGradle, no?

**Comment by CamperPro** [comment]
I'm going to try

**Comment by CamperPro** [comment]
Lol,why so easy, sorry for this stupid question

**Comment by turbodiesel4598** [comment]
No worries!
