### ISSUE TITLE
[Suggestion] Silicon - add configuration option.

### ISSUE THREAD

**Issue by AssB0ys** [turbodiesel4598/NuclearCraft#528]
There is a very convenient config for the nuclearcraft ores "B:hide_disabled_ores=false". Since two major storage mods both use silicon and it's oredictionaried, thought you may add this little adjustment to your configuration. Thank you.

**Comment by turbodiesel4598** [comment]
@AssB0ys I’m not sure what you mean - that config is for hiding disabled mineable ores from recipes. Silicon is not mineable in NC.

**Comment by AssB0ys** [comment]
This is to avoid the duplication in JEI. I thought if within this mod it is already possible for the ores, which also removes the corresponding ingots and dusts, it would be possible for other resources like silicon.

**Comment by turbodiesel4598** [comment]
It technically would be possible, but this sort of thing is already handled by CraftTweaker - items can be removed from ore dictionary entries and removed from JEI. That config is only specifically for the mineable ores.

**Comment by AssB0ys** [comment]
Yes this is understandable.
