### ISSUE TITLE
enh - configurable explosions

### ISSUE THREAD

**Issue by Cronosus** [turbodiesel4598/NuclearCraft#53]
Hello
please, add to config:
- explosion power
- explosion chance
- stability of reactors or used materials (maybe)

it makes working with reactors little harder and more interesting

**Comment by turbodiesel4598** [comment]
Certainly very possible, but what do you mean by 'explosion chance'?

**Comment by Cronosus** [comment]
chance to explosin when is reactor unstable or hot.... 
to make it not explode everytime on same situation.. to make it more unpredictable

**Comment by turbodiesel4598** [comment]
Well, the thing is that there's a very definite heat bar in the GUI to warn when the explosion will occur, so I don't see why there should be a chance to explode.
Anyway, I'll add a config to change the reactor's explosion radius.
