### ISSUE TITLE
java.lang.NoClassDefFoundError: nc/item/armor/ItemHazmatSuit

### ISSUE THREAD

**Issue by portalfan04** [turbodiesel4598/NuclearCraft#530]
https://pastebin.com/9U3wn1Xj

Getting an error whenever i try to launch forge1.12.2-14.23.5.2838 with my current modpack

**Comment by turbodiesel4598** [comment]
Updating IC2 should fix this ;)

For some reason later IC2 builds are labelled as betas so you may need to update it by heading into the mods version list.
