### ISSUE TITLE
GasHelper capabilities performance

### ISSUE THREAD

**Issue by Sir-Will** [turbodiesel4598/NuclearCraft#531]
Any chance this can be done without `getDefaultInstance`?
NuclearCraft-2.16f-1.12.2
![](https://i.imgur.com/oGOM1Mh.jpg)

**Comment by turbodiesel4598** [comment]
Possibly - it will still require reflection though, which is always going to be slow. Unfortunately Mek does not include its gas capabilities in the API, so I have to get them through this slightly bizarre method.

**Comment by turbodiesel4598** [comment]
Talked to the Mek devs - I can use a feature of Forge capabilities that I had forgotten about to get the capability much more effectively. Will sort it out for the next build :)

**Comment by turbodiesel4598** [comment]
Sorted :)
