### ISSUE TITLE
Half life style advanced hazmat suit

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [turbodiesel4598/NuclearCraft#532]
First off big thanks for fixing the armor config for the hazmat suit. 

anyway have you thought of adding an advanced hazmat suit like the h.e.v. from half life? (passive rad shielding (way better than the normal suit) but needs to be recharged from a wall terminal for armor, maybe upgrade modules to boosts horizontal jumping distance, add flashlight, etc.) or hey just add the h.e.v. from half life i'm happy with that too.

**Comment by C4PTRAMPAGE** [comment]
just look at the h.e.v. from lambdacraft. add that.

**Comment by turbodiesel4598** [comment]
Hmm... I'll have to put this on the back-burner for now as it'd be something I'd have to learn how to implement, but I suppose it could be cool :)

**Comment by portalfan04** [comment]
Bump, sounds awesome. Maybe add more tiers that have different mobility, protection, armour. Maybe also add a modular system like modular powersuits/advanced rocketry's EVA suits, with modules including scuba equipment, exoskeletal armours and longjump module. However, these modules require fuel/oxygen/power as well, so charging pads will be needed.

**Comment by turbodiesel4598** [comment]
Chances are I'm not going to add an in-depth system like that, as I just don't have the time, but an addon could always make use of the radiation system to implement something along those lines ;)

**Comment by turbodiesel4598** [comment]
In hindsight it's simply very unlikely I'll get round to adding this - with the limited time I have, I have to focus on the main content of the mod, but if you would ever like to write an addon implementing this, do join our Discord server to let me know if the API needs enhancing in some way!
