### ISSUE TITLE
Crash with ic2classic

### ISSUE THREAD

**Issue by DbpGaming** [turbodiesel4598/NuclearCraft#533]
https://pastebin.com/10MJTGey

seems to be a duplicate of https://github.com/turbodiesel4598/NuclearCraft/issues/530
but there is no "new ic2 version" for ic2classic this is the newest

edit: grabbed a crashlog from testing the slightly older version of NC for the crash here is with the newest https://pastebin.com/40vxPC6z

2.16f is fine

**Comment by turbodiesel4598** [comment]
Already reported in [#526](https://github.com/turbodiesel4598/NuclearCraft/issues/526), and I’ve let the classic devs know about this - hopefully they’ll have a fix soon ;)

**Comment by DbpGaming** [comment]
oh missed that one, alright, thanks alot
