### ISSUE TITLE
How I do increase heat temperature for start fusion reactor to next phase?

### ISSUE THREAD

**Issue by bunchamino** [turbodiesel4598/NuclearCraft#534]
I make 24 teroid fusion reactor , deuterium and tritium fuel. no connect active cooler, no redstone signal.
1st phase reactor need power and heat input to 8000kK. I input 3 energy source in to fusion reactor. (85,000 RF/t , 25,000 RF/t and 25,000 RF/t) this phase heat temp is up to around 4800kK : 50-60% (temperature change 10-20) I can't start reactor.

How I increase temperature in 1st phase?
* I test on creative mode then input energy with creative energy power source e.g. energy cube (mekanism mod) it 's easy to increase heat temperature.

**Comment by turbodiesel4598** [comment]
I recommend just storing up a huge amount of energy, then exporting it all to the reactor core in one large burst to reduce the effects of temperature loss. Enough energy and power will eventually get there ;)
