### ISSUE TITLE
Better opencomputers documentation

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [turbodiesel4598/NuclearCraft#535]
For example please explain the difference between these similar functions:
getCurrentProcessTime(), getFissionFuelTime(), getReactorProcessTime()
after a little while i figured them out but people shouldn't need to go though trail and error to understand methods.

**Comment by turbodiesel4598** [comment]
Will at some point - just a bit busy at the mo :)

**Comment by turbodiesel4598** [comment]
[Pre-overhaul OC method documentation is now in better shape](https://github.com/turbodiesel4598/NuclearCraft/blob/1.12.2/openComputers.txt) :)
