### ISSUE TITLE
Reactor decay heat and breaking multiblock while hot

### ISSUE THREAD

**Issue by CIosure** [turbodiesel4598/NuclearCraft#536]
Hey so NC is really soft on the people who make extreme reactors, I understand that it's quite nice but also a thing that's too easy to do, and I want to suggest a feature in which when a reactor is damaged in any way if it's running or still has heat collected, there is a mass radiation leak or even the reactor possibly going nuts, also residual heat, like in actual reactors, in which fuel, even when most of the reactivity is stopped, still has tiny chain reactions going, as in reactors still producing smaller amounts of heat when turned off with fuel in them.

**Comment by turbodiesel4598** [comment]
Not sure I understand the suggestion. Are you suggesting the addition of radiation leaks when the reactor overheats? Because that already happens. As for the second part, are you asking for a gradual slowdown in the reaction rate rather than a discrete 'stop' to the heat production and fuel use?

**Comment by AquaticFish** [comment]
No, what I'm suggesting is that when a reactor is pretty much broken apart, even one block that damages its structural integrity during its operation (when it's running or is still hot), a big radiation leak occurs just like IRL. And about residual heat, in more common terms, it is known as decay heat and it contributes about 6% of the total reactor core heat during operation, meaning that even when the reactor is off, residual heat is still a worry and can add another aspect to watching out for your reactor and not just automatically turning it on or off

**Comment by turbodiesel4598** [comment]
> No, what I'm suggesting is that when a reactor is pretty much broken apart, even one block that damages its structural integrity during its operation (when it's running or is still hot), a big radiation leak occurs just like IRL.

I'm still not sure what you mean here. At the moment in NC, a meltdown is a sudden event when the heat reaches the maximum allowed level, and when that occurs there is also a large radiation leak.

I think residual decay heat is a good idea though - I'm sure it can be incorporated into the new overhaul reactors in some way :)

**Comment by AquaticFish** [comment]
I'm somehow bad at explaining this, what I mean is that people can literally just mine up a reactor, make their modifications and repeat without any consequences, basically tearing part of the reactor apart, even mid-operation.

**Comment by turbodiesel4598** [comment]
Ah, okay, I get you now. Yes, that will be implemented in the overhaul ;)

**Comment by turbodiesel4598** [comment]
Added radiation leak on breaking a running reactor, and added decay heat and neutron poison mechanics :)
