### ISSUE TITLE
2.16f 1.12 - FluidTextureLoader crash

### ISSUE THREAD

**Issue by Jerakl** [turbodiesel4598/NuclearCraft#537]
Hi! I'm running a modified version of FTB Revelations with a handful of added mods - one being nuclearcraft! All my friends are running 2.16f fine, I'm the only one to have the crash (with almost the exact same mod setup). So far in my testing the only thing causing the crash is Nuclearcraft 2.16f. I have tested both with and without optifine.

Mods are whatever is contained in FTB Revelations 2.7.0 + ProjectE, The Aether Legacy, Extra Botany, AE2Stuff, Mekanism (+tools/generators), IC2C, Gravisuit, Optifine HD E3 (SEUS Renewed shaders), and Immersive Railroading.

Crashlog: https://pastebin.com/SxY0kQvN

If I screwed something up feel free to call me dumb. I searched for others with this issue here, but I was unable to find anything else.

**Comment by turbodiesel4598** [comment]
Could you try updating NC, Foamfix and Forge? If this doesn’t fix the issue then I’ll look into it when I’m home :)
