### ISSUE TITLE
[Suggestion] Uses for corium?

### ISSUE THREAD

**Issue by AquaticFish** [turbodiesel4598/NuclearCraft#538]
It'd be cool if corium had a use, at least to be recycled into its components which might be uranium 238, 235, plutonium 239, etc.

**Comment by turbodiesel4598** [comment]
Thing with corium is that it's meant to just be a nuisance - it's a nasty, radioactive mix of reactor part materials, fuel and depletion products. I'm not sure it should have a 'use', as it's only in-game purpose is to be removed.

**Comment by salomj** [comment]
I typically use corium as a radioactive moat surrounding my base.
