### ISSUE TITLE
[Enhancement] Better internal heat and radiation management in Fission Reactors

### ISSUE THREAD

**Issue by Axelandre42** [turbodiesel4598/NuclearCraft#54]
Hello,

I just wanted that energy production and heat management was more like in he real world.
Fuel Rods produces two things :
- Heat,
- and Radiation.
  The Radiation will be transmitted to other nearby Fuel Rods and each Fuel Rod should be monitorable (I'll talk about after).

```
OFO
FXF <- This is a part of the reactor's design
OFO

O is Any reactor block.
F and X are Fuel Rods.
```

In this case, F will transmit its radiation to X and X will do this in the other way.
So, it's now the heat comes on stage : The heat will be produced by the Fuel Reactivity. It's based on three things :
- Base Reactivity (Neutrons per ticks) (Dependent from the fuel),
- a factor that influences production of Radiation, it's the percentage of the Base Reactivity that go in one Fuel Rod beside of this one,
- and another factor influenced by Radiation recieved.

Now, the heat produced is in the Fuel Rod. So the heat will be sent to adjacent blocks that will take heat into an internal buffer
(To be continued because I'm tired)

**Comment by turbodiesel4598** [comment]
I definitely want to add some more complex mechanics to reactors, but I want make sure that it isn't just another big reactors, so the fuel efficiency works in a different way.
