### ISSUE TITLE
SkyFactory 4 - Electrolyser not outputting oxygen to pressurized tube or fluiduct

### ISSUE THREAD

**Issue by MatthyPlayz** [turbodiesel4598/NuclearCraft#540]
My electrolyser won't output the oxygen (or any fluid) into a tube or fluiduct.
My setup:
![image](https://user-images.githubusercontent.com/34276633/59148200-b5a36580-89d3-11e9-8f77-1c063ada79a8.png)

**Comment by turbodiesel4598** [comment]
@MatthyPlayz Are you pulling out the hydrogen or deuterium? That has to be pulled out first before the oxygen can be extracted.

**Comment by MatthyPlayz** [comment]
Thank you!

**Comment by turbodiesel4598** [comment]
No prob! The output order issue will be fixed soon :)
