### ISSUE TITLE
Uses for IC2's coolant in active/passive cooling of reactors?

### ISSUE THREAD

**Issue by AquaticFish** [turbodiesel4598/NuclearCraft#541]
Hey so, since NuclearCraft has enderium and cryotheum coolers that rely on other mods, it would be cool to see IC2's coolant as a valid option for either actively or passively cooling fusion/fission reactors.

**Comment by turbodiesel4598** [comment]
This is a _maybe_, as I have already planned out the new cooling rules and IC2 coolant is not included. If it doesn't make it into the final cut, then it will be possible to add it to the game via the configs and it is almost certain that someone will use the new addon system to get it into the game that way ;)

**Comment by turbodiesel4598** [comment]
IC2 coolant was not used for one of the sink types, but you will be able to pump coolant through a fission reactor to produce hot coolant ;)
