### ISSUE TITLE
[Crash] compatibility with sgcraft

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [turbodiesel4598/NuclearCraft#542]
The game crashed whilst exception in server tick loop
Error: java.lang.ClassCastException: gcewing.sg.rf.RFPowerTE cannot be cast to nc.capability.radiation.resistance.IRadiationResistance

full log: https://pastebin.com/fda5M5Wj

**Comment by turbodiesel4598** [comment]
Line 23:
`java.lang.ClassCastException: gcewing.sg.rf.RFPowerTE cannot be cast to nc.capability.radiation.resistance.IRadiationResistance`

This is an sgcraft bug, and I'm pretty sure I already reported it or something similar to them a while back. It looks like you may be using an old version of the mod you sure you have one of the latest versions from [here](https://ore.spongepowered.org/Dockter/SGCraft/versions)?

**Comment by C4PTRAMPAGE** [comment]
you sure the fork is legit? i never even knew that site existed.

**Comment by turbodiesel4598** [comment]
I'm pretty sure, yes.
