### ISSUE TITLE
Crash with Skyresources 2 (Invalid cast)

### ISSUE THREAD

**Issue by JulianSchutsch** [turbodiesel4598/NuclearCraft#544]
Minecraft 1.12.2, Forge 14.23.5.2838
Crashlog: https://pastebin.com/vAbYN0ZR

Happens if you place a wooden casing.
Workaround is to disable radiation.

**Comment by turbodiesel4598** [comment]
Unfortunately this is SkyResources' fault. [They should not be returning this in general](https://github.com/Bartz24/SkyResources/blob/1.12-2.0/src/main/java/com/bartz24/skyresources/base/tile/TileCasing.java#L158-L159), as it will crash any time other mods such as NC inject capabilities into these tile entities.

**Comment by JulianSchutsch** [comment]
I tell the mod author there.
