### ISSUE TITLE
[Suggestion] Geiger counter to be able to detect the ACTUAL amount of radiation in an area, instead of the amount you experience while in a hazmat suit

### ISSUE THREAD

**Issue by AquaticFish** [turbodiesel4598/NuclearCraft#545]
Title pretty much says it all, with radiation shielded armor or the hazmat suit, your geiger counter only shows the amount of radiation you're experiencing, not the actual amount in the environment, add a mode for that maybe?

**Comment by big-lip-bob** [comment]
+1

**Comment by turbodiesel4598** [comment]
Sorted for the next version ;)
