### ISSUE TITLE
[Suggestion] Different types of nuclear/non-nuclear bombs

### ISSUE THREAD

**Issue by AquaticFish** [turbodiesel4598/NuclearCraft#546]
I shall not stop torturing Tom, so for this day's painful suggestion, different bombs.
NC has quite a lot of molecules/chemicals for us to play around with, so imagine making nitroglycerin or other explosives to gain an edge over standard TNT, or on the nuclear side, regular and dirty bombs, each capable of taking advantage of every available fissile element, going up in strength depending on how heavy the element is /its fission energy output.

**Comment by turbodiesel4598** [comment]
Check out the [Trinity addon](https://www.curseforge.com/minecraft/mc-mods/trinity) for nuclear explosives ;)
