### ISSUE TITLE
[Crash] opensecurity & nc radiation

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [turbodiesel4598/NuclearCraft#547]
it crashed when i tried to look in the gui of a keycard writer and when attempting to reload the world i get this https://pastebin.com/pQDe8kD0

**Comment by turbodiesel4598** [comment]
Will fix on my side for the next version ;)

**Comment by theEvilJohn** [comment]
This has been fixed on the OpenSecurity side, https://github.com/PC-Logix/OpenSecurity/issues/138

**Comment by turbodiesel4598** [comment]
Aha, great. Well, it's sorted on my side in the case of other mods too :)
