### ISSUE TITLE
[Question] Will Tesla API be supported in future 1.10+ versions?

### ISSUE THREAD

**Issue by SteelShot** [turbodiesel4598/NuclearCraft#55]
As Title says, will there be direct or indirect Tesla API support?

**Comment by turbodiesel4598** [comment]
I'm definitely looking forward to adding direct Tesla support :)

**Comment by SteelShot** [comment]
So, I'm prosuming it will be something like Mekanism does? ie. RTGs can output both the RF and Tesla units, depending on the conduit/machine placed next to it?

**Comment by turbodiesel4598** [comment]
Probably, yes :)

**Comment by SteelShot** [comment]
Awesome to know,  will be waiting for the 1.10+ update, thanks for answering :)
