### ISSUE TITLE
[Crash] Strange crash when played with Sky Resources 2

### ISSUE THREAD

**Issue by DestinyPlayer** [turbodiesel4598/NuclearCraft#550]
https://paste.dimdev.org/orabodahuf.rb - crash log
http://prntscr.com/o52wej - modpack
Basically, I placed a Sky Resources 2 casing on the ground, in a random place, and my game suddenly crashed with this error. There's no client log, only a server crash log. The log seems to point towards some issue with radiation processing in the mod.

**Comment by turbodiesel4598** [comment]
This is a bug with SR2 and the devs have been notified ;)
