### ISSUE TITLE
Alchemistry Integration? 

### ISSUE THREAD

**Issue by ChlorineX** [turbodiesel4598/NuclearCraft#551]
Alchemistry is a mod about chemistry. NuclearCraft and Alchemistry includes a lot of elements in common, such as Californium, Berkelium and Curium. However, these elements in each mod is not convertible to each other. Is it able to make them convertible. Please improve the interaction with Alchemistry, thanks. 
https://github.com/al132mc/alchemistry/issues/69

**Comment by turbodiesel4598** [comment]
@ChlorineX Does Alchemistry add different isotopes in the way NC does or is it just the elements?

**Comment by HydrogenC** [comment]
Just the elements

**Comment by turbodiesel4598** [comment]
In which case, how would suggest implementing this inter-mod compatibility? What are you looking for in particular on NC's side?

**Comment by HydrogenC** [comment]
By adding something like Californium Ingot?

**Comment by ChlorineX** [comment]
This should be done by the author of Alchemistry

**Comment by ChlorineX** [comment]
Is it possible to make ingots in Alchemistry (eg. Neptunium ingot, Plutonium ingot, Americium ingot, Californium ingot) useable in the isotope separator?

**Comment by turbodiesel4598** [comment]
I'll take the discussion over to your PR ;)
