### ISSUE TITLE
Feature Request: Silver ore

### ISSUE THREAD

**Issue by KokSaker** [turbodiesel4598/NuclearCraft#552]
Hello. The mod Nuclearcraft has a silver ingot and a dust but doesn't have a corresponding ore, although for all other metals the ore is present. I don't know if this is a bug, therefore I put this as a feature request.

**Comment by turbodiesel4598** [comment]
This is not a bug - silver is obtained through Alugentum, which is obtained via the rock crusher ;)

**Comment by KokSaker** [comment]
Thanks.
