### ISSUE TITLE
Server Crash when ItemFilter from RFTools placed

### ISSUE THREAD

**Issue by OsirisKalev** [turbodiesel4598/NuclearCraft#553]
https://pastebin.com/Zy4bcA6k

On our server, someone placed down an itemfilter, which then caused the server crash out, with the above crash log. I am putting this here and on the RFTools issue tracker as well, as I can only assume one or both of the mods are causing trouble somewhere with each other.

This was also tested in a singleplayer world with the same result, using rftools-1.12-7.71.jar and NuclearCraft-2.17a-1.12.2.jar.

I have posted a similar bug report over at RFTool's issue tracker: https://github.com/McJtyMods/RFTools/issues/1963 (I don't know how to properly reference issues through this tracker on other mods)

**Comment by turbodiesel4598** [comment]
This is probs on NC's side. Will sort it when I'm home, which should be tomorrow :)

**Comment by turbodiesel4598** [comment]
Finally sorted!

**Comment by 7webfrog** [comment]
I am still having this issue in the All The Mods 3 modpack. A brief look at the crash log in the original post seems like it is very similar to my crash log: [crash-2019-08-05_17.24.49-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/3469521/crash-2019-08-05_17.24.49-server.txt)
The singleplayer worlds that I have placed the item filter in won't load and the server that one is also placed in now will not allow us to connect. Any ideas on how we can get the worlds/server back?

**Comment by turbodiesel4598** [comment]
You are using a very outdated version of NC, updating should fix it ;)
