### ISSUE TITLE
Feral ghoul spawning endlessly

### ISSUE THREAD

**Issue by LemADEC** [turbodiesel4598/NuclearCraft#558]
As of 2.17a-1.12.2, Feral Ghoul are spawning even when there's already plenty around, effectively lagging players. Consider adding a configuration for the spawn weight and max mob per area.

**Comment by turbodiesel4598** [comment]
Don't seem to be able to recreate this. I'm using the same spawning rules as other mobs, and giving their spawning a large weight makes other mobs very rarely spawn in the wasteland instead, and as far as I know doesn't affect the spawning rate. How many are spawning for you?

**Comment by LemADEC** [comment]
they kept on spawning, piling up in the wasteland biome. I've ended up regenerating the map without that biome to address the issue.

**Comment by turbodiesel4598** [comment]
But how much exactly? Dozens per chunk? Have you got a screenshot?

**Comment by LemADEC** [comment]
Those mobs are fairly aggressive, hard to kill. As such, this number of mobs is too high (54 mobs within a 64 m radius, NuclearCraft-2.17a-1.12.2 with a few simple mods, SSP):
![image](https://user-images.githubusercontent.com/4776032/61186782-7e2a7780-a669-11e9-8a65-35f5203e00c5.png)

When I've opened the ticket, we had 120+ mobs within 64 m radius (NuclearCraft-2.17a-1.12.2, spongeforge, medium sized modpack, BiomesOPlenty, SMP).

**Comment by LemADEC** [comment]
For the record, there's a lot of them that are underground.

**Comment by turbodiesel4598** [comment]
Ok, bit of a crude fix unless I can find out how to do something a bit cleverer, but I've changed the spawning rules to that of ambient creatures such as bats so that there should be less of them appearing, and I've also made sure that they can only spawn above ground... freel free to reopen this if the next version doesn't really sort the problem!
