### ISSUE TITLE
(1.7.10) Launcher crashes due to sharing ID 38 with MatterOverdrive

### ISSUE THREAD

**Issue by Jdawg215** [turbodiesel4598/NuclearCraft#56]
My server recently updated to 1.7.10 Nuclearcraft, but now everytime i load in, the launcher breaks and I'm stuck in the launcher menu. Here's the crash report.
[crash-2016-08-23_23.10.43-client.txt](https://github.com/turbodiesel4598/NuclearCraft/files/433978/crash-2016-08-23_23.10.43-client.txt)

**Comment by turbodiesel4598** [comment]
I really don't know how to fix this - mods no longer have control over the IDs assigned to entities, so the issue might just be that you've run out of IDs. Although probably not ideal, the only fix I know of is to remove one of the mods.

**Comment by Jdawg215** [comment]
I dont understand either, but everything worked perfectly until i updated Nuclearcraft :/

**Comment by Ommina** [comment]
Popping in here.  For what it is worth, Matter Overdrive does get its entity ID values from its config file.

I've insufficient knowledge to speculate how MO is making this happen, but it does mean that @Jdawg215 can get both mods playing together by simply fixing up the config.

**Comment by turbodiesel4598** [comment]
I think you may be right. If MO uses configs for the entity IDs, then you'll want to mess with them. I just use the built in system which automatically selects a free ID.
