### ISSUE TITLE
Placing a Turbine Valve is Crashing Server

### ISSUE THREAD

**Issue by tylerlancy** [turbodiesel4598/NuclearCraft#563]
Discovered some kind of bug last night, We had our turbine fully built without a valve, and it was working fine (able to be interacted with). As soon as we place the valve, the server crashes, and has to be restored from a backup.

Here's the log:
https://pastebin.com/qPyvDv4U

Just holler if you need any additional information, I am going to keep tinkering with it for a little while longer to see if I can track down the issue.

**Comment by tylerlancy** [comment]
Sorry, wrong mod 😄

**Comment by turbodiesel4598** [comment]
No worries :P
