### ISSUE TITLE
NuclearCraft 2.17a Crash on Client Start 1.12.2

### ISSUE THREAD

**Issue by raziel23x** [turbodiesel4598/NuclearCraft#564]
When i downgrade NuclearCraft 2.17a to NuclearCraft 2.16f everything works just fine.

Crash Log
https://pastebin.com/fsPRssaM

**Comment by turbodiesel4598** [comment]
Updating IC2 should fix this ;)

**Comment by raziel23x** [comment]
I am running the latest version of all mods

**Comment by Ommina** [comment]
The crash report you posted claims IC2 is their version 109, while the most current release is 164.  In fairness, the most recent version of IC2 marked as a 'release' is 109, while everything subsequent (so far) is 'beta'.  You'll have to embrace the beta.

**Comment by turbodiesel4598** [comment]
Yeh that’s true - soz about that. The maven from which I take the jars for development doesn’t specify whether they are ‘releases’ or ‘betas’, but as far as I can tell all more recent builds are stable and many bugs fixes and additions have been made along the way ;)

**Comment by raziel23x** [comment]
i try to shy away from beta build as many mods have left a bad taste in my mouth due to beta builds actually breaking the modpacks i have worked on lolz
