### ISSUE TITLE
Fission Reactor Port doesn't accept redstone signal.

### ISSUE THREAD

**Issue by wise720** [turbodiesel4598/NuclearCraft#565]
Version 1.17a
Playing on a Server but have the same bug on Singleplayer.
So this problem, I have, is that my Fission Reactor Ports don't accept redstone or better said only for one moment and then they don't power the fission reactor any more. and this moment is mabye a tick.
I'm useing this mods:
![image](https://user-images.githubusercontent.com/26025177/61075514-6f01ba80-a41a-11e9-8aac-82732084c4aa.png)

best regards

 wise720

**Comment by turbodiesel4598** [comment]
Unfortunately this is not at all simple to fix with the current system. The overhaul will totally change the way the reactors are formed and this bug will go away ;)

**Comment by turbodiesel4598** [comment]
Gonna close this as it's basically unfixable on current versions, but rest assured this won't be an issue in the future ;)
