### ISSUE TITLE
[Suggestion] Implement the CommonCapabilities temperature API

### ISSUE THREAD

**Issue by KaseiFR** [turbodiesel4598/NuclearCraft#567]
Hi!

Integrated Dynamics is capable of reading a machine temperature, but NC reactors do not seem compatible. I think it is using the [ITemperature](https://github.com/CyclopsMC/CommonCapabilitiesAPI/blob/master-1.12/capability/temperature/ITemperature.java) capability. Implementing it would allow very precise and flexible reactor control (more than what a redstone comparator currently provides). I guess the IWorker capability could be implemented too.

Since I have some free time at the moment I could work on a PR if you're interested.

**Comment by turbodiesel4598** [comment]
Added support for ITemperature and IWorker to the fusion reactor ;)
