### ISSUE TITLE
GameStages support for radiation effect.

### ISSUE THREAD

**Issue by Fireztonez** [turbodiesel4598/NuclearCraft#569]
Hello,
in my modpack, I want to use nuclearcraft with the Radiation system enabled, but, I also use GameStages, Ore Stages, Item Stages, etc question to lock the progression. So big Tech Mods like NuclearCraft will be really late game... The problem is, if someone contaminates the environments on a server, a new player can really have problems due to the radiation of another player at the beginning. of game, because there is absolutely no way to protect yourself from radiation.

So I want to know if this is possible for you to add a GameStage support for the player radiation. Without that option, I think the game risk to become unplayable on a server...

https://www.curseforge.com/minecraft/mc-mods/game-stages
https://github.com/Darkhax-Minecraft/Game-Stages/blob/1.12.2/README.md

Thank's
FIreztonez

**Comment by turbodiesel4598** [comment]
I'd be happy to try to implement this, but I have never used game stages before - could you roughly explain how it works, or how a pack dev would utilise it? Do I just need to define the stage, with you doing all of the decisions about how to use it, or do I need to also need to define the implementation, in which case what sort of implementation are you looking for?

**Comment by Ommina** [comment]
The thing is, I would find, as a player, the author's proposal... confusing.

Having PlayerB immune from environmental radiation by virtue of not having progressed as far as PlayerA just seems weird.

**Comment by Fireztonez** [comment]
Basically, Gamestages give the possibility to modpack pack dev lock somes things, question to be impossible see, craft or used (depending of what plugin is installed, you can lock or change more things for the specific player stage)...

This can be a little confusing at the start so, I will try to explain with simple example, to show you how powerfull this is:

- The perfect and simplest example is with SevTech Ages, when you start the game you don't know anything, JEI contain about half of a pages of items only... You can mine all the world, you will never find any ores. All ores generate in the world, but the player can't see unless he have the good stage. So all ores is hidden like stone blocks, can be mine with a Wooden Pickaxe and give you Cobblestone.
You can try to craft a Vanillla chest or a Vanilla furnace, but you can't even craft on the first stage!! You do not have access to any maps, and doesn't have WAILA... You are a caveman!!

- At age 1 you unlock Copper ore and Coal Ores, so you can now see in the world and can mine it...  You unlock somes early game craft, like the normal crafting table, the Vanilla Furnace, Vanilla Chest, etc...
Later on you will onlock Journey Map, WAILA, others recipes, access to somes dimensions like the nether, etc...

So I think this explain well what do exactly Game Stages does (With Ore Stages, Waila Stages, Dimension Stages and other plugins...). 
Basically everithing how is player based should be possible to stage with the Game Stages API...

Pack dev can create gamestages using Crafttweaker. There have not real limit question of number of stages in the pack, and player can have 100 different stages apply to is player at the time... All stages is give to player using the command `/gamestages add @p stageName`, and can be remove any time with command `/gamestages remove @p stageName`

So, back to my issue, what I want is to be able to stages the bad things happening to players when it goes on a Radiated environment (I know, this is not something really realist, because radiation will affect everybody in the real world, but I don't think endless Death Loop is fun for anybody!!). So, what I request is basically a way to block every effects caused by player radiations or simple the radiation lock the radiation level calculation for stages set in the config file.

Like that, a new player can go around a contaminated based without dying instantly because of the high level of radiation, but somebody how have unlock the specific stages will walk there have without a good radiation protection it get insane amount of damage or die instantly ;). I think, this is probably the only real good way to avoid a big death loop, if you can't craft any Rad-X potions, any shielding protections or armor to protect you against that radiation... Anyways, this is totally impossible to know when you start on a server if a place have already a big amount of radiation or not, because you have no real Geiger counter or anything when you start the game.

Unless I know I will get a lot of complain about Death-Loop caused by someone else, from people playing on server.

If you need more information let me know and I will try to provide you a littlebit more informations

Fireztonez

**Comment by turbodiesel4598** [comment]
@Fireztonez Thanks for the explanation! I knew how it worked in-game, but wasn't sure how the stages were actually added by a pack or mod dev. So I guess the best way of doing this would be for NC to look for a stage with a particular name, say `ncRadiationImmunity`, and then a pack dev can control when a player has it?

**Comment by turbodiesel4598** [comment]
@Fireztonez?

**Comment by Fireztonez** [comment]
Sorry for the delay for respond, I'm pretty busy this days and not always have time to look my open issues.

I see you close the issue, I hope you will open back!

Yes a stage with a particular name can do the job, or you can add config for that. This is totally up to you the way you want to integrate that. I know most mods give the ability to pack dev to specify exactly what he want, but in that case this doesn't change really anything, because I think only one stages will be need for that. So, I think using a name like that should be a perfect solution and easier to implement.

I'm really happy to ear you work currently on large overhaul of the mod, this sound nice!! I hope the mod will continue in the same direction, with multiple type of fuel, different heat and efficiency level! I really like the puzzle to make good and efficient Fission Reactor!

**Comment by turbodiesel4598** [comment]
Unfortunately I've now stopped development for the 2.x series of NC, but I'll be sure to add this in the overhaul when it is released! And thanks for the kind words :)

**Comment by Fireztonez** [comment]
Ok, I understand. It annoys me a bit that I can not have this function done before that, but, I understand that working on 2 completely different versions at the same time is not easy.

Do you have any idea, without asking for any ETA, how many time the new version can take before tyhe release of the new version? And if this version will be availiable for Minecraft 1.12.2 or only for 1.14+?

Because I really want to know if I will be able to have the mod with that feature in my modpack or if I I should disabled the radiation system.

And, if this will released for 1.12.2,  do you have plan to change a lot the mod with the new version?? I want to know if I work on the integration of nuclearcraft in my modpack, do I will have to redo all that job after the upgrade to the 3.0?

**Comment by turbodiesel4598** [comment]
Yeh, sorry about that - I'm quite short on time anyway too, but I'm glad you understand. I hope to get the first version out in about five days or so, but it will be very far from finished. It is for 1.12.2 and a lot fo stuff is changing, so it won't be compatible with earlier version os of the mod I'm afraid.

**Comment by Fireztonez** [comment]
Ok, no problem,

I'm happy to hear that the new update should come out soon and for 1.12.2!

My modpack is still in early development state, so, if the new version goes out on about five days or so, I will be able to try in my modpack. At this point of the development I have no real problem if the update is not compatible with the old version. And good thing I have not a lot done on the Nuclearcraft Integration in my modpack. I only have stages all the machines and blocks question of removing from JEI!!

So, I hope that the new version will be as good as the previous one and that it will be well integrated in my modpack!

Thank's for your hard work!

**Comment by turbodiesel4598** [comment]
I may be able to get a final pre-overhaul build out with GameStages support. If I do, I'll let you know ;)

**Comment by turbodiesel4598** [comment]
@Fireztonez Ok, I've got a pre-overhaul build, 2.18g, including a game stage called `ncRadiationImmunity`. If given to a player, they are immune to radiation. Will this do the trick?

**Comment by Fireztonez** [comment]
Thank's for that Turbodiesel, if you want I can test that on my modpack and see if everithing works fine.
Technically this will work... Most time people work the other way with gamestages, giving a stages when you progress, but I understand why you do it that way and this is fine... I will just have to automatically give that stage to all new players. I can do it with triumph pretty easy, so this is not really an issue for me!

So if you have a dev version ready, give me the link and I will take a look!

**Comment by turbodiesel4598** [comment]
Will implement as discussed in Discord ;)

**Comment by turbodiesel4598** [comment]
Added CT method to introduce radiation immunity game stages :)
