### ISSUE TITLE
Decay Generator stops working after world reboot

### ISSUE THREAD

**Issue by pyure** [turbodiesel4598/NuclearCraft#571]
To reproduce: 
- Create a functioning decay generator: 
- Thorium -> Decay -> Ion Battery
- Observe power being generated
- Log out to menu, re-enter
- Ion Battery is no longer receiving power.

Could also simply be the battery failing to receive power rather than the decay generator failing to produce power.

Workaround: Replace either the Thorium block or the Battery, and generation of power resumes normally.

Possibly connected: I lost 40k power from ion battery after closing the modpack completely to tweak mods, but I could not reproduce this.

**Comment by turbodiesel4598** [comment]
Ah, forgot to have the recipes refresh on reloading the game. Fixed for the next build ;)

**Comment by pyure** [comment]
7 minute turnaround observed :p

**Comment by turbodiesel4598** [comment]
Gotta love a one-liner :P
