### ISSUE TITLE
Infinite Water Sources do not follow enderio fluid conduit settings

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [turbodiesel4598/NuclearCraft#576]
Hello,
I am currently playing through the modpack Omnifactory and I am using the Dense Infinite Water Source to generate water that I pump into a machine via enderio Ender Fluid Conduits. To limit the production of the machine, I have an ME Fluid Level emitter underneath the ender fluid conduit and the conduit itself is set to extract when there is a redstone signal present, which is given the the level emitter. However, I noticed that water was still entering the machine even though there was no redstone signal being given by the emitter. To check the interaction, I then switch the enderio fluid conduit to never extract, however water was still being input into the machine. The infinite water source is the only source of water that is connected to the machine. I was also able to reproduce this with the dense infinite water source, and enderio fluid conduit and fluid tank, and a redstone torch. Would it be possible for this interaction, where the settings of the fluid conduit are respected,  between the infinite water source and the ender fluid conduit to occur?

A screenshot of the setup
![2019-08-20_00 04 02](https://user-images.githubusercontent.com/31759736/63325020-27563480-c2de-11e9-9688-42d3e8dc6000.png)

MC Version: 1.12.2
NuclearCraft version: 2.17a
Enderio version: 5.0.46

**Comment by turbodiesel4598** [comment]
@ALongStringOfNumbers Which machine in that image is receiving the water? If it’s the one adjacent, the water sources auto-push to adjacent fluid handlers.

**Comment by ALongStringOfNumbers** [comment]
The machine receiving the fluid is the chemical reactor from greg tech community edition, the white machine on the left of the image. Adjacent to the water source, which would be behind it in this picture, is only a ME interface from applied energistics. The only other thing connected to the water source via conduits is a fluid interface, which takes the output fluid of the chemical reactor. I have included a screenshot of the other setup I tested which used an enderio fluid tank, which is a little less cluttered. In this screenshot, the fluid conduit is set to never extract mode, however, water is still inserted into the fluid tank. No input/output options were configured for the tank. As for the original situation, I am having trouble reproducing it consistently, however the original instance is still occurring.

Screenshot:
![2019-08-20_13 24 58](https://user-images.githubusercontent.com/31759736/63381697-104f2b00-c34e-11e9-9063-b47544814ea7.png)

**Comment by turbodiesel4598** [comment]
Hmm, I think this is technically 'intended' behaviour. Whether a conduit is actively pulling or not doesn't determine whether other blocks can automatically push to it. I could add a config to stop these sources from auto-pushing, so that an actively pulling pipe/conduit is required?

**Comment by turbodiesel4598** [comment]
@ALongStringOfNumbers Would this work?

**Comment by ALongStringOfNumbers** [comment]
That would work for me, thanks for looking into it

**Comment by turbodiesel4598** [comment]
No prob! Thanks for the quick response :)
