### ISSUE TITLE
Radiation Glitch

### ISSUE THREAD

**Issue by Solverbolt** [turbodiesel4598/NuclearCraft#579]
Radiation counts are getting glitched and continuing to increase till it kills players, even after they drop the item in question or move far away from it. It even bypasses the hazmat suit that ic2 uses just for radiation, not always, but its being super glitchy. Even areas that are not nuclear wastelands, like slime islands, will randomly, for no reason that we have found, suddenly be outputting for 2 or 3 seconds, a lethal dose of radiation. We are on the current All the Mods 3, and they confirmed they have not made any changes to your mod. 

Just want to know if there is a way to temporarily disable it until the issue can be looked into further.

**Comment by turbodiesel4598** [comment]
@Solverbolt Dropping items on the ground will, by default, still irradiate the chunk it is in, which will in turn spread to other chunks and irradiate the player. Does it say that the IC2 hazmat suit has radiation resistance in-game? If not, then some configs have been modified. Also, which version of the mod are you using?

**Comment by Solverbolt** [comment]
right, but we are moving at least 40 or 50 chunks away from that irradiated chunk. or teleporting home, more than 500 chunks away, and the radiation count is still active and climbing, till it kills players. 
NuclearCraft-2.15-1.12.2.jar

**Comment by turbodiesel4598** [comment]
@Solverbolt 2.15 is a _very_ old version of the mod, so there may be some bugs that got fixed later down the line. Is it possible for you to update to the latest version and see if these issues persist?

**Comment by Solverbolt** [comment]
no idea. I am not the developer behind ATM3. so I have no idea if the newest version will even be compatible with the rest of the modpack, but i can do some testing here in a bit.

**Comment by turbodiesel4598** [comment]
Ok, cheers!

**Comment by turbodiesel4598** [comment]
@Solverbolt Have you managed to see anything?
