### ISSUE TITLE
[1.12.2] Config option to alter the effects the Player gets depending on Radiation Levels.

### ISSUE THREAD

**Issue by Z-Tunic** [turbodiesel4598/NuclearCraft#581]
Unsure if this option already exists but there's config options for Passives & Hostiles where you can change what effects they get... depending on their Radiation Levels... however I don't see any options for changing the effects the Players get based on their Radiation Levels.

Reason for this config option is that I'm using a mod called 'Scaling Health' where it has damage scaling depending on the difficulty. The higher the difficulty the more damage you'll take. At a high enough radiation level you'll get the 'Poison' effect which can be rather deadly with Scaling Health. If you have a high enough difficulty... the poison will actually KO you in a few seconds before you even get fatal Radiation Poisoning.

*EDIT*
It seems "Passives" affects Players, I just had to reload the game to have the effects apply. Would it be do-able to have it's own option?

**Comment by turbodiesel4598** [comment]
Added for 2.18g ;)
