### ISSUE TITLE
[Bug?] Wrong plating tier for basic lithium ion battery recipe?

### ISSUE THREAD

**Issue by JoelLaviron** [turbodiesel4598/NuclearCraft#582]
Hello,

While playing with NuclearCraft 2.17c (in Infitech 3 1.0.9 so with GTCE) I noticed that recipe for the 
basic lithium ion battery ask for Elite Plating (Tier 4) while I would expect to ask for Basic Plating (Tier 1). Is this a mistake? For the next tiers of lithium ion battery, it requires plates of the corresponding tier (so advanced, DU, then Elite).
Looking at the changelog for 2.18 I saw nothing mentioning this.
The recipe only involve NuclearCraft items and is craftable by hand so I assume that it was not modified in Infitech3, I haven't tested with just NuclearCraft yet.

**Comment by turbodiesel4598** [comment]
It's not a mistake, no, though I can understand why it looks a bit bizarre. Lithium ion batteries are incredibly powerful energy storages, so their recipe is expensive to match ;)

**Comment by JoelLaviron** [comment]
Ok, thanks for the info.

**Comment by turbodiesel4598** [comment]
No prob!
