### ISSUE TITLE
Breaking a Manufactory loses upgrades.

### ISSUE THREAD

**Issue by Flanks255** [turbodiesel4598/NuclearCraft#583]
upgrades are lost upon breaking a manufactory.

Steps to reproduce:
place a manufactory
put upgrades in it.
break the manufactory.
the upgrades dont drop, nor remain in the manufactory.

NC: 2.18F
Forge: 14.23.5.2838

**Comment by turbodiesel4598** [comment]
Good spot! In fact, item drops from machines were broken in general :P
Fixed!
