### ISSUE TITLE
changing input/output of batteries requires both hands to be empty. Only right hand should be required ?

### ISSUE THREAD

**Issue by mornuel** [turbodiesel4598/NuclearCraft#584]
NuclearCraft 2.x for version 1.12.2 is no longer being developed as the focus of attention has been shifted to the overhaul. Bugs reports will be responded to, but new features will no longer be accepted! Hopefully you can understand that working on two branches of this project at once is far too time-consuming!

Please use a paste tool such as Pastebin (https://pastebin.com) for crash logs!

**Comment by turbodiesel4598** [comment]
Unfortunately I think this is just how Minecraft works - if the main hand is empty, the hand ‘used’ on right-clicking is the off-hand, so they both have to be empty.
