### ISSUE TITLE
NuclearCraft registers tons of invalid OreDictionary entries

### ISSUE THREAD

**Issue by OneEyeMaker** [turbodiesel4598/NuclearCraft#585]
The title says it all. Mod registers tons of **empty** OreDictionary entries. (Empty entry = entry with name but without any associated ItemStacks).
Most of these entries are modified names of **_fluids_** (!!!). For example: ```ingotBiodiesel```, ```gemBio.ethanol``` and so on.

I guess, *one* of the causes of this bug is usage of method ```OreDictionary.getOres(String)```. This method creates **empty entry** if fails to find existing one.
Instead you should use ```OreDictionary.getOres(String, boolean)``` (with second argument = ```false```) in most cases.

P. S. Please, fix this issue before overhaul.

**Comment by OneEyeMaker** [comment]
Example of creating invalid OreDictionary entry:
1) https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/recipe/processor/IngotFormerRecipes.java#L139-L140

2)https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/util/OreDictHelper.java#L56

**Comment by turbodiesel4598** [comment]
Ah, I did not realise - fixed!
