### ISSUE TITLE
Crash After Right Clicking Manufactory

### ISSUE THREAD

**Issue by MackBaggins** [turbodiesel4598/NuclearCraft#588]
https://pastebin.com/rPcxKKdE

**Comment by turbodiesel4598** [comment]
@MackBaggins I can’t recreate this with a non-Magma client or server. Could you see if the same is true for you? If so, we may need to contact the Magma devs (or whoever’s involved) to ask about which versions of Forge libraries they’re using.

**Comment by turbodiesel4598** [comment]
As discussed in the Discord server, Magma is using an old version of the fastutil library. Should be a reasonably simple fix on their side :)
