### ISSUE TITLE
Can't electrolyze water cells

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [turbodiesel4598/NuclearCraft#59]
Electrolyzer will refuse to work. I tried both Empty fluid cells (Full stack) and Water Cells (Full stack), both with and without upgrades. 

Forge 1614, Nuclearcraft 1.9c

**Comment by turbodiesel4598** [comment]
In the later versions you need to supply it with water as a fluid and use empty cells.

**Comment by SmokeyTheBandicoot** [comment]
Oh, I just tried and it works fine. I tried pumping water in, but I guess I did some mistake with the TE portable tanks. Anyway, would you mind adding the water requirement info in the NEI handler? so it is clearer that you must supply water, right now it only shows 12 empty cells and power

**Comment by SmokeyTheBandicoot** [comment]
Also, how do I obtain uranium 238? I'm a little bit lost...

**Comment by turbodiesel4598** [comment]
Yeh, I should do that for sure.
U-238 (and U-235) is obtained by putting uranium ingots or dust through the Isotope Separator.

**Comment by SmokeyTheBandicoot** [comment]
Thank you very much! It is an awesome mod, I just need to learn it a bit

**Comment by turbodiesel4598** [comment]
Yep, like any mod, it sometimes takes time to get used to it - if you have NEI installed that should help you a ton. Apart from that, feel free to ask me questions :)

**Comment by SmokeyTheBandicoot** [comment]
Yes, I have it installed, there so much stuff and so many machine that it may seem a bit overwelming to someone who first uses your mod, but the content is very promising and rewarding and keeps me interested in this mod. Glad to see it in this state, even if there is much room for improvement ;P

**Comment by SmokeyTheBandicoot** [comment]
uhm, sorry to bother you again, can I ask what is the max power of a max-sized steam fusion? I need a lot of energy :zap: right now

**Comment by turbodiesel4598** [comment]
Well, it very much depends on the fuel combo you use. The equation for the RF generated by the normal fusion reactor is: powerGen = efficiency*fusionRF*size*powerVariable/100,
Where 'size' is the toroid size of the reactor, 'fusionRF' is the reactor's power generation config value (100 by default), 'powerVariable' is the fuel combo's power variable (found [here](https://github.com/turbodiesel4598/NuclearCraft/blob/master/Power%20Variables.txt)), and 'efficiency' is the efficiency of the reactor, calculated by the efficiency equation:
efficiency = 742*(e^(-t/h) + tanh(t/h) - 1),
where 't' is the current reactor temperature and 'h' is the fuel combo's heat variable (found [here](https://github.com/turbodiesel4598/NuclearCraft/blob/master/Heat%20Variables.txt)).

So, for example, a max sized RF reactor using the deuterium-tritium combo generates, at max efficiency: 100*100*25*800/100 = 2000000 RF/t = 2 million RF/t.
Although D-T produces the most power, it also uses up fuel very fast, and you can get an idea of the relative fuel use rates [here](https://github.com/turbodiesel4598/NuclearCraft/blob/master/Fuel%20Variables.txt).

**Comment by SmokeyTheBandicoot** [comment]
Oh, really cool, it is a lot of power. I'll do some testing in creative and I'll decide if and how much to nerf fusion and/or mekanism turbine. It seems that, using D-T fuel the best spot for the temperature is 816.566 degrees for 100% efficiency. So I heat the reactor, wait that it reaches this point and? How do I mantain that temperature?

**Comment by turbodiesel4598** [comment]
Well, what most people do is place a comparator at the base of the reactor core, that reads the efficiency level, and then have a loop of redstone 15 tiles long back into the reactor core to turn it off when it hits the peak efficiency.
By default, this 'peak efficiency' is 90%. In other words, if the efficiency is above 90%, the comparator will emit a full-strength signal. This peak efficiency is configurable.
There is also another config option, disabled by default, that will make the reactor asymptotically approach max efficiency, if you want.
Also, it's glad to see someone's done a bit of maths - yes, the best temperature for D-T is what you say it is. I imagine you already did this, but to find the best temperature, you solve the equation:
sech^2(t/h) = e^(-t/h),
which you get from differentiating by t, setting the derivative to 0 and simplifying :)
