### ISSUE TITLE
Default power values for Turbines and molten salt reactors

### ISSUE THREAD

**Issue by SophisticaSean** [turbodiesel4598/NuclearCraft#591]
Yo, just got a MSR setup going and found it to be actually terrible due to the default power gen from turbines. I followed the tutorial, checked my maths and still I got only like 6k rf/t (best case). 

Compared to a solid fuel reactor, which takes 1/100th of the resources, machines, and automation I think this is imbalanced.

I think the base rf/mb for steam should be at least 80 rf/t or 160 rf/t instead of 16 rf/t. Right now the vanilla molten salt reactors are basically worthless unless you tweak the config. I could have 60k rf/t with a solid fuel reactor for 1/100th of the resources. 

Any thoughts on this? I'm happy to make a pull request to fix the default config values but I wanted your feedback first.

**Comment by SophisticaSean** [comment]
This is with a 2x turbine setup, with a heat exchanger for water -> steam and exhaust steam to low pressure steam.

**Comment by turbodiesel4598** [comment]
Hey there! This will be sorted properly in the future as the overhaul gets underway, but for now increasing the steam RF/t as you say, while lowering the coolant heat multiplier config is a way to get round it ;)
