### ISSUE TITLE
[2.18h] EnderIO Energy Conduit and Fluxduct decouple from fusion reactor on chunk load

### ISSUE THREAD

**Issue by Kexerval** [turbodiesel4598/NuclearCraft#592]
I have run into an issue where my power cables will periodically (it has happened 3 times in the last 8 hours) decouple from the reactor core. I have been unable to pinpoint this unusual behavior, but it is very harmful to constant power generation. I have annotated the below image of our reactor setup.
https://i.imgur.com/3vHo1Na.png

**Comment by Kexerval** [comment]
I have been able to tie this bug to chunk loading/unloading. Reproducible by starting a fusion reactor, linking equipment with duct or conduit, then unloading the chunk then reloading it.

**Comment by Kexerval** [comment]
The fusion core also happens to be in another chunk than the conduit and fluxduct.
See [this](https://i.imgur.com/LewXdTj.png)

**Comment by turbodiesel4598** [comment]
Hmm... a strange one, haven't heard about it before but I'll look at it. Just to make sure, you don't have any core mods installed which could be doing something funny with chunk (un)loading, right?

**Comment by Kexerval** [comment]
@turbodiesel4598 I'll double check and let you know what coremods are loaded.

**Comment by turbodiesel4598** [comment]
OK, unfortunately as I can't recreate this, don't really know how to fix it anyway and am also not working on the pre-overhaul version of NC anymore, I'll close this, but I'm pretty sure that this will not happen with the new fusion reactors (yet to be implemented) due to the superior behaviour on the loading and unloading of chunks ;)

**Comment by Kexerval** [comment]
@turbodiesel4598 I'm interested in testing any builds you have! Let me know if you need anybody!

**Comment by turbodiesel4598** [comment]
It'll be a little qhile before new fusion is in, but initial semi-broen builds with the new fission reactors will be going out on [the Discord server](https://discord.gg/KCPYgWw) shortly ;)
