### ISSUE TITLE
Void output fluid tweak

### ISSUE THREAD

**Issue by dbulm2** [turbodiesel4598/NuclearCraft#593]
Can you make it so that the void output fluid button makes it so that it only clears the mostly-empty tank? Efficiency is a huge problem when you're using whatever fuel you can generate to keep the reactor running, since unless there's exactly 1 bucket of fuel in the reactor it gets jammed (seems like the reason that button exists) but with it active it'll clear out the other tank too, voiding up to 32 buckets of fuel for no reason.

**Comment by turbodiesel4598** [comment]
Unfortuantely I've moved on from those versions of NC and the fusion reactor as it was isn't actually in the game anymore - with the new system it'll be a lot easier to control how the fuels and products are handled with much more precision ;)
