### ISSUE TITLE
[1.12.2] Config option to disable materials for Tinkers Construct doesn't work

### ISSUE THREAD

**Issue by ParaMotor** [turbodiesel4598/NuclearCraft#594]
Config option:

    # Will these materials be registered as tool materials for Tinkers' Construct? Order: boron, tough alloy, hard carbon, boron nitride, thorium, uranium, magnesium, chocolate.
    B:tool_tic_register <
        false
        false
        false
        false
        false
        false
        false
        false
     >

doesn't work. When everything is disabled, the materials are still useable and is showing up in JEI. When Shadows of Greg 2.11.0 (with activated gregsconstruct module) is installed, the game crashes because I can't disable thorium:

https://pastebin.com/zJy31k2q

**Comment by turbodiesel4598** [comment]
It looks like you also have Construct's Armory installed, and you may still have the registration of the materials for the armour still enabled - if you also disable that, then the crash should go away ;)

**Comment by Blueberrypie255** [comment]
I can't disable TC's integration with NuclearCraft. I tried these suggestions but I couldn't find an option for Construct's Armory.

**Comment by Blueberrypie255** [comment]
I have Tinkers Reforged as well and there's no option to remove NuclearCraft integration.
