### ISSUE TITLE
CT method no longer allows "null" after passing to overhauled version

### ISSUE THREAD

**Issue by wormzjl** [turbodiesel4598/NuclearCraft#595]
[NuclearCraft-2o.0.2-1.12.2]

My code:
`mods.nuclearcraft.chemical_reactor.removeRecipeWithOutput([<liquid:methanol>*1000, null]);`

Error in CT log:
```
[INITIALIZATION][CLIENT][ERROR] Processes\petrochem.zs:155 > a method available but none matches the parameters (any[])
This is usually an error in your script, not in the mod
removeRecipeWithOutput(ZenTypeNative: crafttweaker.item.IIngredient, ZenTypeNative: crafttweaker.item.IIngredient)
```

So is there any method which I can remove recipes with a single output now?

**Comment by wormzjl** [comment]
Also add recipe method no longer allows a "null" within

**Comment by turbodiesel4598** [comment]
The syntax for overhaul recipes [has changed](https://github.com/turbodiesel4598/NuclearCraft/blob/master/craftTweaker.txt) - you don't need the double brackets any more ;)

**Comment by wormzjl** [comment]
Cool, thanks for the reply!

**Comment by turbodiesel4598** [comment]
No prob :)
