### ISSUE TITLE
[SF4] reactor keeps exploding at low temperature

### ISSUE THREAD

**Issue by casperge** [turbodiesel4598/NuclearCraft#596]
After igniting the reactor it explodes within a few minutes, even when it's more than 100% cooled and not even at a dangerous temperature. I tried to rebuild it twice but exploded both times.

![2019-10-06_11 40 20](https://user-images.githubusercontent.com/30176707/66267238-c1425400-e82e-11e9-8515-f8f846393e95.png)

temperature a few seconds after the explosion:
![2019-10-06_11 40 29](https://user-images.githubusercontent.com/30176707/66267244-cbfce900-e82e-11e9-99b8-c17427198f08.png)

![2019-10-06_11 40 37](https://user-images.githubusercontent.com/30176707/66267246-d4edba80-e82e-11e9-864d-a160069a4bf3.png)

**Comment by turbodiesel4598** [comment]
You e-magnets are exploding because they are running out of power. Only the core will melt when it hits max temperature ;)
