### ISSUE TITLE
crafttweaker documentation: fluid enricher

### ISSUE THREAD

**Issue by reddler97** [turbodiesel4598/NuclearCraft#598]
the crafttweaker document needs to update the fluid enricher from
mods.nuclearcraft.enricher.addRecipe( [  ...  ]);
to
mods.nuclearcraft.dissolver.addRecipe([  ...  ] );

I am very thankful for a mod called "external tweaker", that allowed me to see the crafting handlers

**Comment by turbodiesel4598** [comment]
Hey there - the main branch is now used for the overhaul builds; I think you are looking for the [old 1.12.2 CT docs](https://github.com/turbodiesel4598/NuclearCraft/blob/1.12.2/craftTweaker.txt) ;)

**Comment by reddler97** [comment]
my bad, sorry

**Comment by turbodiesel4598** [comment]
No worries!
