### ISSUE TITLE
plutonium spawning in overworld

### ISSUE THREAD

**Issue by ShawnRHayes** [turbodiesel4598/NuclearCraft#6]
for some reason I am getting it in overworld generation , tested with only NEI, CCC, forge 1558  version 1.6a

**Comment by turbodiesel4598** [comment]
That is very strange - I've checked the ore gen. class again, and it really shouldn't be - is there netherrack around it when it spawns?

**Comment by ShawnRHayes** [comment]
it is a nether type ore , here is a screenshot https://gyazo.com/bf63b6d183f3fa528e309a8bc9d2412e

**Comment by turbodiesel4598** [comment]
Very, very strange - if you go to the WorldGen class, you can see that plutonium should only be spawning in the Nether. I'm not sure what I can do about this, unless I made a mistake somewhere.

**Comment by ShawnRHayes** [comment]
maybe it needs to be a separate block id , I am just guessing , I never modded MC

**Comment by turbodiesel4598** [comment]
Possibly, but the individual ore blocks are defined and registered separately, so that shouldn't be a problem.

**Comment by ShawnRHayes** [comment]
hope it gets figured out, it looks like an awesome mod and I would love to have it spawn as intended so i could put it in a legit world!

**Comment by turbodiesel4598** [comment]
Well, plutonium ore is definitely not a requirement - it can be bred through fission reactions - you can just go into the ore config file and disable its generation ;)

**Comment by 1skandar** [comment]
Actually, it is a bigger problem than that. Plutonium is spawning in *place* of uranium. 

And I found out why:
From OreGen class:
pitchblende = new WorldGenMinable(NRBlocks.blockOre, NuclearRelativistics.oreSizePitchblende, **6**, Blocks.stone);

annnnd:
plutonium = new WorldGenMinable(NRBlocks.blockOre, **6**, NuclearRelativistics.oreSizePlutonium, Blocks.netherrack)

**Comment by turbodiesel4598** [comment]
*Facepalm* great spot - thanks a bunch - will release a fix as soon as possible (i.e. in 12 hours or so).

**Comment by 1skandar** [comment]
Yup, it is nice when I can both spot a bug AND find the fix all at once. And that is the kind of bug where you look at your code and just not notice it again, and again, and again and then, yeah, facepalm. I've done that way too often. Hell, I had to read the code in question twice before I got it.

**Comment by turbodiesel4598** [comment]
Just released a fix - version 1.6b ;)

I guess I'll close this when it can be confirmed that ores are spawning as intended again.

**Comment by ShawnRHayes** [comment]
thanks 1skandar for finding the code issue  and Turbodiesel for resolving this !
