### ISSUE TITLE
MineTweaker/ModTweaker/ContentTweaker Compatibility

### ISSUE THREAD

**Issue by QuantumTraverse** [turbodiesel4598/NuclearCraft#60]
It would be nice to be able to use the advanced workbench and all the machines for custom recipes, and also be able to add our own custom fuels and isotopes.

**Comment by turbodiesel4598** [comment]
Definitely something I want to get done in 1.10.2!
And yes, extra fuels from other mods... I'll think on how to best implement that. Perhaps specifying the fuel, its 'component isotopes', if it has such a thing, the fuel cell, the depleted fuel cell and the products in some way.

**Comment by QuantumTraverse** [comment]
I was thinking more along the lines of just setting a heat production, RF production, lifetime, and depleted cell for an extra fuel. I am not certain what you meant by "component isotopes," but you could just use the existing MineTweaker functions to add a recipe for the fuel (and possibly also adding extra isotopes for said recipe with ContentTweaker) and then the suggested compatibility with NuclearCraft machines would allow a recipe to get products from the depleted cell.

**Comment by turbodiesel4598** [comment]
What I meant by component isotopes is basically the materials that make up the fuel. For example, they would be U-238 and U-235 for U-235 fuels.
I totally forgot about the actual properties of the fuel, but yes, they should be customisable too.
It's a really nice idea the more I think about it. Alongside being able to customise the fuels already in, adding more would be very cool. Perhaps I should just make it as flexible a system as possible, while also making it easy to use.

**Comment by turbodiesel4598** [comment]
Well, with that idea still brewing away in some corner of our minds, I can tell you that [the latest release, 2.4, has CraftTweaker support](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files) :)

I will make a video and put a file into this repository filling out the details shortly.
