### ISSUE TITLE
[CRASH] java.lang.NoClassDefFoundError: nc.tile.storage.TileLithiumIonBattery

### ISSUE THREAD

**Issue by GREIKA** [turbodiesel4598/NuclearCraft#601]
https://pastebin.com/aJgPwiFD
In case this helps, it worked fine before updating Reika's mods to V23a. I didn't feel like reporting it to Reika as the crash log doesn't mention any of his mods.

**Comment by turbodiesel4598** [comment]
Hey there - I don't know what is causing this, but I'm afraid I'm not supporting the 1.7.10 version of the mod any more.

**Comment by GREIKA** [comment]
I guess I will just have to keep on using V22d of Reika's mods then.

**Comment by GREIKA** [comment]
V23b of either RotaryCraft, ReactorCraft, or DragonAPI fixed this issue.

**Comment by turbodiesel4598** [comment]
Nice :)
