### ISSUE TITLE
[Bug] GTCE EU setting does not apply to turbines

### ISSUE THREAD

**Issue by FrederikRasmussen** [turbodiesel4598/NuclearCraft#607]
I noticed the setting to enable or disable GTCE EU support, and was very happy to discover that I could have a reason for players to use both the fusion reactor from GTCE and the various nuclear power options from NuclearCraft, without needing to balance them (too hard) against each other.

Unfortunately, having constructed a turbine, I seem to still be able to extract power from the NuclearCraft machine and into a GTCE battery buffer.

![image](https://user-images.githubusercontent.com/3720563/67772942-346c6e00-fa5b-11e9-9d9d-9466ee0ea7eb.png)

The cable does not visually connect, but it still transfers power into my buffer below.
![image](https://user-images.githubusercontent.com/3720563/67772971-40f0c680-fa5b-11e9-94bd-491fdd13a6ff.png)

**Comment by turbodiesel4598** [comment]
This is probably true for all blocks which output energy - will fix!

**Comment by FrederikRasmussen** [comment]
<3
I made a quick test with the Voltaic Pile, and it did _not_ seem to have the same bug, for what it's worth!

**Comment by turbodiesel4598** [comment]
I could not recreate that 'lack of bug' with the voltaic piles, i.e. it was also broken for them, but anyways, it's now fixed ;)

**Comment by FrederikRasmussen** [comment]
Huzzah! Thank you for your great work, and happy holidays! :)

**Comment by turbodiesel4598** [comment]
And to you too!
