### ISSUE TITLE
Crafttweaker error no such member electrolyzer

### ISSUE THREAD

**Issue by SmugHatLeo** [turbodiesel4598/NuclearCraft#608]
eh, maybe tis me, but i can't seem to be able to use the electrolyzer method for CT.

**Comment by turbodiesel4598** [comment]
If you're using the pre-overhaul builds, you may be [looking at the wrong branch](https://github.com/turbodiesel4598/NuclearCraft/blob/1.12.2/craftTweaker.txt) of the repo ;)
