### ISSUE TITLE
Borax appears to be uncraftable due to missing sodium hydroxide recipe

### ISSUE THREAD

**Issue by TheDeviantCrafter** [turbodiesel4598/NuclearCraft#611]
Borax dust requires sodium flouride, which requires sodium hydroxide. Sodium flouride can be turned into sodium hydroxide and back, but neither appear to have a recipe that doesn't require the other.

This in turn means the chemical scrubber is uncraftable.

**Comment by Andrew-Rominger** [comment]
Sodium fluoride dust can be crafted in the manufactory from Villiaumite dust

**Comment by turbodiesel4598** [comment]
As Andrew says, look for the recipe chains starting from villiaumite and you should be good ;)
