### ISSUE TITLE
Reduce the size of .getReactorLayout() function in OpenComputers

### ISSUE THREAD

**Issue by SuperSamir** [turbodiesel4598/NuclearCraft#614]
So I have a max sized fission reactor 24 x 24 x 24, and whenever I try to use the function in the title, the OpenComputers computer crashes. It shows "Unrecoverable Error, Out of Memory", and doesn't happen with smaller reactors, so I have to assume it's because of the sheer size of the table generated by the function. I was wondering if it was possible to reduce the size of the table generated?

**Comment by turbodiesel4598** [comment]
It's not really possible, no - you've built a 24^3 reactor which has nearly 14000 entries :P
I don't know much about OC, but I believe you should be able to give your computer more memory to handle these types of expensive calls.
