### ISSUE TITLE
[Bug] Nuclearcraft Axes can't debark log.

### ISSUE THREAD

**Issue by Mrthomas20121** [turbodiesel4598/NuclearCraft#615]
When using nuclearcraft and the mod debark, the axes from nuclearcraft can't be used to debark log.
Nuclearcraft version: NuclearCraft-2.18n-1.12.2

**Comment by turbodiesel4598** [comment]
@Mrthomas20121 Does [this build](https://www.dropbox.com/s/dirqvntzsivmor7/NuclearCraft-2.18o-1.12.2.jar?dl=0) fix the issue?

**Comment by turbodiesel4598** [comment]
Fixed in [v2.18o](https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-mod/files/2853541) ;)
