### ISSUE TITLE
machine has almost all bugs in Sponge 1.12.2 machines

### ISSUE THREAD

**Issue by KiWinger** [turbodiesel4598/NuclearCraft#619]
Tried 4 versions, two lower versions are okay for single person, (two higher versions cannot run, currently used as lower newer versions)
However, in the Sponge 1.12.2 server, the machine cannot operate normally. The GUI disappears immediately after opening the GUI and putting in the composition. After opening the GUI again, everything inside disappears directly, including upgrades and power, and there is no error in the background.

**Comment by turbodiesel4598** [comment]
@KiWinger Which version of the mod are you sing? Are you using the latest build of Sponge? Bugs like this have appeared in the past, but were solved.

**Comment by KiWinger** [comment]
thanks reply!
Currently using version 2.13e
spongeforge-1.12.2-2825-7.1.6-RC3697
minecraft_server.1.12.2(Probably older version

Tried 2.17c and 2.18o,Cannot run single in minecraft java

**Comment by turbodiesel4598** [comment]
@KiWinger It looks like you're running very old versions of both NC and SF, so I'm not sure I can help you unless you update both!

**Comment by KiWinger** [comment]
Is there a recommended combination of NC and SF versions?i can try it update ###
but the recommendation I see on the SF official website is 1.12.2-2838-7.1.8,Should I download the latest version?

**Comment by turbodiesel4598** [comment]
@KiWinger The recommended version of NC is always the latest build. I don't know what SF's is, though it may be the latest build.

**Comment by KiWinger** [comment]
Thank you! I will try it now

**Comment by KiWinger** [comment]
Yes, I tried it yesterday, the latest version did solve the problem, thank you very much :D

**Comment by turbodiesel4598** [comment]
Great!
