### ISSUE TITLE
Not all Fluids can be placed in world

### ISSUE THREAD

**Issue by MuteTiefling** [turbodiesel4598/NuclearCraft#622]
I know this may seem minor, but it's blocking me in a pack I'm creating.

I'm trying to use Thermal Series Florbs in some of my recipes. According to their wiki, they will only register fluids that can be placed in the world. 

Now, for many of the NuclearCraft fluids, this works fine. Lithium, for instance, and all of it's sub forms, have florbs and I can also place them in world. 

Iron, on the other hand, cannot be placed. Neither can gold, quartz, or lapis. Things like Molten Sugar can though. Mostly it seems kind of arbitrary which can and which can't. 

Considering this is just a flag on the fluid, would you consider adding this to more of the fluids added by NC in the upcoming overhaul?

**Comment by turbodiesel4598** [comment]
There is a config called `register_fission_fluid_blocks`, or `register_fluid_blocks` in later builds, which will register the blocks for all of the other fluids added by NC. The ones that don't have associated blocks by default are those which are used in the fuelling and cooling of molten salt reactors.

**Comment by MuteTiefling** [comment]
Ahh, so that's what that means. Got it! Thank you so very much!

**Comment by turbodiesel4598** [comment]
No prob!
