### ISSUE TITLE
[1.12.2][v2.18o] Problem with armor radiation resistance config

### ISSUE THREAD

**Issue by sumrex** [turbodiesel4598/NuclearCraft#623]
No matter what I try no armor I put in the config will go through. My last resort is asking here in hopes that I can get help. No crashing or anything, but the config instructions are definitely wrong and I haven't been able to find any sources that know how it's actually supposed to be done.

Here is a paste of the config section in question:
https://pastebin.com/ZKgPxNvd

**Comment by turbodiesel4598** [comment]
It looks like something about TechGuns is causing the radiation resistance to not be given to its armour pieces. I'll have a look into it!

**Comment by sumrex** [comment]
This is not only Techguns. I have tried doing vanilla minecraft armors, and nuclearphysics hazmat as well.
This is definitely a Nuclearcraft problem

**Comment by turbodiesel4598** [comment]
Strange, I'm not quite getting the same problem...

[Ah, found the problem. I'm returning here, when I should just be continuing the loop.](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/radiation/RadArmor.java#L46) This means that if any of the armours in the config don't exist in the game, it'll cease adding any more resistance levels. The temporary solution is to remove all of the entries not in your game, and I'll get a fix out when I can ;)

**Comment by turbodiesel4598** [comment]
Fixed for the next build :)
