### ISSUE TITLE
Active fluid coolers being fed with water don't count for Water Coolers as synergies with other coolers

### ISSUE THREAD

**Issue by Shunigate** [turbodiesel4598/NuclearCraft#625]
I've built a reactor that relies on synergies for a bit, and decided to test whether the Active fluid coolers counted as Water Coolers (for example, trying to make a Diamond Cooler work).

They do not.

I do not know if this is an intended feature, or just a bug, so I'll report it anyway just to be sure.

I've provided two screenshots, the hotter reactor is the one with Active fluid coolers, and the cooler reactor is the one with Water Coolers in the places of Active fluid coolers.

![javaw_hg2yon1UN7](https://user-images.githubusercontent.com/56971174/74369238-55bc5480-4dd5-11ea-8ceb-4fd35fd8f0b1.png)
![javaw_92p7OMdq1y](https://user-images.githubusercontent.com/56971174/74369251-594fdb80-4dd5-11ea-948f-bc102367bff1.png)

Hope this can get fixed/marked as intended

**Comment by turbodiesel4598** [comment]
This is intended, or at least was never implemented - it should explain on the tooltip ;)
