### ISSUE TITLE
While I'm aware that it is no longer being developed, I would still like to give this suggestion... Perhaps it can be put into the overhaul.

### ISSUE THREAD

**Issue by xenoulexi** [turbodiesel4598/NuclearCraft#627]
I'm playing a game with the [Pollution of the Realms](https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms) mod, and I have gone into the config to add my own contaminants. If you don't know what that particular mod does, it adds blocks of smoke, dust, and sulphur fumes that spawn from machines when they are in use, and these blocks can become a serious danger if you don't take great care to prevent environmental harm. The blocks are transparent and don't have collision, but standing in them causes you to drown and be blinded, eventually, if the contaminants are thick enough, far worse effects, such as poisoning and withering can happen, such as if you're standing in an area that is heavily contaminated with sulphur fumes. I realize, that this system would be a perfect way to simulate radioactive waste.

Perhaps, in addition to creating radiation, the nuclear reactors create invisible blocks that emit radiation and cause poisoning if you're standing for too long in them, to simulate an area of high radioactivity that can be effectively blocked with shielding, such as blocks of lead, as the invisible blocks won't be able to spread into areas where blocks already exist. I am currently doing this manually with the Pollution of the Realms mod, but it would be nice if these two mods could work together in this way...

**Comment by turbodiesel4598** [comment]
The radiation system isn't a huge focus for me right now, as I'm simply rather low on time and have to focus on the multiblocks and their mechanics. Perhaps someone could write an addon implementing such things - some people have already written radiation-related addons for NC, albeit this would be something trickier.

**Comment by xenoulexi** [comment]
Yeah, I can see that... I'm working on my own modification to the Pollution of the Realms mod that I'm going to share, but it would have been nice to get this into the base mod itself.
