### ISSUE TITLE
i cant find the particle accelerators controller

### ISSUE THREAD

**Issue by crazyfisheater** [turbodiesel4598/NuclearCraft#629]
i have made a small particle accelerator but cant find the controller for it i tried searching it in jei but nothing comes up

**Comment by turbodiesel4598** [comment]
@crazyfisheater Which version of the mod is this?

**Comment by crazyfisheater** [comment]
the mod version is 2.18o-1.12.2

уто, 18. феб 2020. у 13:53 Tom Dodd <notifications@github.com> је
написао/ла:

**Comment by turbodiesel4598** [comment]
NC for 1.12.2 does not have a particle accelerator - it was not implemented in the end, but may be in the future :)
