### ISSUE TITLE
Output Fusion Reactor

### ISSUE THREAD

**Issue by gamelnderGamler** [turbodiesel4598/NuclearCraft#63]
I run the latest Nuclearcraft Version. (1.9d)

I have a Lithium 7 - Lithum 7 and a Tritium-Deuterium Fusion Reactor. 

They are both supposed to output Neutron Capsule, but they dont. They only output Helium 4.
the bar wich shows how far the process is going fills up complet but then it stand still and no Neutron Capsule appears. (while it still outputs helium 4)

Maybe iam doing something wrong, but it looks like a bug to me.

**Comment by turbodiesel4598** [comment]
Have you put empty capsules into the input slot about the neutron output?

**Comment by gamelnderGamler** [comment]
no i didnt. 

sorry so its not bug :/

thank you verry much :)

**Comment by turbodiesel4598** [comment]
No problem!
