### ISSUE TITLE
Issues with active coolers

### ISSUE THREAD

**Issue by thecatinthebag** [turbodiesel4598/NuclearCraft#630]
I was playing on the FTB Revelation modpack and when I put down the active coolers in my fission reactor, I started having some issues. The only coolant that was being actually consumed was Resonant Ender, while other liquids like water and gelid cryotheum were not. I tried rebuilding the reactor, reloading the game and all of that, but nothing really changed.

**Comment by turbodiesel4598** [comment]
@thecatinthebag Are these active coolers respecting their passive counterparts' placement rules?

**Comment by thecatinthebag** [comment]
Ah, they weren't. Guess I'm illiterate. Either way, thanks for reminding me that and sorry for wasting your time.

**Comment by turbodiesel4598** [comment]
No worries!
