### ISSUE TITLE
[Suggestion] Command to Remove Radiaton in a radius

### ISSUE THREAD

**Issue by Asrothear** [turbodiesel4598/NuclearCraft#631]
Maybe it would be usefull to have the abillity to remove or reset the Radiation in a radius arround the player including blocks an entity.

the idea came, while i was experimenting with some stuff and had to place quite a lot scrubber´s
the build in command is working fine but the surrunding chunks are still radiated so the radioation is quickly rising

**Comment by Asrothear** [comment]
the idea came, while i was experimenting with some stuff and had to place a quite a lot scrubber´s ^^

**Comment by turbodiesel4598** [comment]
I'm not developing the version if NC you're most likely playing anymore, but I can still add some more radiation commands such as that to the new overhaul branch :)

**Comment by turbodiesel4598** [comment]
Added commands to set the radiation in a radius of chunks around the player, or simply the entire world. Will be in v2o.1.2 :)
