### ISSUE TITLE
Fission fuel dupe in 2.18l - 2.18o

### ISSUE THREAD

**Issue by Gusev-Roman** [turbodiesel4598/NuclearCraft#632]
Hello! Every time when I go to Nether and come back, all fuel (LEU, TBU, etc) will be duped by pipes to a chest, used normally for depleted fuel. Now I have full inventory of nuclear fuel!

**Comment by turbodiesel4598** [comment]
@Gusev-Roman Which version of NC is this? Does this happen with other items or only NC's fuel?

**Comment by Gusev-Roman** [comment]
Yes, version 2.18l-1.12.2
Only fission fuels (not depleted) are dupped. Screenshots added.
![2020-03-02_00 55 37](https://user-images.githubusercontent.com/56547441/75634686-db872f00-5c20-11ea-9320-d77ce433b93b.png)
![2020-03-02_00 55 50](https://user-images.githubusercontent.com/56547441/75634688-dd50f280-5c20-11ea-9309-36b384769f41.png)
![2020-03-02_00 56 18](https://user-images.githubusercontent.com/56547441/75634689-df1ab600-5c20-11ea-9720-22a9920d8d09.png)

**Comment by Gusev-Roman** [comment]
Now checked on latest version (2.18o) too: 
Screenshot 1: before nether -
![2020-03-02_08 54 23](https://user-images.githubusercontent.com/56547441/75653526-d3ee7700-5c6e-11ea-911a-50ee9c0f7947.png)
Screenshot 2: after nether - we can see 29 of TBU fuel appears!
![2020-03-02_09 42 19](https://user-images.githubusercontent.com/56547441/75653527-d51fa400-5c6e-11ea-9eab-e7dbab893bfa.png)

**Comment by turbodiesel4598** [comment]
> I think, reactor may NOT give away items from input slot :)
Are you saying that the TBU is being pulled from the input slot of the controller?

**Comment by Gusev-Roman** [comment]
Yes, fuels are copied, and chunk loading/unloading give us that strange effect.

**Comment by turbodiesel4598** [comment]
@Gusev-Roman Would you be able to see if [this build](https://www.dropbox.com/s/vvowukn56kwj7eo/NuclearCraft-2.18p-1.12.2.jar?dl=0) fixes the issue?

**Comment by Gusev-Roman** [comment]
I will check it today evening

**Comment by Gusev-Roman** [comment]
oops! chunks crashed while going to overworld! 
[crash-2020-03-17_09.15.14-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/4341813/crash-2020-03-17_09.15.14-server.txt)

**Comment by turbodiesel4598** [comment]
Well, believe it or not, that is at leat a sign that a solutio is on the right track :P

I'll get another build ready shortly!

**Comment by turbodiesel4598** [comment]
@Gusev-Roman Ok, [attempt number two!](https://www.dropbox.com/s/8h8n679a0o6b16x/NuclearCraft-2.18p2-1.12.2.jar?dl=0)

**Comment by Gusev-Roman** [comment]
Crash is gone, but fuels are dupped again :(

**Comment by turbodiesel4598** [comment]
@Gusev-Roman Hmm... are you sure? I'm not saving the controller's inventory to the port any more, so is it definitely not just pulling from the controller's inventory?

**Comment by Gusev-Roman** [comment]
Dupe is fixed in 2.18q! Thanks!
