### ISSUE TITLE
[1.12.2] [2.18o] ...invalid update packet for null tile entity: nuclearcraft:capability_default_radiation_resistance

### ISSUE THREAD

**Issue by Bjonnfesk** [turbodiesel4598/NuclearCraft#633]
I have four Railcraft steel tanks close to each other on my FTB Revelation server. Two of them cross a chunk boundary, and these have no issues. The other two _don't_ cross a chunk boundary (cf. [an early Railcraft issue](https://github.com/Railcraft/Railcraft/issues/18), not quite the same, but possibly tangentially related), and "unform", for lack of a better word, every time I log into the server. They are fully formed Railcraft tanks when I log out, and act as if the multiblock is incomplete when I log back in. This happens _individually_ for each player, so it seems to be purely client side - the fact that the tank does _function_ normally (accepts fluid, etc) even when appearing "unformed" supports this. Right clicking the tank at this point usually (but not always) results in exceptionally strange effects, for instance: 

- Your Tinker's Construct hammer being equipped to your head, IC2 Scaffolds to your torso, AE2 Certus Quartz to your legs, and an Immersive Engineering Toolbox to your feet.
- Armour disappearing to make room for the aforementioned items.
- About half your inventory being duplicated.

Switching dimensions reverses all these effects, however, throwing a duplicated item out of your inventory, or giving it to someone else, before switching dimensions makes the duplication persistent.

At the same time as the multiblocks unform, the following is logged (client side, obviously) for every single block of each of the two problematic multiblock tanks:

`[Client thread/ERROR] [minecraft/NetHandlerPlayClient]: Received invalid update packet for null tile entity at BlockPos{x=-836, y=69, z=118} with data: {x:-836,y:69,ForgeCaps:{"nuclearcraft:capability_default_radiation_resistance":{radiationResistance:0.0d}},z:118,id:"railcraft:tank_steel_gauge",sync:[B;0B,8B,1B,4B,4B,0B,0B,0B,0B,0B,0B,-6B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B]}`

(the values vary slightly from block to block)

It's not clear from this message whether it is a NuclearCraft issue or a Railcraft issue, so I will report it on the Railcraft GitHub as well if you think it prudent.

Breaking a block on the tank and replacing it, or adding or removing fluid to the tank, causes it to update and reform, presumably for all players - however, an item from your hotbar may be duplicated into the tank's input slot when opening the tank's GUI for the first time after reforming the multiblock... but again, not always.

If you think this could be a NuclearCraft issue, I'm willing to perform testing on your behalf to somewhat alleviate your workload with solving this issue.

**Comment by turbodiesel4598** [comment]
I could be wrong, but I don't think this is an NC issue. NC attaches new info to TEs when radiation is enabled, namely a radiation resistance, which is the `{"nuclearcraft:capability_default_radiation_resistance":{radiationResistance:0.0d}}` part. This is only a piece of the the whole packet, and for some reason it's invalid. The big `sync` array is something else, possibly RailCraft.

**Comment by turbodiesel4598** [comment]
@Bjonnfesk I could be wrong, but I don't think this is an NC issue. NC attaches new info to TEs when radiation is enabled, namely a radiation resistance, which is the `{"nuclearcraft:capability_default_radiation_resistance":{radiationResistance:0.0d}}` part. This is only a piece of the the whole packet, and for some reason it's invalid. The big `sync` array is something else, possibly RailCraft.

**Comment by Bjonnfesk** [comment]
Hello,

thank you for getting back to me. Are you saying I should post this on RailCraft's GitHub?

**Comment by turbodiesel4598** [comment]
I'm not even sure it's an RC issue. I don't know enough about the packet system I'm afraid.

**Comment by Ommina** [comment]
@Bjonnfesk 

You can add your case to https://github.com/Railcraft/Railcraft/issues/1815, but since there has not been any Railcraft development in over a year now, I wouldn't hold out much optimism that it will be fixed any time soon.

Sadly, not NuclearCraft.  For the time being, your best bet is to shy away from Railcraft Multiblocks.

**Comment by Bjonnfesk** [comment]
I'd say the balance of probability is that is _either_ NuclearCraft or Railcraft, as removing either of them makes the problem go away. I may post on the Railcraft GitHub, but as there doesn't appear to be much enthusiasm for fixing the issue, I may not bother.
