### ISSUE TITLE
Sponge was stuck by NullPointerException!

### ISSUE THREAD

**Issue by ScottCTD** [turbodiesel4598/NuclearCraft#634]
I'm sorry for troubling you... But I'm crazy in solving this one...
Here is the bug description, logs, and crash-report generated by watchdog.

https://paste.ubuntu.com/p/DvNVzrqC5q/

**Comment by turbodiesel4598** [comment]
Hey there - can you explain what happened? Do you know which block it is that caused this? Perhaps a fission port or a machine interface?

**Comment by ScottCTD** [comment]
Sorry, I cannot locate which one caused the this because once I start my server and join, this error will pop up and the server will stuck, which I cannot do anything for the server even in the console.

**Comment by ScottCTD** [comment]
I will tell anything I can about my server even upload it if you ask.
Think you very very much!

**Comment by turbodiesel4598** [comment]
Hmm, I'm really not sure what's going on - [this line](https://github.com/turbodiesel4598/NuclearCraft/blob/1.12.2/src/main/java/nc/tile/dummy/TileDummy.java#L161) should not be causing a null pointer...

Perhaps try going into the config folder, opening `forge.cfg` and setting `removeErroringTileEntities` to true? Unfortunately you're using Sponge and so it could mess with this config and may be messing with NuclearCraft.

**Comment by ScottCTD** [comment]
Actually I set true for removing erroring TileEntities when I start my server from scratch, but ... yeah, still bad.

I will try to find some Sponge's configs.

All in all, thank you for your responds and NuclearCraft is a really fantastic mod that needs us to really "think" to find how to get power.
