### ISSUE TITLE
[Suggestion] Power balancing

### ISSUE THREAD

**Issue by Melvin580** [turbodiesel4598/NuclearCraft#635]
A single 1x1x1 fission reactor produces 360.000 RF/t with LE 235.
This is out of proportion for most mod packs, isnt't it? i.e. Magma generators produce 40 RF/t.

A scaling factor in the configs would be nice to have. I'd say 360 RF/t already a lot for a 1x1x1 reactor.

**Comment by turbodiesel4598** [comment]
@Melvin580 I’m guessing you’re playing PO3, which has buffed the power generation of the low-tier fuels by a factor of about 3000 :P

**Comment by Melvin580** [comment]
YES! So this is not intended?
I would have to change every fuel setting then?

**Comment by MatthyPlayz** [comment]
I mean, if the pack developers at Project Ozone 3 made that edit, then they probably had a reason for it.

**Comment by turbodiesel4598** [comment]
Project Ozone has always involved heavily buffer power gen. If you really want to get the default values, you can reset them pretty easily in-game, then restart :)
