### ISSUE TITLE
[Question / Not Working] Molten Salt Reactor, Valve doesn't spread to Fission Vessel

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#637]
Given Corona i booted up our modpack once again and wanted to finally try out the Molten Salt Reactors.

I set up a recognized 14x14x14 reactor, just like i did with the solid ones.
I wanted to test basic functionality, added a valve, put a creative mekanism tank with LEU-235 in it, made a EnderIO conduit pump it into the valve and so far it works, the valves tank is full.

Then i placed a vessel onto the valve and expected it to fill, like shown in your video. But that doesn't happen. I tried to change the sides to default and fuel spread, but that's not working. What could i be doing wrong?

![nuclearcraft](https://user-images.githubusercontent.com/25908592/78107232-5e083780-73f5-11ea-902a-2354ebf8830d.png)

**Comment by D3nnis3n** [comment]
Also, Shift-Rightclick for changing the opposite side is not really nice when you have CarryMore installed, as it will pick up the vessel instead. No idea how i could fix that.

**Comment by turbodiesel4598** [comment]
I’ll take a look tomorrow as I’m about to get some sleep, but if you head to the Discord server you may be able to get some help a bit sooner from one of the resident MSR experts if they’re about :)

**Comment by D3nnis3n** [comment]
I'm also heading to sleep, even though quite late at 9am, lol. I'll join the discord afterwards :)

Have a good night.

**Comment by D3nnis3n** [comment]
Coolant Spread is working correctly. I also tried putting the valve sideways, so its exactly like in the video, with no success. Finally heading to sleep now, though.

**Comment by D3nnis3n** [comment]
Closed for dumbness.
