### ISSUE TITLE
Issues with CraftTweaker support

### ISSUE THREAD

**Issue by QuantumBlink1337** [turbodiesel4598/NuclearCraft#638]
Hello, I'm trying to write a CraftTweaker script to modify the heavy water and electrolyzer recipe. I followed the documentation, and I'm still having some issues. The first error reports that the Electrolyzer doesn't exist, and that there is a truncated class.
 Here's a copy of my script: https://pastebin.com/sYTrL9AH
Here's my CT log: https://pastebin.com/f5S2920F

**Comment by turbodiesel4598** [comment]
@QuantumBlink1337 Which version of NC is this? If it's pre-overhaul, i.e. 2.x, you want [this branch of the CT docs](https://github.com/turbodiesel4598/NuclearCraft/blob/1.12.2/craftTweaker.txt) ;)

**Comment by QuantumBlink1337** [comment]
Ah, I see. Thanks for the swift response!

**Comment by turbodiesel4598** [comment]
No worries - you were quicker! :P
