### ISSUE TITLE
Fission Reactor output limited by buffer size

### ISSUE THREAD

**Issue by hotag** [turbodiesel4598/NuclearCraft#641]
As for the version in 2.18q that's present in Project Ozone 3, the fission reactor has a limited output set by its buffer size, therefore, designs that can generate 2MRF/t are only outputting 1.15MRF/t

**Comment by turbodiesel4598** [comment]
This is really just down to me not expecting ridiculous configs for power gen like PO3 has. If I find some time to go back to the pre-overhaul branch and get a new build out, I'll sort this out, but it's rather low-priority now :)

**Comment by turbodiesel4598** [comment]
I believe this was fixed in one of the later releases by a pull-request :)
