### ISSUE TITLE
(NCO) [Bug] Fission reactor is defunct

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [turbodiesel4598/NuclearCraft#643]
i copied the reactor design from the overhaul spotlight https://www.youtube.com/watch?v=F8I7ar3AB0w in a creative world for testing but it wont accept any fuel, when i go into the controller and hold shift it says there are no clusters and that it has 0/125 useful components.

**Comment by turbodiesel4598** [comment]
@C4PTRAMPAGE Have you primed the fuel cells?

**Comment by C4PTRAMPAGE** [comment]
by priming the cells you mean having a neutron source pointing at them right?
as for the second question i've tried using the fuel port and directly putting fuel in the cells

**Comment by turbodiesel4598** [comment]
Indeed I mean the neutron sources - have they been given a redstone signal?

The port is what you want to use now - cells can’t accept fuel directly anymore.

**Comment by C4PTRAMPAGE** [comment]
yeah the sources are all getting redstone power, its like the multiblock isn't detecting the parts inside just the frame but that wouldn't make any sense unless you changed the code for that since the overhaul video... fuel ports don't need to be piped to the cells do they?

**Comment by turbodiesel4598** [comment]
@C4PTRAMPAGE Ports get linked to all cells which match their filter, or they link to all unfiltered cells if they have no filter. Perhaps some screenshots would help?

**Comment by C4PTRAMPAGE** [comment]
oops sometimes i dont get around to checking my email, sorry for the delay.
reactor
![2020-04-22_20 03 58](https://user-images.githubusercontent.com/36720741/80048153-fa919700-84d4-11ea-80f5-1a4be9038193.png)
core
![2020-04-22_20 04 11](https://user-images.githubusercontent.com/36720741/80048162-febdb480-84d4-11ea-8728-63558c54b791.png)
cooling
![2020-04-22_20 04 31](https://user-images.githubusercontent.com/36720741/80048166-00877800-84d5-11ea-962c-d632ea7c753c.png)

**Comment by turbodiesel4598** [comment]
@C4PTRAMPAGE No worries. Looks fine to me - where is the fuel being inserted?

**Comment by C4PTRAMPAGE** [comment]
yes those are the ports i was using one for import the other export (future proofing for automation) the problem is it wont accept any fuel i try to put in them.

**Comment by turbodiesel4598** [comment]
@C4PTRAMPAGE Which fuel are you trying to use?

**Comment by C4PTRAMPAGE** [comment]
oh... i cant just shove leu-233 in the reactor anymore it has to be fuel pellets, so i just wasted everyone's time here.

**Comment by C4PTRAMPAGE** [comment]
maybe to avoid future confusion fuels should be a separate tab in the menu and maybe have a tool tip for what sort of reactor they go in.

**Comment by turbodiesel4598** [comment]
I can't seperate them out because they're the same item with different metadata, but the things that can actually be used as fuel have 'fuel' in their name and stats on holding shift, while other things won't ;)
