### ISSUE TITLE
(NCO) [Bug?] Blindness as a radiation debuff causes sky flickering

### ISSUE THREAD

**Issue by Endgineer** [turbodiesel4598/NuclearCraft#644]
First of all, thank you for working on this mod, especially NCO. The changes are absolutely great, and its relative complexity is much needed/appreciated, especially for high power generation like nuclear reactors. (I support the shift to steam rather than direct RF and bigger fusion reactors btw :P)

In the config, when "minecraft:blindness@1" is used to apply blindness as a radiation debuff, the effect causes blinking in-game. I suspect it's because the blindness is applied with a duration of 0:00 (when the game does this weird white effect as it's removing blindness). Maybe increasing the applied duration to 0:05 or something might fix this.

**Comment by turbodiesel4598** [comment]
Ah, well spotted - will be fixed for the next build :)
