### ISSUE TITLE
(NCO) [Bug] Blindness still causes flicker occasionally

### ISSUE THREAD

**Issue by Endgineer** [turbodiesel4598/NuclearCraft#645]
Thanks for fixing the issue! Unfortunately, it seems that at 0:01, blindness still flickers occasionally (every 5-10 seconds or so, a single flicker happens). :C

During that split second flicker, the sky is gray (not white, because the timer hasn't gotten close enough to 0:00)- you can see everything for a split second and then the blindness comes back. I think it may be because the number dips somewhere below 0:01, and since blindness does not have a fade-in effect (i.e. the world just suddenly pops into view), it looks like a flicker. Maybe increasing to 0:02 might fix this issue.

I tested running around with a 20 second blindness effect and the flicker does not happen at all, so I think I've ruled it out being some sort of lag/graphics issue.

**Comment by turbodiesel4598** [comment]
Hmm, must have not tested for long enough - perhaps [this build](https://www.dropbox.com/s/j6dduibi2y2vmeb/NuclearCraft-2o.2.2-1.12.2.jar?dl=0) does the trick?

**Comment by Endgineer** [comment]
I ran around for a good minute without flickering. I think that fixes it! Thanks. ^_^
