### ISSUE TITLE
1.12.2 missing fluid_coal and fluid_steam when I put the Thermal mods on my server

### ISSUE THREAD

**Issue by ImMineOfficial** [turbodiesel4598/NuclearCraft#647]
NuclearCraft 2.x for version 1.12.2 is no longer being developed as the focus of attention has been shifted to the overhaul. Bugs reports will be responded to, but new features will no longer be accepted! Hopefully you can understand that working on two branches of this project at once is far too time-consuming!

I dont have crashlogs for that but a screenshot: 
![grafik](https://user-images.githubusercontent.com/44243306/80291256-76494900-874c-11ea-99e5-f4d6a587169e.png)

I think Thermal Expansion is the problem because this mod adds more ores and fluids. And there is also a Liquidfacted coal fluid and I dont know why it breaks the server. They are different. And for steam I dont know... Hopefully you know how to fix this problem. I have the newest versions for the version 1.12.2 on it. I tried to replace the nuclearcraft:coal and nuclearcraft:steam with a _fluid behind. In singleplayer it works. The server dont crash but its forever on starting 🗡️ 
 

Please use a paste tool such as Pastebin (https://pastebin.com) for crash logs!

**Comment by turbodiesel4598** [comment]
@ImMineOfficial Hey there! Is that actually causing the sevrer any issues, or is it just a console warning? Sometimes things like this show up when two mods try to add the same type of fluid, but it shouldn't be a problem.

**Comment by ImMineOfficial** [comment]
Its only the console. But you cant join because it stopps loading the server :/

**Comment by turbodiesel4598** [comment]
So does the server crash? What message appears when the player tries to join?

**Comment by ImMineOfficial** [comment]
Nothing. The server is still starting. And it stopps only in the console.

**Comment by turbodiesel4598** [comment]
I don't know what you mean by "stops only in the console" then... can you actually join the server?
