### ISSUE TITLE
[Overhauled] NullPointerException in TileSolidFissionCell.updateCell

### ISSUE THREAD

**Issue by marcin212** [turbodiesel4598/NuclearCraft#649]
NuclearCraft: Overhauled - 2o.2.5, 
Crash log: https://pastebin.com/D2cGtQfu

**Comment by turbodiesel4598** [comment]
I think this was just fixed in [2o.2.6](https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-overhauled/files/2947464) :P
