### ISSUE TITLE
[Bug] [Overhauled] NuclearCraft breaks TFC: TNG heating recipes

### ISSUE THREAD

**Issue by FrederikRasmussen** [turbodiesel4598/NuclearCraft#651]
Okay, first of all, my apologies for being unable to find the Overhaul git.

Second, here's a doozy of a bug.

In Terrafirmacraft: The Next Generation, certain items can be heated to transform them. The most basic example is metal ores in a container - you heat the container to Brilliant White (the highest temperature) to convert ores into liquid metal for use in casting metal items.

However, with NuclearCraft: Overhauled installed, the items just void instead, they never become liquid.

I have attached three pictures of the process:
1. Here we have a container heated to Yellow White**, very close to the melting point.
2. Second is a shot after reaching Brilliant White. The large brown receptacle is the crucible, intended to catch liquids. You can see from the screenshot that it is empty.
3. The final shot shows the tooltip of our vessel. It is now empty, and displays no liquids inside.

![javaw_U87iaCbNEa](https://user-images.githubusercontent.com/3720563/81076536-08d7ae00-8eec-11ea-8ebc-8acc45ba9a67.png)
![javaw_DGrMIqFm69](https://user-images.githubusercontent.com/3720563/81076570-12611600-8eec-11ea-9e46-eb766f157eee.png)
![javaw_mYjgy3cTPD](https://user-images.githubusercontent.com/3720563/81076579-155c0680-8eec-11ea-928d-b6c35dcb8f07.png)

I have no idea why this happens, but I would very much appreciate a solution so I can play with both these great mods simultaneously! :)

**Comment by turbodiesel4598** [comment]
Hey there - the overhaul repo is the master branch, while the 1.12.2 branch is the pre-overhaul :)

I’ve not played with TFC before and certainly haven’t some any specific integration with it... does this happen with pre-overhaul NC, or perhaps other mods such as Tinkers’ Construct which also add molten metals?

**Comment by FrederikRasmussen** [comment]
Apologies for the slow reply.

I have now checked NuclearCraft non-overhaul against TFC to see if the same issue occurs - and it does! 😲  (No difference from the test I made previously. Test performed on fresh world)
I don't think TiC has any issues with this, but it also uses quite different 'heating' mechanics than TFC.

I think it is possibly a poor interaction between the radiation handling in NC (if there is such a thing - didn't get much of a chance to play with the Overhaul edition) which might interact poorly with the non-NBT method TFC:TNG uses to handle item temperatures and melting.

**Comment by turbodiesel4598** [comment]
Whoops, looks like I somehow never came back to this :P
I unfortuantely still can't think of why NC could be causing this issue. I don't use NBT to attach radiation values to items, so I don't think it's that. I think I asked about the TiC molten metals as I was wondering whether NC was messing with fluid registration, but maybe TFC doesn't even use that system.

**Comment by FailMelon** [comment]
Like turbo said this is a conflict with fluid registration, the way conflicts are handled within TFC is that when a fluid is found to have already been registered it will use that fluid over its own, adding its own "wrapper" around it. It is when the code tries to get the fluid wrapper where this code:

```
@Nonnull
@SuppressWarnings("ConstantConditions")
public static FluidWrapper getWrapper(@Nonnull Fluid fluid)
{
    if (!WRAPPERS.containsKey(fluid))
    {
        // Should only ever get called for non-tfc fluids, but in which case prevents a null wrapper getting returned
        WRAPPERS.put(fluid, new FluidWrapper(fluid, false));
    }
    return WRAPPERS.get(fluid);
}
```

Prevents the wrapper from working because of equality with HashBiMap<Fluid, FluidWrapper> testing against standard Fluid and NC FluidMolten.

**Comment by FailMelon** [comment]
@turbodiesel4598 This has been merged and fixed now.

**Comment by turbodiesel4598** [comment]
Awesome, nice spot :)
