### ISSUE TITLE
[Suggestion] Player-Only Radiation When Handling Ores/Fuels/Machines

### ISSUE THREAD

**Issue by SSyl** [turbodiesel4598/NuclearCraft#655]
Just a thought I had the other day while playing. I love the radiation mechanic, but it's not so much fun for my wife and friends when my radiation spills over into their farms with their fluffy animals and what not.

Sure, I could build far away, but I had an idea: What if you added an option so radiation is only player-based and you only get affected by handling radioactive materials without proper protection and maybe interacting with certain machines, rather than "dumping" the radiation in the chunk.

Another idea would be to a config option to allow for a player/UUID based whitelist so that only players that are whitlisted are affected by radiation. Everyone/everything else is unaffected by the radiation except the white listed players.

**Comment by turbodiesel4598** [comment]
Hey there! There are a few configs you could play with to effectively get the desired effect:
- Chunk Radiation Limit (`radiation_chunk_limit`) - setting this to zero would nullify all chunk radiation.
- Chunk Radiation Spread Rate (`radiation_spread_rate`) - setting this to zero would stop radiation spreading between chunks entirely.
- Chunk Radiation Decay Rate (`radiation_decay_rate`) - setting this to a very high value would cause chunk radiation to disappear very quickly.

Hopefully this helps :)

**Comment by SSyl** [comment]
I've actually disabled it entirely for now to avoid unintentionally griefing my server-mates (especially my wife who shares the same base as me, but doesn't do any NuclearCraft related)

I could make the spread to zero and decay rate to something high, but then that still removes the challenge of having to deal with radiation for myself.

Essentially what I'd like is for a way for radiation only to affect myself (or other players who would want to "opt-in"). I know it's mostly an unreasonable suggestion, but I wanted to put it out there in case it gave you different ideas for how to implement radiation in the future.

**Comment by turbodiesel4598** [comment]
I see what you mean - I think that could be done (via a config), but I am only working on the overhaul branch of the mod mow unfortunately.

There is another possibility though, which I think should do what you want, but it requires a bit of knowledge about CraftTweaker and GameStages, and I'm afraid I don't really know anything about the latter.

First, you need to define which stages will give players radiation immunity with [this CT method](https://github.com/turbodiesel4598/NuclearCraft/blob/1.12.2/craftTweaker.txt#L333). Then giving your wife, and whoever else, one of the stages defined using that method should give them radiation immunity :)

**Comment by turbodiesel4598** [comment]
I've added a config to give certainb players radiation immunity. [It's just gone up on CF](https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-mod/files/3026229) :)
