### ISSUE TITLE
Placed blocks do not produce radiation

### ISSUE THREAD

**Issue by wootaboot** [turbodiesel4598/NuclearCraft#657]
Seems odd that blocks of californium can be stored by just placing them in the world instead of in a chest. an block that is placed down does not produce any radiation. is this intended?

**Comment by turbodiesel4598** [comment]
Blocks will produce radiation, just very, very slowly. Reason is that blocks are expensive to get (in terms of tick time), so there's only one random block per chunk checked each tick ;)
