### ISSUE TITLE
Fusion Reactor max size

### ISSUE THREAD

**Issue by Conversage** [turbodiesel4598/NuclearCraft#66]
Hey,

just want to know what is the max. size of the fusion reactor. 
Everytime i build it bigger than toroid Size 16 it says Ring incomplete?

Pls Help!

best regards Conversage

**Comment by QuantumTraverse** [comment]
The max size of the fusion reactor is configurable under FusionConfig.cfg. You can change the value there if you want to make a bigger reactor.

**Comment by Conversage** [comment]
ty very mutch sir!

2016-10-07 4:34 GMT+02:00 QuantumTraverse <notifications@github.com>:

**Comment by turbodiesel4598** [comment]
Hmm... the max size by default should be 25 - I don't see any good reason for why it should be maxing out at 16.

**Comment by turbodiesel4598** [comment]
Can I just ask whether or not the issue was just that the config option was setting the maximum size to 16? Because if not, I'd like to see if this issue could be fixed before leaving 1.7.10 behind.

**Comment by Conversage** [comment]
I dont know exactly anymore  but i think it fixes the issue.

Am 31.03.2017 17:11 schrieb "turbodiesel4598" <notifications@github.com>:

Can I just ask whether or not the issue was just that the config option was
setting the maximum size to 16? Because if not, I'd like to see if this
issue could be fixed before leaving 1.7.10 behind.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/turbodiesel4598/NuclearCraft/issues/66#issuecomment-290739356>,
or mute the thread

**Comment by turbodiesel4598** [comment]
Ok. I'll probably close this then, since it didn't/doesn't seem to be a widespread issue.

**Comment by Conversage** [comment]
Go ahead :)

Am 31.03.2017 17:17 schrieb "turbodiesel4598" <notifications@github.com>:
