### ISSUE TITLE
[Pre-Overhaul] Machines stop working in conjuction with machine interfaces

### ISSUE THREAD

**Issue by MorganSimic** [turbodiesel4598/NuclearCraft#662]
Machines that stop working because their buffer is full, will not resume work if the buffer is emptied via autopush from an attached machine interface. Updating the machine via opening the GUI makes the machine run again.

Pack: Enigmatica 2 Expert 1.76a
Mod version: 2.18o

Steps to reproduce:
1. Take a melter, hook it up to power and attach a machine interface.
2. Let the melter fill its internal buffer with anything.
3. Put down an empty fluid containter beside the machine interface.
4. The melter empties its buffer but does not start work again until the GUI is opened.

**Comment by MorganSimic** [comment]
Further testing reveals, this does not only affect the autopush but any means by wich fluid is transfered from the interface rather from the machine itself. So attaching conduits or ducts to the interface to extract fluids yields the same problem.

**Comment by turbodiesel4598** [comment]
Somewhat fixed in 2.18u by removing the auto-push feature of the interface - pulling via a servo or similar should update the machine properly :)
