### ISSUE TITLE
Fission reactor output less than listed on controller.

### ISSUE THREAD

**Issue by 002dynames** [turbodiesel4598/NuclearCraft#663]
Yesterday I updated my server's Nuclearcraft version from 2.18o to 2.18u. After the updates it seems that for some reason the fission reactors are generating less RF/t than it says in the controller at varying rates too. The input to the fluxplugs bounce from 0 to around 3000.
![1592600028(1)](https://user-images.githubusercontent.com/60084881/85179094-0340e800-b24e-11ea-8325-24cfb021003d.jpg)
![1592600126(1)](https://user-images.githubusercontent.com/60084881/85179175-4ac77400-b24e-11ea-9b66-a84c3727b98d.jpg)

I noticed when I saw that I the input to my main energy storage was bouncing up and down as opposed to before that it was consistent.

My guess is that there is a config I did not change after updating the mod as I also deleted the old config file to let the new version generate a new one.

**Comment by turbodiesel4598** [comment]
I think this is due to Flux Networks pulling EU from the controller rather than RF, and since the NC EU:RF ratio is 1:16, while Flux Networks' is 1:4, the power gen is being reduced by a factor of four. Going into the NC processor configs (accessible in-game) and changing that ratio from 16 to 4 should fix this :)

**Comment by 002dynames** [comment]
Oh thank you for replaying so soon. I ended up solving it by having the reactor output to a cryostabilized fluxduct before reaching the flux plug. I am no expert but my guess would be that going through the fluxduct converted the energy into RF. I will go into the NC config and do what you said anyways just in case someone else in my server eventually runs into this issue. Again thanks for the quick reply.

**Comment by turbodiesel4598** [comment]
No worries :)
