### ISSUE TITLE
Fission active cooler values suddenly dropped

### ISSUE THREAD

**Issue by 002dynames** [turbodiesel4598/NuclearCraft#664]
For some reason, the values of active coolers in my fission reactors suddenly went from half to a quarter of the values specified in the config file. For example the default active cooling value for enderium listed is 10800H/t, so normally it would be able to do 5400H/t, I can confirm from the Reactor Planner, but just today it became 2700H/t. Two of my Fission reactors were running just fine yesterday, but as I logged in today one went instantly into meltdown while the other one fortunately didn't because it didn't have fuel in it. I double checked my configs with the default values from the Planner and they seem to match. Also passive coolers seem to not been affected.

I tried looking for an answer on google but had no luck. Do active coolers become less efficient under certain conditions or something?

**Comment by 002dynames** [comment]
Tried deleting the config file so that a new one would be generated after rebooting, now a valid enderium active cooler dropped to 540H/t. The more I experiment the less sense this makes.

**Comment by turbodiesel4598** [comment]
Which version if the mod is this? Active coolers will cool at a slower rate if they're low on coolant, but other than that, they shouldn't vary.

**Comment by 002dynames** [comment]
Sorry I forgot to include the version, it's 2.18u. I ended up doing some more digging here on the github page on passed issues and found out that I was dealing with a problem my own dumb ass created. Turns out I missinterpreted one of the configs which I thought dictated the coolers' consumption rate, I didn't realized they would change the cooling rate proportionally. Sorry for the inconvenience.

**Comment by turbodiesel4598** [comment]
No worries! It is somewhat confusing and I've already began removing such configs for the new branch of the mod :)
