### ISSUE TITLE
Exception Ticking World (Server Crash)

### ISSUE THREAD

**Issue by Darkfiend009** [turbodiesel4598/NuclearCraft#666]
Server crashed while walking through the Nuclear Wasteland biome due to ticking world exception:

Crash Report: https://pastebin.com/fZv1DeFi
Nuclearcraft Version: 2.18u
Forge Version: 2854
Minecraft Version: 1.12.2

**Comment by turbodiesel4598** [comment]
I have absolutely no idea what is actually causing this as it's such a deep crash, so I'll just remove that piece of the biome decoration code and hope it doesn't look much different :P

**Comment by turbodiesel4598** [comment]
Fixed in [2.18v](https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-mod/files/2995656) :)
