### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Coolguy1357911** [turbodiesel4598/NuclearCraft#668]
when ever  i try to launch the game, right after the screen gets to "4/7 " steps complete the game crashes because of something about a chemical reactor. https://pastebin.com/J9hDmC7y is the crash report. thanks!

**Comment by Coolguy1357911** [comment]
totaly forgot to mension that i also have the trinity mod installed so if that means anything sorry i didnt say i

**Comment by turbodiesel4598** [comment]
@Coolguy1357911 This should be fixed with the latest versions of NCO and Trinity :)
