### ISSUE TITLE
Pick-blocking Plutonium Ore Does Not Work

### ISSUE THREAD

**Issue by QuantumTraverse** [turbodiesel4598/NuclearCraft#67]
When I Pick-Block Plutonium Ore, I get a block without a texture called "tile.blockOre.name" with data value 33

**Comment by turbodiesel4598** [comment]
Strangely enough, I just found the source of this issue - it's been around for some time...
Apparently, the pickBlock method looks for the metadata of the dropped item, rather than the block itself, so it ended up being a rather simple fix :)
