### ISSUE TITLE
Visual Negative limit on reactor cooling?

### ISSUE THREAD

**Issue by achman741** [turbodiesel4598/NuclearCraft#68]
I built reactor with a 14x5x15 interior and for testing, completely filled it with helium coolers and got a funny cooling amount: -56,964 H/t. Shouldn't it be 122,500?  A 14x5x15 has 1050 spaces which should equal -122,500 H/t.  I decided to do further testing on another reactor and found a upper limit of -65,536 H/t, got this from 524 helium coolers, 1 standard cooler, and 6 water blocks. If i add another water block the H/t moves to -1H/t.  after i decided to add a fuel cell with TBU-Ox and then it moved back to -65,512 H/t.  With the limit of -65,536, if I add the strange number of-56,964 to it becomes -122,500.  Also with 8 fuel cells in a 2x2x2 shape it gives 240 kH/t, so is the negative rolling over to -1 a bug or minecraft restriction?

**Comment by achman741** [comment]
Also I was testing a 9 fuel cell in a 3x3x1 formation surrounded by graphite, using HEC-243 Ox which is why I was testing for large reactor cooling amounts. Needs 399kH/t Cooling.

**Comment by turbodiesel4598** [comment]
Definitely a fixable bug - I'm on it :)

**Comment by turbodiesel4598** [comment]
Fixed :)
