### ISSUE TITLE
Turbine rotor render crash

### ISSUE THREAD

**Issue by archiecarrot123** [turbodiesel4598/NuclearCraft#683]
Log: https://paste.ee/p/k2WXW

When I changed the dynamos, the client crashed, but not the server (using external server)
It's a 3X5X5 turbine, with extreme alloy rotors. The shaft goes along the X axis, and the dynamos I was changing were on the +X side.
It didn't crash every time, just most times
I was using lots of mods, however it doesn't seem like the affected it
I was using MultiMC to launch it, Nuclearcraft 2o.3.6-1.12.2, and Forge 14.23.5.2854.
No new builds of Nuclearcraft or Forge have come out at time of writing

**Comment by turbodiesel4598** [comment]
Perhaps try [this test build](https://www.dropbox.com/s/ye0ofdgzdo367hd/NuclearCraft-2o.3.7test-1.12.2.jar?dl=0) to see if the issue goes away? Basiaclly just added some extra null-checks.

**Comment by archiecarrot123** [comment]
The test built appears to have fixed the issue
I invalidated and rebuilt the turbine several times, and the game hasn't crashed
Thanks :)

**Comment by archiecarrot123** [comment]
So the turbine blew up, and there were some glitches with the textures. When I fixed it again, the server kicked both players, but didn't crash, and spammed errors for TurbineResendFormPacket. There weren't any errors on the client side.

https://paste.ee/p/dPUcr

**Comment by turbodiesel4598** [comment]
Hmm, this one I'm less sure about, but I think the initial null-pointer is in the TurbineFormPacket, and it's propagating through from TurbineResendFormPacket... [here's the build](https://www.dropbox.com/s/oxax9ldmrg67g35/NuclearCraft-2o.3.7_test2-1.12.2.jar?dl=0). What were the texture glitches, by the way?

**Comment by archiecarrot123** [comment]
Some of the connected textures that form when the turbine is created still existed after it broke, and destroying and reconstructing the blocks fixed the texture on that particular block. When the rotor was invalid but the rest of the turbine was, it formed the connected textures when re-placing, however the turbine didn't work.

**Comment by archiecarrot123** [comment]
The texture glitch still exists, and when I blew up the turbine (the turbine goes up to 200% when I don't get rid of the output), and re-built it, it crashed again.

This time it's the client-side log, as it now has lots of errors, and the server errors were the same
https://paste.ee/p/bibUi

**Comment by turbodiesel4598** [comment]
I think this bug is now fixed with [v2o.4.0](https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-overhauled/files/3043745) :)
