### ISSUE TITLE
Radiation Server Crash

### ISSUE THREAD

**Issue by mxnmnm** [turbodiesel4598/NuclearCraft#684]
The server crashed because of something radiation related causing lag. Not sure if it's related to one of the issues already posted (there seem to be some lag/radiation things mentioned but I'm not sure if it's the exact same issue or not) or not but figured I should post it here just to be safe.

https://pastebin.com/7eVEJASQ

**Comment by turbodiesel4598** [comment]
I'm afraid this is something that I basically have no chance of outright fixing, as I think it's a mod adding some weird override for getting the metadata of one of its blocks, so instead I can add a config to just disable the block checks altogether. [Here's a test build](https://www.dropbox.com/s/nkdn2u58sh5inp1/NuclearCraft-2.18x_test-1.12.2.jar?dl=0) if you want to try it out; the config is called `"Block Radiation Contribution"` in game, or `radiation_check_blocks` in the config file.

**Comment by mxnmnm** [comment]
Do you have any idea of which block is causing it? We're having a tough time recreating this as it is on a server (and the crash isn't consistent and we're not exactly sure what/if the player did anything in particular) so it would need to be uploaded to curse in order to get added to the server pack but I will see if I can get the server owners to try it out anyways.

**Comment by turbodiesel4598** [comment]
Can't tell unfortunately, as it's not been reported before and the log doesn't say. How often is it happening on the server?

**Comment by mxnmnm** [comment]
Sadly the server owners didn't keep track so it might've been a situation where someone placed a block and then broke it afterwards without realizing it was causing the issue. Is there a way to force the routine chunk radiation cycle so we can test things that may potentially cause it?

**Comment by turbodiesel4598** [comment]
How about one which is a bit faster but also logs the blocks it's checking?

**Comment by mxnmnm** [comment]
That could work

**Comment by mxnmnm** [comment]
How fast would it be though?

**Comment by turbodiesel4598** [comment]
I've just made it quicker by having the block checks happen in every chunk of the radiation update cycle, rather than just one of them per round. [Here's the link.](https://www.dropbox.com/s/nc6c8cu895nqia8/NuclearCraft-2.18x_test_logging-1.12.2.jar?dl=0)

**Comment by mxnmnm** [comment]
Honestly I have no clue where to even start and since the pack is getting remade anyways it doesn't make sense timewise to put all of the blocks one by one in a high radiation area. If the issue arises in the new pack I'll be sure to report it and hopefully have more info such as logs rather than just a crash report.

**Comment by turbodiesel4598** [comment]
Alright, no worries, unfortuantely it was a needle-in-a-haystack type problem :P
