### ISSUE TITLE
I can remove fuel from the reactor chamber while it's burning

### ISSUE THREAD

**Issue by carthe** [turbodiesel4598/NuclearCraft#687]
I can remove fuel from the reactor using other mods inventory managers (eg. RFTools Storage Scanner) while it's burning. Basically it gives me infinite fuel as I can remove it near its depletion.
I scanned Fission Reactor Port if that's something that can help you.

![image](https://user-images.githubusercontent.com/32596055/91561105-4ea50000-e93b-11ea-9ae6-eeafb01e7b03.png)

**Comment by turbodiesel4598** [comment]
Unfortunately this is just a flaw in the way the inventories are implemented in pre-overhaul NC, and fixing it would break worlds (it's fixed on the overhaul branch). I've made the slots inaccessible and made them impossible to access via typical automation, but things like this will still get round that :/
