### ISSUE TITLE
[Bug] Can't remove Tinker melting recipes, for sugar and cocoa nibs, with CraftTweaker/ModTweaker

### ISSUE THREAD

**Issue by maxine-red** [turbodiesel4598/NuclearCraft#688]
I'm making my own mod pack and try to remove the melting recipes (in tinker) for the following items:

- sugar
- ground cocoa nibs

Removing them in the NC Melter is possible. Removing other fluids (tested with thermal liquid metals) in Tinker is also possible.

Versions
NC: 2o.4.0-1.12.2
Forge: 14.23.5.2847
TConstruct: 1.12.2-2.13.0.183
Crafttweaker: 1.12-4.1.20.582

I'm testing on a single player map so far and have tested it with only those three mods + JEI

I also looked into the code and my suspicion is that it is added after CT removes recipes for the smeltery. Though I am not a modder, so my hunch can we wrong.

This script is what I use for removing the recipes:
`#modloaded tconstruct nuclearcraft

import mods.tconstruct.Melting;
print("I'm running!");

Melting.removeRecipe(<liquid:sugar>);
Melting.removeRecipe(<liquid:chocolate_liquor>);

Melting.removeRecipe(<liquid:sugar>, <minecraft:sugar>);
Melting.removeRecipe(<liquid:chocolate_liquor>, <nuclearcraft:ground_cocoa_nibs>);`

Both removals are added, just to see if any work. I tested it with each variant alone too and nothing seems to remove those recipes.

Additionally, logs say it successfully registers the altered melting recipe (having them removed).

Oh and I tried disabling chocolate being registered as a material in tinker. Nothing changed.

Something else, that might be related. I also have "nuclearcraft:fluid_sugar" entries in my JEI (same with all other NC fluids)
I'm not sure what's the deal with them and just want to add it in case it helps solve the issue.

If you need more info, let me know!

EDIT: I forgot! I can add alternative recipes, but they don't replace the original ones.
Like I can add sugar melting into 16mb of molten sugar and see it in JEI, but the original recipe (144mb) is still the one used and JEI shows both recipes.

**Comment by turbodiesel4598** [comment]
Thanks for the detailed report! I thought this was just caused, as you say, by the recipes being added by NC too late, but it seems registering them earlier still achieves nothing, so I don't think there's much choice but to go with the PR :)

**Comment by turbodiesel4598** [comment]
Actually, going to keep this open i case I can find something out from the TiC or ModTweaker devs...

**Comment by turbodiesel4598** [comment]
I found out I was actually adding the recipes a little bit too early in the loading sequence, and somehow that stopped the recipe removal from working. Script removal of the recipes should work next version :)
