### ISSUE TITLE
Game keeps crashing when turbine is running

### ISSUE THREAD

**Issue by bubafett** [turbodiesel4598/NuclearCraft#689]
I built a 2x3x3 turbine with 1 set of steel rotor blades and 1 set of extreme alloy rotor blades. When I feed steam into it (using a Thermal Expansion dynamo) the game crashes and keeps crashing when the turbine is still running. The rotor shaft and the rotor blades don't render correctly, they are black. I'm playing on a server.

![turbine](https://user-images.githubusercontent.com/70478634/91662212-45559800-eae1-11ea-8584-dcfb2f7d93bc.png)

**Comment by turbodiesel4598** [comment]
@bubafett Which version of the mod is this?
