### ISSUE TITLE
Cannot use commands in single player

### ISSUE THREAD

**Issue by Take13Gaming** [turbodiesel4598/NuclearCraft#691]
'T' and '/' don't allow me to type, tried rebinding them and ensuring there were no other controls bound to the same keys and still nothing.  Since there's no option for advanced setup options when creating a new world in this version either it becomes difficult to fully customize the experience.  I am on MacOS High Sierra running through the Twitch launcher.  Have not tested multiplayer worlds.

**Comment by turbodiesel4598** [comment]
This doesn't sound like an NC issue - there's something going awry with your game at a more fundamental level.
