### ISSUE TITLE
[1.12.2] NuclearCraft crashes with Cubic Chunks

### ISSUE THREAD

**Issue by Monniasza** [turbodiesel4598/NuclearCraft#693]
Cubic Chunks version: 1.12.2-0.0.1055.0-SNAPSHOT
MalisisCore version: 1.12.1-6.5.1-SNAPSHOT
NuclearCraft version: 2.18x-1.12.2
When I use NuclearCraft with Cubic Chunks, the game crashes as soon as the world loads.
Cubic Chunks: https://www.curseforge.com/minecraft/mc-mods/opencubicchunks/download/2910783
Log: https://paste.ee/p/vaiEi

**Comment by turbodiesel4598** [comment]
Fixed for next version ;)
