### ISSUE TITLE
[Idea for overhaul version] Aneutronic fusion reactors

### ISSUE THREAD

**Issue by MusicMaestro123** [turbodiesel4598/NuclearCraft#698]
An aneutronic fusion reactor would be built completely differently to a standard fusion reactor. This one is a later game one and so would produce more energy as it might in real life. However it takes even longer than a regular fusion reactor to heat up and will produce radiation similarly to a fission reactor.
However, the advantage of this style of reactor is that it's maximum energy output ranges into the 10s of millions. The main fuel for this would be D-T as it has the lowest ignition temperature although there are other combinations such as D-H3 fuel as well but think what you want of it and implement it however you wish. It will always be amazing as much as the rest of your mod!

Thanks

**Comment by turbodiesel4598** [comment]
Hey there! If I get time in the future to add extra stuff not already the to-do list as it stands, things like aneutronic fusion, muon-catalysed fusion and other reactors will be among them. For the foreseeable future, however, I simply don't think I'll have the time I'm afraid.
