### ISSUE TITLE
Reprocessing Plant Recipes for dLEA-242 & dHEA-242 Seem to be Switched

### ISSUE THREAD

**Issue by QuantumTraverse** [turbodiesel4598/NuclearCraft#70]
dLEA-242 currently outputs 24 Am-243, 4 Cm-243, 4 Cm-246, 8 Cm-247
dHEA-242 currently outputs 16 Am-243, 8 Cm-243, 8 Cm-245, 8 Cm-247
Wouldn't it be more logical to have the dLEA output Cm-245 and the dHEA output Cm-246 because of a higher neutron flux and thus a better breeding ability in the more fissile/more "enriched" fuel?

**Comment by turbodiesel4598** [comment]
Yes, you are right - it should. In fact, there are a few product inaccuracies like that. However, I feel that the more 'dangerous' fuels should give the more valuable products (the fissile fuel). Should I stick more to realism in this case?

**Comment by QuantumTraverse** [comment]
I just find that the current system, through which I make much Cm-246 via LEA-242, makes much more Am-242(m) than I can use just in LEA-242. To me, HEA-242 is useless because I don't need to make Cm-245 when I can just make HEC-247 cells.

Furthermore, Pu-242 is only obtainable from HEU-235 & MOX-239, so I do not think your 'dangerousness' test is consistent.

**Comment by turbodiesel4598** [comment]
Right, good to know. Perhaps I should sit down and shuffle the system about a bit. And yes, you're right, the plutonium is a bit off (although I don't think I have much choice). Keeping the 'tech' tree of fuels sensible is the most important thing :)

**Comment by QuantumTraverse** [comment]
If you do do such reshuffling, could you maybe rethink the 24|4|4|8 output system for LE fuels? The realism of such an output scheme seems questionable, but might be fine for balancing out certain fuels, but not for every single LE fuel.
Also, might we eventually be able to get Transcuric fuels?

**Comment by turbodiesel4598** [comment]
Yes, I probably will - I think that was just a first draft that I never really got round to changing. As for Californium and above, I was originally planning to add them, but a few things stopped me. First, their half lives are super-short after Curium, and more importantly, even the National Nuclear Data Centre has very limited information about the neutron capture and fission cross sections of the isotopes of the heavier elements!

**Comment by QuantumTraverse** [comment]
Don't forget about Berkelium, too. What information do you specifically need? I have a great deal I think.
Generic Info on Criticality: http://www.pnl.gov/main/publications/external/technical_reports/PNNL-19176.pdf (specifically pages [as the document labels them, not as the pdf counts] 98 & 108 are useful)
https://ec.europa.eu/energy/sites/ener/files/documents/20131018_trm_evaluation.pdf (pages 6, 13, & 15)
https://www.osti.gov/scitech/servlets/purl/4462458/ (older, but p. 14 could be useful)
Cf Info (SF chance, neutron yield, halflife, etc.): https://e-reports-ext.llnl.gov/pdf/785407.pdf
Cross Sections: http://wwwndc.jaea.go.jp/cgi-bin/Tab80WWW.cgi?/data/JENDL/JENDL-4-prc/intern/Cf251.intern (just look up "JENDL" + the isotope to find a table [they have many isotopes])

**Comment by turbodiesel4598** [comment]
Right, well, now that I had some time to look through this, it appears that Cf-249, Cf-251 and Es-254 could be nuclear fission fuels - why not :)

I'm going to spend a long time tomorrow rewriting the processing plant recipes, but hopefully it will be worth it.

**Comment by turbodiesel4598** [comment]
Although the reactors are not yet actually finished for 1.10.2/1.11.2, a first alpha version will be up on CurseForge by tonight - JEI isn't done yet either, unfortunately, so you'll actually have to put the depleted cells into the reprocessor to see what they produce, but I hope the new system allows for a smoother transition up the fuel tree :)
