### ISSUE TITLE
Nuclearcraft Ores Spawning in other dimension but not in deep dark 

### ISSUE THREAD

**Issue by iMPxNero** [turbodiesel4598/NuclearCraft#700]
So i'm playing skyfactory 4 on my server as i went to the deep dark and looked for nuclearcraft Ores there weren't any but the other modores spawned there i changed the config and put the deep dark in the whitelist reset the world but it still doesnt work

![Unbenannt](https://user-images.githubusercontent.com/73745657/97780132-0399aa00-1b83-11eb-88a2-f104ee6a5e25.PNG)

**Comment by turbodiesel4598** [comment]
@iMPxNero It might be because the deep dark's surface is at a y-level significantly higher than the max y-level for NC ore generation... have you looked around at lower y-levels?
