### ISSUE TITLE
[Overhauled suggested] add support for Alchemistry

### ISSUE THREAD

**Issue by Gan-N** [turbodiesel4598/NuclearCraft#701]
This mod adds all elements on the periodic table. 
Allow Overhauled nuclear materials to be more sophisticated

**Comment by turbodiesel4598** [comment]
Alchemistry's style of element manipulation is quite different to NC's... I would say it is on Alchemistry to "add support" (not exactly sure what that means in this context) for other mods' elements via the ore dictionary.
