### ISSUE TITLE
Heatexchanger crafttweaker recipes wrong implementation

### ISSUE THREAD

**Issue by igentuman** [turbodiesel4598/NuclearCraft#708]
mods.nuclearcraft.HeatExchanger.addRecipe(ILiquidStack fluidInput, ILiquidStack fluidOutput, double heatRequired, int temperatureIn, int temperatureOut);

mods.nuclearcraft.HeatExchanger.removeRecipeWithInput(ILiquidStack fluidInput);
mods.nuclearcraft.HeatExchanger.removeRecipeWithOutput(ILiquidStack fluidOutput);

```
	@ZenMethod
		public static void addRecipe(Object[] objects) {
			CraftTweakerAPI.apply(new CTAddRecipe(NCRecipes.heat_exchanger, Lists.newArrayList(objects)));
		}
		
		@ZenMethod
		public static void removeRecipeWithInput(IIngredient[] inputs) {
			CraftTweakerAPI.apply(new CTRemoveRecipe(NCRecipes.heat_exchanger, IngredientSorption.INPUT, Lists.newArrayList(inputs)));
		}
		
		@ZenMethod
		public static void removeRecipeWithOutput(IIngredient[] outputs) {
			CraftTweakerAPI.apply(new CTRemoveRecipe(NCRecipes.heat_exchanger, IngredientSorption.OUTPUT, Lists.newArrayList(outputs)));
		}
		
```

**Comment by turbodiesel4598** [comment]
The heat excahnger in general isn't functional right now - when it is, the CraftTweaker methods will be sorted out :)
