### ISSUE TITLE
Crash on startup in what looks like recipe handling 

### ISSUE THREAD

**Issue by MicahHaack** [turbodiesel4598/NuclearCraft#712]
Crash Log: https://pastebin.com/X4BquKHG

Occurred after the addition of Gregicality.

**Comment by CvoidWyvern** [comment]
Was having this same problem, looks like the latest Gregicality update fixed this.

**Comment by turbodiesel4598** [comment]
Fixed the capitalisation method erroring in being given an empty string, otherwise this is apparently no longer an issue :P
