### ISSUE TITLE
Comparator Wierdness with solid fission reactor

### ISSUE THREAD

**Issue by Hendiadyoin1** [turbodiesel4598/NuclearCraft#713]
Version: 2.18w-1.12.2

So acoording to the wiki the solid Fission reactor should output its heat value via a comparator;  
That it does *sometimes*, but for some reason it swiches to ourputing a redstone signal propotional to the energy stored, not the heat.  
It may be that it outputs the maximum of both, but that would contradict the wiki and make it difficult to build a emergency stop with just redstone

**Comment by turbodiesel4598** [comment]
@Hendiadyoin1 The wiki is indeed a bit wrong. It shouldn't stop you from making a safety loop though (it'll just also trigger if the energy bugger gets too full).
