### ISSUE TITLE
[Suggestion] ItemFrame overlay for Geiger Counter

### ISSUE THREAD

**Issue by NLBlackEagle** [turbodiesel4598/NuclearCraft#714]
Like the title already suggest, a text overlay such as the Minecraft Clock has as shown in the below image but then with a geiger counter. ( I am not entirely sure if this is a vanilla feature or added by some mod of the modpack but I figured this could be modded into nuclearcraft in either cases )

![afbeelding](https://user-images.githubusercontent.com/4073584/103616790-5ef26a80-4f2d-11eb-9fd3-5d0987691fda.png)

**Comment by turbodiesel4598** [comment]
Without knowing which mod does this, as someone who is not well-versed in MC rendering, I'm afraid that I don't think I am going to be able to recreate the effect :P
