### ISSUE TITLE
question about radioactive biomes

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [turbodiesel4598/NuclearCraft#715]
in the radioactive wasteland for example how is the radiation generated? 

is it directly attached to the biome itself, so if i had a mod to change it i could then use scrubbers to remove the radiation and have it stay gone or are you spawning a radioactive block somewhere as a source?

**Comment by QuantumTraverse** [comment]
The wasteland radiation is tied to the biome itself. You can change its value in the configs. So long as you do not change the value in the configs, you will need to run scrubbers continuously if you want to lower the radiation there.

**Comment by C4PTRAMPAGE** [comment]
i dont think you get my point exactly, what i want is to be able to permanently remove the radiation from wastelands ingame, for example if i had advanced rocketry installed that has a biome changer satellite and if i understand you correctly then changing the biome from wasteland to something else will shut off the respawning radiation in that chunk?

**Comment by QuantumTraverse** [comment]
yes, changing the biome will stop the radiation from respawning
