### ISSUE TITLE
Crashes for JEI rendering recipes in GTCE machines using the overhaul version

### ISSUE THREAD

**Issue by Maxhy21** [turbodiesel4598/NuclearCraft#718]
Game crashes when rendering centrifuge recipes with an 0-16mb random output in GTCE machines.
Crash report: https://pastebin.com/dfYnTN0q
When actually process recipes with random amount of output using GTCE centrifuge, it always produces zero.

**Comment by turbodiesel4598** [comment]
I think I'm just going to have to stop recipes with random outputs being transformed into GTCE recipes.
