### ISSUE TITLE
1.9 Fission reactors not working

### ISSUE THREAD

**Issue by micheldewit** [turbodiesel4598/NuclearCraft#72]
Hi there! 
We are having an issue with the Fission Reactors : When trying to make these "work" (After adding fuel etc) when you flip the "lever" it just wont.. boot up. We are having this issue in 1.9E, D and C, have not tested anything before that.

**Comment by turbodiesel4598** [comment]
Hey! Could you perhaps send a picture of the GUI? That might give me a clue as to what's happening :)

**Comment by micheldewit** [comment]
Found the issue; A conflicting config from another mod, causing the compartment cells not to be registered.

**Comment by micheldewit** [comment]
We were trying for hours on end already, and we just noticed the fact that c Cells actually are overwritten. Added NEIDs and it works..

**Comment by turbodiesel4598** [comment]
Ah, ok... still a weird issue though. I think thaqt sort of stuff should be totally fixed in 1.8 and beyond.
