### ISSUE TITLE
[Suggestion] Control rods

### ISSUE THREAD

**Issue by Paquito86** [turbodiesel4598/NuclearCraft#722]
The mod is amazing, but I would like the option of installing control rods for it to be suitable for the use I want to give it. Adding control rods would make the mod perfect.

**Comment by QuantumTraverse** [comment]
If you have the overhauled version of the mod, there are neutron shields, which are similar to, albeit not the same as, control rods.

**Comment by turbodiesel4598** [comment]
As Quantum says, the overhauled version of the mod introduces neutron shields, which can be thought of as NC's version of control rods :)
