### ISSUE TITLE
No data fixer registered for nuclear_craft:anti_gravity_ammo

### ISSUE THREAD

**Issue by MrWhosHacking** [turbodiesel4598/NuclearCraft#723]
when i run nuclear_craft-1.16.4-0.6.4.jar on forge 35.1.37 i get this error No data fixer registered for nuclear_craft:anti_gravity_ammo

**Comment by Ommina** [comment]
NuclearCraft != nuclear_craft

You want https://github.com/SongXia-NYU/nuclear_craft/issues

**Comment by turbodiesel4598** [comment]
@MrWhosHacking Yeh, unforunately this mod is not mine :P
