### ISSUE TITLE
Unable to resolve texture reference

### ISSUE THREAD

**Issue by MrWhosHacking** [turbodiesel4598/NuclearCraft#724]
Unable to resolve texture reference: #missing in nuclear_craft:item/rocket_launcher_smoke
Unable to resolve texture reference: #missing in nuclear_craft:item/rocket_launcher_incendiary
Unable to resolve texture reference: #missing in nuclear_craft:item/rocket_launcher_high_explosive
when loading. I'm using nuclear_craft-1.16.4-0.6.4.jar

**Comment by QuantumTraverse** [comment]
wrong mod: this mod is "nuclearcraft", not "nuclear_craft". This mod also does not yet have a 1.16 version. The latest version for this mod is 1.12. I think [this link](https://github.com/SongXia-NYU/nuclear_craft/issues) is the correct GitHub to post this report to.

**Comment by turbodiesel4598** [comment]
Yeh, unforunately this mod is not mine :P
