### ISSUE TITLE
Turbines with regular steam can create infinite energy

### ISSUE THREAD

**Issue by TheRealKamisama** [turbodiesel4598/NuclearCraft#725]
## Description
Using other mods' steam sources with nuclearcraft:overhaul's turbines, I can easily create a infinite energy source.  
Here are some numbers that I grab from my pack, which can tell you how imbalance this is  
![Snipaste_2021-02-01_22-24-31.png](https://i.loli.net/2021/02/01/AE1FcVvkiQUs2MI.png)  
![Snipaste_2021-02-01_22-27-12.png](https://i.loli.net/2021/02/01/l1nRCSMfogsuIqd.png)  
The Steam to RF multiplier for default NC is `4rf/mb`  
With a proper design, it can easily become `4.2rf+/mb  `
![Snipaste_2021-02-01_22-14-32.png](https://i.loli.net/2021/02/01/uyFo76xkK9JbieD.png)  
![Snipaste_2021-02-01_22-15-20.png](https://i.loli.net/2021/02/01/Iu4cN6eY1gK8Pzb.png)  
Magneticraft can turn RF into Steam using it's RF Heater, I built a simple example to show this  
The RF to Steam ratio for him is `2rf/mb`  
![Snipaste_2021-02-01_22-17-25.png](https://i.loli.net/2021/02/01/3qcdmoIG5PYplkr.png)  
For GTCE, `1eu/mb` or `4rf/mb`  

For Mekanism's Fusion Reactor or Steam Boiler...
## Suggestion
Nuclearcraft's Rankine cycle is different from others, so I suggest ~~just don't register it's steam in forge~~ changing to other id like "nc_steam"

There isn't a proper standard for how much Steam to produce how much RF, which has been a problem since Power Converter Mod

**Comment by joendter** [comment]
This is in my opinion a balancing problem of the modpack

**Comment by TheRealKamisama** [comment]
Resolved in discord chat, seems this problem doesn't come's from nc's balancing
