### ISSUE TITLE
[Overhauled] Feral Ghoul causing rendering glitches?

### ISSUE THREAD

**Issue by vesko128** [turbodiesel4598/NuclearCraft#727]
Sadly because of the spam it makes in the logs, i can't upload it to pastebin. 
[latest.log](https://github.com/turbodiesel4598/NuclearCraft/files/5927164/latest.log)

Steps to recreate:
1. Launch Minecraft
2. Get in a world
3. Find nuclear wasteland with a feral ghoul

https://www.youtube.com/watch?v=SMXHNjDnj-Q

**Comment by turbodiesel4598** [comment]
@vesko128 I may have managed to fix this - it's a bug which appears in many different flavours, depending on the mods installed along NCO, and has reported by a few others. [Here is a test build if you would like to try :)](https://www.dropbox.com/s/9av03za35d2q4bf/NuclearCraft-2o.5.0beta3-1.12.2.jar?dl=0)

**Comment by vesko128** [comment]
That seems to have fixed the problem, thank you. Could I use this in my modpack for CurseForge or should I wait for you to update NCO before I upload the modpack?

**Comment by turbodiesel4598** [comment]
Thanks for testing! I would recommend waiting, as otherwise something might go wrong when you update the pack again (launchers might accidentally lose track of the manually added build). I hope to get a new build out soon, though - just a few more bugs to sort out :)

**Comment by vesko128** [comment]
Thank you for your support and incredible work, keep it up! :) I'm going to wait before updating my modpack I'm in no rush. Once again thank you very much.

**Comment by turbodiesel4598** [comment]
No worries :)

**Comment by turbodiesel4598** [comment]
Fixed in the build that should hopefully go up on CF tonight :)
