### ISSUE TITLE
Wrong reprocessing?

### ISSUE THREAD

**Issue by chaos234** [turbodiesel4598/NuclearCraft#73]
I don't know why the reprocessing is so false and causing headaches, but I have definitly to reorganize it.

At first each Fission Fuel has the same base values even if the isotopes are different and then they are not reprocessed like assumed.

Mean for that each depleated cell has to output at last 18 tiny lump of itself (e. g. uranium-235) and also it should output the same next tier because actually you have to use over 10 reactors currently to get at last one, ONE HEN-XXX Fuel Cell and this is not the way it should be.

Mean in fact the the Fuel Tech Tree is heavily broken and must be fixed.

So if I have Thorium and Uranium it should giv me back at last 19 tiny pile of the used mainpart. This is important if other fuels are not possible for the currently designed reactor and then it shoul give you at last two Item for the next fuel, totaly ignoring the isotopes as long as they are free configurable and currently identicly so a HEU-233 should give you the same as a HEU-235 which means Uranium, Neptunium (237/236) and Plutonium. Because using the  HEP-241 is not useable in my desinged reactor and I can design what ever reactor I want (well, I am not using helium as coolant block) it isn't useable as long as you play with meltdowns.

Means the hole Fission Fuel has to be compleatly reorganized so any idea what chain is the correct way will be nice.

My Idea is: Thorium/Uranium -> Neptunium/Plutonium without looking at the isotope number and with at last 18 of the used mainpart of the fuel for non-oxid and 9 for oxid.

**Comment by turbodiesel4598** [comment]
The fuel tech tree definitely needs to be looked at, yes - as you say, the main issue right now is that it takes far too long to travel up the tree. However, I want there to be a slight bit of flexibility as I want players to use different isotopes of the same element to obtain particular isotopes. I will sit down and trawl through the mathematics at some point :)

**Comment by turbodiesel4598** [comment]
New tree in place in versions 2.0 and above :)
