### ISSUE TITLE
ItemEnergy/IChargableItem don't charge

### ISSUE THREAD

**Issue by Lach01298** [turbodiesel4598/NuclearCraft#733]
Because most of the items don't have any nbt on them when created they can't be charged (e.g they are not accepted in charging blocks). So when a battery is attempted to be put into a charging slot since it has no nbt defined it capacity is read as 0.

Items with the correct energy nbt can be charged.

Version: 2o.5.0.ALPHA

**Comment by turbodiesel4598** [comment]
Think this is now fixed :)
