### ISSUE TITLE
Fluid colours are not displayed properly in machines [2o.5.0.ALPHA]

### ISSUE THREAD

**Issue by Lach01298** [turbodiesel4598/NuclearCraft#734]
Examples
![image](https://user-images.githubusercontent.com/8176057/114114889-2182ec00-9925-11eb-9fc5-e5251a57d6d6.png)
![image](https://user-images.githubusercontent.com/8176057/114114940-3bbcca00-9925-11eb-8304-99aefb18894b.png)

**Comment by turbodiesel4598** [comment]
A bit of messing about later, I think I've got it :)
