### ISSUE TITLE
NC 5.0.ALPHA Crash - NoSuchMethodError: nc.multiblock.turbine.TurbineLogic.clearSounds

### ISSUE THREAD

**Issue by AnodeCathode** [turbodiesel4598/NuclearCraft#736]
Server upgrade from NuclearCraft-2o.4.7-1.12.2 to NuclearCraft-2o.5.0.ALPHA-1.12.2 

When chunk loaded with existing NC reactor and turbine, server crashes with 

java.lang.NoSuchMethodError: nc.multiblock.turbine.TurbineLogic.clearSounds()V

Complete crash log:
https://pastebin.com/30PsrFM1

**Comment by turbodiesel4598** [comment]
@AnodeCathode This was fixed in the 2o.5.0 release :)
