### ISSUE TITLE
Active Cooling with Enderium not working

### ISSUE THREAD

**Issue by Hunter-Sprouls** [turbodiesel4598/NuclearCraft#737]
Hi, I am running into an issue where the active cooling block is not recognizing liquid enderium. I have put all 8 coolers where they should be, I am at my wits end. I am using refine storage to pump fluid into the buffers and I know this working since I am using ultimate mechanical pipe, from mekanism, to pump into reactor chamber, see screenshots. How I came to my conclusion, the cooling I am producing is 217,080 heat removal when I should be producing 260280, see jpg, with 260280 minus 217080 equaling 43200 which is the 8 enderium coolers. All mods mentioned are all updated to the most resent version 1.12.2 and using default config.
Pipes that I tried using
Super-Laminar Fluid duct // was causing issues so removed 
Ender fluid  conduit // could not figure out if it was working removed
Ultimate mechanical pipe // currently using   
![2021-04-17_08 34 42](https://user-images.githubusercontent.com/26609125/115115694-5dd4ce80-9f5b-11eb-9a03-8fced4f25d06.png)
![2021-04-17_08 34 58](https://user-images.githubusercontent.com/26609125/115115696-60372880-9f5b-11eb-8f2f-ff3dd860fc6b.png)
![2021-04-17_08 35 10](https://user-images.githubusercontent.com/26609125/115115699-64fbdc80-9f5b-11eb-8bf1-622f9a2c4197.png)
![2021-04-17_08 35 18](https://user-images.githubusercontent.com/26609125/115115701-67f6cd00-9f5b-11eb-8190-992fca02fd8c.png)

![HEN-236 5 x 11 x 5 Liquid Cooled Breeder](https://user-images.githubusercontent.com/26609125/115115675-44cc1d80-9f5b-11eb-86bf-ad08a589c70d.png)
Mod list
![image](https://user-images.githubusercontent.com/26609125/115115804-03883d80-9f5c-11eb-85a3-2095b4fe3f88.png)

**Comment by turbodiesel4598** [comment]
Are you using molten enderium or molten ender? The active coolers use the latter (while the pasive coolers are made of enderium).

**Comment by Hunter-Sprouls** [comment]
I just realized that sorry to bother you.

**Comment by turbodiesel4598** [comment]
No worries :P
