### ISSUE TITLE
Fission Reactor Stalling

### ISSUE THREAD

**Issue by CNDRU** [turbodiesel4598/NuclearCraft#738]
in 20.5.1,after the reaction finishes,if I add new nuclear fuel into the reactor,the reaction will not start.When I destory some blocks and recover them,the reaction starts.I'm not sure if something is wrong.

**Comment by turbodiesel4598** [comment]
Are you using the samw fuel again, or a different one?

**Comment by CNDRU** [comment]
In the old version the reactor can work correctly,it's designed for [NI]HEU-235.After the words turned yellow the reactor still couldn't work.After destorying some blocks and replacing them it may work,but this sometimes doesn't work.

**Comment by turbodiesel4598** [comment]
Is the flux the cells are receiving close to the criticality factor? If so, it might be that your reactor is currently neutron poisoned (added in the most recent major version).

**Comment by CNDRU** [comment]
If it is the cause,I advice to make it visual to see if the reactor is neutron positioned and provide ways to solve it.

**Comment by CNDRU** [comment]
Maybe translating made the tune stronger,I'sorry about it.

**Comment by turbodiesel4598** [comment]
You’re definitely right, and neutron poisoning and other important starts will eventually be displayable by fission monitors, but they’re not implemented yet.
