### ISSUE TITLE
[Multiplayer] Recipes issue builds 2.5.x

### ISSUE THREAD

**Issue by igentuman** [turbodiesel4598/NuclearCraft#740]
Latest builds 2.5x having issue with recipes. Only multiplayer affected.
Try to craft any NC recipe in crafting table and you will see wrong output or empty output. But recipe will work.
If you try to use sort of autocrafting (mek formularic assemblicator/AE2/RS autocraft) it won't work or even may crash client.

**Comment by turbodiesel4598** [comment]
Hopefully fixed in [2o.5.2](https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-overhauled/files/3289195) :)
