### ISSUE TITLE
[Minor Bug 1.12.2 NC:Overhaul] Recipe names contain `:`

### ISSUE THREAD

**Issue by juraj-hrivnak** [turbodiesel4598/NuclearCraft#741]
- When modifying recipes using CraftTweaker using `replace all occurrences`.
CraftTweaker throws an error that the recipe names should not contain `:`.

- It's fixable by manually changing the recipe names with CraftTweaker, but the ideal would be to not have the `:` in recipe names by default.

![2021-05-06_14 18 06](https://user-images.githubusercontent.com/71150936/117296945-ef0dd580-ae75-11eb-82e2-6ddc375429fb.png)

**Comment by turbodiesel4598** [comment]
@juraj-hrivnak Which version of NCO?

**Comment by juraj-hrivnak** [comment]
Oh, sorry. I forgot about that.
It's no longer an issue in `NuclearCraft-2o.5.3`

Thank you!

**Comment by turbodiesel4598** [comment]
No worries :)
