### ISSUE TITLE
 JER Profiling crash

### ISSUE THREAD

**Issue by Minfrog314** [turbodiesel4598/NuclearCraft#742]
I have made a small modpack for myself with quite a few mods, and whenever I do a JER diy profile, it crashes. After installing vanillafix, I was able to see that it was from nuclearcraft, so I am reporting it here. And I am using the overhauled version.
Crash Report: https://paste.dimdev.org/ajubijujuq.mccrash
It seems to be a null pointer exception in the server tick loop. 
Hopefully this isn't too difficult to fix.

**Comment by tomdodd4598** [comment]
This unfortunately looks like a bit of a nasty one. I'll be lazy for now and surround that part of the method body with a `try {...} catch (...) {...}`, and someone might see a better solution in the future :)
