### ISSUE TITLE
Heat exchanger tubes not transporting fluid?

### ISSUE THREAD

**Issue by joshop** [turbodiesel4598/NuclearCraft#745]
Heat exchanger tubes appear to not transport fluid at all, whether part of the multiblock or not. When I do something stupid like add a call to `pushFluid()` in `TileHeatExchangerTube`'s update method and recompile the mod, they do transport fluid as expected when set to input spread, but the heat exchanger multiblock still does nothing (the input fluids just zip to the end of the chain of tubes and stay there). Obviously, I don't know how exactly this is supposed to work, but is this a bug or just something that's intentionally not implemented yet?

**Comment by tomdodd4598** [comment]
Which version of the mod is this? How you you have the heat exchanger set up?

**Comment by joshop** [comment]
This is, to my knowledge, the most recent beta version (I pulled it off this repository and compiled it myself, but I might have gotten the wrong branch or something). To test, I tried setting up a heat exchanger that was just a single line of tubes running down it - the multiblock formed, but no fluid entered any except the first tube. I also tried the same thing but with two lines of tubes in contraflow.

**Comment by tomdodd4598** [comment]
So the overhaul branch? If so, heat exchangers aren't implemented yet, so that's why it doesn't seem to work correctly in general :P
Any sort of latent functionality is just a hangover from the pre-overhaul version.

**Comment by joshop** [comment]
Okay, thanks.

**Comment by tomdodd4598** [comment]
No worries :)
