### ISSUE TITLE
Creative Radiation Scrubber/Provider for map maker.

### ISSUE THREAD

**Issue by 012phuong** [turbodiesel4598/NuclearCraft#749]
It would be nice if you can add a creative Radiation Scrubber/Provider that can remove a configurable amount or keep the radiation in one chunk at a desirable level like if you want to have a chunk with a radiation level at 100mRAD, you can configure the block so it can irradiate the chunk up to 100mRAD and stop there.

**Comment by QuantumTraverse** [comment]
One can set chunk radiation through commands, so one can just use a command block to do this.

**Comment by tomdodd4598** [comment]
I should have mentioned this at the time, but as QuantumTraverse says, this can be done with a command block in creative mode.
