### ISSUE TITLE
[1.7.10]fusion reactor not working in galacticraft dimensions

### ISSUE THREAD

**Issue by tonimark** [turbodiesel4598/NuclearCraft#750]
NuclearCraft 2.x for version 1.12.2 is no longer being developed as the focus of attention has been shifted to the overhaul. Bugs reports will be responded to, but new pre-overhaul features will no longer be accepted! Hopefully you can understand that working on two branches of this project at once is far too time-consuming!

when built a fusion reactor exactly like in overworld it won't work as it says "ring incomplete" as in overworld is works just fine dimensions tested: mars 
(galaxy space plugin was used)
reproduce: go to mars, build a fusion reactor, see the bug

**Comment by tomdodd4598** [comment]
Unfortunately I'm not developing NC for 1.7.10 anymore.
