### ISSUE TITLE
[1.12.2]there is still radiation after RTG removal

### ISSUE THREAD

**Issue by tonimark** [turbodiesel4598/NuclearCraft#751]
NuclearCraft 2.x for version 1.12.2 is no longer being developed as the focus of attention has been shifted to the overhaul. Bugs reports will be responded to, but new pre-overhaul features will no longer be accepted! Hopefully you can understand that working on two branches of this project at once is far too time-consuming!

Please use a paste tool such as Pastebin (https://pastebin.com) for crash logs!
this is for newer Minecraft 1.12.2 RTG radiation will stay permanently even if rtg is removed (instantly with click from creative mod) this is in theory impossible since all the nuclear material is gathered in rtg module and can be disposed safely

**Comment by tomdodd4598** [comment]
This is just due to how radiation works in NC - in other words, it's not an RTG-specific thing/issue. The radiation mechanics will be getting a re-do at some point, and should add some more realism, though it should be mentioned that the current system wasn't designed to be realistic :)

**Comment by tonimark** [comment]
> This is just due to how radiation works in NC - in other words, it's not an RTG-specific thing/issue. The radiation mechanics will be getting a re-do at some point, and should add some more realism, though it should be mentioned that the current system wasn't designed to be realistic :)

ok thanks I watched the video but it didn't mention something that each radiation you add is permanent thanks
