### ISSUE TITLE
IntegratedDynamics Machine Reader can't read the temperature from the side of the fusion reactor.

### ISSUE THREAD

**Issue by natedogith1** [turbodiesel4598/NuclearCraft#752]
The CommonCapabilities temperature API is only accessible from the bottom center of the fusion reactor.

Nuclearcraft version: 2.18w-1.12.2
CommonCapabilities version: 1.12.2-2.4.7
Integrated Dynamics version: 1.12.2-1.1.7

**Comment by tomdodd4598** [comment]
Unfortunately this is just due to a problem with the way I implemented fusion reactors in the pre-overhaul. I tried to fix this a couple of years ago but couldn't get it to work.
