### ISSUE TITLE
ExampleMod class accidentally left in (pre-overhaul)

### ISSUE THREAD

**Issue by Primitive-Human** [turbodiesel4598/NuclearCraft#753]
For some reason, the final pre-overhaul release has an ExampleMod.class inside it, which the game also registers as a mod.  Is this an oversight,  or is it actually necessary for the function of the mod?

The release build on Curseforge has this ExampleMod.class in it, but it is absent in the source.

**Comment by tomdodd4598** [comment]
Just looks like I accidentally left it in when moving to a new workspace - it's an easy fix :)

**Comment by tomdodd4598** [comment]
Will release a new build shortly :)
