### ISSUE TITLE
[Suggestion] Possible to have Radiation Levels apply Attribute Modifiers?

### ISSUE THREAD

**Issue by SonicX8000** [turbodiesel4598/NuclearCraft#755]
I think in the pre-overhaul you can have potion effects apply onto hostile/passive/player with Potion Effects depending on the Radiation Level... I wonder if this could be taken a step further.

Is it possible to apply attribute modifiers depending on radiation level? I dunno if the system is the same with it being percentage based (Please correct me on this if I'm wrong on how the radiation system works, it's been awhile) but attribute modifiers could be interesting to mess with. Here's some examples...

Note that I'm only familiar with Operations 0 & 2 since I've been using the quality tools mod to apply little bonuses on weapons & armor... and by default... the percentage set there mostly uses Operation 2.

If Radiation Level is at 10%
`generic.maxHealth -0.1 2`
`generic.armor -1 0`

This will lower your max health by 10% (If you have 50 health, it becomes 45 health) while also lowering your armor by 1.

-----

If Radiation Level is at 35%
`generic.maxHealth -0.25 2`
`generic.armor -4 0`
`generic.armorToughness -2 0`

The previous effect is gone and it now applies this one. This will lower max health by 25% (If you have 20 health... it becomes 15) while also lowering armor by 4 as well as Toughness by 2.

=====

These are just some examples with vanilla attributes but you can also apply modded attributes that is if you know the correct names. Here's an example from Potion Core, Tinkers Evolution and Scaling Feast.

If Radiation Level is at 60%
`generic.maxHealth -0.5 2`
`scalingfeast.maxHungerMod -0.5 2`
`generic.attackDamage -0.3 2`
`potioncore.projectileDamage -0.3 2`
`potioncore.magicDamage -0.3 2`
`potioncore.damageResistance -0.25 2`
`tconevo.evasionChance -0.2 2`

Again, the previous effect is removed and this one is applied now. Now then...

Health is reduced by 50% (If you had 80, it becomes 40)
Hunger is reduced by 50% (If you had 20, it becomes 10)
Attack Damage is lowered by 30%
Projectile Damage is lowered by 30%
Magic Damage is lowered by 30%
You take 25% more damage from all damage sources
Your ability to 'dodge' damage is lowered by 20%

Scaling Feast allows you to increase max hunger, but I kept it within vanilla values. Also if one wanted... you can still apply potion effects for reaching x Radiation Level, much like how it works currently... well... at least pre-overhaul.

Hopefully I explained it well.

**Comment by tomdodd4598** [comment]
Sorry for the very late response! It certainly sounds like a interesting idea, but I don't really know anything about attributes, so I'd have to put some time aside to implement this without messing anything up.

I'll keep this issue open for when I get round for it - the to-do list is currently very, very long :P

**Comment by tomdodd4598** [comment]
Added for the next version of NCO. It'll go into the same config options as those used for potion effects. They seem to work as far as I can tell, but there may be bugs if I have misunderstood the details of how entity attributes and their modifiers work :P
