### ISSUE TITLE
Molybdenum dust can't be melted

### ISSUE THREAD

**Issue by Lach01298** [turbodiesel4598/NuclearCraft#757]
I noticed you forgot a the molybdenum dust melter recipe. As a temporary solution on my end QMD has added it.

**Comment by tomdodd4598** [comment]
It seems for some reason that [I explicitly commented out the recipe for it](https://github.com/tomdodd4598/NuclearCraft/blob/1.12.2o/src/main/java/nc/recipe/processor/MelterRecipes.java#L161)... since I can't remember why, I'll add it back in until I can remember what the reason was :P
