### ISSUE TITLE
Crash report whenever I head into a radiation zone

### ISSUE THREAD

**Issue by i1-iu** [turbodiesel4598/NuclearCraft#758]
[crash-2021-09-04_21.07.02-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/7110794/crash-2021-09-04_21.07.02-server.txt)

**Comment by i1-iu** [comment]
I don't know what causes it, mainly because I cant read crash logs, but it might be because of all the mods I have :)

**Comment by tomdodd4598** [comment]
This is a bizarre error is a few ways... I really can not understand how it has manifested itself. I can only hope that when I update the mod, the issue goes away... maybe try version 2o.5.4 in the meantime?

**Comment by i1-iu** [comment]
Oof. Well thanks for looking at it, I will mess with the configs and see if I can accidentally fix it.

**Comment by tomdodd4598** [comment]
Any luck? Also, I notice now that you are using Optifine. I can't think how that would be causing the problem, but are you able to test without it?
