### ISSUE TITLE
A Question?

### ISSUE THREAD

**Issue by Cazadorsniper** [turbodiesel4598/NuclearCraft#76]
Will this mod be updated to 1.10.2 or 1.11.2 etc...?

**Comment by turbodiesel4598** [comment]
I've finally got a bit of time to do exactly that - I'm currently working on an update to 1.11.2 (as far as I can tell, it should work for 1.10.2 also). Over the next month or so, I hope to get fission done, then I have my third term of uni, and then I will get back to all the rest in the summer :)

This is a video about what's happening if you want it: https://www.youtube.com/watch?v=AhSWMS6t4zI

**Comment by Cazadorsniper** [comment]
cool

**Comment by turbodiesel4598** [comment]
Although fission reactors are not complete, and JEI integration is not yet done, a first alpha version will be on Curseforge by tonight :)
