### ISSUE TITLE
[SUGGESTION]1.17.1

### ISSUE THREAD

**Issue by Colonizor48** [turbodiesel4598/NuclearCraft#761]
I understand not porting to 1.13.2. That version of the game was a technical mess, same with 1.14 to an even grater degree. But 1.17.1 has been ironed out alot. And 1.12.2 is almost 5 years old at this point. This mod should start upgrading to 1.17.1.

**Comment by tomdodd4598** [comment]
1.12.2 is still the main focus, whenever the overhaul is in a stable, finished state, I will move to later versions :)

**Comment by noa12390** [comment]
well your not going to have much choice here soon since most mods have ether moved to 1.16 or are moving to 1.17 and packs are starting to drop support for 1.12 in favor of 1.16 while they wait for 1.17 to get finished

**Comment by tomdodd4598** [comment]
@noa12390 I have plenty of choice :P I can update to the latest version whenever I want, and as this is an open source project, anyone else can too, at any time :)

**Comment by tomdodd4598** [comment]
I'll close this, not because I won't update or acknowledge that people want an update, but just because I eventually will, and because of the existence of the current project ot update pre-overhaul NC to 1.16+, followable on the [Discord server](https://discord.gg/KCPYgWw) :)
