### ISSUE TITLE
[QUESTION] Is there any way that Just Enough Resources (JER) works with NuclearCraft

### ISSUE THREAD

**Issue by ghost** [turbodiesel4598/NuclearCraft#765]
As it's seen in the title, is there a way that JER works with NuclearCraft (at least ore generation)?

**Comment by ghost** [comment]
I have just discovered the Overhauled versions, are these compatible? as I am running the pre-overhauled version as of now.

**Comment by ubergarm** [comment]
@MikevanBree yes `JER` works great with `NuclearCraft:Overhauled` including the ores.

You can see how it looks in my modpack [Rotten Economy](https://www.curseforge.com/minecraft/modpacks/rotten-economy)

I'm using versions:
`forge-1.12.2-14.23.5.2855.jar`
`NuclearCraft-2o.5.5-1.12.2.jar`
`JustEnoughResources-1.12.2-0.9.2.60.jar`

The old "non overhauled" version is [*not* compatible as stated up front on the curseforge page](https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-overhauled). My personal advice is to use new "overhauled" version which is the active branch.

Here is the [command from the wiki](https://github.com/way2muchnoise/JustEnoughResources/wiki/Profiling) I used to run the JER scan: `/jer_profile 10000 all`

Here is a snippet of the output generated from above command: `world-gen.json`:
```
    {
         "block": "nuclearcraft:ore:5",
         "distrib": "0,0.0;1,2.4609375E-5;2,5.875E-4;3,0.0016292969;4,0.0021628905;5,0.0027964844;6,0.0028195314;7,0.0026523438;8,
 0.0026800781;9,0.00264375;10,0.0026011718;11,0.0025246094;12,0.0025039061;13,0.0025;14,0.002554297;15,0.002596875;16,0.0026539064; 17,0.0026109375;18,0.0025070312;19,0.0023984376;20,0.0024632812;21,0.0024570313;22,0.0025292968;23,0.0024023438;24,0.0023785157;
 25,0.0024242187;26,0.0022878905;27,0.0012003906;28,1.1640625E-4;29,0.0;",
         "silktouch": false,
         "dim": "Rotten Earth"
     },
     {
         "block": "nuclearcraft:ore:4",
         "distrib": "0,0.0;1,5.859375E-6;2,3.3164062E-4;3,9.285156E-4;4,0.0011933594;5,0.0015347656;6,0.0015632813;7,0.0015863281;
 8,0.0015347656;9,0.00155;10,0.0015097656;11,0.0015082031;12,0.0014777344;13,0.00149375;14,0.0014699219;15,0.0015402344;16,0.
 0014816406;17,0.0015171875;18,0.0014207031;19,0.0014203124;20,0.0014109375;21,0.0013921876;22,0.0013957032;23,0.0013859374;24,0.
 0014355469;25,0.0013679687;26,0.0014328125;27,0.0014308593;28,0.0014195313;29,0.0015316406;30,0.0013902343;31,6.9023436E-4;32,3.
 046875E-5;33,0.0;",
         "silktouch": false,
         "dim": "Earth"
    }
```

Cheers and have fun!

**Comment by ghost** [comment]
I'll be sure to check this out then! btw, I've said this in a different issue ( #766 ), but my server (Aternos) can't run above 2o.3.x so I'm not sure if it will pop up
