### ISSUE TITLE
[Crash] NuclearCraft Overhaul + EnderIO Redstone conduits

### ISSUE THREAD

**Issue by noblevolt** [turbodiesel4598/NuclearCraft#767]
This is my first time ever submitting an issue so sorry if it is formatted incorrectly. Trying to startup my modded Minecraft server today resulted in it crashing and saying "Description: Exception while updating neighbours", trying the world in singleplayer also causes the same crash. 

Crash Report: https://pastebin.com/b63pFLqW

I am not too smart when it comes to this but as far as I see the Redstone conduits and the Ra-Be sources aren't playing together too well. Removing EnderIO just causes my game to crash when I attempt to load up the world. I figured this might be a good first place to start to look for a solution.

**Comment by HeatherComputer** [comment]
Are you able to consistently trigger the crash?

**Comment by thedeadferryman** [comment]
The same happens to me: https://pastebin.com/Gwuu6hMS
I have an assumption that the bug comes out when the reactor melts down, but the actual reason is unknown...

**Comment by tomdodd4598** [comment]
Attempted to fix this with @thedeadferryman's PR :)
