### ISSUE TITLE
Radiation death persist interaction with PlayerRevive Mod

### ISSUE THREAD

**Issue by ubergarm** [turbodiesel4598/NuclearCraft#768]
## Description
There seems to be some mod interactions between PlayerRevive and NuclearCraft:Overhauled with default configurations. When a player dies due to excessive radiation, it is possible to get stuck in a PlayerRevie "loop" that is difficult to escape. You can see an example in this [twitch stream video showing the glitch](https://www.twitch.tv/videos/1171415273?t=03h10m00s). Essentially before you can click "respawn" or "title screen" you end up in the PlayerRevive count-down again immediately and can't escape even with disconnect/reconnect.

The author of PlayerRevive has responded graciously on this issue which I originally posted there: https://github.com/CreativeMD/PlayerRevive/issues/73

To recreate this you have to have a multiplayer session and could use my modpack [Rotten Economy v0.90](https://www.curseforge.com/minecraft/modpacks/rotten-economy/files/3483967)

## Work Around
The safest solution for now is to change the config in `nuclearcraft.cfg` to disable persisting radiation levels like this:
```
# If enabled, players' radiation levels will persist on death.
B:radiation_death_persist=false
```

In addition, adding the `fatal_rads` line into `playerrevive.json` might help in some cases:
```
"bypassDamageSources": [
    "gorgon",
    "death.attack.sgcraft:transient",
    "death.attack.sgcraft:iris",
    "death.attack.fatal_rads"
]
```

I use this work-around in newer versions of my modpack config. Also thanks so much for `Nuclearcraft:Overhauled`! I've been having a lot of fun with it and built some quests around the radiation system in latest version of my modpack. Also I've been able to configure it to work pretty well with Tech Guns (which has a very similar but non-functional radiation system).

## Musings
My impression is that the [NuclearCraft: Overhauled Github onPlayerRespawn event](https://github.com/tomdodd4598/NuclearCraft/blob/1.12.2o/src/main/java/nc/handler/PlayerRespawnHandler.java#L40-L44) is maybe not triggering properly.  If that is the case, the "revive loop" glitch might occur say if a player has high radiation but the actual death.attack happens to be due to something else than fatal_rads. But I'm not sure how to test this hypothesis.

## Versions
* Forge `forge-1.12.2-14.23.5.2855.jar`
* [PlayerRevive](https://www.curseforge.com/minecraft/mc-mods/playerrevive) `PlayerRevive_v1.2.40_mc1.12.2.jar`
* [NuclearCraft: Overhauled](https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-overhauled) `NuclearCraft-2o.5.5-1.12.2.jar`
* [Rotten Economy Modpack v0.90 Source](https://github.com/ubergarm/RottenEconomy/tree/v0.90)

**Comment by CreativeMD** [comment]
A brief summary of how PlayerRevive works:

It subscribes to the `LivingDeathEvent` ([source](https://github.com/CreativeMD/PlayerRevive/blob/1.12/src/main/java/com/creativemd/playerrevive/server/ReviveEventServer.java#L141)). If a player dies it will cancel the death and set the player into a bleeding state. This will prevent the player from getting damage and set the health to one heart ([source](https://github.com/CreativeMD/PlayerRevive/blob/1.12/src/main/java/com/creativemd/playerrevive/server/ReviveEventServer.java#L141)).
Either the player will get revived (which will remove the bleeding state) or the player gets killed by bledToDeath damage once the time has run out or the player gave up.

I have no clue how this issue occurs, maybe you can help out.

**Comment by tomdodd4598** [comment]
Hey there @ubergarm and @CreativeMD! I've been rather busy lately, so not had as much time to work on NCO in general as I would have liked :P

I tried recreating this just be installing PlayerRevive (for logging etc. in the dev environment), and I couldn't. Trying to follow how the death and respawn events are connected is quite a minefield, so for now I don't have any good ideas about what might be happening.

It's possible that it doesn't have anything to do with NCO's subscription to the `PlayerEvent.Clone` event that you link to, but rather [the dealing of the fatal radiation damage itself](https://github.com/tomdodd4598/NuclearCraft/blob/1.12.2o/src/main/java/nc/radiation/RadiationHandler.java#L93-L95) in the `PlayerTickEvent` subscription.

**Comment by CreativeMD** [comment]
Could be, but honestly I got no idea either :|

**Comment by tomdodd4598** [comment]
Unfortunately, I could not work out what the cause of this could be. For anyone else who runs into this, I would simply recommend the workaround detailed in ubergarm's original post!
