### ISSUE TITLE
Add a programer art resource pack for 1.16+ that uses old textures if you are updating textures for 1.16

### ISSUE THREAD

**Issue by Colonizor48** [turbodiesel4598/NuclearCraft#769]
Title. Some of prefer programer art.

**Comment by tomdodd4598** [comment]
I am currently not in charge of the 1.16 update project, but you can certainly head to the [Discord server](https://discord.gg/KCPYgWw) and follow the management of the new assets. There is currently a decent amount of progress being made, so you may prefer the sort of things they've come up with so far :)
