### ISSUE TITLE
Scrubber units of measure look wrong

### ISSUE THREAD

**Issue by Hawk777** [turbodiesel4598/NuclearCraft#773]
When I right-click an operative scrubber, I get a message along the lines of “Active radiation removal rate: −16 mRad/t”. However, if I understand things correctly—and it’s certainly possible I might not—the way the scrubber works is that it makes the radiation level (i.e. the number returned by a Geiger counter block) go down slowly, continuously, over time, while it is operating. Therefore, should the units of measure in the chat message not be Rad/t², rather than Rad/t, since it is the time derivative (i.e. rate of change) of a number measured in Rad/t?

That said, I do not think the number it displays is *actually* in Rad/t². Maybe something like Rad/(ts) instead? The Rad/t number does not appear to go down by 20× the scrubber removal rate every second. But I’m not certain about my measurement on this point.

**Comment by tomdodd4598** [comment]
The scrubber is reducing the radiation rate in the chunk, which means the equilibrium value of the radiation level in Rad/t is lower while it is active, so the unit is indeed Rad/t :)

**Comment by Hawk777** [comment]
@tomdodd4598 sorry but could you explain this behaviour then? Maybe I’m being really dense but I just don’t understand.

1. Create a brand new superflat creative world.
2. Give yourself a Geiger counter. Observe that the chunk’s contamination level is 0 Rad/t, as one would expect from a superflat world (which contains no radioactive blocks of any kind anywhere nearby).
3. Grab some Californium-252 and hold it in your inventory for a minute or two.
4. Delete the item.
5. Observe that the chunk has been contaminated. There are no radiation sources around any more (items or blocks), but the Geiger counter still reads, in my case, 85 mRad/t. This must be the contamination level of the chunk.
6. Build, fuel, and power a scrubber—I used a Thermal Expansion creative portable tank to supply unlimited Rad-Away, and an Immersive Engineering creative capacitor for power.
7. Right-click the scrubber. In my test, it read −0.006534760551 Rad/t, i.e. about 6 mRad/t. By that point the chunk’s contamination level had dropped a bit, presumably due to spreading, so 6 mRad/t was somewhere around 10% of the chunk’s contamination level.

Now, if the units of measure are indeed Rad/t, then I would expect the chunk contamination level to jump down from, say, 60 mRad/t to 54 mRad/t as soon as the scrubber activated, and jump back *up* again when the scrubber was deactivated—after all, when deactivated, it’s no longer subtracting those 6 mRad/t, instead it goes back to 0. But that’s not what I see at all. Instead, if I depower the scrubber, the Geiger counter number starts dropping much more slowly than it was before, but it does *not* jump back up. Activating the scrubber appears to change the *speed at which contamination goes down*, not the *absolute amount of contamination in the chunk*. It’s not modifying the number of Rad/t in the chunk, it’s modifying the *rate of change* of Rad/t.
