### ISSUE TITLE
Solid fuel cells can have incorrect flux propogation

### ISSUE THREAD

**Issue by Zixiken** [turbodiesel4598/NuclearCraft#776]
I used the reactor planner to design a mza239 reactor with full shutdown factor, but in-game 4/12 cells remain active, and meltdown after a few seconds due to the now-inadequate cooling. [Here](https://discord.com/channels/425461908712325130/528692982757588992/923315551407861810)'s a link to the ncpf I sent in the discord channel. The cells that stay running are on the far right, both top and bottom. Further experimentation showed I'm able to run the reactor with the remainder of the cells entirely removed, and this also works with the left 4 cells. Without the incoming flux from the center cells, the side cells shouldn't have enough flux to reach criticality, though they get close...74/80 for the right cells, and 76/80 for the left. Maybe there's some sort of rounding error happening? I'm running with default configs, and a few other mods so I have something to do with all the power I'm generating.

**Comment by yako0755** [comment]
Same issue here. My LEP-239 Oxide Reactor design with 100% shutdown factor cannot be fully shutdown in the game.
I sent a ncpf file in the discord channel. [Here](https://discord.com/channels/425461908712325130/425529560856002561/911980094963204167)'s the link.
I didn't inspect which cells are still reacting, but the overall heat output reduced by ~1500H/t, so probably only the two cells that directly affected by the neutron shield stopped and the remaining cells are still reacting.

**Comment by tomdodd4598** [comment]
Okay! I finally tracked this down. This is all due to me only partially disabling the neutron poison mechanics (when it is disabled, which it is by default). The next build should fix this :)
