### ISSUE TITLE
Graphite.... does not exist?

### ISSUE THREAD

**Issue by ProfessorFuzz** [turbodiesel4598/NuclearCraft#78]
Apparently I need graphite to produce any form of nuclearcraft machinery.  However there appears to be no way to obtain it as there is no ore block, no crafting recipe that doesn't involve already having graphite (either dust made from graphite, or a block of graphite.)   I first assumed it was because Just enough items wasn't showing me nuclearcraft crafting, but any block that can do nuclearcraft crafting REQUIRES GRAPHITE.  So I couldn't see if there was a way to make it using the ores already in game.

**Comment by turbodiesel4598** [comment]
You see, the issue is that I'm an idiot - you get graphite from the manufactury, but as you say, you need graphite to build it... sorry about that, will fix :P

**Comment by turbodiesel4598** [comment]
I've just uploaded a new version that should fix the graphite issue: https://minecraft.curseforge.com/projects/nuclearcraft-mod/files
To make graphite, you put coal in the Manufactory, and to make tough alloy, first make steel in the Alloy Furnace with graphite and iron, then ferroboron with steel and boron, then tough alloy with ferroboron and lithium.

**Comment by ProfessorFuzz** [comment]
thx
