### ISSUE TITLE
Config file comments not being written properly

### ISSUE THREAD

**Issue by kvieta** [turbodiesel4598/NuclearCraft#780]
for example:

`
fission {
    # gui.nc.config.fission.fission_fuel_time_multiplier.comment
    D:fission_fuel_time_multiplier=1.0

    # gui.nc.config.fission.fission_fuel_heat_multiplier.comment
    D:fission_fuel_heat_multiplier=1.0

    # gui.nc.config.fission.fission_fuel_efficiency_multiplier.comment
    D:fission_fuel_efficiency_multiplier=1.0

    # gui.nc.config.fission.fission_fuel_radiation_multiplier.comment
    D:fission_fuel_radiation_multiplier=1.0

    # gui.nc.config.fission.fission_source_efficiency.comment
    D:fission_source_efficiency <
        0.9
`

rather than using the localisations.
v2o.6.0-1.12.2

**Comment by kvieta** [comment]
[en_us.lang.gz](https://github.com/tomdodd4598/NuclearCraft/files/8448633/en_us.lang.gz)
lang file i am using to fix (not complete)

**Comment by Krutoy242** [comment]
Yeah, have the same problem 
![image](https://user-images.githubusercontent.com/936618/215829412-edcf3b75-6d29-4f79-8331-d7f8e4bc1ee0.png)

**Comment by tomdodd4598** [comment]
Seems to be fixed now, although there are still a bunch of configs I need to write descriptions for!
