### ISSUE TITLE
Missing Manganese (di)oxide smelting recipes.

### ISSUE THREAD

**Issue by warownia1** [turbodiesel4598/NuclearCraft#781]
Manganese Oxide and Manganese Dioxide dusts cannot be smelted into their respective ingots.

**Comment by tomdodd4598** [comment]
Hey there,

Unfortunately I'm getting round to some of these bug reports two years later, but on the latest version of NCO, manganese oxide ingots smelt to manganese ingots, and manganese oxide dust smelts to manganese oxide ingots. There were some bugs in the past regarding these recipes and related ones, but they seem to have been fixed at some point.
