### ISSUE TITLE
Turbines keep exploding despite the fact the number of blades should be able to keep up with the steam flow

### ISSUE THREAD

**Issue by redstoneguy10ls** [turbodiesel4598/NuclearCraft#782]
Basically, as the title explains my steam turbines keep blowing up despite the fact that I should have enough turbine blades. I have about 20 blades and I'm only pumping in 301Mb/t of high pressure steam

**Comment by tomdodd4598** [comment]
This was due to a really silly oversight in the bearing tension maths... [fixed in 2o.6.1](https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-overhauled/files/3783980) :)
