### ISSUE TITLE
Can't autocraft Lithium battery with AE2

### ISSUE THREAD

**Issue by Castanea43** [turbodiesel4598/NuclearCraft#787]
Hi,

i have a problem for crafting Lithium battery Basic, advanced, DU, Elite with AE2 Extended Life 0.53.4 (latest), and a lot of mods (see below)
Screenshot : https://zupimages.net/viewer.php?id=22/35/xgg5.png
but i can craft Ion cell & Solenoid
On NC 2.18zzz

But it's ok with NC:O

List of mods : https://pastebin.com/utwt2Vve

Reproduce in SP & MP
Thanks in advance.

**Comment by tomdodd4598** [comment]
Hi there,

Sorry for only getting to this after nearly two years, but unfortunately I could still not recreate this issue. Since I'm planning on dropping development of the pre-overhaul version of the mod, I hope you don't mind me closing this issue!
