### ISSUE TITLE
Weird oredict-tags and probably broken Interaction with TEs Factorizer (Overhaul)

### ISSUE THREAD

**Issue by Gitcrafter** [turbodiesel4598/NuclearCraft#788]
I noticed, that Boron-11 is oredicted as nuggetBoron-10 and I noticed the same thing with other Elements too, is that intendet? cause the Factorizer from Thermal Expansion(the Factorizer automatically adds Recipes for Nugget>Ingot, Ingot>Block, Block>Ingot, Ingot>Nugget if it finds Nuggets, Ingots and Blocks of the same Material) is adding Recipes for your Elements, for example 9x Boron-10 to 1x Boron-11, I highly doubt, that this is intendet, your Melter is also doing weird things with Boron-10/11 and Lithium-6/7.

**Comment by tomdodd4598** [comment]
I think it's another mod doing this, as I only add boron-10 and boron-11 to the ore dictionary as `ingotBoron10` and `ingotBoron11`, respectively, [here](https://github.com/tomdodd4598/NuclearCraft/blob/1.12.2o/src/main/java/nc/handler/OreDictHandler.java#L187-L188).

**Comment by Gitcrafter** [comment]
After some digging I found out, that it´s the fault of JAOPCA, I will report it to them and see if they do something about it.

Edit: I have reported it now.

**Comment by Gitcrafter** [comment]
I got the answer now, apparently I was using an outdated version of JAOPCA, now with the latest version it is fixed, sorry my bad for bothering you

other topic:
When will you bring back the Fusion Reactor and are you planning on adding other different types like Inertia confinement ones or ones that are used for heating of coolant to produce steam?

**Comment by tomdodd4598** [comment]
No worries! I do plan to bring fusion back to NCO, and they'll either produce steam or hot coolant, but I first need to get the fission reactors finished and heat exchangers sorted :)
