### ISSUE TITLE
Requesting reactor construction help.

### ISSUE THREAD

**Issue by djoboom** [turbodiesel4598/NuclearCraft#789]
I've tried 7 different tutorials, scoured the internet for hours, and dealt with several headaches along the way. Can someone please just explain what is required to make a "Cluster"? Or why the fuel wont go into the reactor?

I'm playing TechNodeFirmaCraft 12.2.82 with a few custom addons that dont affect NuclearCraft in the slightest. 
I can't use item pipes, as the modpack does not contain any.

My design uses 16 Gold Heat Sinks, 24 Iron Heat Sinks, 6 Lapis Heat Sinks, 6 Solid Fuel Fission Fuel Cells, 13 Beryllium Blocks, 4 Po-Be Neutron sources, 8 fission reactor vents (4 water input, 4 steam output), 2 Fission Fuel Vessel Ports (1 in, 1 out), 40 Fission Reactor Conductor Blocks, a Fission Computer Port, and a Solid Fuel Fission Controller.

The images below depict the reactor itself, along with several cutaways of my reactor design.
![2022-09-28_20 30 48](https://user-images.githubusercontent.com/33499246/192918160-13d3feb6-4d3a-4450-a790-e97b05496aaf.png)
![2022-09-28_20 30 56](https://user-images.githubusercontent.com/33499246/192918162-3a06a69f-b23d-499f-b253-d2f9bb0b0d7b.png)

![2022-09-28_20 20 27](https://user-images.githubusercontent.com/33499246/192917057-d866817b-270e-4344-a6e8-06cbbb75abbb.png)
![2022-09-28_20 22 50](https://user-images.githubusercontent.com/33499246/192917313-7cd26c17-8c49-430d-b7c2-3966cec81a1e.png)
![2022-09-28_20 22 57](https://user-images.githubusercontent.com/33499246/192917315-8469eac6-8594-4b21-b866-9c7c678c4c13.png)

**Comment by QuantumTraverse** [comment]
Hopefully you already got help, but in case you didn't: NuclearCraft Overhauled works quite differently than the pre-overhaul version. There is an abstract idea called neutron flux which flows out of each fuel cell through moderators to reflectors or other fuel cells. You need to make sure to have each cell's neutron flux at least above its flux factor. More can be learned about these new mechanics through this [video](https://www.youtube.com/watch?v=GDm0JxynPR0) and the others on the channel.

P.S. You can also join the nuclearcraft [discord](https://discord.gg/KCPYgWw) to talk more about the mod and we can help you through the reactor design and construction process.
