### ISSUE TITLE
Energy Furnace (Suggestion)(1.12.2/Overhaul)

### ISSUE THREAD

**Issue by Gitcrafter** [turbodiesel4598/NuclearCraft#790]
Hello, can you add a Furnace in the Nuclearcraft-style, that uses Energy to do standard Furnace-recipes with Craftweaker-support?

**Comment by tomdodd4598** [comment]
I have definitely considered it. Such a thing is a little low-priority for now, but I definitely won't rule it out :)

**Comment by Gitcrafter** [comment]
Wow, didn´t expected an answer after such a long time

**Comment by tomdodd4598** [comment]
If two months was a long time, how about two years!

The electric furnace will be in the next version of the mod :)

**Comment by Gitcrafter** [comment]
Thank you for adding this

**Comment by tomdodd4598** [comment]
No worries :)
