### ISSUE TITLE
The fission reaThe fission reactor cannot operate normallyvctor cannot operate normally

### ISSUE THREAD

**Issue by Northdarkleave** [turbodiesel4598/NuclearCraft#796]
The fission reactor and neutron irradiation function cannot operate normally. I can guarantee that I have built it correctly. The nuclear fuel and neutron irradiation materials are sufficient. I am sure that I have used the moderator and neutron source correctly, but it does not work in this way, showing no cluster
Can you find a way to fix this bug?

**Comment by QuantumTraverse** [comment]
It's quite hard to fix bugs if you provide no information about how to recreate the bug. Many people have built designs incorporating irradiators, such as can be found in the [NuclearCraft discord](https://discord.gg/KCPYgWw) server, without running into this bug before. Perhaps you have built something wrong. If you post your design and construction in the discord, we can help solve your issue and get you a fully functional irradiation reactor.
