### ISSUE TITLE
Tinkers' Construct Can't Disable Integrations

### ISSUE THREAD

**Issue by Blueberrypie255** [turbodiesel4598/NuclearCraft#799]
I don't want any integrations with nuclearcraft from Tinkers' Construct but they keep happening. I have TC, constructs armory, and tinkers reforged. I cannot find a way to disable it.

**Comment by tomdodd4598** [comment]
There are already configs to disable particular materials from getting tools and armour called `register_tic_tool` and `register_conarm_armor`, respectively, but I've also added a new config option for the next build to disable the addition of smeltery recipes called `register_tic_recipes` :)
