### ISSUE TITLE
Game freeze/crash when placing down Alloy Furnace

### ISSUE THREAD

**Issue by Delphis1968** [turbodiesel4598/NuclearCraft#803]
Modpack - Forever Stranded
Minecraft ver - 1.10.2
NC ver - 2.7c

When placing the Alloy Furnace down, the client freezes. had to stop the task but when trying to load the world, it crashed. I replaced the version with 2.7b and able to get in but now any already placed AE2 export bus can't be right clicked.  I can pick up the Furnace, exit out, put the 2.7c version back in and able to load the world fine and the right click will work again. However if I place the furnace back down, it freezes. Does not freeze in the 2.7b version.

Edit - it does this with all block items I placed.

**Comment by tomdodd4598** [comment]
Unfortunately I am not developing the 1.10.2 version of the mod anymore - the modding toolchain for that version doesn't really exist at this point.
