### ISSUE TITLE
Error building. "Error: Wrong type of arguments; required 3."

### ISSUE THREAD

**Issue by GavinFF-SS** [turbodiesel4598/NuclearCraft#804]
NuclearCraft 2.x pre-overhaul builds are no longer being developed. The focus of attention has been shifted to 2o.x overhaul builds. Hopefully you can understand that working on two branches of this project at once is far too time-consuming!

Please use a paste tool such as Pastebin (https://pastebin.com) for crash logs!

I dont know if this should even go here. I also don't know how to build this mod admittedly so sorry if this seems like something stupid that  is laughably easy to fix. The absence of these classes cause (not even exaggerating) like 99 errors. really all i'm asking is how to build NC:Overhauled.

Much appreciated if you can help.

**Comment by GavinFF-SS** [comment]
I fixed that by making them myself with a Java Decompiler from a  Normal build of NC:O But now a lot of things are saying "error: wrong number of type arguments; required 3"

**Comment by tomdodd4598** [comment]
@GavinFF-SS Replying to this a year late, but NCO is now free of errors again! The last bunch of commits since 2022 were part of a large refactor of underlying parts of the mod, and so until recently, there were a tonne of compile errors :)
