### ISSUE TITLE
1.16.5 Not Working Properly

### ISSUE THREAD

**Issue by N4TEDOG** [turbodiesel4598/NuclearCraft#805]
Hi I’ve tried using nuclear craft on 1.16.5 but nothing seems to be working although the textures are in the game. For instance radiation fuels dropped onto the ground doesn’t create any radiation around it + Geiger counter doesn’t display any HUD or make any noises

**Comment by ArcadeArchie** [comment]
of course it doesn't work since the mod is designed for Minecraft 1.12.2.

**Comment by tomdodd4598** [comment]
Hey there @N4TEDOG,

This is the repository for the 1.12.2 version of the mod. Development of the 1.16 version is currently on hiatus, but there is a new repo [here](https://github.com/igentuman/NuclearCraft-Neoteric) for ports of NC to later versions :)
