### ISSUE TITLE
Wrong World In Grid Update - Console spam

### ISSUE THREAD

**Issue by Porcy** [turbodiesel4598/NuclearCraft#806]
NuclearCraft 2.x pre-overhaul builds are no longer being developed. The focus of attention has been shifted to 2o.x overhaul builds. Hopefully you can understand that working on two branches of this project at once is far too time-consuming!

Please use a paste tool such as Pastebin (https://pastebin.com) for crash logs!

Maybe pre-overhaul (2.18zzz) but would like some input on what could cause that. Have a few nc machines in Compact Machines spamming this :(

![NCWrongWorldGridUpdateSpam](https://github.com/tomdodd4598/NuclearCraft/assets/8096340/516ab82f-0fc1-42c2-86f5-f9d6c742836b)

**Comment by tomdodd4598** [comment]
Unfortunately I'm coming to this report a year late, but unfortunately I don't know why this would be happening, especially since it could be something due to Compact Machines. I'm also not really sure which "grid" the error is referring to...

**Comment by Porcy** [comment]
It seems to be related to IC2 power system. Whenever this message appears, there is no way to make it work; the cables won't connect to each other nor to machines, but only inside a compact machine. I suppose you implement parts / all of EU system in NC and somehow we get this spam. But your machines keep working.

**Comment by tomdodd4598** [comment]
I found a related issue [here](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/issues/1116) which you also commented on last year. Yeh, the "grid" is the probably term IC2 uses for a collection of mutually connected cables and machines which support EU.

Hmm... it's possible that this is an issue with IC2's logic rather than NC's or any of those other mods mentioned. I'll see if I can think of a fix on my end :)

**Comment by tomdodd4598** [comment]
Unfortunately, as far as I can tell, I'm not doing anything wrong on my end. This looks to be an issue with IC2, but I believe in the `IC2.ini` config file, there is a `[debug]` section where you might be able to turn off the continuous stream of error printing.
