### ISSUE TITLE
Small but notable lag with enabled Radiation

### ISSUE THREAD

**Issue by Krutoy242** [turbodiesel4598/NuclearCraft#807]
Overhauled, `radiation_enabled=true`.

I'm maintaining [E2E-E](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended) server. I found that NC:O causing about 2% of TPS lag.

![image](https://github.com/tomdodd4598/NuclearCraft/assets/936618/9a350aea-db64-4526-8dda-0d504a37b448)

By looking through source code, i found that most heavy calls is [loadedChunks.toArray](https://github.com/tomdodd4598/NuclearCraft/blob/e2f445d2465dd27badc16aa6ca7c4af0752bffec/src/main/java/nc/radiation/RadiationHandler.java#L242C17-L242C37) and [transferRadiationFromProviderToChunkBuffer](https://github.com/tomdodd4598/NuclearCraft/blob/1.12.2o/src/main/java/nc/radiation/RadiationHandler.java#L346).

- How can I improve TPS on my server without completely disabling radiation? My `radiation_world_chunks_per_tick` set to `5`, but seems like `loadedChunks.toArray` would constantly consume same amount of CPU, no matter of config.
- How I could optimize `transferRadiationFromProviderToChunkBuffer` or make it not called at all? I cant find a config for disabling TEs to contribute chunk radiation.

### Logs: [debug.zip](https://github.com/TheCodex6824/ThaumicAugmentation/files/12753048/debug.zip)

**Comment by tomdodd4598** [comment]
Hmm, this seems like a tricky one to get around totally, but I have a potential idea to avoid the conversion of the collection of chunks into an array. I'll add it to the next version of NCO, but it might be a bit of time before NCO as a whole is stable again.

I can also add the config option you describe to disable TEs contributing to chunk radiation :)

**Comment by tomdodd4598** [comment]
Sorted, hopefully it works!
