### ISSUE TITLE
NuclearCraft overhaul 1.12.2 reactor defunct

### ISSUE THREAD

**Issue by Solar-Dolphin** [turbodiesel4598/NuclearCraft#809]
So i Built two Solid Fuel Fission Reactors (different sizes) the first one was working for a bit but suddenly it stopped detecting the blocks inside and now wont start no matter what. (tried replacing every block)

**Comment by tomdodd4598** [comment]
Sorry for the late response! Is this still an issue? If so, which version of the mod were you using, and do you have the reactor designs you built?
