### ISSUE TITLE
Hates Refined Storage.

### ISSUE THREAD

**Issue by MagmaSlime123** [turbodiesel4598/NuclearCraft#811]
Title, see the report below. (Modlist included thanks to Forge.)

https://mclo.gs/BStTP48

(Pastebin is being dumb and thinks the paste is 'offensive', not sure why lol.)

**Comment by tomdodd4598** [comment]
I'll try the same fix as the CCL and EU2 crashes :P

**Comment by MagmaSlime123** [comment]
Sorry for opening separate issues lol. Not sure if I should've or not.
