### ISSUE TITLE
Hates CodeChickenLib.

### ISSUE THREAD

**Issue by MagmaSlime123** [turbodiesel4598/NuclearCraft#813]
Title, see the report below. (Modlist included thanks to Forge.)

https://mclo.gs/P48ce3P

(Pastebin is being dumb and thinks the paste is 'offensive', not sure why lol.)

**Comment by tomdodd4598** [comment]
Hey there,

The only thing I can think to do is to check that the capability isn't already attached. I'll get that implemented :)
