### ISSUE TITLE
Zeta Log spam over Recipe getResultItem is null

### ISSUE THREAD

**Issue by border999** [turbodiesel4598/NuclearCraft#814]
NuclearCraft-1.20.1-1.0.0-beta.2
I recommend running your mod with Zeta to see for yourself and fixing the issue from your end. Zeta will not suppress the spam, I checked. https://www.curseforge.com/minecraft/mc-mods/zeta
![image](https://github.com/tomdodd4598/NuclearCraft/assets/11824584/9f4fffd0-0360-4074-8eaf-7263b5725081)

**Comment by igentuman** [comment]
Two moments: You posted bug to wrong repo. NuclearCraft-1.20.1-1.0.0-beta.2 is outdated. Current version is NuclearCraft-1.20.1-1.0.0-beta.5

**Comment by border999** [comment]
![image](https://github.com/tomdodd4598/NuclearCraft/assets/11824584/2dc83ed8-9309-416a-955a-58f518cba403)

**Comment by border999** [comment]
closing and updating mod. Seeing if issue persists.
