### ISSUE TITLE
Bioplastic

### ISSUE THREAD

**Issue by UnicornZeus** [turbodiesel4598/NuclearCraft#817]
Hi I'm trying to make bioplastic but when I go to make it, it just doesn't 
![image_2024-05-06_024700073](https://github.com/tomdodd4598/NuclearCraft/assets/151785675/b64445ec-e391-4272-bc1a-38f817fc701e)

**Comment by UnicornZeus** [comment]
https://github.com/tomdodd4598/NuclearCraft/assets/151785675/82857bd7-52c5-48cd-87c8-2742716d7b49

**Comment by tomdodd4598** [comment]
Hi there,

This is the repository for the 1.12.2 version of NC. The repository for NC Neoteric can be found [here](https://github.com/igentuman/NuclearCraft-Neoteric/issues) :)
