### ISSUE TITLE
Manufactory recipes add to game load about ~1 second even if Manufactory machine is disabled

### ISSUE THREAD

**Issue by Krutoy242** [turbodiesel4598/NuclearCraft#818]
I disabled Manufactory since in E2EE using other machines instead of it:
```ruby
    B:register_processor <
        true
        false
        [...]
```

But considering this Spark profile, Manufactory still registering recipes and doing some kind of calculations that increasing modpack loading time https://spark.lucko.me/HlEM0qGvQZ?hl=564364

I know, 1 second sounds neglible, but I would be happy to no wait even 1 second for disabled features 😅.
Please make is so Manufactory recipes not registered if machine is disabled.

`NuclearCraft-2o.6.2-1.12.2`
[debug.log](https://github.com/user-attachments/files/15802323/debug.log)

**Comment by tomdodd4598** [comment]
Just in case people are disabling the Manufactory, but still using its recipes, such as for GTCEu integration, I will add new global and per-machine configs for disabling default recipe addition (`default_processor_recipes`, i.e. _"Register Default Recipes"_) :)
