### ISSUE TITLE
1.12.2 - LoaderExceptionModCrash: Caught exception from NuclearCraft (nuclearcraft)

### ISSUE THREAD

**Issue by OmSenshi** [turbodiesel4598/NuclearCraft#819]
**Hello**! How are u guys? Hope everything is fine.

I created a server to play with friends, I turned it on several times while making some changes and **no problems happened**.

After inserting Sponge-Forge, I came across an error in NuclearCraft

`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NuclearCraft (nuclearcraft)
Caused by: java.lang.NoClassDefFoundError: li/cil/oc/api/detail/Builder`

Complete Crash-log on link below

https://pastebin.com/NxM626Gb

I don't understand much about mods and settings, I apologize if I do something stupid

**Comment by zeng-github01** [comment]
On the surface, this is a bug related to OpenComputer Mod. I don't know why it is related to Nuclear Craft.

**Comment by igentuman** [comment]
No it related to NC. During NC tile registration it throw an error.

**Comment by zeng-github01** [comment]
> No it related to NC. During NC tile registration it throw an error.

This appears to be a crash caused by a third party. The class name in the log is from OpenComputer. There is no direct correlation between the two

This looks weird.

**Comment by tomdodd4598** [comment]
Unfortunately I have absolutely no idea what could be causing this. I don't reference that OC Builder class anywhere in NCO, and so can only imagine that somehow, in some strange way, SpongeForge's changes are causing the game to try to find a non-existent class. I haven't changed the code of the tile entity it is erroring on itself for five years, too...
