### ISSUE TITLE
Please Include Config to Stop Pizza Drops

### ISSUE THREAD

**Issue by Boolyman** [turbodiesel4598/NuclearCraft#82]
The Pizza from Nuclearcraft is inbalanced for some modpacks, but there is no config to turn it off.  It is basically a "Golden Apple" that has a chance to drop from every mob in the game... if gives full hunger refill PLUS BUFFS.  Can you please add an option in your configs to not automatically include it in the loot tables'?

**Comment by turbodiesel4598** [comment]
Sure thing - that should have been an option from the start.

**Comment by turbodiesel4598** [comment]
[Fixed in version 2.1a :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files)
