### ISSUE TITLE
Issue with NC Radiation

### ISSUE THREAD

**Issue by akurbs** [turbodiesel4598/NuclearCraft#821]
Hello!

A world of my is consistently crashing with the following report (https://pastebin.com/TjnGAJVK). I've tried disabling radiation to no avail so any help would be greatly appreciated!

Thanks!

**Comment by tomdodd4598** [comment]
Unfortunately, this looks like a nasty world NBT corruption which can occasionally occur when loading/saving Mincecraft worlds. If you do not have a backup of the world, then it might be possible with some tool like MCEdit or NBTExplorer to go through the world files and remove the troublesome NBT entry for `nuclearcraft:capability_radiation_source`.
