### ISSUE TITLE
NC:O processors not working on servers

### ISSUE THREAD

**Issue by infiner5** [turbodiesel4598/NuclearCraft#822]
crafttweaker.log: https://pastebin.com/dme0vvj2
NCO 2o.7.7
Issue: Custom processors cant be run at servers
replication: setup a server (in my case I used a PC to host it), add a NC:O addon with a custom processor in it, and start the server
tested on a standart forge server, then on a CleanroomLoader server which on both had the same log. Should also mention i tested 2 different addons on each of the server

**Comment by tomdodd4598** [comment]
Will be fixed in the next version :)
