### ISSUE TITLE
Can you realize that Fusion Reactor can use GregTech's gases?

### ISSUE THREAD

**Issue by BurovB** [turbodiesel4598/NuclearCraft#85]
I think it's will be interesting if player can use GT's gases in Fusion Reactor

**Comment by turbodiesel4598** [comment]
I think your question is whether I could add GT support to the fusion reactor. Unfortunately, I am low on time, and need to work on 1.10.2 and 1.11.2. I might look into it for those versions :)

**Comment by BurovB** [comment]
Ok, thank you for your prompt response
