### ISSUE TITLE
Crash server when placing down alloy furnace (Spongepowered)

### ISSUE THREAD

**Issue by Rongmario** [turbodiesel4598/NuclearCraft#86]
https://hastebin.com/tuteximixa.sql

**Comment by turbodiesel4598** [comment]
I'm not exactly sure how to fix this, as the problem seems to be on Sponge's side, and I don't know anything about Sponge - you may want to go ask them what the issue is.

**Comment by Rongmario** [comment]
Gotcha, will reference it here.

**Comment by Rongmario** [comment]
#https://github.com/SpongePowered/SpongeForge/issues/1457

**Comment by Towsty** [comment]
Not to add to the sponge train here but the same issue exists when place coal in a manufactory.

**Comment by turbodiesel4598** [comment]
I've commented on a thread on the sponge website about these issues, and hopefully someone who knows about sponge replies.

**Comment by turbodiesel4598** [comment]
Should be fixed in the latest version  2.2 :)

**Comment by Rongmario** [comment]
Good one turbo!
