### ISSUE TITLE
Fission Controller not accepting valid Fuel Rod

### ISSUE THREAD

**Issue by Zeinder** [turbodiesel4598/NuclearCraft#88]
The graphite provided by extreme reactors in ingot form is not accepted by the alloy furnace. This makes steel, ferroboron, and tough alloy uncraftable without some sort of exchange when these mods are used together.

**Comment by turbodiesel4598** [comment]
Ah, I made a silly mistake - I added my graphite ingot and dust to a separate universal ore dict category "graphite", which I obviously forgot would exclude other mods' materials - it is a simple fix and I'll get it out soon :)

**Comment by Zeinder** [comment]
On an unrelated note, the fission reactor isn't accepting fuel. I put the fuel cell in, and it doesn't consume it and it says no fuel. It's 2x2x1, Reactor Cell, 2x Redstone Coolers, and a Graphite Block.

**Comment by turbodiesel4598** [comment]
Hmmm - I'm not getting this issue. Could you show me with a picture or something?

**Comment by Zeinder** [comment]
Well, it just got strange. Apparently if I exit the game with fuel in the reactor, it will properly add it to the system when I start it up again. Reactor Layout:
![2017-04-24_21 14 54](https://cloud.githubusercontent.com/assets/7060121/25364843/341e8ed4-2933-11e7-9c67-cf767b30e5f3.png)

**Comment by turbodiesel4598** [comment]
Which version of NC are you using, and which MC version? Are you on a server?

**Comment by Zeinder** [comment]
I thought it might be betterfps because it has a tendency to cause problems, but no change after disabling it. What kind of mods might interfere? I can make a backup and start disabling things.

**Comment by turbodiesel4598** [comment]
I don't know - perhaps start with a backup with only NC installed, and see if the problem is still there.

**Comment by Zeinder** [comment]
So, I opened the curse/twitch client. Created a new custom 1.11.2 profile, installed only NC, and made a reactor in creative. Same result, doesn't consume the fuel unless I put it in and reload the world.

**Comment by turbodiesel4598** [comment]
Ah... sorry about that - I somehow allowed mistake somewhere to creep into the 1.11.2 version that isn't there in the 1.10.2 version - I'll get that fixed :)

**Comment by turbodiesel4598** [comment]
[This new version should fix the issue :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2412150)

**Comment by Zeinder** [comment]
Yep, updated. Burnt through my current fuel rod, and when I put the new one in it consumed it properly. Confirmed fixed.
