### ISSUE TITLE
Crash when Creating WitherBoss (Spongepowered)

### ISSUE THREAD

**Issue by YOYOK9** [turbodiesel4598/NuclearCraft#89]
So I'm aware this has been brought up already But my issue is caused by the creation of a wither boss... not sure how the 2 are connected but everytime someone tries to spawn one the server crashes and gives the crash.

Sponge thread:
https://forums.spongepowered.org/t/crash-on-wither-spawn/18603

Crash:
https://pastebin.com/WH39GXz9

**Comment by turbodiesel4598** [comment]
Man, I don't know... perhaps the people at Sponge could be a little more specific in what I'm apparently doing wrong to break their API all the time. I just can't understand how the issue is on NC's end when it runs fine without Sponge.

**Comment by YOYOK9** [comment]
Have you tried contacting them about it?

**Comment by turbodiesel4598** [comment]
I will do :)

**Comment by YOYOK9** [comment]
Cool! Love your mod and really dont want to have to remove it from my modpack :(

**Comment by MoeBoy76** [comment]
not sure what is happening exactly but it's calling the below recursively until the JVM reaches a StackOverflow
https://github.com/turbodiesel4598/NuclearCraft/blob/1.10.2/src/main/java/nc/tile/NCTile.java#L58

**Comment by turbodiesel4598** [comment]
Should be fixed in the latest version  2.2 :)
