### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Cazadorsniper** [turbodiesel4598/NuclearCraft#9]
When making a server for my pack this mod errors, causing the server to shutdown.
Here is the crash report:
http://pastebin.com/sS4XU3JJ

Although might be something im doing wrong.

**Comment by turbodiesel4598** [comment]
Very strange bug - I'm not having issues, but I found what's crashing you. I'll get an update out as soon as possible to fix it :)

**Comment by Cazadorsniper** [comment]
thank you :)

**Comment by turbodiesel4598** [comment]
Fixed in 1.6c
