### ISSUE TITLE
Fuel Reprocessor Accepting input in output slots

### ISSUE THREAD

**Issue by BrewAndCode** [turbodiesel4598/NuclearCraft#90]
latest v2.1c

I have all depleted rods being inserted into the left side of the fuel reprocessor.  I have tried this various ways.  Refined storage export bus and Ender IO buffer.  If a rod fails to insert into the left-hand slot of the machine for some reason (another rod type is processing) it gets inserted into one of the output slots and the machine starts flashing and fails to process anything until the item is removed.

**Comment by turbodiesel4598** [comment]
Someone on YouTube was telling me about this a few days ago - that bug will be fixed for the next version, which should be out soon :)

**Comment by BrewAndCode** [comment]
FYI you can work around this by using a vanilla hopper to pipe in items using whatever export tool you use to export to the hopper or a chest over the hopper.  For some reason the hopper doesn't overload the machines.

Also; this is happening with the Decay block as well; though you probably know that.

**Comment by turbodiesel4598** [comment]
Should be fixed in the latest version  2.2 :)
