### ISSUE TITLE
Diamond Cooler calculation

### ISSUE THREAD

**Issue by BrewAndCode** [turbodiesel4598/NuclearCraft#91]
Do I not understand the definition of "Sandwiched between water coolers"

My reactor is producing the same heat with or without the diamond coolers located in this screenshot.

To me sandwiched between means one on top/bottom or one on left/right.

Does it mean fully encased?   fully encased horizontally or on all axis? i.e. 4 water coolers or 6?
![image](https://cloud.githubusercontent.com/assets/6723474/25603893/008cacf4-2ece-11e7-8c5c-e467715799cd.png)

**Comment by turbodiesel4598** [comment]
I should make it more clear in the next release - 'sandwiched' means on four sides in the same plane, and 'between' means one either side - thanks for pointing that out :)

**Comment by turbodiesel4598** [comment]
Made clear in the upcoming version 2.3 :)
