### ISSUE TITLE
Please add JEI intergration of Alloy Recipes ASAP

### ISSUE THREAD

**Issue by loveyanbei** [turbodiesel4598/NuclearCraft#92]
No one can craft any alloy without reading code.

**Comment by turbodiesel4598** [comment]
I am working on it :)
I have little time and am going into JEI pretty much blind!

**Comment by BrewAndCode** [comment]
NEI is dead; it actually uses JEI to display recipes.  Regardless the author has made it clear in his videos and posts that JEI recipe integration isn't in.  IMHO this is a lower priority than core functionality.

**Comment by YOYOK9** [comment]
How are things going with this? Any news on possible completion dates?

**Comment by eclcol** [comment]
It would be great if you could somehow either integrate this into one of the recipe systems or document the processes on your wiki. I just spent half an hour trying to figure out how to make graphite dust - much less any of the fuels... My understanding is that you've done some of this with videos, but that's not a usable format for me, and for documentation of this sort it's very cumbersome to use in any event. Thanks.

**Comment by sandalle** [comment]
I was just wondering if Tough Alloy was broken as I couldn't find a recipe and had to Google it (found http://nuclearcraft.wikia.com/wiki/Tough_Alloy). I've no idea how to code Minecraft mods, but I did find https://github.com/mezz/JustEnoughItems/wiki if that will help you. :)

**Comment by turbodiesel4598** [comment]
Hi there - thank you all so much for your patience. JEI and MineTeaker support is finished and will feature in the next version of the mod. I am adding a few more machines and once that's done, I will release it :)

**Comment by turbodiesel4598** [comment]
[JEI support has been added for version 2.4, available to download from Curse. Enjoy :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files)
