### ISSUE TITLE
suggestion: reverse recipes for tiny piles

### ISSUE THREAD

**Issue by BrewAndCode** [turbodiesel4598/NuclearCraft#93]
I'm doing this myself manually in my pack via MT right now but it would be convenient, storage wise, if all of the full elements could be crafted back into 9 of the tiny piles just like the nugget/ingot relationship.

This makes it easier for mods like StorageDrawer's compacting drawer to accept the tiny piles as they just examine the recipes.

If you likey; I can submit a pull commit with the changes.  I know you're swamped.

**Comment by turbodiesel4598** [comment]
Don't worry - that should be a reasonably quick addition :)

**Comment by turbodiesel4598** [comment]
Sorted.

**Comment by turbodiesel4598** [comment]
Added in the latest version  2.2 :)
