### ISSUE TITLE
crashed 

### ISSUE THREAD

**Issue by coolgaza16** [turbodiesel4598/NuclearCraft#95]
was in my test world as not used this mod before and made a small fusion reactor and a small fission reactor and one of them crashed my world as report says something about depletion. and now I cant open that world as when I do it instantly crashes

[crash-2017-05-06_09.54.40-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/980805/crash-2017-05-06_09.54.40-server.txt)

**Comment by turbodiesel4598** [comment]
You're using an old version of the mod (1.9d) - that was a known bug, and was fixed in the latest version for 1.7.10, v1.9f.
