### ISSUE TITLE
Interface Blocks Crash Game on Placement

### ISSUE THREAD

**Issue by CJL48** [turbodiesel4598/NuclearCraft#96]
The Machine Interface, Buffer, and Fission Port all cause a crash when present in the world in NC 2.2.
On placing said blocks or attempting to load a world with said blocks present, minecraft crashes.
[crash-2017-05-07_12.09.35-client.txt](https://github.com/turbodiesel4598/NuclearCraft/files/981722/crash-2017-05-07_12.09.35-client.txt)

**Comment by turbodiesel4598** [comment]
Hmmm, strange... I'll look into it

**Comment by turbodiesel4598** [comment]
Should be fixed in version 2.2a :)

**Comment by CJL48** [comment]
Thanks.
