### ISSUE TITLE
Crash when making steel

### ISSUE THREAD

**Issue by T4rk1n** [turbodiesel4598/NuclearCraft#99]
I put iron and graphite in the alloy furnace, then I crash.

[crash_report](https://pastebin.com/fPY1GgED)

**Comment by turbodiesel4598** [comment]
I'm on it.

**Comment by turbodiesel4598** [comment]
Hmm - this is a really weird one. At first, I could recreate the issue easily, but suddenly, for no reason I could see, the issue just... vanished. I'll try to do a bit more experimenting, but perhaps I did make some change that unexpectedly fixed the issue...

**Comment by turbodiesel4598** [comment]
Ok - I think I found the issue - should now be fixed :)

**Comment by turbodiesel4598** [comment]
Fixed in latest version 2.2b :)

**Comment by turbodiesel4598** [comment]
Sorry, is this issue not present then?

**Comment by T4rk1n** [comment]
Just tested 2.2b, no more crash.

**Comment by turbodiesel4598** [comment]
Awesome - thanks :)
